%EXAMPLE_NEUROIMGING_2_RVS_PET
% Script example pipeline neuroimaing (PET) conversion to
% regional values (SUVR)
clear variables %#ok<*NASGU>

%% Create dataset
example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];

% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
% create_data_NIfTI_WMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_PET(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', '/home/hang/GitHub/IndividualConnectome-WithYuwei/group_data/HangFDG_dataBIDS/AD_PositiveAmyloid', ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

gr_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', '/home/hang/GitHub/IndividualConnectome-WithYuwei/group_data/HangFDG_dataBIDS/AD_PositiveAmyloid', ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

gr_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', '/home/hang/GitHub/IndividualConnectome-WithYuwei/group_data/HangFDG_dataBIDS/AD_PositiveAmyloid', ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

gr_anat_wmprob = im_gr_wm.get('GR');

%% Convert neuroimaging data to probability density functions
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas_mapping.csv']
    };

% set the reference brain regions for PET normalization
ref_brain_regions = {};
ref_brain_regions_idx = 120-7:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end
ref_brain_regions_idx_tds = 7;
for i = 1:length(ref_brain_regions_idx_tds)
    ref_brain_regions{end + 1} = ba_td.get('BR_DICT').get('IT', ref_brain_regions_idx_tds).get('ID');
end

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

ad = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_pet, ...
    'GR_LIST_ANAT_REF', {gr_anat_gmprob, gr_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 1.0);

gr_pdfs = ad.get('GR_FUN');
ba_pdfs = ad.get('BA');

%% Export data
directory_base = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Converted data PET'];
mkdir(directory_base);
ex = ExporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', directory_base, ...
    'GR', gr_pdfs ...
    );
ex.get('SAVE');

file = [directory_base filesep 'brain_atlas.xlsx'];
ex = ExporterBrainAtlasXLS( ...
    'FILE', file, ...
    'BA', ba_pdfs ...
    );
ex.get('SAVE');
