%EXAMPLE_NEUROIMGING_2_RVS_T1W
% Script example pipeline neuroimaing (T1w) conversion to
% regional values (VOLUME)
clear variables %#ok<*NASGU>

%% Create dataset
atlas_path = [fileparts(which('group_roi_means_mri.xlsx')) filesep 'BN_Atlas_246_1d5mm.nii'];
% example_data_dir = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('group_roi_means_mri.xlsx')) filesep 'bna_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

bna_atlas = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-50-60.vois.xlsx')) filesep 'age-50-60'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age50_60 = im_gr_gm.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-40-50.vois.xlsx')) filesep 'age-40-50'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age40_50 = im_gr_gm.get('GR');


im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-30-40.vois.xlsx')) filesep 'age-30-40'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age30_40 = im_gr_gm.get('GR');


im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-18-30.vois.xlsx')) filesep 'age-18-30'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age18_30 = im_gr_gm.get('GR');



%% Convert neuroimaging data to probability density functions
ba_nifti_files = {
    atlas_path
    };

ba_mapping_files = {
    [fileparts(which('group_roi_means_mri.xlsx')) filesep  'bna_atlas_mapping.xlsx']
    };

brain_regions_to_convert = {};
convert_brain_regions_idx = 1:246; % cerebral all regions in bnas
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = bna_atlas.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

age50_60_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age50_60);

gr5060_pdf = age50_60_gr.get('GR_FUN');

age40_50_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age40_50);

gr4050_pdf = age40_50_gr.get('GR_FUN');

age30_40_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age30_40);

gr3040_pdf = age30_40_gr.get('GR_FUN');

age18_30_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age18_30);

gr1830_pdf = age18_30_gr.get('GR_FUN');
ba = age50_60_gr.get('BA');

%% convert correlation conn.
c5060 = ConverterPDFs2CON( ...
    'GR_PDFS', gr5060_pdf, ...
    'METHOD', 'correlation' ...
    );

gr_con5060 = c5060.get('GR_CON');


c3040 = ConverterPDFs2CON( ...
    'GR_PDFS', gr3040_pdf, ...
    'METHOD', 'correlation' ...
    );

gr_con3040 = c3040.get('GR_CON');

c1830 = ConverterPDFs2CON( ...
    'GR_PDFS', gr1830_pdf, ...
    'METHOD', 'correlation' ...
    );

gr_con1830 = c1830.get('GR_CON');

c4050 = ConverterPDFs2CON( ...
    'GR_PDFS', gr4050_pdf, ...
    'METHOD', 'correlation' ...
    );

gr_con4050 = c4050.get('GR_CON');

%% export connectivity perturbation 
directory = [fileparts(which('jiawei_correlation')) filesep 'Converted data structural T1w ROI correlation'];
mkdir(directory);


directory1 = [directory filesep 'group_subjects_corr3040'];
mkdir(directory1);
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', directory1, ...
    'GR', gr_con3040 ...
    );
ex.get('SAVE');

directory2 = [directory filesep 'group_subjects_corr4050'];
mkdir(directory2);
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', directory2, ...
    'GR', gr_con4050 ...
    );
ex.get('SAVE');

directory3 = [directory filesep 'group_subjects_corr5060'];
mkdir(directory3);
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', directory3, ...
    'GR', gr_con5060 ...
    );
ex.get('SAVE');

file = [directory filesep 'brain_atlas.xlsx'];
ex = ExporterBrainAtlasXLS( ...
    'FILE', file, ...
    'BA', bna_atlas ...
    );
ex.get('SAVE');