%EXAMPLE_NEUROIMGING_2_RVS_T1W
% Script example pipeline neuroimaing (T1w) conversion to
% regional values (VOLUME)
clear variables %#ok<*NASGU>

%% Create dataset
atlas_path = [fileparts(which('group_roi_means_mri.xlsx')) filesep 'BN_Atlas_246_1d5mm.nii'];
% example_data_dir = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('group_roi_means_mri.xlsx')) filesep 'bna_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

bna_atlas = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-50-60.vois.xlsx')) filesep 'age-50-60'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age50_60 = im_gr_gm.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-40-50.vois.xlsx')) filesep 'age-40-50'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age40_50 = im_gr_gm.get('GR');


im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-30-40.vois.xlsx')) filesep 'age-30-40'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age30_40 = im_gr_gm.get('GR');


im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('age-18-30.vois.xlsx')) filesep 'age-18-30'], ...
    'MODALITY', 'mri', ...
    'TARGET', 'sub', ...
    'WAITBAR', true ...
    );

age18_30 = im_gr_gm.get('GR');



%% Convert neuroimaging data to probability density functions
ba_nifti_files = {
    atlas_path
    };

ba_mapping_files = {
    [fileparts(which('group_roi_means_mri.xlsx')) filesep  'bna_atlas_mapping.xlsx']
    };

brain_regions_to_convert = {};
convert_brain_regions_idx = 1:246; % cerebral all regions in bnas
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = bna_atlas.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

age50_60_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age50_60);

gr5060_pdf = age50_60_gr.get('GR_FUN');

age40_50_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age40_50);

gr4050_pdf = age40_50_gr.get('GR_FUN');

age30_40_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age30_40);

gr3040_pdf = age30_40_gr.get('GR_FUN');

age18_30_gr = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {bna_atlas}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
        'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'GR_NEUROIMAGING', age18_30);

gr1830_pdf = age18_30_gr.get('GR_FUN');
ba = age50_60_gr.get('BA');


%% Analysis ST WU
a_WU5060 = AnalyzeGroup_ST_WU( ...
    'GR', gr5060_pdf, ...
    'CORRELATION_RULE', Correlation.PEARSON ...
    );

a_WU3040 = AnalyzeGroup_ST_WU( ...
    'TEMPLATE', a_WU5060, ...
    'GR', gr3040 ...
    );

a_WU4050 = AnalyzeGroup_ST_WU( ...
    'TEMPLATE', a_WU5060, ...
    'GR', gr4050 ...
    );

a_WU1830 = AnalyzeGroup_ST_WU( ...
    'TEMPLATE', a_WU5060, ...
    'GR', gr1830 ...
    );


% measure calculation
g_WU5060 = a_WU5060.memorize('G'); % essential to memorize in case there are measures with non-default rules
strength_WU5060 = g_WU5060.get('MEASURE', 'Strength').get('M');
strength_av_WU5060 = g_WU5060.get('MEASURE', 'StrengthAv').get('M');
distance_WU5060 = g_WU5060.get('MEASURE', 'Distance').get('M');

g_WU3040 = a_WU3040.get('G');
strength_WU3040 = a_WU3040.get('MEASURE', 'Strength').get('M');
strength_av_WU3040 = a_WU3040.get('MEASURE', 'StrengthAv').get('M');
distance_WU3040 = a_WU3040.get('MEASURE', 'Distance').get('M');

g_WU4050 = a_WU4050.get('G');
strength_WU4050 = a_WU4050.get('MEASURE', 'Strength').get('M');
strength_av_WU4050 = a_WU4050.get('MEASURE', 'StrengthAv').get('M');
distance_WU4050 = a_WU4050.get('MEASURE', 'Distance').get('M');

g_WU1830 = a_WU1830.get('G');
strength_WU1830 = a_WU1830.get('MEASURE', 'Strength').get('M');
strength_av_WU1830 = a_WU1830.get('MEASURE', 'StrengthAv').get('M');
distance_WU1830 = a_WU1830.get('MEASURE', 'Distance').get('M');

% comparison
c_WU = CompareGroup( ...
    'P', 100, ...
    'A1', a_WU5060, ...
    'A2', a_WU1830, ...
    'WAITBAR', true, ...
    'VERBOSE', false, ...
    'MEMORIZE', true ...
    );

strength_WU_diff = c_WU.get('COMPARISON', 'Strength').get('DIFF');
strength_WU_p1 = c_WU.get('COMPARISON', 'Strength').get('P1');
strength_WU_p2 = c_WU.get('COMPARISON', 'Strength').get('P2');
strength_WU_cil = c_WU.get('COMPARISON', 'Strength').get('CIL');
strength_WU_ciu = c_WU.get('COMPARISON', 'Strength').get('CIU');

strength_av_WU_diff = c_WU.get('COMPARISON', 'StrengthAv').get('DIFF');
strength_av_WU_p1 = c_WU.get('COMPARISON', 'StrengthAv').get('P1');
strength_av_WU_p2 = c_WU.get('COMPARISON', 'StrengthAv').get('P2');
strength_av_WU_cil = c_WU.get('COMPARISON', 'StrengthAv').get('CIL');
strength_av_WU_ciu = c_WU.get('COMPARISON', 'StrengthAv').get('CIU');

distance_WU_diff = c_WU.get('COMPARISON', 'Distance').get('DIFF');
distance_WU_p1 = c_WU.get('COMPARISON', 'Distance').get('P1');
distance_WU_p2 = c_WU.get('COMPARISON', 'Distance').get('P2');
distance_WU_cil = c_WU.get('COMPARISON', 'Distance').get('CIL');
distance_WU_ciu = c_WU.get('COMPARISON', 'Distance').get('CIU');