%TEST_NNCLASSIFIERMLP_VOIS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nn = NNClassifierMLP_VOIs();
	 
	% get('ELCLASS')
	if isa(NNClassifierMLP_VOIs, 'ConcreteElement')
		assert(strcmp(NNClassifierMLP_VOIs().get('ELCLASS'), 'NNClassifierMLP_VOIs'), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs().get(''ELCLASS'') should return ''NNClassifierMLP_VOIs''.')
	end
	 
	% getBuild()
	assert(NNClassifierMLP_VOIs.getBuild() == 1 && NNClassifierMLP_VOIs.getBuild() > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getBuild() should return the NNClassifierMLP_VOIs build number.')
	assert(nn.getBuild() == 1 && nn.getBuild() > 0 , ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getBuild() should return the NNClassifierMLP_VOIs build number.')
	assert(Element.getBuild(nn) == 1 && Element.getBuild(nn) > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nn) should return the NNClassifierMLP_VOIs build number.')
	assert(Element.getBuild('NNClassifierMLP_VOIs') == 1 && Element.getBuild('NNClassifierMLP_VOIs') > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNClassifierMLP_VOIs'') should return the NNClassifierMLP_VOIs build number.')
	 
	% getClass()
	assert(strcmp(NNClassifierMLP_VOIs.getClass(), 'NNClassifierMLP_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getClass() should return ''NNClassifierMLP_VOIs''.')
	assert(strcmp(nn.getClass(), 'NNClassifierMLP_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getClass() should return ''NNClassifierMLP_VOIs''.')
	assert(strcmp(Element.getClass(nn), 'NNClassifierMLP_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nn) should return ''NNClassifierMLP_VOIs''.')
	assert(strcmp(Element.getClass('NNClassifierMLP_VOIs'), 'NNClassifierMLP_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNClassifierMLP_VOIs'') should return ''NNClassifierMLP_VOIs''.')
	 
	% getSubclasses()
	assert(isequal(NNClassifierMLP_VOIs.getSubclasses(), subclasses('NNClassifierMLP_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getSubclasses() should return the same result as subclasses(''NNClassifierMLP_VOIs'', [], [], true).')
	assert(isequal(nn.getSubclasses(), subclasses('NNClassifierMLP_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNClassifierMLP_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses(nn), subclasses('NNClassifierMLP_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nn) should return the same result as subclasses(''NNClassifierMLP_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNClassifierMLP_VOIs'), subclasses('NNClassifierMLP_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNClassifierMLP_VOIs'') should return the same result as subclasses(''NNClassifierMLP_VOIs'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(NNClassifierMLP_VOIs.getProps(), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(nn.getProps(), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(Element.getProps(nn), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nn) should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(Element.getProps('NNClassifierMLP_VOIs'), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNClassifierMLP_VOIs'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNClassifierMLP_VOIs.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getProps(category) does not work.')
	tmp = cellfun(@(category) nn.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nn, category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nn, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNClassifierMLP_VOIs', category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNClassifierMLP_VOIs'', category) does not work.')
	 
	% getPropNumber()
	assert(NNClassifierMLP_VOIs.getPropNumber() == length(NNClassifierMLP_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getPropNumber() should return the number of properties.')
	assert(nn.getPropNumber() == length(NNClassifierMLP_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nn) == length(NNClassifierMLP_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nn) should return the number of properties.')
	assert(Element.getPropNumber('NNClassifierMLP_VOIs') == length(NNClassifierMLP_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNClassifierMLP_VOIs'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNClassifierMLP_VOIs.getPropNumber(category), categories)) == NNClassifierMLP_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nn.getPropNumber(category), categories)) == NNClassifierMLP_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nn, category), categories)) == NNClassifierMLP_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nn, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNClassifierMLP_VOIs', category), categories)) == NNClassifierMLP_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNClassifierMLP_VOIs'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNClassifierMLP_VOIs.existsProp(NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.existsProp(prop) does not work.')
	assert(~nn.existsProp(NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.existsProp(prop) does not work.')
	assert(~Element.existsProp(nn, NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nn, prop) does not work.')
	assert(~Element.existsProp('NNClassifierMLP_VOIs', NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
	assert_with_error('NNClassifierMLP_VOIs.existsProp(NaN)', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], nn)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], nn)
	assert_with_error('Element.existsProp(''NNClassifierMLP_VOIs'', NaN)', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		assert(NNClassifierMLP_VOIs.existsProp(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.existsProp(prop) does not work.')
		assert(nn.existsProp(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.existsProp(prop) does not work.')
		assert(Element.existsProp(nn, prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nn, prop) does not work.')
		assert(Element.existsProp('NNClassifierMLP_VOIs', prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNClassifierMLP_VOIs'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNClassifierMLP_VOIs.existsTag(''), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.existsTag(tag) does not work.')
	assert(~nn.existsTag(''), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'nn.existsTag(tag) does not work.')
	assert(~Element.existsTag(nn, ''), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nn, tag) does not work.')
	assert(~Element.existsTag('NNClassifierMLP_VOIs', ''), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNClassifierMLP_VOIs'', tag) does not work.')
	 
	assert_with_error('NNClassifierMLP_VOIs.existsTag('''')', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], nn)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], nn)
	assert_with_error('Element.existsTag(''NNClassifierMLP_VOIs'', '''')', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
		assert(NNClassifierMLP_VOIs.existsTag(tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.existsTag(tag) does not work.')
		assert(nn.existsTag(tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.existsTag(tag) does not work.')
		assert(Element.existsTag(nn, tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nn, tga) does not work.')
		assert(Element.existsTag('NNClassifierMLP_VOIs', tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		assert(NNClassifierMLP_VOIs.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropProp(prop) does not work.')
		assert(nn.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nn, prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nn, prop) does not work.')
		assert(Element.getPropProp('NNClassifierMLP_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
		tag = nn.getPropTag(prop);
		assert(NNClassifierMLP_VOIs.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropProp(tag) does not work.')
		assert(nn.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nn, tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nn, tag) does not work.')
		assert(Element.getPropProp('NNClassifierMLP_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		assert(strcmp(NNClassifierMLP_VOIs.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropTag(prop) does not work.')
		assert(strcmp(nn.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nn, prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nn, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNClassifierMLP_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
		assert(strcmp(NNClassifierMLP_VOIs.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropTag(tag) does not work.')
		assert(strcmp(nn.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nn, tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nn, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNClassifierMLP_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		assert(Category.existsCategory(NNClassifierMLP_VOIs.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nn.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nn, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
		assert(Category.existsCategory(NNClassifierMLP_VOIs.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nn.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nn, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		assert(Format.existsFormat(NNClassifierMLP_VOIs.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nn.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nn, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
		assert(Format.existsFormat(NNClassifierMLP_VOIs.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nn.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nn, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		assert(ischar(NNClassifierMLP_VOIs.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropDescription(prop) does not work.')
		assert(ischar(nn.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nn, prop) does not work.')
		assert(ischar(Element.getPropDescription(nn, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNClassifierMLP_VOIs'', prop) does not work.')
	 
		assert(ischar(NNClassifierMLP_VOIs.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.getPropDescription(tag) does not work.')
		assert(ischar(nn.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nn, tag) does not work.')
		assert(ischar(Element.getPropDescription(nn, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNClassifierMLP_VOIs'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		settings = NNClassifierMLP_VOIs.getPropSettings(prop);
		settings = nn.getPropSettings(prop);
		settings = Element.getPropSettings(nn, prop);
		settings = Element.getPropSettings('NNClassifierMLP_VOIs', prop);
	 
		settings = NNClassifierMLP_VOIs.getPropSettings(tag);
		settings = nn.getPropSettings(tag);
		settings = Element.getPropSettings(nn, tag);
		settings = Element.getPropSettings('NNClassifierMLP_VOIs', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		default = NNClassifierMLP_VOIs.getPropDefault(prop);
		default = nn.getPropDefault(prop);
		default = Element.getPropDefault(nn, prop);
		default = Element.getPropDefault('NNClassifierMLP_VOIs', prop);
	 
		default = NNClassifierMLP_VOIs.getPropDefault(tag);
		default = nn.getPropDefault(tag);
		default = Element.getPropDefault(nn, tag);
		default = Element.getPropDefault('NNClassifierMLP_VOIs', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		conditioned_default = NNClassifierMLP_VOIs.getPropDefaultConditioned(prop);
		conditioned_default = nn.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nn, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNClassifierMLP_VOIs', prop);
	 
		conditioned_default = NNClassifierMLP_VOIs.getPropDefaultConditioned(tag);
		conditioned_default = nn.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nn, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNClassifierMLP_VOIs', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		tag = nn.getPropTag(prop);
	 
		assert(~NNClassifierMLP_VOIs.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.checkProp(prop, value) does not work.')
		assert(~nn.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nn, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nn, prop, value) does not work.')
		assert(~Element.checkProp('NNClassifierMLP_VOIs', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_VOIs'', prop, value) does not work.')
	 
		assert_with_error('NNClassifierMLP_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], prop, nn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], prop, nn)
		assert_with_error('Element.checkProp(''NNClassifierMLP_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNClassifierMLP_VOIs.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.checkProp(tag, value) does not work.')
		assert(~nn.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nn, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nn, tag, value) does not work.')
		assert(~Element.checkProp('NNClassifierMLP_VOIs', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_VOIs'', tag, value) does not work.')
	 
		assert_with_error('NNClassifierMLP_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], tag, nn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], tag, nn)
		assert_with_error('Element.checkProp(''NNClassifierMLP_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNClassifierMLP_VOIs.checkProp(prop, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.checkProp(prop, <conditioned default value>) does not work.')
		assert(nn.checkProp(prop, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nn, prop, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nn, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNClassifierMLP_VOIs', prop, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_VOIs'', prop, <conditioned default value>) does not work.')
	 
		assert(NNClassifierMLP_VOIs.checkProp(tag, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.checkProp(tag, <conditioned default value>) does not work.')
		assert(nn.checkProp(tag, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'nn.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nn, tag, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nn, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNClassifierMLP_VOIs', tag, Element.getPropDefaultConditioned(NNClassifierMLP_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_VOIs'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_VOIs.D_VOIS])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nn.getr(prop) == NNClassifierMLP_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_VOIs.getCategoryName(NNClassifierMLP_VOIs.getPropCategory(prop)) ', NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nn.getr(TAG) == NNClassifierMLP_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_VOIs.getCategoryName(NNClassifierMLP_VOIs.getPropCategory(prop)) ', NNClassifierMLP_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nn.getPropSettings(prop))
					assert( ...
						nn.checkFormat(nn.getPropFormat(prop), nn.get(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nn.checkFormat(nn.getPropFormat(prop), nn.get(prop), nn.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nn.getr(prop) == NNClassifierMLP_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_VOIs.getCategoryName(NNClassifierMLP_VOIs.getPropCategory(prop)) ', NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nn.getr(TAG) == NNClassifierMLP_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_VOIs.getCategoryName(NNClassifierMLP_VOIs.getPropCategory(prop)) ', NNClassifierMLP_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_VOIs']);
				assert( ...
					~isa(nn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nn.getPropSettings(prop))
					assert( ...
						nn.checkFormat(nn.getPropFormat(prop), nn.get(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nn.checkFormat(nn.getPropFormat(prop), nn.get(prop), nn.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nn.getr(prop), NNClassifierMLP_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNClassifierMLP_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nn.getr(TAG), NNClassifierMLP_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNClassifierMLP_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNClassifierMLP_VOIs.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_VOIs.D_VOIS])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nn.checkFormat(nn.getPropFormat(prop), nn.getr(prop),nn.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_VOIs']);
				assert( ...
					~isa(nn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_VOIs']);
	% 			assert( ...
	% 				~isa(nn.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nn.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nn.checkFormat(nn.getPropFormat(prop), nn.getr(prop),nn.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_VOIs']);
				assert( ...
					~isa(nn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nn.checkFormat(nn.getPropFormat(prop), nn.getr(prop),nn.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nn.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_VOIs');
					delete(ancestor(nn.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNClassifierMLP_VOIs.getProps(Category.RESULT))
		for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
	 
			% excluded props
			if any(prop == [NNClassifierMLP_VOIs.D_VOIS])
				continue
			end
	 
			switch NNClassifierMLP_VOIs.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nn.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nn.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs();
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		assert( ...
			~nn.isLocked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nn.isLocked(TAG), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nn.lock()
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nn.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nn.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs();
	 
	warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_VOIs');
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		nn.lock(prop)
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nn.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nn.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs();
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		assert( ...
			nn.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nn.isChecked(TAG), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nn.unchecked()
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		assert( ...
			~nn.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nn.checked()
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		assert( ...
			nn.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_VOIs.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNClassifierMLP_VOIs
	nn_0 = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	% NNClassifierMLP_VOIs with 1st callbacks
	nn_1 = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, nn_0.getCallback(4), ..., ...
		NNClassifierMLP_VOIs.ID, nn_0.getCallback(5), ..., ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, nn_0.getCallback(9), ..., ...
		NNClassifierMLP_VOIs.DP_CLASSES, nn_0.getCallback(10), ..., ...
		NNClassifierMLP_VOIs.EPOCHS, nn_0.getCallback(11), ..., ...
		NNClassifierMLP_VOIs.BATCH, nn_0.getCallback(12), ..., ...
		NNClassifierMLP_VOIs.SHUFFLE, nn_0.getCallback(13), ..., ...
		NNClassifierMLP_VOIs.SOLVER, nn_0.getCallback(14), ..., ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, nn_0.getCallback(19), ..., ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, nn_0.getCallback(23), ..., ...
		NNClassifierMLP_VOIs.WAITBAR, nn_0.getCallback(24), ..., ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, nn_0.getCallback(25), ..., ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, nn_0.getCallback(27), ..., ...
		NNClassifierMLP_VOIs.D_VOIS, nn_0.getCallback(28), ..., ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	prop_number = NNClassifierMLP_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nn_1.get(prop), nn_0.get(prop)) && ~isa(nn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNClassifierMLP_VOIs with 2nd callbacks
	nn_2 = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, nn_1.getCallback(4), ..., ...
		NNClassifierMLP_VOIs.ID, nn_1.getCallback(5), ..., ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, nn_1.getCallback(9), ..., ...
		NNClassifierMLP_VOIs.DP_CLASSES, nn_1.getCallback(10), ..., ...
		NNClassifierMLP_VOIs.EPOCHS, nn_1.getCallback(11), ..., ...
		NNClassifierMLP_VOIs.BATCH, nn_1.getCallback(12), ..., ...
		NNClassifierMLP_VOIs.SHUFFLE, nn_1.getCallback(13), ..., ...
		NNClassifierMLP_VOIs.SOLVER, nn_1.getCallback(14), ..., ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, nn_1.getCallback(19), ..., ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, nn_1.getCallback(23), ..., ...
		NNClassifierMLP_VOIs.WAITBAR, nn_1.getCallback(24), ..., ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, nn_1.getCallback(25), ..., ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, nn_1.getCallback(27), ..., ...
		NNClassifierMLP_VOIs.D_VOIS, nn_1.getCallback(28), ..., ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	prop_number = NNClassifierMLP_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nn_2.get(prop), nn_0.get(prop)) && ~isa(nn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNClassifierMLP_VOIs with 3rd callbacks
	nn_3 = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, nn_2.getCallback(4), ..., ...
		NNClassifierMLP_VOIs.ID, nn_2.getCallback(5), ..., ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, nn_2.getCallback(9), ..., ...
		NNClassifierMLP_VOIs.DP_CLASSES, nn_2.getCallback(10), ..., ...
		NNClassifierMLP_VOIs.EPOCHS, nn_2.getCallback(11), ..., ...
		NNClassifierMLP_VOIs.BATCH, nn_2.getCallback(12), ..., ...
		NNClassifierMLP_VOIs.SHUFFLE, nn_2.getCallback(13), ..., ...
		NNClassifierMLP_VOIs.SOLVER, nn_2.getCallback(14), ..., ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, nn_2.getCallback(19), ..., ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, nn_2.getCallback(23), ..., ...
		NNClassifierMLP_VOIs.WAITBAR, nn_2.getCallback(24), ..., ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, nn_2.getCallback(25), ..., ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, nn_2.getCallback(27), ..., ...
		NNClassifierMLP_VOIs.D_VOIS, nn_2.getCallback(28), ..., ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	prop_number = NNClassifierMLP_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nn_3.get(prop), nn_0.get(prop)) && ~isa(nn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nn = NNClassifierMLP_VOIs();
	 
	nn_copy = nn.copy();
	 
	assert(nn_copy ~= nn, ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nn_copy, nn), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		value = nn.getr(prop);
		value_copy = nn_copy.getr(prop);
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nn_copy.isLocked(prop) == nn.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nn_copy.isChecked(prop) == nn.isChecked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nn_copy.getPropSeed(prop) == nn.getPropSeed(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		if NNClassifierMLP_VOIs.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_VOIs']);
			% nn.memorize(prop);
			% warning(warning_backup)
		elseif NNClassifierMLP_VOIs.getPropCategory(prop) == Category.EVANESCENT && nn.getPropFormat(prop) == Format.HANDLE
			nn.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_VOIs');
			delete(ancestor(nn.get(prop), 'figure'))
			warning(warning_backup)
		else
			nn.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nn_copy = nn.copy();
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		value = nn.getr(prop);
		value_copy = nn_copy.getr(prop);
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nn_copy.isLocked(prop) == nn.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nn_copy.isChecked(prop) == nn.isChecked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nn_copy.getPropSeed(prop) == nn.getPropSeed(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nn_0 = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, nn_0.getCallback(4), ..., ...
		NNClassifierMLP_VOIs.ID, nn_0.getCallback(5), ..., ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, nn_0.getCallback(9), ..., ...
		NNClassifierMLP_VOIs.DP_CLASSES, nn_0.getCallback(10), ..., ...
		NNClassifierMLP_VOIs.EPOCHS, nn_0.getCallback(11), ..., ...
		NNClassifierMLP_VOIs.BATCH, nn_0.getCallback(12), ..., ...
		NNClassifierMLP_VOIs.SHUFFLE, nn_0.getCallback(13), ..., ...
		NNClassifierMLP_VOIs.SOLVER, nn_0.getCallback(14), ..., ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, nn_0.getCallback(19), ..., ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, nn_0.getCallback(23), ..., ...
		NNClassifierMLP_VOIs.WAITBAR, nn_0.getCallback(24), ..., ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, nn_0.getCallback(25), ..., ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, nn_0.getCallback(27), ..., ...
		NNClassifierMLP_VOIs.D_VOIS, nn_0.getCallback(28), ..., ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	nn_copy = nn.copy();
	nn_0_copy = nn_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
		value = nn.getr(prop);
		value_copy = nn_copy.getr(prop);
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nn_0.getCallback(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The callback should be obtained from NNClassifierMLP_VOIs.getCallback().' ...
						)
					assert( ...
						value_copy == nn_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The callback should be obtained from NNClassifierMLP_VOIs.getCallback().' ...
						)
				end
	 
					assert( ...
						nn_copy.isLocked(prop) == nn.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nn_copy.isChecked(prop) == nn.isChecked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nn_copy.getPropSeed(prop) == nn.getPropSeed(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn_template = NNClassifierMLP_VOIs();
	nn = NNClassifierMLP_VOIs('TEMPLATE', nn_template);
	 
	for prop = 1:1:NNClassifierMLP_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_VOIs.D_VOIS])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_VOIs.getPropTag(prop));
		switch NNClassifierMLP_VOIs.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNClassifierMLP_VOIs.TEMPLATE
					assert( ...
						isa(nn.getr(prop), 'NNClassifierMLP_VOIs'), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs.getr(''TEMPLATE'') should be a NNClassifierMLP_VOIs element.' ...
						)
					assert( ...
						isa(nn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nn.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nn.getr(prop).get('EL') == nn_template && nn.getr(prop).get('PROP') == prop && strcmp(nn.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs.getr(' TAG ') should be a Callback to nn_template.' TAG '.'] ...
						)
					assert( ...
						isa(nn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nn_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_VOIs TEMPLATE does not work. NNClassifierMLP_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnclassifiermlp_vois_to_be_erased.b2'];
	 
	Element.save(nn, filename)
	 
	nn_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nn.copy(), nn_loaded), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.save(nn) and/or NNClassifierMLP_VOIs.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nn = NNClassifierMLP_VOIs( ...
		NNClassifierMLP_VOIs.ELCLASS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.NAME, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.DESCRIPTION, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TEMPLATE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.TEMPLATE), ...
		NNClassifierMLP_VOIs.ID, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.ID), ...
		NNClassifierMLP_VOIs.LABEL, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LABEL), ...
		NNClassifierMLP_VOIs.NOTES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.NOTES), ...
		NNClassifierMLP_VOIs.TOSTRING, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.D, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D), ...
		NNClassifierMLP_VOIs.DP_CLASSES, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.DP_CLASSES), ...
		NNClassifierMLP_VOIs.EPOCHS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.EPOCHS), ...
		NNClassifierMLP_VOIs.BATCH, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.BATCH), ...
		NNClassifierMLP_VOIs.SHUFFLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SHUFFLE), ...
		NNClassifierMLP_VOIs.SOLVER, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.SOLVER), ...
		NNClassifierMLP_VOIs.MODEL, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.INPUTS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGETS, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TRAIN, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VERBOSE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VERBOSE), ...
		NNClassifierMLP_VOIs.PLOT_TRAINING, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.PLOT_TRAINING), ...
		NNClassifierMLP_VOIs.PREDICT, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.TARGET_CLASSES, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.LAYERS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.LAYERS), ...
		NNClassifierMLP_VOIs.WAITBAR, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.WAITBAR), ...
		NNClassifierMLP_VOIs.INTERRUPTIBLE, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.INTERRUPTIBLE), ...
		NNClassifierMLP_VOIs.FEATURE_IMPORTANCE, NNClassifierMLP_VOIs.getNoValue(), ...
		NNClassifierMLP_VOIs.VOI_SELECTION, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.VOI_SELECTION), ...
		NNClassifierMLP_VOIs.D_VOIS, NNClassifierMLP_VOIs.getPropDefault(NNClassifierMLP_VOIs.D_VOIS), ...
		NNClassifierMLP_VOIs.VOI_INPUT, NNClassifierMLP_VOIs.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(nn);
	[nn_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nn_dec ~= nn, ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_VOIs.encodeJSON() or NNClassifierMLP_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNClassifierMLP_VOIs.getPropFormat(prop), num2cell(NNClassifierMLP_VOIs.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNClassifierMLP_VOIs.getPropFormat(prop), num2cell(NNClassifierMLP_VOIs.getProps())) == Format.NET)
		assert(isequal(nn_dec, nn), ...
			[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_VOIs.encodeJSON() or NNClassifierMLP_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: train the MLPClassifier VOI with example data
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	% Step 1: Ensure example data exists
	data_dir = [fileparts(which('NNDataPoint_VOIs')) filesep 'Example data NN CLA CON XLS VOIs'];
	if ~isfile([data_dir filesep 'atlas.xlsx'])
	    create_data_NN_CLA_CON_XLS_VOIs(data_dir); % Generate example files with VOIs
	end
	
	% Step 2: Load Brain Atlas
	im_ba = ImporterBrainAtlasXLS('FILE', [data_dir filesep 'atlas.xlsx'], 'WAITBAR', true);
	ba = im_ba.get('BA');
	
	% Step 3: Load Groups of SubjectCON (primary connectivity data)
	im_gr1 = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [data_dir filesep 'CON_Group_1_XLS'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	);
	gr1 = im_gr1.get('GR');
	
	im_gr2 = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [data_dir filesep 'CON_Group_2_XLS'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	);
	gr2 = im_gr2.get('GR');
	
	% Step 4: Create NNDataPoint_CON_CLA for primary connectivity data
	% Group 1
	sub_dict1 = gr1.get('SUB_DICT');
	sub_list1 = sub_dict1.get('IT_LIST');
	[~, group_folder_name1] = fileparts(im_gr1.get('DIRECTORY'));
	it_list1 = cellfun(@(x) NNDataPoint_CON_CLA( ...
	    'ID', x.get('ID'), ...
	    'SUB', x, ...
	    'TARGET_CLASS', {group_folder_name1}), ...
	    sub_list1, 'UniformOutput', false);
	
	% Group 2
	sub_dict2 = gr2.get('SUB_DICT');
	sub_list2 = sub_dict2.get('IT_LIST');
	[~, group_folder_name2] = fileparts(im_gr2.get('DIRECTORY'));
	it_list2 = cellfun(@(x) NNDataPoint_CON_CLA( ...
	    'ID', x.get('ID'), ...
	    'SUB', x, ...
	    'TARGET_CLASS', {group_folder_name2}), ...
	    sub_list2, 'UniformOutput', false);
	
	% Create IndexedDictionary for primary data
	dp_list1 = IndexedDictionary('IT_CLASS', 'NNDataPoint_CON_CLA', 'IT_LIST', it_list1);
	dp_list2 = IndexedDictionary('IT_CLASS', 'NNDataPoint_CON_CLA', 'IT_LIST', it_list2);
	
	% Create NNDataset for primary data
	d1 = NNDataset('DP_CLASS', 'NNDataPoint_CON_CLA', 'DP_DICT', dp_list1);
	d2 = NNDataset('DP_CLASS', 'NNDataPoint_CON_CLA', 'DP_DICT', dp_list2);
	
	% Split primary datasets into training and test sets (70% training, 30% test)
	d_split1 = NNDatasetSplit('D', d1, 'SPLIT', {1:1:5 6:1:10});
	d_split2 = NNDatasetSplit('D', d2, 'SPLIT', {1:1:5 6:1:10});
	
	% Combine training and test sets for primary data
	d_training = NNDatasetCombine('D_LIST', {d_split1.get('D_LIST_IT', 1), d_split2.get('D_LIST_IT', 1)}).get('D');
	d_test = NNDatasetCombine('D_LIST', {d_split1.get('D_LIST_IT', 2), d_split2.get('D_LIST_IT', 2)}).get('D');
	
	% Step 5: Create NNDataPoint_VOIs for VOI data  data using gr.get('VOIS')
	% Group 1
	it_list_voi1 = cellfun(@(sub) NNDataPoint_VOIs( ...
	    'ID', sub.get('ID'), ...
	    'VOI_DICT', IndexedDictionary( ...
	        'ID', 'subject_idict', ...
	        'IT_CLASS', 'SubjectCON', ... % Adjusted to match SubjectCON
	        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
	        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
	    ), ...
	    'TARGET_CLASS', {group_folder_name1} ...
	), sub_list1, 'UniformOutput', false);
	
	% Group 2
	it_list_voi2 = cellfun(@(sub) NNDataPoint_VOIs( ...
	    'ID', sub.get('ID'), ...
	    'VOI_DICT', IndexedDictionary( ...
	        'ID', 'subject_idict', ...
	        'IT_CLASS', 'SubjectCON', ...
	        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
	        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
	    ), ...
	    'TARGET_CLASS', {group_folder_name2} ...
	), sub_list2, 'UniformOutput', false);
	
	% Create IndexedDictionary for VOI data
	voi_dp_list1 = IndexedDictionary('IT_CLASS', 'NNDataPoint_VOIs', 'IT_LIST', it_list_voi1);
	voi_dp_list2 = IndexedDictionary('IT_CLASS', 'NNDataPoint_VOIs', 'IT_LIST', it_list_voi2);
	
	% Create NNDataset for VOI data
	d_vois1 = NNDataset('DP_CLASS', 'NNDataPoint_VOIs', 'DP_DICT', voi_dp_list1);
	d_vois2 = NNDataset('DP_CLASS', 'NNDataPoint_VOIs', 'DP_DICT', voi_dp_list2);
	
	% Split VOI datasets into training and test sets (same split as primary data)
	d_vois_split1 = NNDatasetSplit('D', d_vois1, 'SPLIT', {1:1:5 6:1:10});
	d_vois_split2 = NNDatasetSplit('D', d_vois2, 'SPLIT', {1:1:5 6:1:10});
	
	% Combine training and test sets for VOI data
	d_vois_training = NNDatasetCombine('D_LIST', {d_vois_split1.get('D_LIST_IT', 1), d_vois_split2.get('D_LIST_IT', 1)}).get('D');
	d_vois_test = NNDatasetCombine('D_LIST', {d_vois_split1.get('D_LIST_IT', 2), d_vois_split2.get('D_LIST_IT', 2)}).get('D');
	
	% Step 6: Define and train the neural network with VOIs
	nn = NNClassifierMLP_VOIs( ...
	    'D', d_training, ...
	    'D_VOIS', d_vois_training, ...
	    'LAYERS', [128 128], ...
	    'VOI_SELECTION', {'Age', 'Sex'} ...
	);
	nn.get('TRAIN');
	
	% Check if the number of fully connected layers matches the specified LAYERS property
	trained_model = nn.get('MODEL');
	assert(length(nn.get('LAYERS')) == sum(contains({trained_model.Layers.Name}, 'Dense')) - 1, ...
	    [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	    'NNClassifierMLP_VOIs does not construct the layers correctly. The number of hidden layers should match the specified LAYERS property.' ...
	);
	
	% Check if the number of fully connected layers matches the specified LAYERS property
	trained_model = nn.get('MODEL');
	assert(length(nn.get('LAYERS')) == sum(contains({trained_model.Layers.Name}, 'Dense')) - 1, ...
	    [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	    'NNClassifierMLP_VOIs does not construct the layers correctly. The number of hidden layers should match the specified LAYERS property.' ...
	);
	D = nn.get('D');
	D_VOIS = nn.get('D_VOIS');
	D_DP_DICT_IT = cellfun(@(x)  x.get('ID'), D.get('DP_DICT').get('IT_LIST'), 'UniformOutput',false);
	DVOIS_VOI= cellfun(@(x)  x.get('VOI_DICT'), D_VOIS.get('DP_DICT').get('IT_LIST'), 'UniformOutput',false);
	DVOIS_ID= cellfun(@(x)  x.get('ID'), D_VOIS.get('DP_DICT').get('IT_LIST'), 'UniformOutput',false);
	is_same_order = isequal(DVOIS_ID, D_DP_DICT_IT);
	assert(is_same_order, ...
	    [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	    'NNClassifierMLP_VOIs does not have coherent voi id and connectivity id.' ...
	);
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
		[' When testing NNClassifierMLP_VOIs no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

