%TEST_NNDATAPOINT_VOIS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dp = NNDataPoint_VOIs();
	 
	% get('ELCLASS')
	if isa(NNDataPoint_VOIs, 'ConcreteElement')
		assert(strcmp(NNDataPoint_VOIs().get('ELCLASS'), 'NNDataPoint_VOIs'), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs().get(''ELCLASS'') should return ''NNDataPoint_VOIs''.')
	end
	 
	% getBuild()
	assert(NNDataPoint_VOIs.getBuild() == 1 && NNDataPoint_VOIs.getBuild() > 0, ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getBuild() should return the NNDataPoint_VOIs build number.')
	assert(dp.getBuild() == 1 && dp.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getBuild() should return the NNDataPoint_VOIs build number.')
	assert(Element.getBuild(dp) == 1 && Element.getBuild(dp) > 0, ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dp) should return the NNDataPoint_VOIs build number.')
	assert(Element.getBuild('NNDataPoint_VOIs') == 1 && Element.getBuild('NNDataPoint_VOIs') > 0, ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDataPoint_VOIs'') should return the NNDataPoint_VOIs build number.')
	 
	% getClass()
	assert(strcmp(NNDataPoint_VOIs.getClass(), 'NNDataPoint_VOIs'), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getClass() should return ''NNDataPoint_VOIs''.')
	assert(strcmp(dp.getClass(), 'NNDataPoint_VOIs'), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getClass() should return ''NNDataPoint_VOIs''.')
	assert(strcmp(Element.getClass(dp), 'NNDataPoint_VOIs'), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dp) should return ''NNDataPoint_VOIs''.')
	assert(strcmp(Element.getClass('NNDataPoint_VOIs'), 'NNDataPoint_VOIs'), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDataPoint_VOIs'') should return ''NNDataPoint_VOIs''.')
	 
	% getSubclasses()
	assert(isequal(NNDataPoint_VOIs.getSubclasses(), subclasses('NNDataPoint_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getSubclasses() should return the same result as subclasses(''NNDataPoint_VOIs'', [], [], true).')
	assert(isequal(dp.getSubclasses(), subclasses('NNDataPoint_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDataPoint_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses(dp), subclasses('NNDataPoint_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dp) should return the same result as subclasses(''NNDataPoint_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDataPoint_VOIs'), subclasses('NNDataPoint_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDataPoint_VOIs'') should return the same result as subclasses(''NNDataPoint_VOIs'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(NNDataPoint_VOIs.getProps(), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(dp.getProps(), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(Element.getProps(dp), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dp) should return a row vector [1:1:N].')
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(Element.getProps('NNDataPoint_VOIs'), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDataPoint_VOIs'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDataPoint_VOIs.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getProps(category) does not work.')
	tmp = cellfun(@(category) dp.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dp, category), categories, 'UniformOutput', false);
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dp, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDataPoint_VOIs', category), categories, 'UniformOutput', false);
	assert(isempty(NNDataPoint_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDataPoint_VOIs.getProps())), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDataPoint_VOIs'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDataPoint_VOIs.getPropNumber() == length(NNDataPoint_VOIs.getProps()), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getPropNumber() should return the number of properties.')
	assert(dp.getPropNumber() == length(NNDataPoint_VOIs.getProps()), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dp) == length(NNDataPoint_VOIs.getProps()), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dp) should return the number of properties.')
	assert(Element.getPropNumber('NNDataPoint_VOIs') == length(NNDataPoint_VOIs.getProps()), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDataPoint_VOIs'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDataPoint_VOIs.getPropNumber(category), categories)) == NNDataPoint_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dp.getPropNumber(category), categories)) == NNDataPoint_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dp, category), categories)) == NNDataPoint_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dp, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDataPoint_VOIs', category), categories)) == NNDataPoint_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDataPoint_VOIs'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDataPoint_VOIs.existsProp(NaN), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.existsProp(prop) does not work.')
	assert(~dp.existsProp(NaN), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.existsProp(prop) does not work.')
	assert(~Element.existsProp(dp, NaN), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dp, prop) does not work.')
	assert(~Element.existsProp('NNDataPoint_VOIs', NaN), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDataPoint_VOIs'', prop) does not work.')
	 
	assert_with_error('NNDataPoint_VOIs.existsProp(NaN)', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], dp)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], dp)
	assert_with_error('Element.existsProp(''NNDataPoint_VOIs'', NaN)', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		assert(NNDataPoint_VOIs.existsProp(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.existsProp(prop) does not work.')
		assert(dp.existsProp(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.existsProp(prop) does not work.')
		assert(Element.existsProp(dp, prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dp, prop) does not work.')
		assert(Element.existsProp('NNDataPoint_VOIs', prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDataPoint_VOIs'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDataPoint_VOIs.existsTag(''), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.existsTag(tag) does not work.')
	assert(~dp.existsTag(''), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'dp.existsTag(tag) does not work.')
	assert(~Element.existsTag(dp, ''), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dp, tag) does not work.')
	assert(~Element.existsTag('NNDataPoint_VOIs', ''), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDataPoint_VOIs'', tag) does not work.')
	 
	assert_with_error('NNDataPoint_VOIs.existsTag('''')', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], dp)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], dp)
	assert_with_error('Element.existsTag(''NNDataPoint_VOIs'', '''')', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
		assert(NNDataPoint_VOIs.existsTag(tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.existsTag(tag) does not work.')
		assert(dp.existsTag(tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.existsTag(tag) does not work.')
		assert(Element.existsTag(dp, tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dp, tga) does not work.')
		assert(Element.existsTag('NNDataPoint_VOIs', tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		assert(NNDataPoint_VOIs.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropProp(prop) does not work.')
		assert(dp.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dp, prop) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dp, prop) does not work.')
		assert(Element.getPropProp('NNDataPoint_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDataPoint_VOIs'', prop) does not work.')
	 
		tag = dp.getPropTag(prop);
		assert(NNDataPoint_VOIs.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropProp(tag) does not work.')
		assert(dp.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dp, tag) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dp, tag) does not work.')
		assert(Element.getPropProp('NNDataPoint_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		assert(strcmp(NNDataPoint_VOIs.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropTag(prop) does not work.')
		assert(strcmp(dp.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dp, prop), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dp, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDataPoint_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDataPoint_VOIs'', prop) does not work.')
	 
		assert(strcmp(NNDataPoint_VOIs.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropTag(tag) does not work.')
		assert(strcmp(dp.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dp, tag), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dp, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDataPoint_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDataPoint_VOIs.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dp.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dp, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDataPoint_VOIs'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDataPoint_VOIs.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dp.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dp, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDataPoint_VOIs.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dp.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dp, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDataPoint_VOIs'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDataPoint_VOIs.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dp.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dp, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		assert(ischar(NNDataPoint_VOIs.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropDescription(prop) does not work.')
		assert(ischar(dp.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dp, prop) does not work.')
		assert(ischar(Element.getPropDescription(dp, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDataPoint_VOIs'', prop) does not work.')
	 
		assert(ischar(NNDataPoint_VOIs.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.getPropDescription(tag) does not work.')
		assert(ischar(dp.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dp, tag) does not work.')
		assert(ischar(Element.getPropDescription(dp, tag)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDataPoint_VOIs'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		settings = NNDataPoint_VOIs.getPropSettings(prop);
		settings = dp.getPropSettings(prop);
		settings = Element.getPropSettings(dp, prop);
		settings = Element.getPropSettings('NNDataPoint_VOIs', prop);
	 
		settings = NNDataPoint_VOIs.getPropSettings(tag);
		settings = dp.getPropSettings(tag);
		settings = Element.getPropSettings(dp, tag);
		settings = Element.getPropSettings('NNDataPoint_VOIs', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		default = NNDataPoint_VOIs.getPropDefault(prop);
		default = dp.getPropDefault(prop);
		default = Element.getPropDefault(dp, prop);
		default = Element.getPropDefault('NNDataPoint_VOIs', prop);
	 
		default = NNDataPoint_VOIs.getPropDefault(tag);
		default = dp.getPropDefault(tag);
		default = Element.getPropDefault(dp, tag);
		default = Element.getPropDefault('NNDataPoint_VOIs', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		conditioned_default = NNDataPoint_VOIs.getPropDefaultConditioned(prop);
		conditioned_default = dp.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dp, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDataPoint_VOIs', prop);
	 
		conditioned_default = NNDataPoint_VOIs.getPropDefaultConditioned(tag);
		conditioned_default = dp.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dp, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDataPoint_VOIs', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		tag = dp.getPropTag(prop);
	 
		assert(~NNDataPoint_VOIs.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.checkProp(prop, value) does not work.')
		assert(~dp.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dp, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dp, prop, value) does not work.')
		assert(~Element.checkProp('NNDataPoint_VOIs', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDataPoint_VOIs'', prop, value) does not work.')
	 
		assert_with_error('NNDataPoint_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], prop, dp)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], prop, dp)
		assert_with_error('Element.checkProp(''NNDataPoint_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDataPoint_VOIs.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.checkProp(tag, value) does not work.')
		assert(~dp.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dp, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dp, tag, value) does not work.')
		assert(~Element.checkProp('NNDataPoint_VOIs', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDataPoint_VOIs'', tag, value) does not work.')
	 
		assert_with_error('NNDataPoint_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], tag, dp)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], tag, dp)
		assert_with_error('Element.checkProp(''NNDataPoint_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDataPoint_VOIs.checkProp(prop, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.checkProp(prop, <conditioned default value>) does not work.')
		assert(dp.checkProp(prop, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dp, prop, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dp, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDataPoint_VOIs', prop, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDataPoint_VOIs'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDataPoint_VOIs.checkProp(tag, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.checkProp(tag, <conditioned default value>) does not work.')
		assert(dp.checkProp(tag, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'dp.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dp, tag, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dp, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDataPoint_VOIs', tag, Element.getPropDefaultConditioned(NNDataPoint_VOIs, prop)), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDataPoint_VOIs'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNDataPoint_VOIs.VOI_DICT])
			continue
		end
	 
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dp.getr(prop) == NNDataPoint_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDataPoint_VOIs.getCategoryName(NNDataPoint_VOIs.getPropCategory(prop)) ', NNDataPoint_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dp.getr(TAG) == NNDataPoint_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDataPoint_VOIs.getCategoryName(NNDataPoint_VOIs.getPropCategory(prop)) ', NNDataPoint_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dp.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dp.getPropSettings(prop))
					assert( ...
						dp.checkFormat(dp.getPropFormat(prop), dp.get(prop)), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dp.checkFormat(dp.getPropFormat(prop), dp.get(prop), dp.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dp.getr(prop) == NNDataPoint_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDataPoint_VOIs.getCategoryName(NNDataPoint_VOIs.getPropCategory(prop)) ', NNDataPoint_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dp.getr(TAG) == NNDataPoint_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDataPoint_VOIs.getCategoryName(NNDataPoint_VOIs.getPropCategory(prop)) ', NNDataPoint_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDataPoint_VOIs']);
				assert( ...
					~isa(dp.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dp.getPropSettings(prop))
					assert( ...
						dp.checkFormat(dp.getPropFormat(prop), dp.get(prop)), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dp.checkFormat(dp.getPropFormat(prop), dp.get(prop), dp.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dp.getr(prop), NNDataPoint_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDataPoint_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dp.getr(TAG), NNDataPoint_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDataPoint_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDataPoint_VOIs.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNDataPoint_VOIs.VOI_DICT])
			continue
		end
	 
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dp.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dp.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dp.checkFormat(dp.getPropFormat(prop), dp.getr(prop),dp.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDataPoint_VOIs']);
				assert( ...
					~isa(dp.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDataPoint_VOIs']);
	% 			assert( ...
	% 				~isa(dp.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNDataPoint_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dp.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dp.checkFormat(dp.getPropFormat(prop), dp.getr(prop),dp.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNDataPoint_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDataPoint_VOIs']);
				assert( ...
					~isa(dp.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dp.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dp.checkFormat(dp.getPropFormat(prop), dp.getr(prop),dp.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dp.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDataPoint_VOIs');
					delete(ancestor(dp.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDataPoint_VOIs.getProps(Category.RESULT))
		for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
	 
			% excluded props
			if any(prop == [NNDataPoint_VOIs.VOI_DICT])
				continue
			end
	 
			switch NNDataPoint_VOIs.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dp.isLocked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dp.isLocked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs();
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		assert( ...
			~dp.isLocked(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dp.isLocked(TAG), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dp.lock()
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dp.isLocked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dp.isLocked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs();
	 
	warning_backup = warning('off', 'BRAPH2:NNDataPoint_VOIs');
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		dp.lock(prop)
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dp.isLocked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dp.isLocked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs();
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		assert( ...
			dp.isChecked(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dp.isChecked(TAG), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dp.unchecked()
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		assert( ...
			~dp.isChecked(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dp.checked()
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		assert( ...
			dp.isChecked(prop), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNDataPoint_VOIs.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDataPoint_VOIs
	dp_0 = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	% NNDataPoint_VOIs with 1st callbacks
	dp_1 = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, dp_0.getCallback(4), ..., ...
		NNDataPoint_VOIs.ID, dp_0.getCallback(5), ..., ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, dp_0.getCallback(11), ..., ...
		NNDataPoint_VOIs.TARGET_CLASS, dp_0.getCallback(12) ... ...
		);
	 
	prop_number = NNDataPoint_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dp_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dp_1.get(prop), dp_0.get(prop)) && ~isa(dp_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dp_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDataPoint_VOIs with 2nd callbacks
	dp_2 = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, dp_1.getCallback(4), ..., ...
		NNDataPoint_VOIs.ID, dp_1.getCallback(5), ..., ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, dp_1.getCallback(11), ..., ...
		NNDataPoint_VOIs.TARGET_CLASS, dp_1.getCallback(12) ... ...
		);
	 
	prop_number = NNDataPoint_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dp_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dp_2.get(prop), dp_0.get(prop)) && ~isa(dp_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dp_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDataPoint_VOIs with 3rd callbacks
	dp_3 = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, dp_2.getCallback(4), ..., ...
		NNDataPoint_VOIs.ID, dp_2.getCallback(5), ..., ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, dp_2.getCallback(11), ..., ...
		NNDataPoint_VOIs.TARGET_CLASS, dp_2.getCallback(12) ... ...
		);
	 
	prop_number = NNDataPoint_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dp_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dp_3.get(prop), dp_0.get(prop)) && ~isa(dp_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dp_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dp = NNDataPoint_VOIs();
	 
	dp_copy = dp.copy();
	 
	assert(dp_copy ~= dp, ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dp_copy, dp), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		value = dp.getr(prop);
		value_copy = dp_copy.getr(prop);
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dp_copy.isLocked(prop) == dp.isLocked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dp_copy.isChecked(prop) == dp.isChecked(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dp_copy.getPropSeed(prop) == dp.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		if NNDataPoint_VOIs.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDataPoint_VOIs']);
			% dp.memorize(prop);
			% warning(warning_backup)
		elseif NNDataPoint_VOIs.getPropCategory(prop) == Category.EVANESCENT && dp.getPropFormat(prop) == Format.HANDLE
			dp.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDataPoint_VOIs');
			delete(ancestor(dp.get(prop), 'figure'))
			warning(warning_backup)
		else
			dp.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dp_copy = dp.copy();
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		value = dp.getr(prop);
		value_copy = dp_copy.getr(prop);
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dp_copy.isLocked(prop) == dp.isLocked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dp_copy.isChecked(prop) == dp.isChecked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dp_copy.getPropSeed(prop) == dp.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dp_0 = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, dp_0.getCallback(4), ..., ...
		NNDataPoint_VOIs.ID, dp_0.getCallback(5), ..., ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, dp_0.getCallback(11), ..., ...
		NNDataPoint_VOIs.TARGET_CLASS, dp_0.getCallback(12) ... ...
		);
	 
	dp_copy = dp.copy();
	dp_0_copy = dp_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
		value = dp.getr(prop);
		value_copy = dp_copy.getr(prop);
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNDataPoint_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNDataPoint_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dp_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The callback should be obtained from NNDataPoint_VOIs.getCallback().' ...
						)
					assert( ...
						value_copy == dp_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The callback should be obtained from NNDataPoint_VOIs.getCallback().' ...
						)
				end
	 
					assert( ...
						dp_copy.isLocked(prop) == dp.isLocked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dp_copy.isChecked(prop) == dp.isChecked(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dp_copy.getPropSeed(prop) == dp.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp_template = NNDataPoint_VOIs();
	dp = NNDataPoint_VOIs('TEMPLATE', dp_template);
	 
	for prop = 1:1:NNDataPoint_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNDataPoint_VOIs.VOI_DICT])
			continue
		end
	 
		TAG = upper(NNDataPoint_VOIs.getPropTag(prop));
		switch NNDataPoint_VOIs.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDataPoint_VOIs.TEMPLATE
					assert( ...
						isa(dp.getr(prop), 'NNDataPoint_VOIs'), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs.getr(''TEMPLATE'') should be a NNDataPoint_VOIs element.' ...
						)
					assert( ...
						isa(dp_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dp.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dp.getr(prop).get('EL') == dp_template && dp.getr(prop).get('PROP') == prop && strcmp(dp.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs.getr(' TAG ') should be a Callback to dp_template.' TAG '.'] ...
						)
					assert( ...
						isa(dp_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dp.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dp_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNDataPoint_VOIs TEMPLATE does not work. NNDataPoint_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatapoint_vois_to_be_erased.b2'];
	 
	Element.save(dp, filename)
	 
	dp_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dp.copy(), dp_loaded), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.save(dp) and/or NNDataPoint_VOIs.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dp = NNDataPoint_VOIs( ...
		NNDataPoint_VOIs.ELCLASS, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.NAME, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.DESCRIPTION, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TEMPLATE, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TEMPLATE), ...
		NNDataPoint_VOIs.ID, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.ID), ...
		NNDataPoint_VOIs.LABEL, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.LABEL), ...
		NNDataPoint_VOIs.NOTES, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.NOTES), ...
		NNDataPoint_VOIs.TOSTRING, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.INPUT, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.TARGET, NNDataPoint_VOIs.getNoValue(), ...
		NNDataPoint_VOIs.VOI_DICT, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.VOI_DICT), ...
		NNDataPoint_VOIs.TARGET_CLASS, NNDataPoint_VOIs.getPropDefault(NNDataPoint_VOIs.TARGET_CLASS) ...
		);
	 
	[json, struct, el_list] = encodeJSON(dp);
	[dp_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dp_dec ~= dp, ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNDataPoint_VOIs.encodeJSON() or NNDataPoint_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDataPoint_VOIs.getPropFormat(prop), num2cell(NNDataPoint_VOIs.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDataPoint_VOIs.getPropFormat(prop), num2cell(NNDataPoint_VOIs.getProps())) == Format.NET)
		assert(isequal(dp_dec, dp), ...
			[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNDataPoint_VOIs.encodeJSON() or NNDataPoint_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Construct the data point with the adjacency matrix derived from its weighted undirected graph (GraphWU)
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	% ensure the example data is generated
	if ~isfile([fileparts(which('NNDataPoint_VOIs')) filesep 'Example data NN CLA CON XLS VOIs' filesep 'atlas.xlsx'])
	    create_data_NN_CLA_CON_XLS_VOIs() % create example files
	end
	
	% Load BrainAtlas
	im_ba = ImporterBrainAtlasXLS( ...
	    'FILE', [fileparts(which('NNDataPoint_VOIs')) filesep 'Example data NN CLA CON XLS VOIs' filesep 'atlas.xlsx'], ...
	    'WAITBAR', true ...
	    );
	
	ba = im_ba.get('BA');
	
	% Load Groups of SubjectCON
	im_gr1 = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [fileparts(which('NNDataPoint_VOIs')) filesep 'Example data NN CLA CON XLS VOIs' filesep 'CON_Group_1_XLS'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	    );
	
	gr1 = im_gr1.get('GR');
	
	% Get the subject dictionary and extract the list of subjects
	sub_dict1 = gr1.get('SUB_DICT');
	sub_list1 = sub_dict1.get('IT_LIST'); % Get all subjects as a cell array
	[~, group_folder_name1] = fileparts(im_gr1.get('DIRECTORY'));
	% Use cellfun to create NNDataPoint_VOIs for each subject
	it_list_voi1 = cellfun(@(sub) NNDataPoint_VOIs( ...
	    'ID', sub.get('ID'), ...
	    'VOI_DICT', IndexedDictionary( ...
	        'ID', 'subject_idict', ...
	        'IT_CLASS', 'SubjectNIfTI', ...
	        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
	        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
	        ), ...
	    'TARGET_CLASS', {group_folder_name1} ...
	    ), sub_list1, 'UniformOutput', false);
	
	% create NNDataPoint_Graph_CLA DICT items
	dp_list1 = IndexedDictionary(...
	        'IT_CLASS', 'NNDataPoint_VOIs', ...
	        'IT_LIST', it_list_voi1 ...
	        );
	
	% create a NNDataset containing the NNDataPoint_Graph_CLA DICT
	d1 = NNDataset( ...
	    'DP_CLASS', 'NNDataPoint_VOIs', ...
	    'DP_DICT', dp_list1 ...
	    );
	
	% Verify VOI values by comparing Age from SubjectCON and NNDataPoint_VOIs
	for i = 1:gr1.get('SUB_DICT').get('LENGTH')
	    % Get the original subject and its ID
	    sub = gr1.get('SUB_DICT').get('IT', i);
	    sub_id = sub.get('ID');
	    
	    % Find the corresponding NNDataPoint_VOIs by ID
	    dp_voi = d1.get('DP_DICT').get('IT_FROM_KEY', sub_id);
	    
	    % Retrieve Age VOI from SubjectCON using IT_FROM_KEY
	    voi_age = sub.get('VOI_DICT').get('IT_FROM_KEY', 'Age');
	    age_sub = voi_age.get('V');
	    
	    % Retrieve Age VOI from NNDataPoint_VOIs (as TARGET since TARGET_CLASS is 'Age')
	    age_dp = dp_voi.get('VOI_DICT').get('IT_FROM_KEY','Age').get('V');  % TARGET should be Age value
	    
	    % Assert that the Age values match
	    assert(isequal(age_sub, age_dp), ...
	        [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
	        ['Age VOI mismatch for subject ' sub_id ': expected ' num2str(age_sub) ', got ' num2str(age_dp)]);
	    
	    % Retrieve Age VOI from SubjectCON using IT_FROM_KEY
	    voi_sex = sub.get('VOI_DICT').get('IT_FROM_KEY', 'Sex');
	    sex_sub = voi_sex.get('V');
	    
	    % Retrieve Age VOI from NNDataPoint_VOIs (as TARGET since TARGET_CLASS is 'Age')
	    sex_dp = dp_voi.get('VOI_DICT').get('IT_FROM_KEY','Sex').get('V');  % TARGET should be Age value
	    
	    % Assert that the Age values match
	    assert(isequal(sex_sub, sex_dp), ...
	        [BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
	        ['Age VOI mismatch for subject ' sub_id ': expected ' num2str(age_sub) ', got ' num2str(age_dp)]);
	end
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDataPoint_VOIs:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDataPoint_VOIs no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

