% EXAMPLE_CON_WU
% Script example pipeline Correlation CON WU
clear variables %#ok<*NASGU>

addpath(genpath(fileparts(which('braph2individualconnectome'))))
%% load Atlas

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [which('aal94_atlas.xlsx')], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');
%% load Nifty images
%%group1
im_gr1_WM_GM = ImporterGroupSubjNIfTI('DIRECTORY',[fileparts(which('Example data Nifti/atlas.xlsx')) filesep 'Group1'], ...
    'NIFTI_TYPE', {'T1'},...
    'WAITBAR', true);
gr1_WM_GM = im_gr1_WM_GM.get('GR');

im_gr1_PET = ImporterGroupSubjNIfTI('DIRECTORY',[fileparts(which('Example data Nifti/atlas.xlsx')) filesep 'Group1'], ...
    'NIFTI_TYPE', {'PET'},...
    'WAITBAR', true);
gr1_PET = im_gr1_PET.get('GR');

%%group2
im_gr2_WM_GM = ImporterGroupSubjNIfTI('DIRECTORY',[fileparts(which('Example data Nifti/atlas.xlsx')) filesep 'Group2'], ...
    'NIFTI_TYPE', {'T1'},...
    'WAITBAR', true);
gr2_WM_GM = im_gr2_WM_GM.get('GR');

im_gr2_PET = ImporterGroupSubjNIfTI('DIRECTORY',[fileparts(which('Example data Nifti/atlas.xlsx')) filesep 'Group2'], ...
    'NIFTI_TYPE', {'PET'},...
    'WAITBAR', true);
gr2_PET = im_gr2_PET.get('GR');


%% PDF Construtor

path_dict = IndexedDictionary( ...
    'IT_CLASS', 'FILE_PATH', ...
    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii'))} ...
    );

mapping_path_dict = IndexedDictionary( ...
    'IT_CLASS', 'FILE_PATH', ...
    'IT_LIST', {FILE_PATH('PATH', which('AAL2_Atlas_Labels.csv'))} ...
    );

ref_region_list = {2001}; % Reference region label

atlas = ba;
br_dict = atlas.get('BR_DICT');
selected_ids = num2cell(1:94);
selected_br = cellfun(@(id) br_dict.get('IT', id), selected_ids, 'UniformOutput', false);
selected_br_dict = IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST', selected_br);

gr1 = PDFConstructor('GR_PET', gr1_PET, ...
    'GR_T1', gr1_WM_GM, ...
    'BA', {ba}, ...
    'ATLAS_PATH_DICT', path_dict, ...
    'MAPPING_PATH_DICT', mapping_path_dict, ...
    'REF_REGION_LIST', ref_region_list, ...
    'PDF_REGION_SELECTION', selected_br_dict);
PDF_gr1 = gr1.get('GR');


gr2 = PDFConstructor('GR_PET', gr2_PET, ...
    'GR_T1', gr2_WM_GM, ...
    'BA', {ba}, ...
    'ATLAS_PATH_DICT', path_dict, ...
    'MAPPING_PATH_DICT', mapping_path_dict, ...
    'REF_REGION_LIST', ref_region_list, ...
    'PDF_REGION_SELECTION', selected_br_dict);
PDF_gr2 = gr2.get('GR');


%% Load Groups of SubjectCON Correlation based
a_WU1 = AnalyzeEnsembleDivergence_FUN_WU( ...
    'GR', PDF_gr1);
a_WU2 = AnalyzeEnsembleDivergence_FUN_WU( ...
    'GR', PDF_gr2, ...
    'TEMPLATE', a_WU1);


%% NN DATASET
% ǵroup 1
[~, group_folder_name1] = fileparts(im_gr1_PET.get('DIRECTORY'));
it_list1 = cellfun(@(x) NNDataPoint_Graph_CLA( ...
    'ID', x.get('ID'), ...
    'G', x, ...
    'TARGET_CLASS', {group_folder_name1}), ...
     a_WU1.get('G_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% Get the subject dictionary and extract the list of subjects
sub_dict1 = gr1_WM_GM.get('SUB_DICT');
sub_list1 = sub_dict1.get('IT_LIST'); % Get all subjects as a cell array

% ǵroup 2
[~, group_folder_name2] = fileparts(im_gr2_PET.get('DIRECTORY'));
it_list2 = cellfun(@(x) NNDataPoint_Graph_CLA( ...
    'ID', x.get('ID'), ...
    'G', x, ...
    'TARGET_CLASS', {group_folder_name2}), ...
     a_WU2.get('G_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% Get the subject dictionary and extract the list of subjects
sub_dict2 = gr2_WM_GM.get('SUB_DICT');
sub_list2 = sub_dict2.get('IT_LIST'); % Get all subjects as a cell array

dp_list1 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_Graph_CLA', ...
        'IT_LIST', it_list1 ...
        );

dp_list2 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_Graph_CLA', ...
        'IT_LIST', it_list2 ...
        );

d1 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_Graph_CLA', ...
    'DP_DICT', dp_list1 ...
    );

d2 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_Graph_CLA', ...
    'DP_DICT', dp_list2 ...
    );
%% Create a classifier cross-validation
nncv = NNClassifierMLP_CrossValidation('D', {d1, d2}, 'KFOLDS', 2);
nncv.get('TRAIN');

%% Evaluate the performance
confusion_matrix = nncv.get('C_MATRIX');
av_auc = nncv.get('AV_AUC');
av_macro_auc = nncv.get('AV_MACRO_AUC');