%TEST_ANALYZEENSEMBLEDIVERGENCE_FUN_WU

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	a = AnalyzeEnsembleDivergence_FUN_WU();
	 
	% get('ELCLASS')
	if isa(AnalyzeEnsembleDivergence_FUN_WU, 'ConcreteElement')
		assert(strcmp(AnalyzeEnsembleDivergence_FUN_WU().get('ELCLASS'), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU().get(''ELCLASS'') should return ''AnalyzeEnsembleDivergence_FUN_WU''.')
	end
	 
	% getBuild()
	assert(AnalyzeEnsembleDivergence_FUN_WU.getBuild() == 1 && AnalyzeEnsembleDivergence_FUN_WU.getBuild() > 0, ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getBuild() should return the AnalyzeEnsembleDivergence_FUN_WU build number.')
	assert(a.getBuild() == 1 && a.getBuild() > 0 , ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getBuild() should return the AnalyzeEnsembleDivergence_FUN_WU build number.')
	assert(Element.getBuild(a) == 1 && Element.getBuild(a) > 0, ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(a) should return the AnalyzeEnsembleDivergence_FUN_WU build number.')
	assert(Element.getBuild('AnalyzeEnsembleDivergence_FUN_WU') == 1 && Element.getBuild('AnalyzeEnsembleDivergence_FUN_WU') > 0, ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''AnalyzeEnsembleDivergence_FUN_WU'') should return the AnalyzeEnsembleDivergence_FUN_WU build number.')
	 
	% getClass()
	assert(strcmp(AnalyzeEnsembleDivergence_FUN_WU.getClass(), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getClass() should return ''AnalyzeEnsembleDivergence_FUN_WU''.')
	assert(strcmp(a.getClass(), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getClass() should return ''AnalyzeEnsembleDivergence_FUN_WU''.')
	assert(strcmp(Element.getClass(a), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(a) should return ''AnalyzeEnsembleDivergence_FUN_WU''.')
	assert(strcmp(Element.getClass('AnalyzeEnsembleDivergence_FUN_WU'), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''AnalyzeEnsembleDivergence_FUN_WU'') should return ''AnalyzeEnsembleDivergence_FUN_WU''.')
	 
	% getSubclasses()
	assert(isequal(AnalyzeEnsembleDivergence_FUN_WU.getSubclasses(), subclasses('AnalyzeEnsembleDivergence_FUN_WU', [], [], true)), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getSubclasses() should return the same result as subclasses(''AnalyzeEnsembleDivergence_FUN_WU'', [], [], true).')
	assert(isequal(a.getSubclasses(), subclasses('AnalyzeEnsembleDivergence_FUN_WU', [], [], true)), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''AnalyzeEnsembleDivergence_FUN_WU'', [], [], true).')
	assert(isequal(Element.getSubclasses(a), subclasses('AnalyzeEnsembleDivergence_FUN_WU', [], [], true)), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(a) should return the same result as subclasses(''AnalyzeEnsembleDivergence_FUN_WU'', [], [], true).')
	assert(isequal(Element.getSubclasses('AnalyzeEnsembleDivergence_FUN_WU'), subclasses('AnalyzeEnsembleDivergence_FUN_WU', [], [], true)), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''AnalyzeEnsembleDivergence_FUN_WU'') should return the same result as subclasses(''AnalyzeEnsembleDivergence_FUN_WU'', [], [], true).')
	 
	% getProps()
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(AnalyzeEnsembleDivergence_FUN_WU.getProps(), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getProps() should return a row vector [1:1:N].')
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(a.getProps(), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getProps() should return a row vector [1:1:N].')
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(Element.getProps(a), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(a) should return a row vector [1:1:N].')
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(Element.getProps('AnalyzeEnsembleDivergence_FUN_WU'), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''AnalyzeEnsembleDivergence_FUN_WU'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) AnalyzeEnsembleDivergence_FUN_WU.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getProps(category) does not work.')
	tmp = cellfun(@(category) a.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(a, category), categories, 'UniformOutput', false);
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(a, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('AnalyzeEnsembleDivergence_FUN_WU', category), categories, 'UniformOutput', false);
	assert(isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(AnalyzeEnsembleDivergence_FUN_WU.getProps())), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''AnalyzeEnsembleDivergence_FUN_WU'', category) does not work.')
	 
	% getPropNumber()
	assert(AnalyzeEnsembleDivergence_FUN_WU.getPropNumber() == length(AnalyzeEnsembleDivergence_FUN_WU.getProps()), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getPropNumber() should return the number of properties.')
	assert(a.getPropNumber() == length(AnalyzeEnsembleDivergence_FUN_WU.getProps()), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(a) == length(AnalyzeEnsembleDivergence_FUN_WU.getProps()), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(a) should return the number of properties.')
	assert(Element.getPropNumber('AnalyzeEnsembleDivergence_FUN_WU') == length(AnalyzeEnsembleDivergence_FUN_WU.getProps()), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''AnalyzeEnsembleDivergence_FUN_WU'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(category), categories)) == AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) a.getPropNumber(category), categories)) == AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(a, category), categories)) == AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(a, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('AnalyzeEnsembleDivergence_FUN_WU', category), categories)) == AnalyzeEnsembleDivergence_FUN_WU.getPropNumber(), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''AnalyzeEnsembleDivergence_FUN_WU'', category) does not work.')
	 
	% existsProp(prop)
	assert(~AnalyzeEnsembleDivergence_FUN_WU.existsProp(NaN), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.existsProp(prop) does not work.')
	assert(~a.existsProp(NaN), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.existsProp(prop) does not work.')
	assert(~Element.existsProp(a, NaN), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(a, prop) does not work.')
	assert(~Element.existsProp('AnalyzeEnsembleDivergence_FUN_WU', NaN), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
	assert_with_error('AnalyzeEnsembleDivergence_FUN_WU.existsProp(NaN)', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], a)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], a)
	assert_with_error('Element.existsProp(''AnalyzeEnsembleDivergence_FUN_WU'', NaN)', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		assert(AnalyzeEnsembleDivergence_FUN_WU.existsProp(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.existsProp(prop) does not work.')
		assert(a.existsProp(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.existsProp(prop) does not work.')
		assert(Element.existsProp(a, prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(a, prop) does not work.')
		assert(Element.existsProp('AnalyzeEnsembleDivergence_FUN_WU', prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~AnalyzeEnsembleDivergence_FUN_WU.existsTag(''), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.existsTag(tag) does not work.')
	assert(~a.existsTag(''), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'a.existsTag(tag) does not work.')
	assert(~Element.existsTag(a, ''), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(a, tag) does not work.')
	assert(~Element.existsTag('AnalyzeEnsembleDivergence_FUN_WU', ''), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	 
	assert_with_error('AnalyzeEnsembleDivergence_FUN_WU.existsTag('''')', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], a)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], a)
	assert_with_error('Element.existsTag(''AnalyzeEnsembleDivergence_FUN_WU'', '''')', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
		assert(AnalyzeEnsembleDivergence_FUN_WU.existsTag(tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.existsTag(tag) does not work.')
		assert(a.existsTag(tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.existsTag(tag) does not work.')
		assert(Element.existsTag(a, tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(a, tga) does not work.')
		assert(Element.existsTag('AnalyzeEnsembleDivergence_FUN_WU', tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		assert(AnalyzeEnsembleDivergence_FUN_WU.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropProp(prop) does not work.')
		assert(a.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropProp(prop) does not work.')
		assert(Element.getPropProp(a, prop) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(a, prop) does not work.')
		assert(Element.getPropProp('AnalyzeEnsembleDivergence_FUN_WU', prop) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
		tag = a.getPropTag(prop);
		assert(AnalyzeEnsembleDivergence_FUN_WU.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropProp(tag) does not work.')
		assert(a.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropProp(tag) does not work.')
		assert(Element.getPropProp(a, tag) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(a, tag) does not work.')
		assert(Element.getPropProp('AnalyzeEnsembleDivergence_FUN_WU', prop) == prop, ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		assert(strcmp(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop) does not work.')
		assert(strcmp(a.getPropTag(prop), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(a, prop), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(a, prop) does not work.')
		assert(strcmp(Element.getPropTag('AnalyzeEnsembleDivergence_FUN_WU', prop), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
		assert(strcmp(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(tag), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropTag(tag) does not work.')
		assert(strcmp(a.getPropTag(tag), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(a, tag), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(a, tag) does not work.')
		assert(strcmp(Element.getPropTag('AnalyzeEnsembleDivergence_FUN_WU', prop), tag), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		assert(Category.existsCategory(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(a.getPropCategory(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(a, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
		assert(Category.existsCategory(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(a.getPropCategory(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(a, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		assert(Format.existsFormat(AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(a.getPropFormat(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(a, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
		assert(Format.existsFormat(AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(a.getPropFormat(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(a, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		assert(ischar(AnalyzeEnsembleDivergence_FUN_WU.getPropDescription(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropDescription(prop) does not work.')
		assert(ischar(a.getPropDescription(prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(a, prop) does not work.')
		assert(ischar(Element.getPropDescription(a, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''AnalyzeEnsembleDivergence_FUN_WU'', prop) does not work.')
	 
		assert(ischar(AnalyzeEnsembleDivergence_FUN_WU.getPropDescription(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.getPropDescription(tag) does not work.')
		assert(ischar(a.getPropDescription(tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(a, tag) does not work.')
		assert(ischar(Element.getPropDescription(a, tag)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''AnalyzeEnsembleDivergence_FUN_WU'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		settings = AnalyzeEnsembleDivergence_FUN_WU.getPropSettings(prop);
		settings = a.getPropSettings(prop);
		settings = Element.getPropSettings(a, prop);
		settings = Element.getPropSettings('AnalyzeEnsembleDivergence_FUN_WU', prop);
	 
		settings = AnalyzeEnsembleDivergence_FUN_WU.getPropSettings(tag);
		settings = a.getPropSettings(tag);
		settings = Element.getPropSettings(a, tag);
		settings = Element.getPropSettings('AnalyzeEnsembleDivergence_FUN_WU', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		default = AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(prop);
		default = a.getPropDefault(prop);
		default = Element.getPropDefault(a, prop);
		default = Element.getPropDefault('AnalyzeEnsembleDivergence_FUN_WU', prop);
	 
		default = AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(tag);
		default = a.getPropDefault(tag);
		default = Element.getPropDefault(a, tag);
		default = Element.getPropDefault('AnalyzeEnsembleDivergence_FUN_WU', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		conditioned_default = AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(prop);
		conditioned_default = a.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(a, prop);
		conditioned_default = Element.getPropDefaultConditioned('AnalyzeEnsembleDivergence_FUN_WU', prop);
	 
		conditioned_default = AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(tag);
		conditioned_default = a.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(a, tag);
		conditioned_default = Element.getPropDefaultConditioned('AnalyzeEnsembleDivergence_FUN_WU', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		tag = a.getPropTag(prop);
	 
		assert(~AnalyzeEnsembleDivergence_FUN_WU.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.checkProp(prop, value) does not work.')
		assert(~a.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(a, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(a, prop, value) does not work.')
		assert(~Element.checkProp('AnalyzeEnsembleDivergence_FUN_WU', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', prop, value) does not work.')
	 
		assert_with_error('AnalyzeEnsembleDivergence_FUN_WU.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], prop, a)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], prop, a)
		assert_with_error('Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~AnalyzeEnsembleDivergence_FUN_WU.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.checkProp(tag, value) does not work.')
		assert(~a.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(a, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(a, tag, value) does not work.')
		assert(~Element.checkProp('AnalyzeEnsembleDivergence_FUN_WU', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', tag, value) does not work.')
	 
		assert_with_error('AnalyzeEnsembleDivergence_FUN_WU.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], tag, a)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], tag, a)
		assert_with_error('Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(AnalyzeEnsembleDivergence_FUN_WU.checkProp(prop, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.checkProp(prop, <conditioned default value>) does not work.')
		assert(a.checkProp(prop, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(a, prop, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(a, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('AnalyzeEnsembleDivergence_FUN_WU', prop, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', prop, <conditioned default value>) does not work.')
	 
		assert(AnalyzeEnsembleDivergence_FUN_WU.checkProp(tag, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.checkProp(tag, <conditioned default value>) does not work.')
		assert(a.checkProp(tag, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'a.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(a, tag, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(a, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('AnalyzeEnsembleDivergence_FUN_WU', tag, Element.getPropDefaultConditioned(AnalyzeEnsembleDivergence_FUN_WU, prop)), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''AnalyzeEnsembleDivergence_FUN_WU'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
	 
		% excluded props
		if any(prop == [AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE])
			continue
		end
	 
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					a.getr(prop) == AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['Being a ' AnalyzeEnsembleDivergence_FUN_WU.getCategoryName(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)) ', AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					a.getr(TAG) == AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['Being a ' AnalyzeEnsembleDivergence_FUN_WU.getCategoryName(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)) ', AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(a.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(a.getPropSettings(prop))
					assert( ...
						a.checkFormat(a.getPropFormat(prop), a.get(prop)), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						a.checkFormat(a.getPropFormat(prop), a.get(prop), a.getPropSettings(prop)), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					a.getr(prop) == AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['Being a ' AnalyzeEnsembleDivergence_FUN_WU.getCategoryName(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)) ', AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					a.getr(TAG) == AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['Being a ' AnalyzeEnsembleDivergence_FUN_WU.getCategoryName(AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)) ', AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU']);
				assert( ...
					~isa(a.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(a.getPropSettings(prop))
					assert( ...
						a.checkFormat(a.getPropFormat(prop), a.get(prop)), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						a.checkFormat(a.getPropFormat(prop), a.get(prop), a.getPropSettings(prop)), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(a.getr(prop), AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(a.getr(TAG), AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') must be inizialized to its default value ' ...
					'given by AnalyzeEnsembleDivergence_FUN_WU.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
	 
		% excluded props
		if any(prop == [AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE])
			continue
		end
	 
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(a.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(a.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					a.checkFormat(a.getPropFormat(prop), a.getr(prop),a.getPropSettings(prop)), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU']);
				assert( ...
					~isa(a.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU']);
	% 			assert( ...
	% 				~isa(a.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
	% 				['AnalyzeEnsembleDivergence_FUN_WU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(a.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
	% 				['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				a.checkFormat(a.getPropFormat(prop), a.getr(prop),a.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
	% 				['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU']);
				assert( ...
					~isa(a.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(a.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					a.checkFormat(a.getPropFormat(prop), a.getr(prop),a.getPropSettings(prop)), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if a.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:AnalyzeEnsembleDivergence_FUN_WU');
					delete(ancestor(a.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(AnalyzeEnsembleDivergence_FUN_WU.getProps(Category.RESULT))
		for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
	 
			% excluded props
			if any(prop == [AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE])
				continue
			end
	 
			switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						a.isLocked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~a.isLocked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU();
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		assert( ...
			~a.isLocked(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~a.isLocked(TAG), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	a.lock()
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					a.isLocked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~a.isLocked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU();
	 
	warning_backup = warning('off', 'BRAPH2:AnalyzeEnsembleDivergence_FUN_WU');
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		a.lock(prop)
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					a.isLocked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~a.isLocked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU();
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		assert( ...
			a.isChecked(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			a.isChecked(TAG), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	a.unchecked()
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		assert( ...
			~a.isChecked(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	a.checked()
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		assert( ...
			a.isChecked(prop), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			['AnalyzeEnsembleDivergence_FUN_WU.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic AnalyzeEnsembleDivergence_FUN_WU
	a_0 = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	% AnalyzeEnsembleDivergence_FUN_WU with 1st callbacks
	a_1 = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, a_0.getCallback(4), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, a_0.getCallback(5), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, a_0.getCallback(9), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, a_0.getCallback(10), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, a_0.getCallback(11), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	prop_number = AnalyzeEnsembleDivergence_FUN_WU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(a_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(a_1.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(a_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% AnalyzeEnsembleDivergence_FUN_WU with 2nd callbacks
	a_2 = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, a_1.getCallback(4), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, a_1.getCallback(5), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, a_1.getCallback(9), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, a_1.getCallback(10), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, a_1.getCallback(11), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	prop_number = AnalyzeEnsembleDivergence_FUN_WU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(a_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(a_2.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(a_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% AnalyzeEnsembleDivergence_FUN_WU with 3rd callbacks
	a_3 = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, a_2.getCallback(4), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, a_2.getCallback(5), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, a_2.getCallback(9), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, a_2.getCallback(10), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, a_2.getCallback(11), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	prop_number = AnalyzeEnsembleDivergence_FUN_WU.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(a_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(a_3.get(prop), a_0.get(prop)) && ~isa(a_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(a_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	a = AnalyzeEnsembleDivergence_FUN_WU();
	 
	a_copy = a.copy();
	 
	assert(a_copy ~= a, ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(a_copy, a), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		value = a.getr(prop);
		value_copy = a_copy.getr(prop);
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					a_copy.isLocked(prop) == a.isLocked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					a_copy.isChecked(prop) == a.isChecked(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					a_copy.getPropSeed(prop) == a.getPropSeed(prop), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		if AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU']);
			% a.memorize(prop);
			% warning(warning_backup)
		elseif AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop) == Category.EVANESCENT && a.getPropFormat(prop) == Format.HANDLE
			a.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:AnalyzeEnsembleDivergence_FUN_WU');
			delete(ancestor(a.get(prop), 'figure'))
			warning(warning_backup)
		else
			a.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	a_copy = a.copy();
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		value = a.getr(prop);
		value_copy = a_copy.getr(prop);
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						a_copy.isLocked(prop) == a.isLocked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						a_copy.isChecked(prop) == a.isChecked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						a_copy.getPropSeed(prop) == a.getPropSeed(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	a_0 = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, a_0.getCallback(4), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, a_0.getCallback(5), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, a_0.getCallback(9), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, a_0.getCallback(10), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, a_0.getCallback(11), ..., ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	a_copy = a.copy();
	a_0_copy = a_copy.getr('ID').get('EL');
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
		value = a.getr(prop);
		value_copy = a_copy.getr(prop);
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
							'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == a_0.getCallback(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The callback should be obtained from AnalyzeEnsembleDivergence_FUN_WU.getCallback().' ...
						)
					assert( ...
						value_copy == a_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The callback should be obtained from AnalyzeEnsembleDivergence_FUN_WU.getCallback().' ...
						)
				end
	 
					assert( ...
						a_copy.isLocked(prop) == a.isLocked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						a_copy.isChecked(prop) == a.isChecked(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						a_copy.getPropSeed(prop) == a.getPropSeed(prop), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a_template = AnalyzeEnsembleDivergence_FUN_WU();
	a = AnalyzeEnsembleDivergence_FUN_WU('TEMPLATE', a_template);
	 
	for prop = 1:1:AnalyzeEnsembleDivergence_FUN_WU.getPropNumber()
	 
		% excluded props
		if any(prop == [AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE])
			continue
		end
	 
		TAG = upper(AnalyzeEnsembleDivergence_FUN_WU.getPropTag(prop));
		switch AnalyzeEnsembleDivergence_FUN_WU.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE
					assert( ...
						isa(a.getr(prop), 'AnalyzeEnsembleDivergence_FUN_WU'), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU.getr(''TEMPLATE'') should be a AnalyzeEnsembleDivergence_FUN_WU element.' ...
						)
					assert( ...
						isa(a_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						'AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(a.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						a.getr(prop).get('EL') == a_template && a.getr(prop).get('PROP') == prop && strcmp(a.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') should be a Callback to a_template.' TAG '.'] ...
						)
					assert( ...
						isa(a_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
						['AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(a.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(a_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
					['AnalyzeEnsembleDivergence_FUN_WU TEMPLATE does not work. AnalyzeEnsembleDivergence_FUN_WU_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'analyzeensembledivergence_fun_wu_to_be_erased.b2'];
	 
	Element.save(a, filename)
	 
	a_loaded = Element.load(filename);
	 
	assert( ...
		isequal(a.copy(), a_loaded), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.save(a) and/or AnalyzeEnsembleDivergence_FUN_WU.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	a = AnalyzeEnsembleDivergence_FUN_WU( ...
		AnalyzeEnsembleDivergence_FUN_WU.ELCLASS, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.NAME, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.DESCRIPTION, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.ID, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.ID), ...
		AnalyzeEnsembleDivergence_FUN_WU.LABEL, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.LABEL), ...
		AnalyzeEnsembleDivergence_FUN_WU.NOTES, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.NOTES), ...
		AnalyzeEnsembleDivergence_FUN_WU.TOSTRING, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.WAITBAR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.WAITBAR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GR, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GR), ...
		AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE, AnalyzeEnsembleDivergence_FUN_WU.getPropDefault(AnalyzeEnsembleDivergence_FUN_WU.GRAPH_TEMPLATE), ...
		AnalyzeEnsembleDivergence_FUN_WU.G_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.ME_DICT, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.MEASUREENSEMBLE, AnalyzeEnsembleDivergence_FUN_WU.getNoValue(), ...
		AnalyzeEnsembleDivergence_FUN_WU.CONNECTOME_CONSTUCT_METHOD, AnalyzeEnsembleDivergence_FUN_WU.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(a);
	[a_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(a_dec ~= a, ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		'AnalyzeEnsembleDivergence_FUN_WU.encodeJSON() or AnalyzeEnsembleDivergence_FUN_WU.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(prop), num2cell(AnalyzeEnsembleDivergence_FUN_WU.getProps())) == Format.HANDLE) && all(cellfun(@(prop) AnalyzeEnsembleDivergence_FUN_WU.getPropFormat(prop), num2cell(AnalyzeEnsembleDivergence_FUN_WU.getProps())) == Format.NET)
		assert(isequal(a_dec, a), ...
			[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
			'AnalyzeEnsembleDivergence_FUN_WU.encodeJSON() or AnalyzeEnsembleDivergence_FUN_WU.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Example
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	group_dir = fullfile(fileparts(which('AnalyzeEnsembleDivergence_FUN_WU')),'Example data Nifti');
	if ~exist(group_dir)
	    create_example_NIfTI([],group_dir) % only creates files if the example folder doesn't already exist
	end
end

%% Test 13: Verify the divergence-based individual connectome pipeline
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', which('aal94_atlas.xlsx'));
	ba = im_ba.get('BA');
	
	group_dir = fullfile(fileparts(which('AnalyzeEnsembleDivergence_FUN_WU')),'Example data Nifti', 'Group1');
	im_gr1_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr1_WM_GM = im_gr1_WM_GM.get('GR');
	
	im_gr1_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr1_PET = im_gr1_PET.get('GR');
	
	path_dict = IndexedDictionary(...
	    'IT_CLASS', 'FILE_PATH', ...
	    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii'))} ...
	    );
	
	% suvr_brain_label = readtable(which('AAL2_Atlas_Labels.csv'));
	% suvr_brain_label = suvr_brain_label.Var4;
	ref_region_list = [2001];% reference region label
	
	gr1 = PDFConstructor('GR_PET',gr1_PET, ...
	    'GR_T1',gr1_WM_GM, ...
	    'BA', ba,...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'ATLAS_KIND', {'AAL2'});
	
	
	PDF_gr1 = gr1.get('GR');
	g_temp  = GraphWU('STANDARDIZE_RULE', 'range');
	a_WU1 = AnalyzeEnsembleDivergence_FUN_WU( ...
	    'GR', PDF_gr1, ...
	    'GRAPH_TEMPLATE', g_temp...
	    );
	
	num_subjects = a_WU1.get('G_DICT').get('LENGTH');
	
	strength_first20 = zeros(num_subjects, 20);
	strength_others = zeros(num_subjects,size(a_WU1.get('G_DICT').get('IT', 1).get('B'),1)- 20);
	
	% Loop through subjects to calculate strength
	
	for i = 1:num_subjects
	    g = a_WU1.get('G_DICT').get('IT', i);
	    strength = g.get('MEASURE', 'Strength').get('M'); % Strength for all regions
	    A = g.get('A');
	    strength20_regions = sum(A{1}(1:20,1:20),2);
	    strengthother_regions = sum(A{1}(21:end,21:end),2);
	    mean_20 = mean(strength20_regions(:));
	    mean_others = mean(strengthother_regions(:));
	    % Assert for each subject
	    assert(mean_20 < mean_others, ...
	        sprintf('Test failed for subject %d: The first 20 regions do not have higher Divergence than the other regions.',  i));
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':AnalyzeEnsembleDivergence_FUN_WU:' BRAPH2.FAIL_TEST], ...
		[' When testing AnalyzeEnsembleDivergence_FUN_WU no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

