distribution_name = 'Individual Connectome';
distribution_moniker = 'individualconnectome';
pipeline_folders = {
    'region-of-interest suvr'
    'correlation_suvr connectivity'
    'divergence_suvr connectivity'
    'mahalanobis_suvr connectivity'
    'correlation_suvr connectivity'
    };
braph2_version = 'heads/ywc-lite-genesis';

%% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util', '+_Exporter.gen.m', '+_Importer.gen.m', ...
    '+ds*', '-ds_examples', ...
    '+atlas*', ...
    '+gt', '+_Measure.gen.m', '+_Graph.gen.m', '+_GraphAdjPF.gen.m', '+_GraphHistPF.gen.m', '+_GraphPP_MDict.gen.m', '+_NoValue.gen.m', ...
        '+_MeasurePF.gen.m', '+_MeasurePF_GU.gen.m', '+_MeasurePF_NU.gen.m', '+_MeasurePF_NxPP_Node.gen.m', '+_MeasurePF_xUPP_Layer.gen.m', ...
    '+cohort*', ...
    '+analysis*', ...
    '-nn', ...
    '+gui*', '-gui_examples', ...
    '+brainsurfs*', ...
    '+atlases*', ...
    '+graphs',  '+_GraphWU.gen.m', ...
    '+measures', '+_Strength.gen.m','+_Degree.gen.m',...
    '-neuralnetworks', ...
    '+pipelines', ...
        '+connectivity*', '-_AnalyzeEnsemble_CON_BUD.gen.m', '-_AnalyzeEnsemble_CON_BUT.gen.m', ...
        '+functional*', '-_AnalyzeEnsemble_FUN_BUD.gen.m', '-_AnalyzeEnsemble_FUN_BUT.gen.m', ...
        '+structural*', '-_AnalyzeEnsemble_ST_BUD.gen.m', '-_AnalyzeEnsemble_ST_BUT.gen.m', ... 
        '+region-of-interest suvr*', ...
        '+corelation_suvr connectivity*', ...
        '+divergence_suvr connectivity*', ...
        '+mahalanobis_suvr connectivity*', ...
        '+correlation_suvr connectivity*', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    ['graphs' filesep 'test_GraphWU.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeEnsemble_ST_WU.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUD.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUT.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_AnalyzeEnsemble_FUN_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUD.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUT.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_AnalyzeEnsemble_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUD.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_but.braph2'] ...   
    };