distribution_name = 'Individual Connectome';
distribution_moniker = 'individualconnectome';
pipeline_folders = {
    'region-of-interest suvr'
    'correlation_suvr connectivity'
    'divergence_suvr connectivity'
    'distance_suvr connectivity'
    'deviation_suvr connectivity'
    'group_data'
    };
braph2_version = 'heads/ywc-lite-genesis';

%% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util', '+_Exporter.gen.m', '+_Importer.gen.m', ...
    '+ds*', '-ds_examples', ...
    '+atlas*', ...
    '+gt', '+_Measure.gen.m', '+_Graph.gen.m', '+_GraphAdjPF.gen.m', '+_GraphHistPF.gen.m', '+_GraphPP_MDict.gen.m', '+_NoValue.gen.m', ...
        '+_MeasurePF.gen.m', '+_MeasurePF_GU.gen.m', '+_MeasurePF_NU.gen.m', '+_MeasurePF_NxPP_Node.gen.m', '+_MeasurePF_xUPP_Layer.gen.m', ...
    '+cohort*', ...
    '+analysis*', ...
    '+nn*', ...
    '+gui*', ...
    '+brainsurfs*', ...
    '+atlases*', ...
    '+graphs',  '+_GraphWU.gen.m', ...
    '+measures', '+_Strength.gen.m','+_Degree.gen.m', ...
    '+neuralnetworks*','-_NNRegressorMLP.gen.m','-_NNRegressorMLP_CrossValidation.gen.m','-_NNRegressorMLP_CrossValidationPF_Scatter.gen.m', ...
        '-_NNRegressorMLP_Evaluator.gen.m','-_NNRegressorMLP_EvaluatorPF_Scatter.gen.m', ...
    '+pipelines', ...
        '+connectivity*', '-_AnalyzeEnsemble_CON_BUD.gen.m', '-_AnalyzeEnsemble_CON_BUT.gen.m', ...
        '+functional*', '-_AnalyzeEnsemble_FUN_BUD.gen.m', '-_AnalyzeEnsemble_FUN_BUT.gen.m', ...
        '+structural*', '-_AnalyzeGroup_ST_BUD.gen.m', '-_AnalyzeGroup_ST_BUT.gen.m', ... 
        '+region-of-interest suvr*', ...
        '+correlation_suvr connectivity*', ...
        '+divergence_suvr connectivity*', ...
        '+deviation_suvr connectivity*', ...
        '+distance_suvr connectivity*', ...
        '+group_data*', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    ['measures' filesep 'test_Degree.m'], ...
    ['measures' filesep 'test_Strength.m'], ...    
    ['graphs' filesep 'test_GraphWU.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeEnsemble_ST_WU.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUD.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUT.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeGroup_ST_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_AnalyzeEnsemble_FUN_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUD.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUT.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_AnalyzeEnsemble_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUD.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_but.braph2'], ...  
    ['neuralnetworks' filesep 'test_NNClassifierMLP.m'], ...  
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_CLA.m'], ...  
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_REG.m'], ... 
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_CLA.m'], ... 
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_REG.m'], ... 
    ['neuralnetworks' filesep 'test_NNRegressorMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_CrossValidation.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_Evaluator.m'], ...
    };