distribution_name = 'Individual Connectome';
distribution_moniker = 'individualconnectome';
pipeline_folders = {
    'region-of-interest suvr'
    'correlation_suvr connectivity'
    'divergence_suvr connectivity'
    'distance_suvr connectivity'
    'perturbation connectivity'
    };
braph2_version = 'heads/develop';

%% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util', '+_Exporter.gen.m', '+_Importer.gen.m', ...
    '+ds*', '-ds_examples', ...
    '+atlas*', ...
    '+gt', '+_Measure.gen.m', '+_Graph.gen.m', '+_GraphAdjPF.gen.m', '+_GraphHistPF.gen.m', '+_GraphPP_MDict.gen.m', '+_NoValue.gen.m', ...
        '+_MeasurePF.gen.m', '+_MeasurePF_GU.gen.m', '+_MeasurePF_NU.gen.m', '+_MeasurePF_NxPP_Node.gen.m', '+_MeasurePF_xUPP_Layer.gen.m','+_MeasurePF_BU.gen.m', ...
    '+cohort*', ...
    '+analysis*', ...
    '+nn*', ...
    '+gui*', ...
    '+brainsurfs*', ...
    '+atlases*', ...
    '+graphs',  '+_GraphWU.gen.m', '+_GraphBU.gen.m','+_GraphWD.gen.m', '+_GraphBD.gen.m', '+_MultigraphBUT.gen.m', '+_MultigraphBUD.gen.m', '+_MultiplexWU.gen.m', ...
    '+measures', '+_Strength.gen.m', '+_Degree.gen.m', '+_GlobalEfficiency.gen.m', '+_LocalEfficiency.gen.m', '+_Clustering.gen.m','+_CorePeriphery.gen.m', '+_Distance.gen.m', '+_Triangles.gen.m', '+_Richness.gen.m', ...
    '+neuralnetworks*','-_NNRegressorMLP.gen.m','-_NNRegressorMLP_CrossValidation.gen.m','-_NNRegressorMLP_CrossValidationPF_Scatter.gen.m', ...
        '-_NNRegressorMLP_Evaluator.gen.m','-_NNRegressorMLP_EvaluatorPF_Scatter.gen.m', ...
    '+pipelines', ...
        '+connectivity*', ...
        '+functional*',  ...
        '+structural*',  ...
        '+region-of-interest suvr*', ...
        '+correlation_suvr connectivity*', ...
        '+divergence_suvr connectivity*', ...
        '+distance_suvr connectivity*', ...
        '+perturbation connectivity*',...
        '+structural NN*', ...
        '+connectivity NN*', ...
        '+functional NN*', ...
        '+connectivity multiplex*', '-_AnalyzeEnsemble_CON_MP_BUD.gen.m', '-_AnalyzeEnsemble_CON_MP_BUT.gen.m', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    ['measures' filesep 'test_Degree.m'], ...
    ['measures' filesep 'test_Strength.m'], ...
    ['src' filesep 'test_Exporter.m'], ...
    ['graphs' filesep 'test_GraphWU.m'], ...
    ['pipelines' filesep 'structural NN' filesep 'test_NNDataPoint_ST_CLA.m'], ...
    ['pipelines' filesep 'structural NN' filesep 'test_NNDataPoint_ST_REG.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeEnsemble_ST_WU.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUD.m'], ...
    ['pipelines' filesep 'structural' filesep 'example_ST_BUT.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeGroup_ST_WU.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_SubjectST.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_ImporterGroupSubjectST_XLS.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_ImporterGroupSubjectST_TXT.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_ExporterGroupSubjectST_XLS.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_ExporterGroupSubjectST_TXT.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeGroup_ST_BUT.m'], ...
    ['pipelines' filesep 'structural' filesep 'test_AnalyzeGroup_ST_BUD.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_AnalyzeEnsemble_FUN_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUD.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_BUT.m'], ...
    ['pipelines' filesep 'functional' filesep 'example_FUN_WU.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_ExporterGroupSubjectFUN_TXT.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_ExporterGroupSubjectFUN_XLS.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_ImporterGroupSubjectFUN_TXT.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_ImporterGroupSubjectFUN_XLS.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_SubjectFUN.m'], ...
    ['pipelines' filesep 'functional' filesep 'test_AnalyzeEnsemble_FUN_BUD.m'], ...
    ['pipelines' filesep 'functional NN' filesep 'test_NNDataPoint_FUN_CLA.m'], ...
    ['pipelines' filesep 'functional NN' filesep 'test_NNDataPoint_FUN_REG.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_AnalyzeEnsemble_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_AnalyzeEnsemble_CON_BUD.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_AnalyzeEnsemble_CON_BUT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_ExporterGroupSubjectCON_TXT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_ExporterGroupSubjectCON_XLS.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_ImporterGroupSubjectCON_TXT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'test_ImporterGroupSubjectCON_XLS.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUD.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_BUT.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'example_CON_WU.m'], ...
    ['pipelines' filesep 'connectivity multiplex' filesep 'test_AnalyzeEnsemble_CON_MP_WU.m'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_connectivity_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_functional_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_wu.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_analysis_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_bud.braph2'], ...
    ['pipelines' filesep 'connectivity' filesep 'pipeline_structural_comparison_but.braph2'], ...
    ['pipelines' filesep 'connectivity NN' filesep 'test_NNDataPoint_CON_CLA.m'], ...
    ['pipelines' filesep 'connectivity NN' filesep 'test_NNDataPoint_CON_REG.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP.m'], ...  
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_CLA.m'], ...  
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_REG.m'], ... 
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_CLA.m'], ... 
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_REG.m'], ... 
    ['neuralnetworks' filesep 'test_NNRegressorMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_CrossValidation.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP.m'], ...
    ['measures' filesep 'test_Triangles.m'], ...
    ['measures' filesep 'test_Richness.m'], ...
    ['measures' filesep 'test_LocalEfficiency.m'], ...
    ['measures' filesep 'test_GlobalEfficiency.m'], ...
    ['measures' filesep 'test_Distance.m'], ...
    ['measures' filesep 'test_CorePeriphery.m'], ...
    ['measures' filesep 'test_Clustering.m'], ...
    ['graphs' filesep 'test_GraphBD.m'], ...
    ['graphs' filesep 'test_GraphBU.m'], ...
    ['graphs' filesep 'test_GraphWD.m'], ...
    ['graphs' filesep 'test_MultigraphBUD.m'], ...
    ['graphs' filesep 'test_MultigraphBUT.m'], ...
    ['graphs' filesep 'test_MultiplexWU.m'], ...
    };