% EXAMPLE_CON_WU
% Script example pipeline Correlation CON WU
clear variables %#ok<*NASGU>
addpath(genpath('/home/hang/GitHub/Individual-connectome/group_data/ADNI_DATA'));
addpath(genpath('/home/hang/GitHub/IndividualConnectome-WithYuwei/braph2individualconnectome'));
%% load Nifty images
%%group1
im_gr3_WM_GM = ImporterGroupSubjNIfTI('DIRECTORY', [fileparts(which('AD_PositiveAmyloid.vois.xlsx')) filesep 'AD_PositiveAmyloid'], ...
    'NIFTI_TYPE', {'wc1','wc2'},...
    'WAITBAR', true);
gr3_WM_GM = im_gr3_WM_GM.get('GR');

im_gr3_PET = ImporterGroupSubjNIfTI('DIRECTORY', [fileparts(which('AD_PositiveAmyloid.vois.xlsx')) filesep 'AD_PositiveAmyloid'], ...
    'NIFTI_TYPE', {'wroriented_raw_pet'},...
    'WAITBAR', true);
gr3_PET = im_gr3_PET.get('GR');

%%group2
im_gr1_WM_GM = ImporterGroupSubjNIfTI('DIRECTORY',[fileparts(which('Healthy_NegativeAmyloid.vois.xlsx')) filesep 'Healthy_NegativeAmyloid'], ...
    'NIFTI_TYPE', {'wc1','wc2'},...
    'WAITBAR', true);
gr1_WM_GM = im_gr1_WM_GM.get('GR');

im_gr1_PET = ImporterGroupSubjNIfTI('DIRECTORY', [fileparts(which('Healthy_NegativeAmyloid.vois.xlsx')) filesep 'Healthy_NegativeAmyloid'], ...
    'NIFTI_TYPE', {'wroriented_raw_pet'},...
    'WAITBAR', true);
gr1_PET = im_gr1_PET.get('GR');

%%group3
im_gr2_WM_GM = ImporterGroupSubjNIfTI('DIRECTORY', [fileparts(which('MCI_PositiveAmyloid.vois.xlsx')) filesep 'MCI_PositiveAmyloid'], ...
    'NIFTI_TYPE', {'wc1','wc2'},...
    'WAITBAR', true);
gr2_WM_GM = im_gr2_WM_GM.get('GR');

im_gr2_PET = ImporterGroupSubjNIfTI('DIRECTORY', [fileparts(which('MCI_PositiveAmyloid.vois.xlsx')) filesep 'MCI_PositiveAmyloid'], ...
    'NIFTI_TYPE', {'wroriented_raw_pet'},...
    'WAITBAR', true);
gr2_PET = im_gr2_PET.get('GR');
%% PDF Construtor
path_dict = IndexedDictionary(...
    'IT_CLASS', 'FILE_PATH', ...
    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii')),FILE_PATH('PATH', which('upsampled_TD.nii'))} ...
    );

mapping_path_dict = IndexedDictionary(...
    'IT_CLASS', 'FILE_PATH', ...
    'IT_LIST', {FILE_PATH('PATH', which('AAL2_Atlas_Labels_Abbre.csv')),FILE_PATH('PATH', which('TD_Atlas_Labels.csv'))} ...
    );
% Import two brain atlases
im_ba1 = ImporterBrainAtlasXLS('FILE', which('aal120_atlas.xlsx'),  'WAITBAR', true);
ba1 = im_ba1.get('BA');
im_ba2 = ImporterBrainAtlasXLS('FILE', which('TD_atlas.xlsx'), 'WAITBAR', true);
ba2 = im_ba2.get('BA');

% Create ItemList for BA
ba_list = {ba1, ba2}; 
atlas = ba_list{1};
br_dict = atlas.get('BR_DICT');
selected_ids = num2cell(1:120);
selected_br = cellfun(@(id) br_dict.get('IT', id), selected_ids, 'UniformOutput', false);
selected_br_dict = IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST',  {selected_br{1:94}});
gr1 = PDFConstructor('GR_PET',gr1_PET, ...
    'GR_T1',gr1_WM_GM, ...
    'BA', ba_list,...
    'ATLAS_PATH_DICT' ,path_dict, ...
    'MAPPING_PATH_DICT', mapping_path_dict, ...
    'REF_REGION_LIST',{[9100,9110,9120,9130,9140,9150,9160,9170], 7}, ...
    'ATLAS_INDEX', 1, ...
    'ATLAS_KIND', {'AAL2','TD'}, ...
    'PDF_REGION_SELECTION', selected_br_dict);
pdf_gr1 = gr1.get('GR');

gr2 = PDFConstructor('GR_PET',gr2_PET, ...
    'GR_T1',gr2_WM_GM, ...
    'BA', ba_list,...
    'ATLAS_PATH_DICT' ,path_dict, ...
    'MAPPING_PATH_DICT', mapping_path_dict, ...
    'REF_REGION_LIST',{[9100,9110,9120,9130,9140,9150,9160,9170], 7}, ...
    'ATLAS_INDEX', 1, ...
    'ATLAS_KIND', {'AAL2','TD'}, ...
    'PDF_REGION_SELECTION', selected_br_dict);
pdf_gr2 = gr2.get('GR');

gr3 = PDFConstructor('GR_PET',gr3_PET, ...
    'GR_T1',gr3_WM_GM, ...
    'BA', ba_list,...
    'ATLAS_PATH_DICT' ,path_dict, ...
    'MAPPING_PATH_DICT', mapping_path_dict, ...
    'REF_REGION_LIST',{[9100,9110,9120,9130,9140,9150,9160,9170], 7}, ...
    'ATLAS_INDEX', 1, ...
    'ATLAS_KIND', {'AAL2','TD'}, ...
    'PDF_REGION_SELECTION', selected_br_dict);
pdf_gr3 = gr3.get('GR');

%% Load Groups of SubjectCON Correlation based
g_temp  = GraphWU('STANDARDIZE_RULE', 'range');
a_WU1 = AnalyzeEnsemble_FUN_WU( ...
    'GR', pdf_gr1, ...
    'REPETITION', 0, ...
    'GRAPH_TEMPLATE', g_temp...
    );
gr1_corr = a_WU1.get('G_DICT');

a_WU2 = AnalyzeEnsemble_FUN_WU( ...
    'GR', pdf_gr2, ...
    'REPETITION', 0, ...
    'GRAPH_TEMPLATE', g_temp...
    );
gr2_corr = a_WU2.get('G_DICT');

a_WU3 = AnalyzeEnsemble_FUN_WU( ...
    'GR', pdf_gr3, ...
    'REPETITION', 0, ...
    'GRAPH_TEMPLATE', g_temp...
    );
gr3_corr = a_WU3.get('G_DICT');
%%

% ǵroup 1
[~, group_folder_name1] = fileparts(im_gr1_PET.get('DIRECTORY'));
it_list1 = cellfun(@(x) NNDataPoint_Graph_CLA( ...
    'ID', x.get('ID'), ...
    'G', x, ...
    'TARGET_CLASS', {group_folder_name1}), ...
     a_WU1.get('G_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% Get the subject dictionary and extract the list of subjects
sub_dict1 = gr1_WM_GM.get('SUB_DICT');
sub_list1 = sub_dict1.get('IT_LIST'); % Get all subjects as a cell array

% Use cellfun to create NNDataPoint_VOIs for each subject
it_list_voi1 = cellfun(@(sub) NNDataPoint_VOIs( ...
    'ID', sub.get('ID'), ...
    'VOI_DICT', IndexedDictionary( ...
        'ID', 'subject_idict', ...
        'IT_CLASS', 'SubjectNIfTI', ...
        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
        ), ...
    'TARGET_CLASS', {group_folder_name1} ...
    ), sub_list1, 'UniformOutput', false);

% ǵroup 2
[~, group_folder_name2] = fileparts(im_gr2_PET.get('DIRECTORY'));
it_list2 = cellfun(@(x) NNDataPoint_Graph_CLA( ...
    'ID', x.get('ID'), ...
    'G', x, ...
    'TARGET_CLASS', {group_folder_name2}), ...
     a_WU2.get('G_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% Get the subject dictionary and extract the list of subjects
sub_dict2 = gr2_WM_GM.get('SUB_DICT');
sub_list2 = sub_dict2.get('IT_LIST'); % Get all subjects as a cell array

% Use cellfun to create NNDataPoint_VOIs for each subject
it_list_voi2 = cellfun(@(sub) NNDataPoint_VOIs( ...
    'ID', sub.get('ID'), ...
    'VOI_DICT', IndexedDictionary( ...
        'ID', 'subject_idict', ...
        'IT_CLASS', 'SubjectNIfTI', ...
        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
        ), ...
    'TARGET_CLASS', {group_folder_name2} ...
    ), sub_list2, 'UniformOutput', false);

% ǵroup 3
[~, group_folder_name3] = fileparts(im_gr3_PET.get('DIRECTORY'));
it_list3 = cellfun(@(x) NNDataPoint_Graph_CLA( ...
    'ID', x.get('ID'), ...
    'G', x, ...
    'TARGET_CLASS', {group_folder_name3}), ...
     a_WU3.get('G_DICT').get('IT_LIST'), ...
    'UniformOutput', false);
% Get the subject dictionary and extract the list of subjects
sub_dict3 = gr3_WM_GM.get('SUB_DICT');
sub_list3 = sub_dict3.get('IT_LIST'); % Get all subjects as a cell array

% Use cellfun to create NNDataPoint_VOIs for each subject
it_list_voi3 = cellfun(@(sub) NNDataPoint_VOIs( ...
    'ID', sub.get('ID'), ...
    'VOI_DICT', IndexedDictionary( ...
        'ID', 'subject_idict', ...
        'IT_CLASS', 'SubjectNIfTI', ...
        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
        ), ...
    'TARGET_CLASS', {group_folder_name3} ...
    ), sub_list3, 'UniformOutput', false);



dp_list1 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_Graph_CLA', ...
        'IT_LIST', it_list1 ...
        );

dp_list2 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_Graph_CLA', ...
        'IT_LIST', it_list2 ...
        );

dp_list3 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_Graph_CLA', ...
        'IT_LIST', it_list3 ...
        );


dp_list_voi1 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_VOIs', ...
        'IT_LIST', it_list_voi1 ...
        );

dp_list_voi2 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_VOIs', ...
        'IT_LIST', it_list_voi2 ...
        );

dp_list_voi3 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_VOIs', ...
        'IT_LIST', it_list_voi3 ...
        );



d1 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_Graph_CLA', ...
    'DP_DICT', dp_list1 ...
    );
d1_vois = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_VOIs', ...
    'DP_DICT', dp_list_voi1 ...
    );

d2 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_Graph_CLA', ...
    'DP_DICT', dp_list2 ...
    );
d2_vois = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_VOIs', ...
    'DP_DICT', dp_list_voi2 ...
    );

d3 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_Graph_CLA', ...
    'DP_DICT', dp_list3 ...
    );
d3_vois = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_VOIs', ...
    'DP_DICT', dp_list_voi3 ...
    );





%% Classification with Train-Test Split
num_runs = 50;
train_size = 80;
confusion_cn_mci = cell(1, num_runs);
auc_cn_mci = zeros(1, num_runs);
confusion_cn_ad = cell(1, num_runs);
auc_cn_ad = zeros(1, num_runs);
%%
len_gr1 = length(it_list1);
len_gr2 = length(it_list2);
len_gr3 = length(it_list3);

parfor run = 1:num_runs
    tic
    rng(run);
    disp(run)
    nn_template = NNClassifierMLP_VOIs('EPOCHS', 50, 'LAYERS', [128 128]);
    num_dp_d1 = d1.get('DP_DICT').get('LENGTH');
    num_dp_d2 = d2.get('DP_DICT').get('LENGTH');
    num_dp_d3 = d3.get('DP_DICT').get('LENGTH');
    shuffled_indices_d1 = randperm(num_dp_d1);
    shuffled_indices_d2 = randperm(num_dp_d2);
    shuffled_indices_d3 = randperm(num_dp_d3);
    split_points_d1 = round(linspace(0, num_dp_d1, 6));
    split_points_d2 = round(linspace(0, num_dp_d2, 6));
    split_points_d3 = round(linspace(0, num_dp_d3, 6));
    SPLIT_cn_mci_ad = cell(3, 5);
    for i = 1:5
        SPLIT_cn_mci_ad{1, i} = shuffled_indices_d1(split_points_d1(i)+1:split_points_d1(i+1));
        SPLIT_cn_mci_ad{2, i} = shuffled_indices_d2(split_points_d2(i)+1:split_points_d2(i+1));
        SPLIT_cn_mci_ad{3, i} = shuffled_indices_d3(split_points_d3(i)+1:split_points_d3(i+1));   
    end
    nncv_mci_ad = NNClassifierMLP_CrossValidation_VOIs('D', {d1, d2, d3}, 'D_VOIS', {d1_vois, d2_vois, d3_vois}, ...
        'KFOLDS', 5, 'NN_TEMPLATE', nn_template, 'SPLIT', SPLIT_cn_mci_ad);
    nncv_mci_ad.get('TRAIN');

        % Evaluate performance for CN vs. AD5tr43
    cm_cn_mci_ad = nncv_mci_ad.get('C_MATRIX');
    confusion_matrix_cn_mci_ad{run} = cm_cn_mci_ad;
    av_macro_auc_cn_mci_ad(run) = nncv_mci_ad.get('AV_MACRO_AUC');
    TP = cm_cn_mci_ad(2,2); TN = cm_cn_mci_ad(1,1); FP = cm_cn_mci_ad(1,2); FN = cm_cn_mci_ad(2,1);
    sensitivity_cn_mci_ad(run) = TP / (TP + FN);
    specificity_cn_mci_ad(run) = TN / (TN + FP);
    toc
end

%% Save Results
results.CN_vs_MCI_vs_AD.Confusion = {confusion_matrix_cn_mci_ad};
results.CN_vs_MCI_vs_AD.AUC = av_macro_auc_cn_mci_ad(av_macro_auc_cn_mci_ad~=0);
results.CN_vs_MCI_vs_AD.Spe = specificity_cn_mci_ad(specificity_cn_mci_ad~=0);
results.CN_vs_MCI_vs_AD.Sen = sensitivity_cn_mci_ad(sensitivity_cn_mci_ad~=0);


save('Results/classification_results_correlation_3class.mat', 'results');