%EXAMPLE_CON_WU
% Script example pipeline CON WU

clear variables %#ok<*NASGU>


%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [which('aal94_atlas.xlsx')], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');



%% load Nifty images
im_gr1_WM_GM = ImporterGroupSubjNifti('DIRECTORY', ['/home/hang/GitHub/Individual-connectome/group_data/test/test'], ...
    'NIFTI_TYPE', {'WM','GM'},...
    'WAITBAR', true);
gr1_WM_GM = im_gr1_WM_GM.get('GR');

im_gr1_PET = ImporterGroupSubjNifti('DIRECTORY', ['/home/hang/GitHub/Individual-connectome/group_data/test/test'], ...
    'NIFTI_TYPE', {'PET'},...
    'WAITBAR', true);
gr1_PET = im_gr1_PET.get('GR');

%% PDF Construtor
path_dict = IndexedDictionary(...
    'IT_CLASS', 'FILE_PATH', ...
    'IT_LIST', {FILE_PATH('PATH', '/home/hang/GitHub/Individual-connectome/group_data/test/atlas/AAL2_registered.nii'),FILE_PATH('PATH', '/home/hang/GitHub/Individual-connectome/group_data/test/atlas/TD_lobe_registered.nii')} ...
    );
suvr_brain_label = readtable('group_data/test/atlas/AAL2_Atlas_Labels.csv');
suvr_brain_label = suvr_brain_label.Var4;
im_gr_pdf = PDFConstructor('GR_PET',gr1_PET, ...
    'GR_T1',gr1_WM_GM, ...
    'BA', ba,...
    'ATLAS_PATH_DICT' ,path_dict, ...
    'REF_REGION_LIST',{[9100,9110,9120,9130,9140,9150,9160,9170], 7}, ...
    'ATLAS_KIND', {'AAL2','TD'},...
    'SUVR_REGION_SELECTION',suvr_brain_label);
gr1 = im_gr_pdf.get('GR');



%% Load Groups of SubjectCON divergence based
a_WU1 = AnalyzeEnsembleDivergence_FUN_WU( ...
    'GR', gr1 ...
    );
gr1_divergence = a_WU1.get('G_DICT');



