%TEST_INDIVIDUALDISTANCECONCONSTRUCTOR

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	icd = IndividualDistanceConConstructor();
	 
	% get('ELCLASS')
	if isa(IndividualDistanceConConstructor, 'ConcreteElement')
		assert(strcmp(IndividualDistanceConConstructor().get('ELCLASS'), 'IndividualDistanceConConstructor'), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor().get(''ELCLASS'') should return ''IndividualDistanceConConstructor''.')
	end
	 
	% getBuild()
	assert(IndividualDistanceConConstructor.getBuild() == 1 && IndividualDistanceConConstructor.getBuild() > 0, ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getBuild() should return the IndividualDistanceConConstructor build number.')
	assert(icd.getBuild() == 1 && icd.getBuild() > 0 , ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getBuild() should return the IndividualDistanceConConstructor build number.')
	assert(Element.getBuild(icd) == 1 && Element.getBuild(icd) > 0, ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(icd) should return the IndividualDistanceConConstructor build number.')
	assert(Element.getBuild('IndividualDistanceConConstructor') == 1 && Element.getBuild('IndividualDistanceConConstructor') > 0, ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''IndividualDistanceConConstructor'') should return the IndividualDistanceConConstructor build number.')
	 
	% getClass()
	assert(strcmp(IndividualDistanceConConstructor.getClass(), 'IndividualDistanceConConstructor'), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getClass() should return ''IndividualDistanceConConstructor''.')
	assert(strcmp(icd.getClass(), 'IndividualDistanceConConstructor'), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getClass() should return ''IndividualDistanceConConstructor''.')
	assert(strcmp(Element.getClass(icd), 'IndividualDistanceConConstructor'), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(icd) should return ''IndividualDistanceConConstructor''.')
	assert(strcmp(Element.getClass('IndividualDistanceConConstructor'), 'IndividualDistanceConConstructor'), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''IndividualDistanceConConstructor'') should return ''IndividualDistanceConConstructor''.')
	 
	% getSubclasses()
	assert(isequal(IndividualDistanceConConstructor.getSubclasses(), subclasses('IndividualDistanceConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getSubclasses() should return the same result as subclasses(''IndividualDistanceConConstructor'', [], [], true).')
	assert(isequal(icd.getSubclasses(), subclasses('IndividualDistanceConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''IndividualDistanceConConstructor'', [], [], true).')
	assert(isequal(Element.getSubclasses(icd), subclasses('IndividualDistanceConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(icd) should return the same result as subclasses(''IndividualDistanceConConstructor'', [], [], true).')
	assert(isequal(Element.getSubclasses('IndividualDistanceConConstructor'), subclasses('IndividualDistanceConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''IndividualDistanceConConstructor'') should return the same result as subclasses(''IndividualDistanceConConstructor'', [], [], true).')
	 
	% getProps()
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(IndividualDistanceConConstructor.getProps(), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getProps() should return a row vector [1:1:N].')
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(icd.getProps(), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getProps() should return a row vector [1:1:N].')
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(Element.getProps(icd), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(icd) should return a row vector [1:1:N].')
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(Element.getProps('IndividualDistanceConConstructor'), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''IndividualDistanceConConstructor'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) IndividualDistanceConConstructor.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getProps(category) does not work.')
	tmp = cellfun(@(category) icd.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(icd, category), categories, 'UniformOutput', false);
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(icd, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('IndividualDistanceConConstructor', category), categories, 'UniformOutput', false);
	assert(isempty(IndividualDistanceConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualDistanceConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''IndividualDistanceConConstructor'', category) does not work.')
	 
	% getPropNumber()
	assert(IndividualDistanceConConstructor.getPropNumber() == length(IndividualDistanceConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getPropNumber() should return the number of properties.')
	assert(icd.getPropNumber() == length(IndividualDistanceConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(icd) == length(IndividualDistanceConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(icd) should return the number of properties.')
	assert(Element.getPropNumber('IndividualDistanceConConstructor') == length(IndividualDistanceConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''IndividualDistanceConConstructor'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) IndividualDistanceConConstructor.getPropNumber(category), categories)) == IndividualDistanceConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) icd.getPropNumber(category), categories)) == IndividualDistanceConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(icd, category), categories)) == IndividualDistanceConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(icd, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('IndividualDistanceConConstructor', category), categories)) == IndividualDistanceConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''IndividualDistanceConConstructor'', category) does not work.')
	 
	% existsProp(prop)
	assert(~IndividualDistanceConConstructor.existsProp(NaN), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.existsProp(prop) does not work.')
	assert(~icd.existsProp(NaN), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.existsProp(prop) does not work.')
	assert(~Element.existsProp(icd, NaN), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(icd, prop) does not work.')
	assert(~Element.existsProp('IndividualDistanceConConstructor', NaN), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''IndividualDistanceConConstructor'', prop) does not work.')
	 
	assert_with_error('IndividualDistanceConConstructor.existsProp(NaN)', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsProp(''IndividualDistanceConConstructor'', NaN)', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		assert(IndividualDistanceConConstructor.existsProp(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.existsProp(prop) does not work.')
		assert(icd.existsProp(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.existsProp(prop) does not work.')
		assert(Element.existsProp(icd, prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(icd, prop) does not work.')
		assert(Element.existsProp('IndividualDistanceConConstructor', prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''IndividualDistanceConConstructor'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~IndividualDistanceConConstructor.existsTag(''), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.existsTag(tag) does not work.')
	assert(~icd.existsTag(''), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'icd.existsTag(tag) does not work.')
	assert(~Element.existsTag(icd, ''), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(icd, tag) does not work.')
	assert(~Element.existsTag('IndividualDistanceConConstructor', ''), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''IndividualDistanceConConstructor'', tag) does not work.')
	 
	assert_with_error('IndividualDistanceConConstructor.existsTag('''')', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsTag(''IndividualDistanceConConstructor'', '''')', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
		assert(IndividualDistanceConConstructor.existsTag(tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.existsTag(tag) does not work.')
		assert(icd.existsTag(tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.existsTag(tag) does not work.')
		assert(Element.existsTag(icd, tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(icd, tga) does not work.')
		assert(Element.existsTag('IndividualDistanceConConstructor', tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		assert(IndividualDistanceConConstructor.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropProp(prop) does not work.')
		assert(icd.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropProp(prop) does not work.')
		assert(Element.getPropProp(icd, prop) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(icd, prop) does not work.')
		assert(Element.getPropProp('IndividualDistanceConConstructor', prop) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''IndividualDistanceConConstructor'', prop) does not work.')
	 
		tag = icd.getPropTag(prop);
		assert(IndividualDistanceConConstructor.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropProp(tag) does not work.')
		assert(icd.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropProp(tag) does not work.')
		assert(Element.getPropProp(icd, tag) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(icd, tag) does not work.')
		assert(Element.getPropProp('IndividualDistanceConConstructor', prop) == prop, ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(strcmp(IndividualDistanceConConstructor.getPropTag(prop), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropTag(prop) does not work.')
		assert(strcmp(icd.getPropTag(prop), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(icd, prop), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(icd, prop) does not work.')
		assert(strcmp(Element.getPropTag('IndividualDistanceConConstructor', prop), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''IndividualDistanceConConstructor'', prop) does not work.')
	 
		assert(strcmp(IndividualDistanceConConstructor.getPropTag(tag), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropTag(tag) does not work.')
		assert(strcmp(icd.getPropTag(tag), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(icd, tag), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(icd, tag) does not work.')
		assert(strcmp(Element.getPropTag('IndividualDistanceConConstructor', prop), tag), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(Category.existsCategory(IndividualDistanceConConstructor.getPropCategory(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(icd.getPropCategory(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(icd, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''IndividualDistanceConConstructor'', prop) does not work.')
	 
		assert(Category.existsCategory(IndividualDistanceConConstructor.getPropCategory(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(icd.getPropCategory(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(icd, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(Format.existsFormat(IndividualDistanceConConstructor.getPropFormat(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(icd.getPropFormat(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(icd, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''IndividualDistanceConConstructor'', prop) does not work.')
	 
		assert(Format.existsFormat(IndividualDistanceConConstructor.getPropFormat(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(icd.getPropFormat(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(icd, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(ischar(IndividualDistanceConConstructor.getPropDescription(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropDescription(prop) does not work.')
		assert(ischar(icd.getPropDescription(prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(icd, prop) does not work.')
		assert(ischar(Element.getPropDescription(icd, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''IndividualDistanceConConstructor'', prop) does not work.')
	 
		assert(ischar(IndividualDistanceConConstructor.getPropDescription(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.getPropDescription(tag) does not work.')
		assert(ischar(icd.getPropDescription(tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(icd, tag) does not work.')
		assert(ischar(Element.getPropDescription(icd, tag)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''IndividualDistanceConConstructor'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		settings = IndividualDistanceConConstructor.getPropSettings(prop);
		settings = icd.getPropSettings(prop);
		settings = Element.getPropSettings(icd, prop);
		settings = Element.getPropSettings('IndividualDistanceConConstructor', prop);
	 
		settings = IndividualDistanceConConstructor.getPropSettings(tag);
		settings = icd.getPropSettings(tag);
		settings = Element.getPropSettings(icd, tag);
		settings = Element.getPropSettings('IndividualDistanceConConstructor', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		default = IndividualDistanceConConstructor.getPropDefault(prop);
		default = icd.getPropDefault(prop);
		default = Element.getPropDefault(icd, prop);
		default = Element.getPropDefault('IndividualDistanceConConstructor', prop);
	 
		default = IndividualDistanceConConstructor.getPropDefault(tag);
		default = icd.getPropDefault(tag);
		default = Element.getPropDefault(icd, tag);
		default = Element.getPropDefault('IndividualDistanceConConstructor', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		conditioned_default = IndividualDistanceConConstructor.getPropDefaultConditioned(prop);
		conditioned_default = icd.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(icd, prop);
		conditioned_default = Element.getPropDefaultConditioned('IndividualDistanceConConstructor', prop);
	 
		conditioned_default = IndividualDistanceConConstructor.getPropDefaultConditioned(tag);
		conditioned_default = icd.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(icd, tag);
		conditioned_default = Element.getPropDefaultConditioned('IndividualDistanceConConstructor', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(~IndividualDistanceConConstructor.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.checkProp(prop, value) does not work.')
		assert(~icd.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(icd, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, prop, value) does not work.')
		assert(~Element.checkProp('IndividualDistanceConConstructor', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualDistanceConConstructor'', prop, value) does not work.')
	 
		assert_with_error('IndividualDistanceConConstructor.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], prop, icd)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], prop, icd)
		assert_with_error('Element.checkProp(''IndividualDistanceConConstructor'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~IndividualDistanceConConstructor.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.checkProp(tag, value) does not work.')
		assert(~icd.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(icd, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, tag, value) does not work.')
		assert(~Element.checkProp('IndividualDistanceConConstructor', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualDistanceConConstructor'', tag, value) does not work.')
	 
		assert_with_error('IndividualDistanceConConstructor.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], tag, icd)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], tag, icd)
		assert_with_error('Element.checkProp(''IndividualDistanceConConstructor'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(IndividualDistanceConConstructor.checkProp(prop, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.checkProp(prop, <conditioned default value>) does not work.')
		assert(icd.checkProp(prop, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(icd, prop, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('IndividualDistanceConConstructor', prop, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualDistanceConConstructor'', prop, <conditioned default value>) does not work.')
	 
		assert(IndividualDistanceConConstructor.checkProp(tag, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.checkProp(tag, <conditioned default value>) does not work.')
		assert(icd.checkProp(tag, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(icd, tag, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('IndividualDistanceConConstructor', tag, Element.getPropDefaultConditioned(IndividualDistanceConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualDistanceConConstructor'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					icd.getr(prop) == IndividualDistanceConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualDistanceConConstructor.getCategoryName(IndividualDistanceConConstructor.getPropCategory(prop)) ', IndividualDistanceConConstructor.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					icd.getr(TAG) == IndividualDistanceConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualDistanceConConstructor.getCategoryName(IndividualDistanceConConstructor.getPropCategory(prop)) ', IndividualDistanceConConstructor.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(icd.getPropSettings(prop))
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop)), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop), icd.getPropSettings(prop)), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					icd.getr(prop) == IndividualDistanceConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualDistanceConConstructor.getCategoryName(IndividualDistanceConConstructor.getPropCategory(prop)) ', IndividualDistanceConConstructor.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					icd.getr(TAG) == IndividualDistanceConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualDistanceConConstructor.getCategoryName(IndividualDistanceConConstructor.getPropCategory(prop)) ', IndividualDistanceConConstructor.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':IndividualDistanceConConstructor']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(icd.getPropSettings(prop))
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop)), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop), icd.getPropSettings(prop)), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(icd.getr(prop), IndividualDistanceConConstructor.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by IndividualDistanceConConstructor.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(icd.getr(TAG), IndividualDistanceConConstructor.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' TAG ') must be inizialized to its default value ' ...
					'given by IndividualDistanceConConstructor.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in IndividualDistanceConConstructor.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(icd.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':IndividualDistanceConConstructor']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':IndividualDistanceConConstructor']);
	% 			assert( ...
	% 				~isa(icd.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualDistanceConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(icd.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualDistanceConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':IndividualDistanceConConstructor']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(icd.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if icd.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:IndividualDistanceConConstructor');
					delete(ancestor(icd.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(IndividualDistanceConConstructor.getProps(Category.RESULT))
		for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch IndividualDistanceConConstructor.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						icd.isLocked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~icd.isLocked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor();
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		assert( ...
			~icd.isLocked(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~icd.isLocked(TAG), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	icd.lock()
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					icd.isLocked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~icd.isLocked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor();
	 
	warning_backup = warning('off', 'BRAPH2:IndividualDistanceConConstructor');
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		icd.lock(prop)
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					icd.isLocked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~icd.isLocked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor();
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		assert( ...
			icd.isChecked(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			icd.isChecked(TAG), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	icd.unchecked()
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		assert( ...
			~icd.isChecked(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	icd.checked()
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		assert( ...
			icd.isChecked(prop), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualDistanceConConstructor.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic IndividualDistanceConConstructor
	icd_0 = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	% IndividualDistanceConConstructor with 1st callbacks
	icd_1 = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, icd_0.getCallback(4), ..., ...
		IndividualDistanceConConstructor.ID, icd_0.getCallback(5), ..., ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, icd_0.getCallback(9), ..., ...
		IndividualDistanceConConstructor.GR_SUVR, icd_0.getCallback(10), ..., ...
		IndividualDistanceConConstructor.GR_SUVR_REF, icd_0.getCallback(11), ..., ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	prop_number = IndividualDistanceConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_1.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% IndividualDistanceConConstructor with 2nd callbacks
	icd_2 = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, icd_1.getCallback(4), ..., ...
		IndividualDistanceConConstructor.ID, icd_1.getCallback(5), ..., ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, icd_1.getCallback(9), ..., ...
		IndividualDistanceConConstructor.GR_SUVR, icd_1.getCallback(10), ..., ...
		IndividualDistanceConConstructor.GR_SUVR_REF, icd_1.getCallback(11), ..., ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	prop_number = IndividualDistanceConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_2.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% IndividualDistanceConConstructor with 3rd callbacks
	icd_3 = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, icd_2.getCallback(4), ..., ...
		IndividualDistanceConConstructor.ID, icd_2.getCallback(5), ..., ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, icd_2.getCallback(9), ..., ...
		IndividualDistanceConConstructor.GR_SUVR, icd_2.getCallback(10), ..., ...
		IndividualDistanceConConstructor.GR_SUVR_REF, icd_2.getCallback(11), ..., ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	prop_number = IndividualDistanceConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_3.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	icd = IndividualDistanceConConstructor();
	 
	icd_copy = icd.copy();
	 
	assert(icd_copy ~= icd, ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(icd_copy, icd), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					icd_copy.isLocked(prop) == icd.isLocked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					icd_copy.isChecked(prop) == icd.isChecked(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		if IndividualDistanceConConstructor.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':IndividualDistanceConConstructor']);
			% icd.memorize(prop);
			% warning(warning_backup)
		elseif IndividualDistanceConConstructor.getPropCategory(prop) == Category.EVANESCENT && icd.getPropFormat(prop) == Format.HANDLE
			icd.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:IndividualDistanceConConstructor');
			delete(ancestor(icd.get(prop), 'figure'))
			warning(warning_backup)
		else
			icd.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	icd_copy = icd.copy();
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						icd_copy.isLocked(prop) == icd.isLocked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.isChecked(prop) == icd.isChecked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	icd_0 = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, icd_0.getCallback(4), ..., ...
		IndividualDistanceConConstructor.ID, icd_0.getCallback(5), ..., ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, icd_0.getCallback(9), ..., ...
		IndividualDistanceConConstructor.GR_SUVR, icd_0.getCallback(10), ..., ...
		IndividualDistanceConConstructor.GR_SUVR_REF, icd_0.getCallback(11), ..., ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	icd_copy = icd.copy();
	icd_0_copy = icd_copy.getr('ID').get('EL');
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualDistanceConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualDistanceConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == icd_0.getCallback(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The callback should be obtained from IndividualDistanceConConstructor.getCallback().' ...
						)
					assert( ...
						value_copy == icd_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The callback should be obtained from IndividualDistanceConConstructor.getCallback().' ...
						)
				end
	 
					assert( ...
						icd_copy.isLocked(prop) == icd.isLocked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.isChecked(prop) == icd.isChecked(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd_template = IndividualDistanceConConstructor();
	icd = IndividualDistanceConConstructor('TEMPLATE', icd_template);
	 
	for prop = 1:1:IndividualDistanceConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualDistanceConConstructor.getPropTag(prop));
		switch IndividualDistanceConConstructor.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == IndividualDistanceConConstructor.TEMPLATE
					assert( ...
						isa(icd.getr(prop), 'IndividualDistanceConConstructor'), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor.getr(''TEMPLATE'') should be a IndividualDistanceConConstructor element.' ...
						)
					assert( ...
						isa(icd_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(icd.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						icd.getr(prop).get('EL') == icd_template && icd.getr(prop).get('PROP') == prop && strcmp(icd.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor.getr(' TAG ') should be a Callback to icd_template.' TAG '.'] ...
						)
					assert( ...
						isa(icd_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(icd_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualDistanceConConstructor TEMPLATE does not work. IndividualDistanceConConstructor_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'individualdistanceconconstructor_to_be_erased.b2'];
	 
	Element.save(icd, filename)
	 
	icd_loaded = Element.load(filename);
	 
	assert( ...
		isequal(icd.copy(), icd_loaded), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.save(icd) and/or IndividualDistanceConConstructor.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = IndividualDistanceConConstructor( ...
		IndividualDistanceConConstructor.ELCLASS, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.NAME, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.DESCRIPTION, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.TEMPLATE, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.TEMPLATE), ...
		IndividualDistanceConConstructor.ID, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.ID), ...
		IndividualDistanceConConstructor.LABEL, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.LABEL), ...
		IndividualDistanceConConstructor.NOTES, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.NOTES), ...
		IndividualDistanceConConstructor.TOSTRING, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.WAITBAR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.WAITBAR), ...
		IndividualDistanceConConstructor.GR_SUVR, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR), ...
		IndividualDistanceConConstructor.GR_SUVR_REF, IndividualDistanceConConstructor.getPropDefault(IndividualDistanceConConstructor.GR_SUVR_REF), ...
		IndividualDistanceConConstructor.CONNECTOME_CONSTUCT_METHOD, IndividualDistanceConConstructor.getNoValue(), ...
		IndividualDistanceConConstructor.GR, IndividualDistanceConConstructor.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(icd);
	[icd_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(icd_dec ~= icd, ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualDistanceConConstructor.encodeJSON() or IndividualDistanceConConstructor.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) IndividualDistanceConConstructor.getPropFormat(prop), num2cell(IndividualDistanceConConstructor.getProps())) == Format.HANDLE) && all(cellfun(@(prop) IndividualDistanceConConstructor.getPropFormat(prop), num2cell(IndividualDistanceConConstructor.getProps())) == Format.NET)
		assert(isequal(icd_dec, icd), ...
			[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualDistanceConConstructor.encodeJSON() or IndividualDistanceConConstructor.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Example data
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	group_dir = fullfile(fileparts(which('IndividualDistanceConConstructor')),'Example data Nifti');
	if ~exist(group_dir)
	    create_example_NIfTI([],group_dir)
	end
end

%% Test 13: Verify the Distance-based individual connectome pipeline
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', which('aal94_atlas.xlsx'));
	ba = im_ba.get('BA');
	
	group_dir = fullfile(fileparts(which('IndividualDistanceConConstructor')),'Example data Nifti', 'Group1');
	im_gr1_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr1_WM_GM = im_gr1_WM_GM.get('GR');
	
	im_gr1_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr1_PET = im_gr1_PET.get('GR');
	
	path_dict = IndexedDictionary(...
	    'IT_CLASS', 'FILE_PATH', ...
	    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii'))} ...
	    );
	
	% suvr_brain_label = readtable(which('AAL2_Atlas_Labels.csv'));
	% suvr_brain_label = suvr_brain_label.Var4;
	ref_region_list = [2001];% reference region label
	
	gr1 = SUVRConstructor('GR_PET',gr1_PET, ...
	    'GR_T1',gr1_WM_GM, ...
	    'BA', ba,...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'ATLAS_KIND', {'AAL2'});
	
	
	SUVR_gr1 = gr1.get('GR');
	
	
	constructor1 = IndividualDistanceConConstructor( ...
	    'GR_SUVR', SUVR_gr1);
	
	distance_connectomes_gr1 = constructor1.get('GR');
	
	g_temp  = GraphWU('STANDARDIZE_RULE', 'range');
	a_WU1 = AnalyzeEnsemble_CON_WU('GR', distance_connectomes_gr1,'GRAPH_TEMPLATE', g_temp);
	num_subjects = a_WU1.get('G_DICT').get('LENGTH');
	
	% Initialize arrays for strength measures
	strength_first20_1 = zeros(num_subjects, 20);
	strength_others_1 = zeros(num_subjects,size(distance_connectomes_gr1.get('SUB_DICT').get('IT', 1).get('CON'),1)- 20);
	
	for i = 1:num_subjects
	    g = a_WU1.get('G_DICT').get('IT', i);
	    strength = g.get('MEASURE', 'Strength').get('M'); % Strength for all regions
	    strength20_regions = strength{1}(1:20,:);
	    strengthother_regions = strength{1}(21:end,:);
	    mean_20 = mean(strength20_regions(:));
	    mean_others = mean(strengthother_regions(:));
	    % Assert for each subject
	    assert(mean_20 < mean_others, ...
	        sprintf('Test failed for subject %d: The first 20 regions do not have higher distance than the other regions.', i));
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':IndividualDistanceConConstructor:' BRAPH2.FAIL_TEST], ...
		[' When testing IndividualDistanceConConstructor no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

