%TEST_IMPORTERGROUPSUBJECTNEUROIMAGING_NIFTI

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	im = ImporterGroupSubjectNeuroimaging_NIfTI();
	 
	% get('ELCLASS')
	if isa(ImporterGroupSubjectNeuroimaging_NIfTI, 'ConcreteElement')
		assert(strcmp(ImporterGroupSubjectNeuroimaging_NIfTI().get('ELCLASS'), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI().get(''ELCLASS'') should return ''ImporterGroupSubjectNeuroimaging_NIfTI''.')
	end
	 
	% getBuild()
	assert(ImporterGroupSubjectNeuroimaging_NIfTI.getBuild() == 1 && ImporterGroupSubjectNeuroimaging_NIfTI.getBuild() > 0, ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getBuild() should return the ImporterGroupSubjectNeuroimaging_NIfTI build number.')
	assert(im.getBuild() == 1 && im.getBuild() > 0 , ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getBuild() should return the ImporterGroupSubjectNeuroimaging_NIfTI build number.')
	assert(Element.getBuild(im) == 1 && Element.getBuild(im) > 0, ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(im) should return the ImporterGroupSubjectNeuroimaging_NIfTI build number.')
	assert(Element.getBuild('ImporterGroupSubjectNeuroimaging_NIfTI') == 1 && Element.getBuild('ImporterGroupSubjectNeuroimaging_NIfTI') > 0, ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ImporterGroupSubjectNeuroimaging_NIfTI'') should return the ImporterGroupSubjectNeuroimaging_NIfTI build number.')
	 
	% getClass()
	assert(strcmp(ImporterGroupSubjectNeuroimaging_NIfTI.getClass(), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getClass() should return ''ImporterGroupSubjectNeuroimaging_NIfTI''.')
	assert(strcmp(im.getClass(), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getClass() should return ''ImporterGroupSubjectNeuroimaging_NIfTI''.')
	assert(strcmp(Element.getClass(im), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(im) should return ''ImporterGroupSubjectNeuroimaging_NIfTI''.')
	assert(strcmp(Element.getClass('ImporterGroupSubjectNeuroimaging_NIfTI'), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ImporterGroupSubjectNeuroimaging_NIfTI'') should return ''ImporterGroupSubjectNeuroimaging_NIfTI''.')
	 
	% getSubclasses()
	assert(isequal(ImporterGroupSubjectNeuroimaging_NIfTI.getSubclasses(), subclasses('ImporterGroupSubjectNeuroimaging_NIfTI', [], [], true)), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getSubclasses() should return the same result as subclasses(''ImporterGroupSubjectNeuroimaging_NIfTI'', [], [], true).')
	assert(isequal(im.getSubclasses(), subclasses('ImporterGroupSubjectNeuroimaging_NIfTI', [], [], true)), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ImporterGroupSubjectNeuroimaging_NIfTI'', [], [], true).')
	assert(isequal(Element.getSubclasses(im), subclasses('ImporterGroupSubjectNeuroimaging_NIfTI', [], [], true)), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(im) should return the same result as subclasses(''ImporterGroupSubjectNeuroimaging_NIfTI'', [], [], true).')
	assert(isequal(Element.getSubclasses('ImporterGroupSubjectNeuroimaging_NIfTI'), subclasses('ImporterGroupSubjectNeuroimaging_NIfTI', [], [], true)), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ImporterGroupSubjectNeuroimaging_NIfTI'') should return the same result as subclasses(''ImporterGroupSubjectNeuroimaging_NIfTI'', [], [], true).')
	 
	% getProps()
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(ImporterGroupSubjectNeuroimaging_NIfTI.getProps(), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getProps() should return a row vector [1:1:N].')
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(im.getProps(), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getProps() should return a row vector [1:1:N].')
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(Element.getProps(im), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(im) should return a row vector [1:1:N].')
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(Element.getProps('ImporterGroupSubjectNeuroimaging_NIfTI'), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ImporterGroupSubjectNeuroimaging_NIfTI'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ImporterGroupSubjectNeuroimaging_NIfTI.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getProps(category) does not work.')
	tmp = cellfun(@(category) im.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(im, category), categories, 'UniformOutput', false);
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(im, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ImporterGroupSubjectNeuroimaging_NIfTI', category), categories, 'UniformOutput', false);
	assert(isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ImporterGroupSubjectNeuroimaging_NIfTI'', category) does not work.')
	 
	% getPropNumber()
	assert(ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber() == length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber() should return the number of properties.')
	assert(im.getPropNumber() == length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(im) == length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(im) should return the number of properties.')
	assert(Element.getPropNumber('ImporterGroupSubjectNeuroimaging_NIfTI') == length(ImporterGroupSubjectNeuroimaging_NIfTI.getProps()), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ImporterGroupSubjectNeuroimaging_NIfTI'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(category), categories)) == ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) im.getPropNumber(category), categories)) == ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(im, category), categories)) == ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(im, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ImporterGroupSubjectNeuroimaging_NIfTI', category), categories)) == ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber(), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ImporterGroupSubjectNeuroimaging_NIfTI'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ImporterGroupSubjectNeuroimaging_NIfTI.existsProp(NaN), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.existsProp(prop) does not work.')
	assert(~im.existsProp(NaN), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.existsProp(prop) does not work.')
	assert(~Element.existsProp(im, NaN), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(im, prop) does not work.')
	assert(~Element.existsProp('ImporterGroupSubjectNeuroimaging_NIfTI', NaN), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
	assert_with_error('ImporterGroupSubjectNeuroimaging_NIfTI.existsProp(NaN)', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', NaN)', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.existsProp(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.existsProp(prop) does not work.')
		assert(im.existsProp(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.existsProp(prop) does not work.')
		assert(Element.existsProp(im, prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(im, prop) does not work.')
		assert(Element.existsProp('ImporterGroupSubjectNeuroimaging_NIfTI', prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ImporterGroupSubjectNeuroimaging_NIfTI.existsTag(''), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.existsTag(tag) does not work.')
	assert(~im.existsTag(''), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'im.existsTag(tag) does not work.')
	assert(~Element.existsTag(im, ''), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(im, tag) does not work.')
	assert(~Element.existsTag('ImporterGroupSubjectNeuroimaging_NIfTI', ''), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	 
	assert_with_error('ImporterGroupSubjectNeuroimaging_NIfTI.existsTag('''')', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsTag(''ImporterGroupSubjectNeuroimaging_NIfTI'', '''')', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.existsTag(tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.existsTag(tag) does not work.')
		assert(im.existsTag(tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.existsTag(tag) does not work.')
		assert(Element.existsTag(im, tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(im, tga) does not work.')
		assert(Element.existsTag('ImporterGroupSubjectNeuroimaging_NIfTI', tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropProp(prop) does not work.')
		assert(im.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropProp(prop) does not work.')
		assert(Element.getPropProp(im, prop) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(im, prop) does not work.')
		assert(Element.getPropProp('ImporterGroupSubjectNeuroimaging_NIfTI', prop) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
		tag = im.getPropTag(prop);
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropProp(tag) does not work.')
		assert(im.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropProp(tag) does not work.')
		assert(Element.getPropProp(im, tag) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(im, tag) does not work.')
		assert(Element.getPropProp('ImporterGroupSubjectNeuroimaging_NIfTI', prop) == prop, ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(strcmp(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop) does not work.')
		assert(strcmp(im.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(im, prop), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(im, prop) does not work.')
		assert(strcmp(Element.getPropTag('ImporterGroupSubjectNeuroimaging_NIfTI', prop), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
		assert(strcmp(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(tag) does not work.')
		assert(strcmp(im.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(im, tag), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(im, tag) does not work.')
		assert(strcmp(Element.getPropTag('ImporterGroupSubjectNeuroimaging_NIfTI', prop), tag), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(Category.existsCategory(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(im.getPropCategory(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(im, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
		assert(Category.existsCategory(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(im.getPropCategory(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(im, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(Format.existsFormat(ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(im.getPropFormat(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(im, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
		assert(Format.existsFormat(ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(im.getPropFormat(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(im, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(ischar(ImporterGroupSubjectNeuroimaging_NIfTI.getPropDescription(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropDescription(prop) does not work.')
		assert(ischar(im.getPropDescription(prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(im, prop) does not work.')
		assert(ischar(Element.getPropDescription(im, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop) does not work.')
	 
		assert(ischar(ImporterGroupSubjectNeuroimaging_NIfTI.getPropDescription(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.getPropDescription(tag) does not work.')
		assert(ischar(im.getPropDescription(tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(im, tag) does not work.')
		assert(ischar(Element.getPropDescription(im, tag)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		settings = ImporterGroupSubjectNeuroimaging_NIfTI.getPropSettings(prop);
		settings = im.getPropSettings(prop);
		settings = Element.getPropSettings(im, prop);
		settings = Element.getPropSettings('ImporterGroupSubjectNeuroimaging_NIfTI', prop);
	 
		settings = ImporterGroupSubjectNeuroimaging_NIfTI.getPropSettings(tag);
		settings = im.getPropSettings(tag);
		settings = Element.getPropSettings(im, tag);
		settings = Element.getPropSettings('ImporterGroupSubjectNeuroimaging_NIfTI', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		default = ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(prop);
		default = im.getPropDefault(prop);
		default = Element.getPropDefault(im, prop);
		default = Element.getPropDefault('ImporterGroupSubjectNeuroimaging_NIfTI', prop);
	 
		default = ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(tag);
		default = im.getPropDefault(tag);
		default = Element.getPropDefault(im, tag);
		default = Element.getPropDefault('ImporterGroupSubjectNeuroimaging_NIfTI', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		conditioned_default = ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(prop);
		conditioned_default = im.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(im, prop);
		conditioned_default = Element.getPropDefaultConditioned('ImporterGroupSubjectNeuroimaging_NIfTI', prop);
	 
		conditioned_default = ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(tag);
		conditioned_default = im.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(im, tag);
		conditioned_default = Element.getPropDefaultConditioned('ImporterGroupSubjectNeuroimaging_NIfTI', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(~ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(prop, value) does not work.')
		assert(~im.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(im, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, prop, value) does not work.')
		assert(~Element.checkProp('ImporterGroupSubjectNeuroimaging_NIfTI', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop, value) does not work.')
	 
		assert_with_error('ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], prop, im)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], prop, im)
		assert_with_error('Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(tag, value) does not work.')
		assert(~im.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(im, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, tag, value) does not work.')
		assert(~Element.checkProp('ImporterGroupSubjectNeuroimaging_NIfTI', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag, value) does not work.')
	 
		assert_with_error('ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], tag, im)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], tag, im)
		assert_with_error('Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(prop, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(prop, <conditioned default value>) does not work.')
		assert(im.checkProp(prop, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(im, prop, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ImporterGroupSubjectNeuroimaging_NIfTI', prop, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', prop, <conditioned default value>) does not work.')
	 
		assert(ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(tag, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.checkProp(tag, <conditioned default value>) does not work.')
		assert(im.checkProp(tag, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(im, tag, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ImporterGroupSubjectNeuroimaging_NIfTI', tag, Element.getPropDefaultConditioned(ImporterGroupSubjectNeuroimaging_NIfTI, prop)), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterGroupSubjectNeuroimaging_NIfTI'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					im.getr(prop) == ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterGroupSubjectNeuroimaging_NIfTI.getCategoryName(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)) ', ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					im.getr(TAG) == ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterGroupSubjectNeuroimaging_NIfTI.getCategoryName(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)) ', ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(im.getPropSettings(prop))
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop)), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop), im.getPropSettings(prop)), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					im.getr(prop) == ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterGroupSubjectNeuroimaging_NIfTI.getCategoryName(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)) ', ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					im.getr(TAG) == ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterGroupSubjectNeuroimaging_NIfTI.getCategoryName(ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)) ', ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(im.getPropSettings(prop))
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop)), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop), im.getPropSettings(prop)), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(im.getr(prop), ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(im.getr(TAG), ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(im.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI']);
	% 			assert( ...
	% 				~isa(im.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterGroupSubjectNeuroimaging_NIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(im.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(im.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if im.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ImporterGroupSubjectNeuroimaging_NIfTI');
					delete(ancestor(im.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ImporterGroupSubjectNeuroimaging_NIfTI.getProps(Category.RESULT))
		for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI();
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		assert( ...
			~im.isLocked(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~im.isLocked(TAG), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	im.lock()
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI();
	 
	warning_backup = warning('off', 'BRAPH2:ImporterGroupSubjectNeuroimaging_NIfTI');
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		im.lock(prop)
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI();
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		assert( ...
			im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			im.isChecked(TAG), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	im.unchecked()
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		assert( ...
			~im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	im.checked()
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		assert( ...
			im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			['ImporterGroupSubjectNeuroimaging_NIfTI.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ImporterGroupSubjectNeuroimaging_NIfTI
	im_0 = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	% ImporterGroupSubjectNeuroimaging_NIfTI with 1st callbacks
	im_1 = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, im_0.getCallback(4), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, im_0.getCallback(5), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, im_0.getCallback(9), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, im_0.getCallback(10), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, im_0.getCallback(11), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, im_0.getCallback(12), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, im_0.getCallback(13), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	prop_number = ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_1.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ImporterGroupSubjectNeuroimaging_NIfTI with 2nd callbacks
	im_2 = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, im_1.getCallback(4), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, im_1.getCallback(5), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, im_1.getCallback(9), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, im_1.getCallback(10), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, im_1.getCallback(11), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, im_1.getCallback(12), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, im_1.getCallback(13), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	prop_number = ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_2.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ImporterGroupSubjectNeuroimaging_NIfTI with 3rd callbacks
	im_3 = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, im_2.getCallback(4), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, im_2.getCallback(5), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, im_2.getCallback(9), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, im_2.getCallback(10), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, im_2.getCallback(11), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, im_2.getCallback(12), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, im_2.getCallback(13), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	prop_number = ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_3.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	im = ImporterGroupSubjectNeuroimaging_NIfTI();
	 
	im_copy = im.copy();
	 
	assert(im_copy ~= im, ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(im_copy, im), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					im_copy.isLocked(prop) == im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					im_copy.isChecked(prop) == im.isChecked(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		if ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI']);
			% im.memorize(prop);
			% warning(warning_backup)
		elseif ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop) == Category.EVANESCENT && im.getPropFormat(prop) == Format.HANDLE
			im.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ImporterGroupSubjectNeuroimaging_NIfTI');
			delete(ancestor(im.get(prop), 'figure'))
			warning(warning_backup)
		else
			im.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	im_copy = im.copy();
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						im_copy.isLocked(prop) == im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.isChecked(prop) == im.isChecked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	im_0 = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, im_0.getCallback(4), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, im_0.getCallback(5), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, im_0.getCallback(9), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, im_0.getCallback(10), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, im_0.getCallback(11), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, im_0.getCallback(12), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, im_0.getCallback(13), ..., ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	im_copy = im.copy();
	im_0_copy = im_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
							'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == im_0.getCallback(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The callback should be obtained from ImporterGroupSubjectNeuroimaging_NIfTI.getCallback().' ...
						)
					assert( ...
						value_copy == im_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The callback should be obtained from ImporterGroupSubjectNeuroimaging_NIfTI.getCallback().' ...
						)
				end
	 
					assert( ...
						im_copy.isLocked(prop) == im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.isChecked(prop) == im.isChecked(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_template = ImporterGroupSubjectNeuroimaging_NIfTI();
	im = ImporterGroupSubjectNeuroimaging_NIfTI('TEMPLATE', im_template);
	 
	for prop = 1:1:ImporterGroupSubjectNeuroimaging_NIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ImporterGroupSubjectNeuroimaging_NIfTI.getPropTag(prop));
		switch ImporterGroupSubjectNeuroimaging_NIfTI.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE
					assert( ...
						isa(im.getr(prop), 'ImporterGroupSubjectNeuroimaging_NIfTI'), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI.getr(''TEMPLATE'') should be a ImporterGroupSubjectNeuroimaging_NIfTI element.' ...
						)
					assert( ...
						isa(im_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						'ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(im.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						im.getr(prop).get('EL') == im_template && im.getr(prop).get('PROP') == prop && strcmp(im.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') should be a Callback to im_template.' TAG '.'] ...
						)
					assert( ...
						isa(im_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
						['ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(im_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
					['ImporterGroupSubjectNeuroimaging_NIfTI TEMPLATE does not work. ImporterGroupSubjectNeuroimaging_NIfTI_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'importergroupsubjectneuroimaging_nifti_to_be_erased.b2'];
	 
	Element.save(im, filename)
	 
	im_loaded = Element.load(filename);
	 
	assert( ...
		isequal(im.copy(), im_loaded), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.save(im) and/or ImporterGroupSubjectNeuroimaging_NIfTI.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterGroupSubjectNeuroimaging_NIfTI( ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ELCLASS, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NAME, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DESCRIPTION, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TEMPLATE), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.ID, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.ID), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.LABEL, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.LABEL), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.NOTES, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.NOTES), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TOSTRING, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.WAITBAR), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.DIRECTORY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.SESSION, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.SESSION), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.MODALITY), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.TARGET, ImporterGroupSubjectNeuroimaging_NIfTI.getPropDefault(ImporterGroupSubjectNeuroimaging_NIfTI.TARGET), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GET_DIR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue(), ...
		ImporterGroupSubjectNeuroimaging_NIfTI.GR, ImporterGroupSubjectNeuroimaging_NIfTI.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(im);
	[im_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(im_dec ~= im, ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		'ImporterGroupSubjectNeuroimaging_NIfTI.encodeJSON() or ImporterGroupSubjectNeuroimaging_NIfTI.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(prop), num2cell(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ImporterGroupSubjectNeuroimaging_NIfTI.getPropFormat(prop), num2cell(ImporterGroupSubjectNeuroimaging_NIfTI.getProps())) == Format.NET)
		assert(isequal(im_dec, im), ...
			[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
			'ImporterGroupSubjectNeuroimaging_NIfTI.encodeJSON() or ImporterGroupSubjectNeuroimaging_NIfTI.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Create example files
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	create_example_NIfTI() % only creates files if the example folder doesn't already exist
end

%% Test 13: GUI
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	example_data_dir = fullfile(fileparts(which('SUVRConstructor')), 'Example data NIfTI');
	im_gr1 = ImporterGroupSubjectNeuroimaging_NIfTI('DIRECTORY',[example_data_dir filesep 'Group1'], ...
	    'NIfTI_TYPE', {'T1'},...
	    'WAITBAR', true);
	gr = im_gr1.get('GR');
	gui = GUIElement('PE', gr, 'CLOSEREQ', false);
	gui.get('DRAW')
	gui.get('SHOW')
	
	gui.get('CLOSE')
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ImporterGroupSubjectNeuroimaging_NIfTI:' BRAPH2.FAIL_TEST], ...
		[' When testing ImporterGroupSubjectNeuroimaging_NIfTI no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

