%TEST_SUBJECTNEUROIMAGING

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	sub = SubjectNeuroimaging();
	 
	% get('ELCLASS')
	if isa(SubjectNeuroimaging, 'ConcreteElement')
		assert(strcmp(SubjectNeuroimaging().get('ELCLASS'), 'SubjectNeuroimaging'), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging().get(''ELCLASS'') should return ''SubjectNeuroimaging''.')
	end
	 
	% getBuild()
	assert(SubjectNeuroimaging.getBuild() == 1 && SubjectNeuroimaging.getBuild() > 0, ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getBuild() should return the SubjectNeuroimaging build number.')
	assert(sub.getBuild() == 1 && sub.getBuild() > 0 , ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getBuild() should return the SubjectNeuroimaging build number.')
	assert(Element.getBuild(sub) == 1 && Element.getBuild(sub) > 0, ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(sub) should return the SubjectNeuroimaging build number.')
	assert(Element.getBuild('SubjectNeuroimaging') == 1 && Element.getBuild('SubjectNeuroimaging') > 0, ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SubjectNeuroimaging'') should return the SubjectNeuroimaging build number.')
	 
	% getClass()
	assert(strcmp(SubjectNeuroimaging.getClass(), 'SubjectNeuroimaging'), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getClass() should return ''SubjectNeuroimaging''.')
	assert(strcmp(sub.getClass(), 'SubjectNeuroimaging'), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getClass() should return ''SubjectNeuroimaging''.')
	assert(strcmp(Element.getClass(sub), 'SubjectNeuroimaging'), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(sub) should return ''SubjectNeuroimaging''.')
	assert(strcmp(Element.getClass('SubjectNeuroimaging'), 'SubjectNeuroimaging'), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SubjectNeuroimaging'') should return ''SubjectNeuroimaging''.')
	 
	% getSubclasses()
	assert(isequal(SubjectNeuroimaging.getSubclasses(), subclasses('SubjectNeuroimaging', [], [], true)), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getSubclasses() should return the same result as subclasses(''SubjectNeuroimaging'', [], [], true).')
	assert(isequal(sub.getSubclasses(), subclasses('SubjectNeuroimaging', [], [], true)), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SubjectNeuroimaging'', [], [], true).')
	assert(isequal(Element.getSubclasses(sub), subclasses('SubjectNeuroimaging', [], [], true)), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(sub) should return the same result as subclasses(''SubjectNeuroimaging'', [], [], true).')
	assert(isequal(Element.getSubclasses('SubjectNeuroimaging'), subclasses('SubjectNeuroimaging', [], [], true)), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SubjectNeuroimaging'') should return the same result as subclasses(''SubjectNeuroimaging'', [], [], true).')
	 
	% getProps()
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(SubjectNeuroimaging.getProps(), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(sub.getProps(), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(Element.getProps(sub), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub) should return a row vector [1:1:N].')
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(Element.getProps('SubjectNeuroimaging'), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectNeuroimaging'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SubjectNeuroimaging.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getProps(category) does not work.')
	tmp = cellfun(@(category) sub.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(sub, category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SubjectNeuroimaging', category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNeuroimaging.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNeuroimaging.getProps())), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectNeuroimaging'', category) does not work.')
	 
	% getPropNumber()
	assert(SubjectNeuroimaging.getPropNumber() == length(SubjectNeuroimaging.getProps()), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getPropNumber() should return the number of properties.')
	assert(sub.getPropNumber() == length(SubjectNeuroimaging.getProps()), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(sub) == length(SubjectNeuroimaging.getProps()), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub) should return the number of properties.')
	assert(Element.getPropNumber('SubjectNeuroimaging') == length(SubjectNeuroimaging.getProps()), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectNeuroimaging'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SubjectNeuroimaging.getPropNumber(category), categories)) == SubjectNeuroimaging.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) sub.getPropNumber(category), categories)) == SubjectNeuroimaging.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(sub, category), categories)) == SubjectNeuroimaging.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SubjectNeuroimaging', category), categories)) == SubjectNeuroimaging.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectNeuroimaging'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SubjectNeuroimaging.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.existsProp(prop) does not work.')
	assert(~sub.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.existsProp(prop) does not work.')
	assert(~Element.existsProp(sub, NaN), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(sub, prop) does not work.')
	assert(~Element.existsProp('SubjectNeuroimaging', NaN), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SubjectNeuroimaging'', prop) does not work.')
	 
	assert_with_error('SubjectNeuroimaging.existsProp(NaN)', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(''SubjectNeuroimaging'', NaN)', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		assert(SubjectNeuroimaging.existsProp(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.existsProp(prop) does not work.')
		assert(sub.existsProp(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.existsProp(prop) does not work.')
		assert(Element.existsProp(sub, prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(sub, prop) does not work.')
		assert(Element.existsProp('SubjectNeuroimaging', prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SubjectNeuroimaging'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SubjectNeuroimaging.existsTag(''), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.existsTag(tag) does not work.')
	assert(~sub.existsTag(''), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'sub.existsTag(tag) does not work.')
	assert(~Element.existsTag(sub, ''), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(sub, tag) does not work.')
	assert(~Element.existsTag('SubjectNeuroimaging', ''), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SubjectNeuroimaging'', tag) does not work.')
	 
	assert_with_error('SubjectNeuroimaging.existsTag('''')', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(''SubjectNeuroimaging'', '''')', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
		assert(SubjectNeuroimaging.existsTag(tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.existsTag(tag) does not work.')
		assert(sub.existsTag(tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.existsTag(tag) does not work.')
		assert(Element.existsTag(sub, tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(sub, tga) does not work.')
		assert(Element.existsTag('SubjectNeuroimaging', tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		assert(SubjectNeuroimaging.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropProp(prop) does not work.')
		assert(sub.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(prop) does not work.')
		assert(Element.getPropProp(sub, prop) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, prop) does not work.')
		assert(Element.getPropProp('SubjectNeuroimaging', prop) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectNeuroimaging'', prop) does not work.')
	 
		tag = sub.getPropTag(prop);
		assert(SubjectNeuroimaging.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropProp(tag) does not work.')
		assert(sub.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(tag) does not work.')
		assert(Element.getPropProp(sub, tag) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, tag) does not work.')
		assert(Element.getPropProp('SubjectNeuroimaging', prop) == prop, ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(strcmp(SubjectNeuroimaging.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropTag(prop) does not work.')
		assert(strcmp(sub.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(sub, prop), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, prop) does not work.')
		assert(strcmp(Element.getPropTag('SubjectNeuroimaging', prop), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectNeuroimaging'', prop) does not work.')
	 
		assert(strcmp(SubjectNeuroimaging.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropTag(tag) does not work.')
		assert(strcmp(sub.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(sub, tag), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, tag) does not work.')
		assert(strcmp(Element.getPropTag('SubjectNeuroimaging', prop), tag), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Category.existsCategory(SubjectNeuroimaging.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectNeuroimaging'', prop) does not work.')
	 
		assert(Category.existsCategory(SubjectNeuroimaging.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Format.existsFormat(SubjectNeuroimaging.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectNeuroimaging'', prop) does not work.')
	 
		assert(Format.existsFormat(SubjectNeuroimaging.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(ischar(SubjectNeuroimaging.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropDescription(prop) does not work.')
		assert(ischar(sub.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectNeuroimaging'', prop) does not work.')
	 
		assert(ischar(SubjectNeuroimaging.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.getPropDescription(tag) does not work.')
		assert(ischar(sub.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectNeuroimaging'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		settings = SubjectNeuroimaging.getPropSettings(prop);
		settings = sub.getPropSettings(prop);
		settings = Element.getPropSettings(sub, prop);
		settings = Element.getPropSettings('SubjectNeuroimaging', prop);
	 
		settings = SubjectNeuroimaging.getPropSettings(tag);
		settings = sub.getPropSettings(tag);
		settings = Element.getPropSettings(sub, tag);
		settings = Element.getPropSettings('SubjectNeuroimaging', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		default = SubjectNeuroimaging.getPropDefault(prop);
		default = sub.getPropDefault(prop);
		default = Element.getPropDefault(sub, prop);
		default = Element.getPropDefault('SubjectNeuroimaging', prop);
	 
		default = SubjectNeuroimaging.getPropDefault(tag);
		default = sub.getPropDefault(tag);
		default = Element.getPropDefault(sub, tag);
		default = Element.getPropDefault('SubjectNeuroimaging', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		conditioned_default = SubjectNeuroimaging.getPropDefaultConditioned(prop);
		conditioned_default = sub.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(sub, prop);
		conditioned_default = Element.getPropDefaultConditioned('SubjectNeuroimaging', prop);
	 
		conditioned_default = SubjectNeuroimaging.getPropDefaultConditioned(tag);
		conditioned_default = sub.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(sub, tag);
		conditioned_default = Element.getPropDefaultConditioned('SubjectNeuroimaging', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(~SubjectNeuroimaging.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.checkProp(prop, value) does not work.')
		assert(~sub.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(sub, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, value) does not work.')
		assert(~Element.checkProp('SubjectNeuroimaging', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNeuroimaging'', prop, value) does not work.')
	 
		assert_with_error('SubjectNeuroimaging.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(''SubjectNeuroimaging'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SubjectNeuroimaging.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.checkProp(tag, value) does not work.')
		assert(~sub.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(sub, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, value) does not work.')
		assert(~Element.checkProp('SubjectNeuroimaging', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNeuroimaging'', tag, value) does not work.')
	 
		assert_with_error('SubjectNeuroimaging.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(''SubjectNeuroimaging'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SubjectNeuroimaging.checkProp(prop, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.checkProp(prop, <conditioned default value>) does not work.')
		assert(sub.checkProp(prop, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, prop, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectNeuroimaging', prop, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNeuroimaging'', prop, <conditioned default value>) does not work.')
	 
		assert(SubjectNeuroimaging.checkProp(tag, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.checkProp(tag, <conditioned default value>) does not work.')
		assert(sub.checkProp(tag, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, tag, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectNeuroimaging', tag, Element.getPropDefaultConditioned(SubjectNeuroimaging, prop)), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNeuroimaging'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					sub.getr(prop) == SubjectNeuroimaging.getNoValue(), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNeuroimaging.getCategoryName(SubjectNeuroimaging.getPropCategory(prop)) ', SubjectNeuroimaging.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectNeuroimaging.getNoValue(), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNeuroimaging.getCategoryName(SubjectNeuroimaging.getPropCategory(prop)) ', SubjectNeuroimaging.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					sub.getr(prop) == SubjectNeuroimaging.getNoValue(), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNeuroimaging.getCategoryName(SubjectNeuroimaging.getPropCategory(prop)) ', SubjectNeuroimaging.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectNeuroimaging.getNoValue(), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNeuroimaging.getCategoryName(SubjectNeuroimaging.getPropCategory(prop)) ', SubjectNeuroimaging.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SubjectNeuroimaging']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(sub.getr(prop), SubjectNeuroimaging.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SubjectNeuroimaging.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(sub.getr(TAG), SubjectNeuroimaging.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SubjectNeuroimaging.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectNeuroimaging.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectNeuroimaging']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectNeuroimaging']);
	% 			assert( ...
	% 				~isa(sub.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNeuroimaging.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(sub.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNeuroimaging.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SubjectNeuroimaging']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if sub.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SubjectNeuroimaging');
					delete(ancestor(sub.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SubjectNeuroimaging.getProps(Category.RESULT))
		for prop = 1:1:SubjectNeuroimaging.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch SubjectNeuroimaging.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging();
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		assert( ...
			~sub.isLocked(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~sub.isLocked(TAG), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	sub.lock()
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging();
	 
	warning_backup = warning('off', 'BRAPH2:SubjectNeuroimaging');
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		sub.lock(prop)
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging();
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			sub.isChecked(TAG), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	sub.unchecked()
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		assert( ...
			~sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	sub.checked()
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			['SubjectNeuroimaging.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SubjectNeuroimaging
	sub_0 = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	% SubjectNeuroimaging with 1st callbacks
	sub_1 = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectNeuroimaging.ID, sub_0.getCallback(5), ..., ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectNeuroimaging.NIFTI_FILE, sub_0.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNeuroimaging.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_1.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectNeuroimaging with 2nd callbacks
	sub_2 = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, sub_1.getCallback(4), ..., ...
		SubjectNeuroimaging.ID, sub_1.getCallback(5), ..., ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, sub_1.getCallback(9), ..., ...
		SubjectNeuroimaging.NIFTI_FILE, sub_1.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNeuroimaging.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_2.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectNeuroimaging with 3rd callbacks
	sub_3 = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, sub_2.getCallback(4), ..., ...
		SubjectNeuroimaging.ID, sub_2.getCallback(5), ..., ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, sub_2.getCallback(9), ..., ...
		SubjectNeuroimaging.NIFTI_FILE, sub_2.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNeuroimaging.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_3.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	sub = SubjectNeuroimaging();
	 
	sub_copy = sub.copy();
	 
	assert(sub_copy ~= sub, ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(sub_copy, sub), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					sub_copy.isLocked(prop) == sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.isChecked(prop) == sub.isChecked(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		if SubjectNeuroimaging.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SubjectNeuroimaging']);
			% sub.memorize(prop);
			% warning(warning_backup)
		elseif SubjectNeuroimaging.getPropCategory(prop) == Category.EVANESCENT && sub.getPropFormat(prop) == Format.HANDLE
			sub.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SubjectNeuroimaging');
			delete(ancestor(sub.get(prop), 'figure'))
			warning(warning_backup)
		else
			sub.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	sub_copy = sub.copy();
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	sub_0 = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectNeuroimaging.ID, sub_0.getCallback(5), ..., ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectNeuroimaging.NIFTI_FILE, sub_0.getCallback(10) ... ...
		);
	 
	sub_copy = sub.copy();
	sub_0_copy = sub_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					'SubjectNeuroimaging.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
							'SubjectNeuroimaging.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == sub_0.getCallback(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The callback should be obtained from SubjectNeuroimaging.getCallback().' ...
						)
					assert( ...
						value_copy == sub_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The callback should be obtained from SubjectNeuroimaging.getCallback().' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub_template = SubjectNeuroimaging();
	sub = SubjectNeuroimaging('TEMPLATE', sub_template);
	 
	for prop = 1:1:SubjectNeuroimaging.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNeuroimaging.getPropTag(prop));
		switch SubjectNeuroimaging.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SubjectNeuroimaging.TEMPLATE
					assert( ...
						isa(sub.getr(prop), 'SubjectNeuroimaging'), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging.getr(''TEMPLATE'') should be a SubjectNeuroimaging element.' ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						'SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(sub.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						sub.getr(prop).get('EL') == sub_template && sub.getr(prop).get('PROP') == prop && strcmp(sub.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging.getr(' TAG ') should be a Callback to sub_template.' TAG '.'] ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
						['SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(sub_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
					['SubjectNeuroimaging TEMPLATE does not work. SubjectNeuroimaging_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'subjectneuroimaging_to_be_erased.b2'];
	 
	Element.save(sub, filename)
	 
	sub_loaded = Element.load(filename);
	 
	assert( ...
		isequal(sub.copy(), sub_loaded), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.save(sub) and/or SubjectNeuroimaging.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNeuroimaging( ...
		SubjectNeuroimaging.ELCLASS, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.NAME, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.DESCRIPTION, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.TEMPLATE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.TEMPLATE), ...
		SubjectNeuroimaging.ID, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.ID), ...
		SubjectNeuroimaging.LABEL, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.LABEL), ...
		SubjectNeuroimaging.NOTES, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NOTES), ...
		SubjectNeuroimaging.TOSTRING, SubjectNeuroimaging.getNoValue(), ...
		SubjectNeuroimaging.VOI_DICT, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.VOI_DICT), ...
		SubjectNeuroimaging.NIFTI_FILE, SubjectNeuroimaging.getPropDefault(SubjectNeuroimaging.NIFTI_FILE) ...
		);
	 
	[json, struct, el_list] = encodeJSON(sub);
	[sub_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(sub_dec ~= sub, ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		'SubjectNeuroimaging.encodeJSON() or SubjectNeuroimaging.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SubjectNeuroimaging.getPropFormat(prop), num2cell(SubjectNeuroimaging.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SubjectNeuroimaging.getPropFormat(prop), num2cell(SubjectNeuroimaging.getProps())) == Format.NET)
		assert(isequal(sub_dec, sub), ...
			[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
			'SubjectNeuroimaging.encodeJSON() or SubjectNeuroimaging.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GUI
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% Step 1: Load Brain Atlas
	im_ba = ImporterBrainAtlasXLS('FILE', 'desikan_atlas.xlsx');
	ba = im_ba.get('BA');
	
	% Step 2: Create Group with SubjectNeuroimaging instances
	gr = Group('SUB_CLASS', 'SubjectNeuroimaging', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectNeuroimaging'));
	for i = 1:1:50
	    sub = SubjectNeuroimaging( ...
	        'ID', ['SUB Nifti ' int2str(i)]);
	    % Add the file path to the subject's nifty dictionary
	    sub.memorize('NIFTI_PATH_DICT').get('ADD', FILE_PATH('ID', convertStringsToChars(string(i)), 'PATH', convertStringsToChars('*/*')));
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 100 * rand()));
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', randi(2, 1)));
	    gr.get('SUB_DICT').get('ADD', sub);
	end
	
	% Step 3: Test GUI
	gui = GUIElement('PE', gr, 'CLOSEREQ', false);
	gui.get('DRAW');
	gui.get('SHOW');
	
	% Pause for visual confirmation
	disp('GUI is open. Closing in 3 seconds...');
	pause(3);
	
	gui.get('CLOSE');
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SubjectNeuroimaging:' BRAPH2.FAIL_TEST], ...
		[' When testing SubjectNeuroimaging no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

