%TEST_INDIVIDUALPERTURBATIONCONCONSTRUCTOR

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	ipc = IndividualPerturbationConConstructor();
	 
	% get('ELCLASS')
	if isa(IndividualPerturbationConConstructor, 'ConcreteElement')
		assert(strcmp(IndividualPerturbationConConstructor().get('ELCLASS'), 'IndividualPerturbationConConstructor'), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor().get(''ELCLASS'') should return ''IndividualPerturbationConConstructor''.')
	end
	 
	% getBuild()
	assert(IndividualPerturbationConConstructor.getBuild() == 1 && IndividualPerturbationConConstructor.getBuild() > 0, ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getBuild() should return the IndividualPerturbationConConstructor build number.')
	assert(ipc.getBuild() == 1 && ipc.getBuild() > 0 , ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getBuild() should return the IndividualPerturbationConConstructor build number.')
	assert(Element.getBuild(ipc) == 1 && Element.getBuild(ipc) > 0, ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(ipc) should return the IndividualPerturbationConConstructor build number.')
	assert(Element.getBuild('IndividualPerturbationConConstructor') == 1 && Element.getBuild('IndividualPerturbationConConstructor') > 0, ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''IndividualPerturbationConConstructor'') should return the IndividualPerturbationConConstructor build number.')
	 
	% getClass()
	assert(strcmp(IndividualPerturbationConConstructor.getClass(), 'IndividualPerturbationConConstructor'), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getClass() should return ''IndividualPerturbationConConstructor''.')
	assert(strcmp(ipc.getClass(), 'IndividualPerturbationConConstructor'), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getClass() should return ''IndividualPerturbationConConstructor''.')
	assert(strcmp(Element.getClass(ipc), 'IndividualPerturbationConConstructor'), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(ipc) should return ''IndividualPerturbationConConstructor''.')
	assert(strcmp(Element.getClass('IndividualPerturbationConConstructor'), 'IndividualPerturbationConConstructor'), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''IndividualPerturbationConConstructor'') should return ''IndividualPerturbationConConstructor''.')
	 
	% getSubclasses()
	assert(isequal(IndividualPerturbationConConstructor.getSubclasses(), subclasses('IndividualPerturbationConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getSubclasses() should return the same result as subclasses(''IndividualPerturbationConConstructor'', [], [], true).')
	assert(isequal(ipc.getSubclasses(), subclasses('IndividualPerturbationConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''IndividualPerturbationConConstructor'', [], [], true).')
	assert(isequal(Element.getSubclasses(ipc), subclasses('IndividualPerturbationConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(ipc) should return the same result as subclasses(''IndividualPerturbationConConstructor'', [], [], true).')
	assert(isequal(Element.getSubclasses('IndividualPerturbationConConstructor'), subclasses('IndividualPerturbationConConstructor', [], [], true)), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''IndividualPerturbationConConstructor'') should return the same result as subclasses(''IndividualPerturbationConConstructor'', [], [], true).')
	 
	% getProps()
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(IndividualPerturbationConConstructor.getProps(), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getProps() should return a row vector [1:1:N].')
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(ipc.getProps(), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getProps() should return a row vector [1:1:N].')
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(Element.getProps(ipc), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ipc) should return a row vector [1:1:N].')
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(Element.getProps('IndividualPerturbationConConstructor'), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''IndividualPerturbationConConstructor'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) IndividualPerturbationConConstructor.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getProps(category) does not work.')
	tmp = cellfun(@(category) ipc.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(ipc, category), categories, 'UniformOutput', false);
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(ipc, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('IndividualPerturbationConConstructor', category), categories, 'UniformOutput', false);
	assert(isempty(IndividualPerturbationConConstructor.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(IndividualPerturbationConConstructor.getProps())), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''IndividualPerturbationConConstructor'', category) does not work.')
	 
	% getPropNumber()
	assert(IndividualPerturbationConConstructor.getPropNumber() == length(IndividualPerturbationConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getPropNumber() should return the number of properties.')
	assert(ipc.getPropNumber() == length(IndividualPerturbationConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(ipc) == length(IndividualPerturbationConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ipc) should return the number of properties.')
	assert(Element.getPropNumber('IndividualPerturbationConConstructor') == length(IndividualPerturbationConConstructor.getProps()), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''IndividualPerturbationConConstructor'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) IndividualPerturbationConConstructor.getPropNumber(category), categories)) == IndividualPerturbationConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) ipc.getPropNumber(category), categories)) == IndividualPerturbationConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(ipc, category), categories)) == IndividualPerturbationConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(ipc, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('IndividualPerturbationConConstructor', category), categories)) == IndividualPerturbationConConstructor.getPropNumber(), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''IndividualPerturbationConConstructor'', category) does not work.')
	 
	% existsProp(prop)
	assert(~IndividualPerturbationConConstructor.existsProp(NaN), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.existsProp(prop) does not work.')
	assert(~ipc.existsProp(NaN), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.existsProp(prop) does not work.')
	assert(~Element.existsProp(ipc, NaN), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(ipc, prop) does not work.')
	assert(~Element.existsProp('IndividualPerturbationConConstructor', NaN), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
	assert_with_error('IndividualPerturbationConConstructor.existsProp(NaN)', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], ipc)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], ipc)
	assert_with_error('Element.existsProp(''IndividualPerturbationConConstructor'', NaN)', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		assert(IndividualPerturbationConConstructor.existsProp(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.existsProp(prop) does not work.')
		assert(ipc.existsProp(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.existsProp(prop) does not work.')
		assert(Element.existsProp(ipc, prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(ipc, prop) does not work.')
		assert(Element.existsProp('IndividualPerturbationConConstructor', prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''IndividualPerturbationConConstructor'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~IndividualPerturbationConConstructor.existsTag(''), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.existsTag(tag) does not work.')
	assert(~ipc.existsTag(''), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'ipc.existsTag(tag) does not work.')
	assert(~Element.existsTag(ipc, ''), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(ipc, tag) does not work.')
	assert(~Element.existsTag('IndividualPerturbationConConstructor', ''), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''IndividualPerturbationConConstructor'', tag) does not work.')
	 
	assert_with_error('IndividualPerturbationConConstructor.existsTag('''')', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], ipc)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], ipc)
	assert_with_error('Element.existsTag(''IndividualPerturbationConConstructor'', '''')', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
		assert(IndividualPerturbationConConstructor.existsTag(tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.existsTag(tag) does not work.')
		assert(ipc.existsTag(tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.existsTag(tag) does not work.')
		assert(Element.existsTag(ipc, tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(ipc, tga) does not work.')
		assert(Element.existsTag('IndividualPerturbationConConstructor', tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		assert(IndividualPerturbationConConstructor.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropProp(prop) does not work.')
		assert(ipc.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropProp(prop) does not work.')
		assert(Element.getPropProp(ipc, prop) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ipc, prop) does not work.')
		assert(Element.getPropProp('IndividualPerturbationConConstructor', prop) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
		tag = ipc.getPropTag(prop);
		assert(IndividualPerturbationConConstructor.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropProp(tag) does not work.')
		assert(ipc.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropProp(tag) does not work.')
		assert(Element.getPropProp(ipc, tag) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(ipc, tag) does not work.')
		assert(Element.getPropProp('IndividualPerturbationConConstructor', prop) == prop, ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		assert(strcmp(IndividualPerturbationConConstructor.getPropTag(prop), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropTag(prop) does not work.')
		assert(strcmp(ipc.getPropTag(prop), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(ipc, prop), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ipc, prop) does not work.')
		assert(strcmp(Element.getPropTag('IndividualPerturbationConConstructor', prop), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
		assert(strcmp(IndividualPerturbationConConstructor.getPropTag(tag), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropTag(tag) does not work.')
		assert(strcmp(ipc.getPropTag(tag), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(ipc, tag), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(ipc, tag) does not work.')
		assert(strcmp(Element.getPropTag('IndividualPerturbationConConstructor', prop), tag), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		assert(Category.existsCategory(IndividualPerturbationConConstructor.getPropCategory(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(ipc.getPropCategory(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ipc, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
		assert(Category.existsCategory(IndividualPerturbationConConstructor.getPropCategory(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(ipc.getPropCategory(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(ipc, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		assert(Format.existsFormat(IndividualPerturbationConConstructor.getPropFormat(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(ipc.getPropFormat(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ipc, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
		assert(Format.existsFormat(IndividualPerturbationConConstructor.getPropFormat(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(ipc.getPropFormat(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(ipc, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		assert(ischar(IndividualPerturbationConConstructor.getPropDescription(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropDescription(prop) does not work.')
		assert(ischar(ipc.getPropDescription(prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ipc, prop) does not work.')
		assert(ischar(Element.getPropDescription(ipc, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''IndividualPerturbationConConstructor'', prop) does not work.')
	 
		assert(ischar(IndividualPerturbationConConstructor.getPropDescription(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.getPropDescription(tag) does not work.')
		assert(ischar(ipc.getPropDescription(tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(ipc, tag) does not work.')
		assert(ischar(Element.getPropDescription(ipc, tag)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''IndividualPerturbationConConstructor'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		settings = IndividualPerturbationConConstructor.getPropSettings(prop);
		settings = ipc.getPropSettings(prop);
		settings = Element.getPropSettings(ipc, prop);
		settings = Element.getPropSettings('IndividualPerturbationConConstructor', prop);
	 
		settings = IndividualPerturbationConConstructor.getPropSettings(tag);
		settings = ipc.getPropSettings(tag);
		settings = Element.getPropSettings(ipc, tag);
		settings = Element.getPropSettings('IndividualPerturbationConConstructor', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		default = IndividualPerturbationConConstructor.getPropDefault(prop);
		default = ipc.getPropDefault(prop);
		default = Element.getPropDefault(ipc, prop);
		default = Element.getPropDefault('IndividualPerturbationConConstructor', prop);
	 
		default = IndividualPerturbationConConstructor.getPropDefault(tag);
		default = ipc.getPropDefault(tag);
		default = Element.getPropDefault(ipc, tag);
		default = Element.getPropDefault('IndividualPerturbationConConstructor', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		conditioned_default = IndividualPerturbationConConstructor.getPropDefaultConditioned(prop);
		conditioned_default = ipc.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(ipc, prop);
		conditioned_default = Element.getPropDefaultConditioned('IndividualPerturbationConConstructor', prop);
	 
		conditioned_default = IndividualPerturbationConConstructor.getPropDefaultConditioned(tag);
		conditioned_default = ipc.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(ipc, tag);
		conditioned_default = Element.getPropDefaultConditioned('IndividualPerturbationConConstructor', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		tag = ipc.getPropTag(prop);
	 
		assert(~IndividualPerturbationConConstructor.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.checkProp(prop, value) does not work.')
		assert(~ipc.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(ipc, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ipc, prop, value) does not work.')
		assert(~Element.checkProp('IndividualPerturbationConConstructor', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualPerturbationConConstructor'', prop, value) does not work.')
	 
		assert_with_error('IndividualPerturbationConConstructor.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], prop, ipc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], prop, ipc)
		assert_with_error('Element.checkProp(''IndividualPerturbationConConstructor'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~IndividualPerturbationConConstructor.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.checkProp(tag, value) does not work.')
		assert(~ipc.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(ipc, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ipc, tag, value) does not work.')
		assert(~Element.checkProp('IndividualPerturbationConConstructor', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualPerturbationConConstructor'', tag, value) does not work.')
	 
		assert_with_error('IndividualPerturbationConConstructor.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], tag, ipc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], tag, ipc)
		assert_with_error('Element.checkProp(''IndividualPerturbationConConstructor'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(IndividualPerturbationConConstructor.checkProp(prop, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.checkProp(prop, <conditioned default value>) does not work.')
		assert(ipc.checkProp(prop, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(ipc, prop, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ipc, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('IndividualPerturbationConConstructor', prop, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualPerturbationConConstructor'', prop, <conditioned default value>) does not work.')
	 
		assert(IndividualPerturbationConConstructor.checkProp(tag, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.checkProp(tag, <conditioned default value>) does not work.')
		assert(ipc.checkProp(tag, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'ipc.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(ipc, tag, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(ipc, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('IndividualPerturbationConConstructor', tag, Element.getPropDefaultConditioned(IndividualPerturbationConConstructor, prop)), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''IndividualPerturbationConConstructor'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					ipc.getr(prop) == IndividualPerturbationConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualPerturbationConConstructor.getCategoryName(IndividualPerturbationConConstructor.getPropCategory(prop)) ', IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ipc.getr(TAG) == IndividualPerturbationConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualPerturbationConConstructor.getCategoryName(IndividualPerturbationConConstructor.getPropCategory(prop)) ', IndividualPerturbationConConstructor.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(ipc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ipc.getPropSettings(prop))
					assert( ...
						ipc.checkFormat(ipc.getPropFormat(prop), ipc.get(prop)), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ipc.checkFormat(ipc.getPropFormat(prop), ipc.get(prop), ipc.getPropSettings(prop)), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					ipc.getr(prop) == IndividualPerturbationConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualPerturbationConConstructor.getCategoryName(IndividualPerturbationConConstructor.getPropCategory(prop)) ', IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					ipc.getr(TAG) == IndividualPerturbationConConstructor.getNoValue(), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['Being a ' IndividualPerturbationConConstructor.getCategoryName(IndividualPerturbationConConstructor.getPropCategory(prop)) ', IndividualPerturbationConConstructor.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':IndividualPerturbationConConstructor']);
				assert( ...
					~isa(ipc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(ipc.getPropSettings(prop))
					assert( ...
						ipc.checkFormat(ipc.getPropFormat(prop), ipc.get(prop)), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						ipc.checkFormat(ipc.getPropFormat(prop), ipc.get(prop), ipc.getPropSettings(prop)), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(ipc.getr(prop), IndividualPerturbationConConstructor.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by IndividualPerturbationConConstructor.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(ipc.getr(TAG), IndividualPerturbationConConstructor.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' TAG ') must be inizialized to its default value ' ...
					'given by IndividualPerturbationConConstructor.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in IndividualPerturbationConConstructor.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(ipc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ipc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ipc.checkFormat(ipc.getPropFormat(prop), ipc.getr(prop),ipc.getPropSettings(prop)), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':IndividualPerturbationConConstructor']);
				assert( ...
					~isa(ipc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':IndividualPerturbationConConstructor']);
	% 			assert( ...
	% 				~isa(ipc.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualPerturbationConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(ipc.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				ipc.checkFormat(ipc.getPropFormat(prop), ipc.getr(prop),ipc.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
	% 				['IndividualPerturbationConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':IndividualPerturbationConConstructor']);
				assert( ...
					~isa(ipc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(ipc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					ipc.checkFormat(ipc.getPropFormat(prop), ipc.getr(prop),ipc.getPropSettings(prop)), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if ipc.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:IndividualPerturbationConConstructor');
					delete(ancestor(ipc.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(IndividualPerturbationConConstructor.getProps(Category.RESULT))
		for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch IndividualPerturbationConConstructor.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						ipc.isLocked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~ipc.isLocked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor();
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		assert( ...
			~ipc.isLocked(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~ipc.isLocked(TAG), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	ipc.lock()
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					ipc.isLocked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~ipc.isLocked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor();
	 
	warning_backup = warning('off', 'BRAPH2:IndividualPerturbationConConstructor');
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		ipc.lock(prop)
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					ipc.isLocked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~ipc.isLocked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor();
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		assert( ...
			ipc.isChecked(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			ipc.isChecked(TAG), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	ipc.unchecked()
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		assert( ...
			~ipc.isChecked(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	ipc.checked()
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		assert( ...
			ipc.isChecked(prop), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			['IndividualPerturbationConConstructor.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic IndividualPerturbationConConstructor
	ipc_0 = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	% IndividualPerturbationConConstructor with 1st callbacks
	ipc_1 = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, ipc_0.getCallback(4), ..., ...
		IndividualPerturbationConConstructor.ID, ipc_0.getCallback(5), ..., ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, ipc_0.getCallback(9), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR, ipc_0.getCallback(10), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, ipc_0.getCallback(11), ..., ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, ipc_0.getCallback(14) ... ...
		);
	 
	prop_number = IndividualPerturbationConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ipc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ipc_1.get(prop), ipc_0.get(prop)) && ~isa(ipc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ipc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% IndividualPerturbationConConstructor with 2nd callbacks
	ipc_2 = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, ipc_1.getCallback(4), ..., ...
		IndividualPerturbationConConstructor.ID, ipc_1.getCallback(5), ..., ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, ipc_1.getCallback(9), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR, ipc_1.getCallback(10), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, ipc_1.getCallback(11), ..., ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, ipc_1.getCallback(14) ... ...
		);
	 
	prop_number = IndividualPerturbationConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ipc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ipc_2.get(prop), ipc_0.get(prop)) && ~isa(ipc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ipc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% IndividualPerturbationConConstructor with 3rd callbacks
	ipc_3 = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, ipc_2.getCallback(4), ..., ...
		IndividualPerturbationConConstructor.ID, ipc_2.getCallback(5), ..., ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, ipc_2.getCallback(9), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR, ipc_2.getCallback(10), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, ipc_2.getCallback(11), ..., ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, ipc_2.getCallback(14) ... ...
		);
	 
	prop_number = IndividualPerturbationConConstructor.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(ipc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(ipc_3.get(prop), ipc_0.get(prop)) && ~isa(ipc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(ipc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	ipc = IndividualPerturbationConConstructor();
	 
	ipc_copy = ipc.copy();
	 
	assert(ipc_copy ~= ipc, ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(ipc_copy, ipc), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		value = ipc.getr(prop);
		value_copy = ipc_copy.getr(prop);
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					ipc_copy.isLocked(prop) == ipc.isLocked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ipc_copy.isChecked(prop) == ipc.isChecked(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					ipc_copy.getPropSeed(prop) == ipc.getPropSeed(prop), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		if IndividualPerturbationConConstructor.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':IndividualPerturbationConConstructor']);
			% ipc.memorize(prop);
			% warning(warning_backup)
		elseif IndividualPerturbationConConstructor.getPropCategory(prop) == Category.EVANESCENT && ipc.getPropFormat(prop) == Format.HANDLE
			ipc.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:IndividualPerturbationConConstructor');
			delete(ancestor(ipc.get(prop), 'figure'))
			warning(warning_backup)
		else
			ipc.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	ipc_copy = ipc.copy();
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		value = ipc.getr(prop);
		value_copy = ipc_copy.getr(prop);
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						ipc_copy.isLocked(prop) == ipc.isLocked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ipc_copy.isChecked(prop) == ipc.isChecked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ipc_copy.getPropSeed(prop) == ipc.getPropSeed(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	ipc_0 = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, ipc_0.getCallback(4), ..., ...
		IndividualPerturbationConConstructor.ID, ipc_0.getCallback(5), ..., ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, ipc_0.getCallback(9), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR, ipc_0.getCallback(10), ..., ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, ipc_0.getCallback(11), ..., ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, ipc_0.getCallback(14) ... ...
		);
	 
	ipc_copy = ipc.copy();
	ipc_0_copy = ipc_copy.getr('ID').get('EL');
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
		value = ipc.getr(prop);
		value_copy = ipc_copy.getr(prop);
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					'IndividualPerturbationConConstructor.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
							'IndividualPerturbationConConstructor.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == ipc_0.getCallback(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The callback should be obtained from IndividualPerturbationConConstructor.getCallback().' ...
						)
					assert( ...
						value_copy == ipc_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The callback should be obtained from IndividualPerturbationConConstructor.getCallback().' ...
						)
				end
	 
					assert( ...
						ipc_copy.isLocked(prop) == ipc.isLocked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ipc_copy.isChecked(prop) == ipc.isChecked(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						ipc_copy.getPropSeed(prop) == ipc.getPropSeed(prop), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc_template = IndividualPerturbationConConstructor();
	ipc = IndividualPerturbationConConstructor('TEMPLATE', ipc_template);
	 
	for prop = 1:1:IndividualPerturbationConConstructor.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(IndividualPerturbationConConstructor.getPropTag(prop));
		switch IndividualPerturbationConConstructor.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == IndividualPerturbationConConstructor.TEMPLATE
					assert( ...
						isa(ipc.getr(prop), 'IndividualPerturbationConConstructor'), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor.getr(''TEMPLATE'') should be a IndividualPerturbationConConstructor element.' ...
						)
					assert( ...
						isa(ipc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						'IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(ipc.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						ipc.getr(prop).get('EL') == ipc_template && ipc.getr(prop).get('PROP') == prop && strcmp(ipc.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor.getr(' TAG ') should be a Callback to ipc_template.' TAG '.'] ...
						)
					assert( ...
						isa(ipc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
						['IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(ipc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(ipc_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
					['IndividualPerturbationConConstructor TEMPLATE does not work. IndividualPerturbationConConstructor_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'individualperturbationconconstructor_to_be_erased.b2'];
	 
	Element.save(ipc, filename)
	 
	ipc_loaded = Element.load(filename);
	 
	assert( ...
		isequal(ipc.copy(), ipc_loaded), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.save(ipc) and/or IndividualPerturbationConConstructor.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ipc = IndividualPerturbationConConstructor( ...
		IndividualPerturbationConConstructor.ELCLASS, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.NAME, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.DESCRIPTION, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.TEMPLATE, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.TEMPLATE), ...
		IndividualPerturbationConConstructor.ID, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.ID), ...
		IndividualPerturbationConConstructor.LABEL, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.LABEL), ...
		IndividualPerturbationConConstructor.NOTES, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.NOTES), ...
		IndividualPerturbationConConstructor.TOSTRING, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.WAITBAR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.WAITBAR), ...
		IndividualPerturbationConConstructor.GR_SUVR, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR), ...
		IndividualPerturbationConConstructor.GR_SUVR_REF, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.GR_SUVR_REF), ...
		IndividualPerturbationConConstructor.CONNECTOME_CONSTRUCT_METHOD, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.GR, IndividualPerturbationConConstructor.getNoValue(), ...
		IndividualPerturbationConConstructor.VOI_SELECTION, IndividualPerturbationConConstructor.getPropDefault(IndividualPerturbationConConstructor.VOI_SELECTION) ...
		);
	 
	[json, struct, el_list] = encodeJSON(ipc);
	[ipc_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(ipc_dec ~= ipc, ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		'IndividualPerturbationConConstructor.encodeJSON() or IndividualPerturbationConConstructor.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) IndividualPerturbationConConstructor.getPropFormat(prop), num2cell(IndividualPerturbationConConstructor.getProps())) == Format.HANDLE) && all(cellfun(@(prop) IndividualPerturbationConConstructor.getPropFormat(prop), num2cell(IndividualPerturbationConConstructor.getProps())) == Format.NET)
		assert(isequal(ipc_dec, ipc), ...
			[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
			'IndividualPerturbationConConstructor.encodeJSON() or IndividualPerturbationConConstructor.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Example data
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	group_dir = fullfile(fileparts(which('IndividualDeviationConConstructor')),'Example data Nifti');
	if ~exist(group_dir)
	    create_example_NIfTI([],group_dir)
	end
end

%% Test 13: Verify Perturbation-Based Connectome Constructor
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', which('aal94_atlas.xlsx'));
	ba = im_ba.get('BA');
	atlas = ba;
	br_dict = atlas.get('BR_DICT');
	selected_ids = num2cell(1:94);
	selected_br = cellfun(@(id) br_dict.get('IT', id), selected_ids, 'UniformOutput', false);
	selected_br_dict = IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST',  selected_br);
	group_dir = fullfile(fileparts(which('IndividualDeviationConConstructor')),'Example data Nifti', 'Group1');
	
	im_gr1_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr1_WM_GM = im_gr1_WM_GM.get('GR');
	
	im_gr1_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr1_PET = im_gr1_PET.get('GR');
	
	healthy_dir = fullfile(fileparts(which('IndividualDeviationConConstructor')),'Example data Nifti', 'Group2');
	im_gr_ref_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', healthy_dir, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr_ref_WM_GM = im_gr_ref_WM_GM.get('GR');
	
	im_gr_ref_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', healthy_dir, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr_ref_PET = im_gr_ref_PET.get('GR');
	
	path_dict = IndexedDictionary(...
	    'IT_CLASS', 'FILE_PATH', ...
	    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii'))} ...
	    );
	
	ref_region_list = [2001]; % reference region label
	
	gr = SUVRConstructor('GR_PET',gr1_PET, ...
	    'GR_T1',gr1_WM_GM, ...
	    'BA', {ba},...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'ATLAS_KIND', {'AAL2'}, ...
	    'SUVR_REGION_SELECTION', selected_br_dict);
	
	gr_ref = SUVRConstructor('GR_PET',gr_ref_PET, ...
	    'GR_T1',gr_ref_WM_GM, ...
	    'BA', {ba},...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'ATLAS_KIND', {'AAL2'}, ...
	    'SUVR_REGION_SELECTION', selected_br_dict);
	
	suvr_gr = gr.get('GR');
	suvr_gr_ref = gr_ref.get('GR');
	
	constructor = IndividualPerturbationConConstructor( ...
	    'GR_SUVR', suvr_gr, ...
	    'GR_SUVR_REF', suvr_gr_ref ...
	    );
	
	perturbation_connectomes = constructor.get('GR');
	
	g_temp = GraphWU('STANDARDIZE_RULE', 'range');
	a_WU1 = AnalyzeEnsemble_CON_WU('GR', perturbation_connectomes, 'GRAPH_TEMPLATE', g_temp);
	num_subjects = a_WU1.get('G_DICT').get('LENGTH');
	
	for i = 1:num_subjects
	    g = a_WU1.get('G_DICT').get('IT', i);
	    strength = g.get('MEASURE', 'Strength').get('M'); % Strength for all regions
	
	    % Separate the first 20 regions and others
	    strength_first20(i, :) = strength{1}(1:20);
	    strength_others(i, :) = strength{1}(21:end);
	
	    % Compute the mean strength for the two sets of regions for each subject
	    mean_strength_first20 = mean(strength_first20(i, :));
	    mean_strength_others = mean(strength_others(i, :));
	
	    % Assert for each subject
	    assert(mean_strength_first20 < mean_strength_others, ...
	        sprintf('Test failed for subject %d: The first 20 regions do not have higher strength than the other regions.', i));
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':IndividualPerturbationConConstructor:' BRAPH2.FAIL_TEST], ...
		[' When testing IndividualPerturbationConConstructor no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

