%EXAMPLE_NIFTI_2_ROI_STRUCTURAL
% Script example pipeline neuroimaing (T1w) conversion to region-of-interest structural
% data
clear variables %#ok<*NASGU>

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data ST XLS' filesep 'atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_t1w = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data ST XLS' filesep 'ST_Group_1.xlsx'], ...
    'MODALITY', 'anat', ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr_t1w = im_gr_t1w.get('GR');

%% Convert neuroimaging data to region-of-interest structural data
gr_pdfs = ConverterNeuroimaging2PDFs( ...
    'BA', ba, ...
    'SELECTED_BR', selected_br_dict', ...
    'GR_NEUROIMAGING', gr_t1w, ...
    'BA_NIfTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_REGION_LIST', ref_region_list).get('GR_PDFS')

%% Export to group of ST
directory = [fileparts(which('test_braph2')) filesep 'trial_group_subjects_FUN_to_be_erased'];
ex = ExporterGroupSubjectFUN_XLS( ...
    'FILE', directory, ...
    'GR', gr_pdfs ...
    );

ex.get('SAVE');
