%TEST_CONVERTERNEUROIMAGING2PDFS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	cn = ConverterNeuroimaging2PDFs();
	 
	% get('ELCLASS')
	if isa(ConverterNeuroimaging2PDFs, 'ConcreteElement')
		assert(strcmp(ConverterNeuroimaging2PDFs().get('ELCLASS'), 'ConverterNeuroimaging2PDFs'), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs().get(''ELCLASS'') should return ''ConverterNeuroimaging2PDFs''.')
	end
	 
	% getBuild()
	assert(ConverterNeuroimaging2PDFs.getBuild() == 1 && ConverterNeuroimaging2PDFs.getBuild() > 0, ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getBuild() should return the ConverterNeuroimaging2PDFs build number.')
	assert(cn.getBuild() == 1 && cn.getBuild() > 0 , ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getBuild() should return the ConverterNeuroimaging2PDFs build number.')
	assert(Element.getBuild(cn) == 1 && Element.getBuild(cn) > 0, ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(cn) should return the ConverterNeuroimaging2PDFs build number.')
	assert(Element.getBuild('ConverterNeuroimaging2PDFs') == 1 && Element.getBuild('ConverterNeuroimaging2PDFs') > 0, ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ConverterNeuroimaging2PDFs'') should return the ConverterNeuroimaging2PDFs build number.')
	 
	% getClass()
	assert(strcmp(ConverterNeuroimaging2PDFs.getClass(), 'ConverterNeuroimaging2PDFs'), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getClass() should return ''ConverterNeuroimaging2PDFs''.')
	assert(strcmp(cn.getClass(), 'ConverterNeuroimaging2PDFs'), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getClass() should return ''ConverterNeuroimaging2PDFs''.')
	assert(strcmp(Element.getClass(cn), 'ConverterNeuroimaging2PDFs'), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(cn) should return ''ConverterNeuroimaging2PDFs''.')
	assert(strcmp(Element.getClass('ConverterNeuroimaging2PDFs'), 'ConverterNeuroimaging2PDFs'), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ConverterNeuroimaging2PDFs'') should return ''ConverterNeuroimaging2PDFs''.')
	 
	% getSubclasses()
	assert(isequal(ConverterNeuroimaging2PDFs.getSubclasses(), subclasses('ConverterNeuroimaging2PDFs', [], [], true)), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getSubclasses() should return the same result as subclasses(''ConverterNeuroimaging2PDFs'', [], [], true).')
	assert(isequal(cn.getSubclasses(), subclasses('ConverterNeuroimaging2PDFs', [], [], true)), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ConverterNeuroimaging2PDFs'', [], [], true).')
	assert(isequal(Element.getSubclasses(cn), subclasses('ConverterNeuroimaging2PDFs', [], [], true)), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(cn) should return the same result as subclasses(''ConverterNeuroimaging2PDFs'', [], [], true).')
	assert(isequal(Element.getSubclasses('ConverterNeuroimaging2PDFs'), subclasses('ConverterNeuroimaging2PDFs', [], [], true)), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ConverterNeuroimaging2PDFs'') should return the same result as subclasses(''ConverterNeuroimaging2PDFs'', [], [], true).')
	 
	% getProps()
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(ConverterNeuroimaging2PDFs.getProps(), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(cn.getProps(), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(Element.getProps(cn), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(cn) should return a row vector [1:1:N].')
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(Element.getProps('ConverterNeuroimaging2PDFs'), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterNeuroimaging2PDFs'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ConverterNeuroimaging2PDFs.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getProps(category) does not work.')
	tmp = cellfun(@(category) cn.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(cn, category), categories, 'UniformOutput', false);
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(cn, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ConverterNeuroimaging2PDFs', category), categories, 'UniformOutput', false);
	assert(isempty(ConverterNeuroimaging2PDFs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterNeuroimaging2PDFs.getProps())), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterNeuroimaging2PDFs'', category) does not work.')
	 
	% getPropNumber()
	assert(ConverterNeuroimaging2PDFs.getPropNumber() == length(ConverterNeuroimaging2PDFs.getProps()), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getPropNumber() should return the number of properties.')
	assert(cn.getPropNumber() == length(ConverterNeuroimaging2PDFs.getProps()), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(cn) == length(ConverterNeuroimaging2PDFs.getProps()), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(cn) should return the number of properties.')
	assert(Element.getPropNumber('ConverterNeuroimaging2PDFs') == length(ConverterNeuroimaging2PDFs.getProps()), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterNeuroimaging2PDFs'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ConverterNeuroimaging2PDFs.getPropNumber(category), categories)) == ConverterNeuroimaging2PDFs.getPropNumber(), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) cn.getPropNumber(category), categories)) == ConverterNeuroimaging2PDFs.getPropNumber(), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(cn, category), categories)) == ConverterNeuroimaging2PDFs.getPropNumber(), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(cn, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ConverterNeuroimaging2PDFs', category), categories)) == ConverterNeuroimaging2PDFs.getPropNumber(), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterNeuroimaging2PDFs'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ConverterNeuroimaging2PDFs.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.existsProp(prop) does not work.')
	assert(~cn.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.existsProp(prop) does not work.')
	assert(~Element.existsProp(cn, NaN), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(cn, prop) does not work.')
	assert(~Element.existsProp('ConverterNeuroimaging2PDFs', NaN), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
	assert_with_error('ConverterNeuroimaging2PDFs.existsProp(NaN)', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsProp(''ConverterNeuroimaging2PDFs'', NaN)', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		assert(ConverterNeuroimaging2PDFs.existsProp(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.existsProp(prop) does not work.')
		assert(cn.existsProp(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.existsProp(prop) does not work.')
		assert(Element.existsProp(cn, prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(cn, prop) does not work.')
		assert(Element.existsProp('ConverterNeuroimaging2PDFs', prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ConverterNeuroimaging2PDFs.existsTag(''), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.existsTag(tag) does not work.')
	assert(~cn.existsTag(''), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'cn.existsTag(tag) does not work.')
	assert(~Element.existsTag(cn, ''), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(cn, tag) does not work.')
	assert(~Element.existsTag('ConverterNeuroimaging2PDFs', ''), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	 
	assert_with_error('ConverterNeuroimaging2PDFs.existsTag('''')', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsTag(''ConverterNeuroimaging2PDFs'', '''')', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
		assert(ConverterNeuroimaging2PDFs.existsTag(tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.existsTag(tag) does not work.')
		assert(cn.existsTag(tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.existsTag(tag) does not work.')
		assert(Element.existsTag(cn, tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(cn, tga) does not work.')
		assert(Element.existsTag('ConverterNeuroimaging2PDFs', tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		assert(ConverterNeuroimaging2PDFs.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropProp(prop) does not work.')
		assert(cn.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropProp(prop) does not work.')
		assert(Element.getPropProp(cn, prop) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(cn, prop) does not work.')
		assert(Element.getPropProp('ConverterNeuroimaging2PDFs', prop) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
		tag = cn.getPropTag(prop);
		assert(ConverterNeuroimaging2PDFs.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropProp(tag) does not work.')
		assert(cn.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropProp(tag) does not work.')
		assert(Element.getPropProp(cn, tag) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(cn, tag) does not work.')
		assert(Element.getPropProp('ConverterNeuroimaging2PDFs', prop) == prop, ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(strcmp(ConverterNeuroimaging2PDFs.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropTag(prop) does not work.')
		assert(strcmp(cn.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(cn, prop), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(cn, prop) does not work.')
		assert(strcmp(Element.getPropTag('ConverterNeuroimaging2PDFs', prop), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
		assert(strcmp(ConverterNeuroimaging2PDFs.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropTag(tag) does not work.')
		assert(strcmp(cn.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(cn, tag), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(cn, tag) does not work.')
		assert(strcmp(Element.getPropTag('ConverterNeuroimaging2PDFs', prop), tag), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(Category.existsCategory(ConverterNeuroimaging2PDFs.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(cn.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(cn, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
		assert(Category.existsCategory(ConverterNeuroimaging2PDFs.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(cn.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(cn, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(Format.existsFormat(ConverterNeuroimaging2PDFs.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(cn.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(cn, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
		assert(Format.existsFormat(ConverterNeuroimaging2PDFs.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(cn.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(cn, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(ischar(ConverterNeuroimaging2PDFs.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropDescription(prop) does not work.')
		assert(ischar(cn.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(cn, prop) does not work.')
		assert(ischar(Element.getPropDescription(cn, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterNeuroimaging2PDFs'', prop) does not work.')
	 
		assert(ischar(ConverterNeuroimaging2PDFs.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.getPropDescription(tag) does not work.')
		assert(ischar(cn.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(cn, tag) does not work.')
		assert(ischar(Element.getPropDescription(cn, tag)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterNeuroimaging2PDFs'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		settings = ConverterNeuroimaging2PDFs.getPropSettings(prop);
		settings = cn.getPropSettings(prop);
		settings = Element.getPropSettings(cn, prop);
		settings = Element.getPropSettings('ConverterNeuroimaging2PDFs', prop);
	 
		settings = ConverterNeuroimaging2PDFs.getPropSettings(tag);
		settings = cn.getPropSettings(tag);
		settings = Element.getPropSettings(cn, tag);
		settings = Element.getPropSettings('ConverterNeuroimaging2PDFs', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		default = ConverterNeuroimaging2PDFs.getPropDefault(prop);
		default = cn.getPropDefault(prop);
		default = Element.getPropDefault(cn, prop);
		default = Element.getPropDefault('ConverterNeuroimaging2PDFs', prop);
	 
		default = ConverterNeuroimaging2PDFs.getPropDefault(tag);
		default = cn.getPropDefault(tag);
		default = Element.getPropDefault(cn, tag);
		default = Element.getPropDefault('ConverterNeuroimaging2PDFs', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		conditioned_default = ConverterNeuroimaging2PDFs.getPropDefaultConditioned(prop);
		conditioned_default = cn.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(cn, prop);
		conditioned_default = Element.getPropDefaultConditioned('ConverterNeuroimaging2PDFs', prop);
	 
		conditioned_default = ConverterNeuroimaging2PDFs.getPropDefaultConditioned(tag);
		conditioned_default = cn.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(cn, tag);
		conditioned_default = Element.getPropDefaultConditioned('ConverterNeuroimaging2PDFs', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(~ConverterNeuroimaging2PDFs.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.checkProp(prop, value) does not work.')
		assert(~cn.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(cn, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, prop, value) does not work.')
		assert(~Element.checkProp('ConverterNeuroimaging2PDFs', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterNeuroimaging2PDFs'', prop, value) does not work.')
	 
		assert_with_error('ConverterNeuroimaging2PDFs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], prop, cn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], prop, cn)
		assert_with_error('Element.checkProp(''ConverterNeuroimaging2PDFs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ConverterNeuroimaging2PDFs.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.checkProp(tag, value) does not work.')
		assert(~cn.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(cn, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, tag, value) does not work.')
		assert(~Element.checkProp('ConverterNeuroimaging2PDFs', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterNeuroimaging2PDFs'', tag, value) does not work.')
	 
		assert_with_error('ConverterNeuroimaging2PDFs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], tag, cn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], tag, cn)
		assert_with_error('Element.checkProp(''ConverterNeuroimaging2PDFs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ConverterNeuroimaging2PDFs.checkProp(prop, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.checkProp(prop, <conditioned default value>) does not work.')
		assert(cn.checkProp(prop, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(cn, prop, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterNeuroimaging2PDFs', prop, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterNeuroimaging2PDFs'', prop, <conditioned default value>) does not work.')
	 
		assert(ConverterNeuroimaging2PDFs.checkProp(tag, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.checkProp(tag, <conditioned default value>) does not work.')
		assert(cn.checkProp(tag, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(cn, tag, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterNeuroimaging2PDFs', tag, Element.getPropDefaultConditioned(ConverterNeuroimaging2PDFs, prop)), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterNeuroimaging2PDFs'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS ConverterNeuroimaging2PDFs.BIN_CENTERS])
			continue
		end
	 
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					cn.getr(prop) == ConverterNeuroimaging2PDFs.getNoValue(), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterNeuroimaging2PDFs.getCategoryName(ConverterNeuroimaging2PDFs.getPropCategory(prop)) ', ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					cn.getr(TAG) == ConverterNeuroimaging2PDFs.getNoValue(), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterNeuroimaging2PDFs.getCategoryName(ConverterNeuroimaging2PDFs.getPropCategory(prop)) ', ConverterNeuroimaging2PDFs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(cn.getPropSettings(prop))
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop)), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop), cn.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					cn.getr(prop) == ConverterNeuroimaging2PDFs.getNoValue(), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterNeuroimaging2PDFs.getCategoryName(ConverterNeuroimaging2PDFs.getPropCategory(prop)) ', ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					cn.getr(TAG) == ConverterNeuroimaging2PDFs.getNoValue(), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterNeuroimaging2PDFs.getCategoryName(ConverterNeuroimaging2PDFs.getPropCategory(prop)) ', ConverterNeuroimaging2PDFs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ConverterNeuroimaging2PDFs']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(cn.getPropSettings(prop))
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop)), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop), cn.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(cn.getr(prop), ConverterNeuroimaging2PDFs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ConverterNeuroimaging2PDFs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(cn.getr(TAG), ConverterNeuroimaging2PDFs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ConverterNeuroimaging2PDFs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterNeuroimaging2PDFs.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS ConverterNeuroimaging2PDFs.BIN_CENTERS])
			continue
		end
	 
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(cn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterNeuroimaging2PDFs']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterNeuroimaging2PDFs']);
	% 			assert( ...
	% 				~isa(cn.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterNeuroimaging2PDFs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(cn.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ConverterNeuroimaging2PDFs']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(cn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if cn.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ConverterNeuroimaging2PDFs');
					delete(ancestor(cn.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ConverterNeuroimaging2PDFs.getProps(Category.RESULT))
		for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
	 
			% excluded props
			if any(prop == [ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS ConverterNeuroimaging2PDFs.BIN_CENTERS])
				continue
			end
	 
			switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs();
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		assert( ...
			~cn.isLocked(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~cn.isLocked(TAG), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	cn.lock()
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs();
	 
	warning_backup = warning('off', 'BRAPH2:ConverterNeuroimaging2PDFs');
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		cn.lock(prop)
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs();
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		assert( ...
			cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			cn.isChecked(TAG), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	cn.unchecked()
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		assert( ...
			~cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	cn.checked()
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		assert( ...
			cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			['ConverterNeuroimaging2PDFs.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ConverterNeuroimaging2PDFs
	cn_0 = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	% ConverterNeuroimaging2PDFs with 1st callbacks
	cn_1 = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, cn_0.getCallback(4), ..., ...
		ConverterNeuroimaging2PDFs.ID, cn_0.getCallback(5), ..., ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, cn_0.getCallback(9), ..., ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, cn_0.getCallback(10), ..., ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, cn_0.getCallback(11), ..., ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, cn_0.getCallback(12), ..., ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, cn_0.getCallback(13), ..., ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, cn_0.getCallback(14), ..., ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, cn_0.getCallback(15), ..., ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, cn_0.getCallback(16), ..., ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, cn_0.getCallback(17), ..., ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, cn_0.getCallback(22) ... ...
		);
	 
	prop_number = ConverterNeuroimaging2PDFs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_1.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterNeuroimaging2PDFs with 2nd callbacks
	cn_2 = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, cn_1.getCallback(4), ..., ...
		ConverterNeuroimaging2PDFs.ID, cn_1.getCallback(5), ..., ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, cn_1.getCallback(9), ..., ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, cn_1.getCallback(10), ..., ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, cn_1.getCallback(11), ..., ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, cn_1.getCallback(12), ..., ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, cn_1.getCallback(13), ..., ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, cn_1.getCallback(14), ..., ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, cn_1.getCallback(15), ..., ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, cn_1.getCallback(16), ..., ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, cn_1.getCallback(17), ..., ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, cn_1.getCallback(22) ... ...
		);
	 
	prop_number = ConverterNeuroimaging2PDFs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_2.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterNeuroimaging2PDFs with 3rd callbacks
	cn_3 = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, cn_2.getCallback(4), ..., ...
		ConverterNeuroimaging2PDFs.ID, cn_2.getCallback(5), ..., ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, cn_2.getCallback(9), ..., ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, cn_2.getCallback(10), ..., ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, cn_2.getCallback(11), ..., ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, cn_2.getCallback(12), ..., ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, cn_2.getCallback(13), ..., ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, cn_2.getCallback(14), ..., ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, cn_2.getCallback(15), ..., ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, cn_2.getCallback(16), ..., ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, cn_2.getCallback(17), ..., ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, cn_2.getCallback(22) ... ...
		);
	 
	prop_number = ConverterNeuroimaging2PDFs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_3.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	cn = ConverterNeuroimaging2PDFs();
	 
	cn_copy = cn.copy();
	 
	assert(cn_copy ~= cn, ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(cn_copy, cn), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					cn_copy.isLocked(prop) == cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					cn_copy.isChecked(prop) == cn.isChecked(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		if ConverterNeuroimaging2PDFs.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ConverterNeuroimaging2PDFs']);
			% cn.memorize(prop);
			% warning(warning_backup)
		elseif ConverterNeuroimaging2PDFs.getPropCategory(prop) == Category.EVANESCENT && cn.getPropFormat(prop) == Format.HANDLE
			cn.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ConverterNeuroimaging2PDFs');
			delete(ancestor(cn.get(prop), 'figure'))
			warning(warning_backup)
		else
			cn.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	cn_copy = cn.copy();
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						cn_copy.isLocked(prop) == cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.isChecked(prop) == cn.isChecked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	cn_0 = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, cn_0.getCallback(4), ..., ...
		ConverterNeuroimaging2PDFs.ID, cn_0.getCallback(5), ..., ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, cn_0.getCallback(9), ..., ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, cn_0.getCallback(10), ..., ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, cn_0.getCallback(11), ..., ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, cn_0.getCallback(12), ..., ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, cn_0.getCallback(13), ..., ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, cn_0.getCallback(14), ..., ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, cn_0.getCallback(15), ..., ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, cn_0.getCallback(16), ..., ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, cn_0.getCallback(17), ..., ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, cn_0.getCallback(22) ... ...
		);
	 
	cn_copy = cn.copy();
	cn_0_copy = cn_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					'ConverterNeuroimaging2PDFs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
							'ConverterNeuroimaging2PDFs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == cn_0.getCallback(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The callback should be obtained from ConverterNeuroimaging2PDFs.getCallback().' ...
						)
					assert( ...
						value_copy == cn_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The callback should be obtained from ConverterNeuroimaging2PDFs.getCallback().' ...
						)
				end
	 
					assert( ...
						cn_copy.isLocked(prop) == cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.isChecked(prop) == cn.isChecked(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn_template = ConverterNeuroimaging2PDFs();
	cn = ConverterNeuroimaging2PDFs('TEMPLATE', cn_template);
	 
	for prop = 1:1:ConverterNeuroimaging2PDFs.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS ConverterNeuroimaging2PDFs.BIN_CENTERS])
			continue
		end
	 
		TAG = upper(ConverterNeuroimaging2PDFs.getPropTag(prop));
		switch ConverterNeuroimaging2PDFs.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ConverterNeuroimaging2PDFs.TEMPLATE
					assert( ...
						isa(cn.getr(prop), 'ConverterNeuroimaging2PDFs'), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs.getr(''TEMPLATE'') should be a ConverterNeuroimaging2PDFs element.' ...
						)
					assert( ...
						isa(cn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						'ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(cn.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						cn.getr(prop).get('EL') == cn_template && cn.getr(prop).get('PROP') == prop && strcmp(cn.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs.getr(' TAG ') should be a Callback to cn_template.' TAG '.'] ...
						)
					assert( ...
						isa(cn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
						['ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(cn_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
					['ConverterNeuroimaging2PDFs TEMPLATE does not work. ConverterNeuroimaging2PDFs_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'converterneuroimaging2pdfs_to_be_erased.b2'];
	 
	Element.save(cn, filename)
	 
	cn_loaded = Element.load(filename);
	 
	assert( ...
		isequal(cn.copy(), cn_loaded), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.save(cn) and/or ConverterNeuroimaging2PDFs.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterNeuroimaging2PDFs( ...
		ConverterNeuroimaging2PDFs.ELCLASS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.NAME, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.DESCRIPTION, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.TEMPLATE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.TEMPLATE), ...
		ConverterNeuroimaging2PDFs.ID, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ID), ...
		ConverterNeuroimaging2PDFs.LABEL, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.LABEL), ...
		ConverterNeuroimaging2PDFs.NOTES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.NOTES), ...
		ConverterNeuroimaging2PDFs.TOSTRING, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA_LIST, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_LIST), ...
		ConverterNeuroimaging2PDFs.BA_NIFTI_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_NIFTI_FILES), ...
		ConverterNeuroimaging2PDFs.BA_MAPPING_FILES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BA_MAPPING_FILES), ...
		ConverterNeuroimaging2PDFs.GR_NEUROIMAGING, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_NEUROIMAGING), ...
		ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.GR_LIST_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.THRESHOLD_ANAT_REF), ...
		ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.ANAT_REF_COMBINE_RULE), ...
		ConverterNeuroimaging2PDFs.CONVERT_BR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.CONVERT_BR), ...
		ConverterNeuroimaging2PDFs.BIN_EDGES, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.BIN_EDGES), ...
		ConverterNeuroimaging2PDFs.BIN_CENTERS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BR_LABEL_IN_MAPS, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.BA, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.GR_FUN, ConverterNeuroimaging2PDFs.getNoValue(), ...
		ConverterNeuroimaging2PDFs.WAITBAR, ConverterNeuroimaging2PDFs.getPropDefault(ConverterNeuroimaging2PDFs.WAITBAR) ...
		);
	 
	[json, struct, el_list] = encodeJSON(cn);
	[cn_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(cn_dec ~= cn, ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		'ConverterNeuroimaging2PDFs.encodeJSON() or ConverterNeuroimaging2PDFs.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ConverterNeuroimaging2PDFs.getPropFormat(prop), num2cell(ConverterNeuroimaging2PDFs.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ConverterNeuroimaging2PDFs.getPropFormat(prop), num2cell(ConverterNeuroimaging2PDFs.getProps())) == Format.NET)
		assert(isequal(cn_dec, cn), ...
			[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
			'ConverterNeuroimaging2PDFs.encodeJSON() or ConverterNeuroimaging2PDFs.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Sanity check - convert GM probability NIfTI data to regional PDFs
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	example_data_dir = fullfile(fileparts(which('ConverterNeuroimaging2PDFs')), 'Example data NIfTI');
	example_atlas_dir = fullfile(fileparts(which('ConverterNeuroimaging2PDFs')), 'example atlases NIfTI');
	
	if isempty(dir(fullfile(example_data_dir, 'sub-*', 'ses-*', 'anat', '*_GMprob.nii')))
	    create_data_NIfTI_GMProb();
	end
	
	im_ba = ImporterBrainAtlasXLS( ...
	    'FILE', fullfile(example_atlas_dir, 'aal120_atlas.xlsx'), ...
	    'WAITBAR', false ...
	    );
	
	ba_aal120 = im_ba.get('BA');
	
	im_gr = ImporterGroupSubjectNeuroimaging_NIfTI( ...
	    'DIRECTORY', example_data_dir, ...
	    'MODALITY', 'anat', ...
	    'TARGET', 'GMprob', ...
	    'BA', ba_aal120, ...
	    'WAITBAR', false ...
	    );
	
	gr_gmprob = im_gr.get('GR');
	
	brain_regions_to_convert = {};
	for i = 1:5
	    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', i).get('ID'); %#ok<AGROW>
	end
	
	bin_edges = linspace(0, 1, 101);
	
	cn = ConverterNeuroimaging2PDFs( ...
	    'BA_LIST', {ba_aal120}, ...
	    'BA_NIFTI_FILES', {fullfile(example_atlas_dir, 'aal120_atlas.nii')}, ...
	    'BA_MAPPING_FILES', {fullfile(example_atlas_dir, 'aal120_atlas_mapping.csv')}, ...
	    'CONVERT_BR', brain_regions_to_convert, ...
	    'GR_NEUROIMAGING', gr_gmprob, ...
	    'BIN_EDGES', bin_edges, ...
	    'WAITBAR', false ...
	    );
	
	gr_fun = cn.get('GR_FUN');
	
	assert(isequal(gr_fun.get('SUB_DICT').get('LENGTH'), 10), ...
	    'The converted group should contain 10 subjects.')
	
	sub_fun = gr_fun.get('SUB_DICT').get('IT', 1);
	fun = sub_fun.get('FUN');
	
	assert(isequal(size(fun), [100 5]), ...
	    'The converted subject should contain a 100-by-5 PDF matrix.')
	
	assert(all(~isnan(fun(:))), ...
	    'The converted regional PDFs should not contain NaN values.')
end

%% Test 13: Sanity check - convert PET NIfTI data to regional PDFs
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	example_data_dir = fullfile(fileparts(which('ConverterNeuroimaging2PDFs')), 'Example data NIfTI');
	example_atlas_dir = fullfile(fileparts(which('ConverterNeuroimaging2PDFs')), 'example atlases NIfTI');
	
	if isempty(dir(fullfile(example_data_dir, 'sub-*', 'ses-*', 'pet', '*_pet.nii')))
	    create_data_NIfTI_PET();
	end
	
	if isempty(dir(fullfile(example_data_dir, 'sub-*', 'ses-*', 'anat', '*_GMprob.nii')))
	    create_data_NIfTI_GMProb();
	end
	
	if isempty(dir(fullfile(example_data_dir, 'sub-*', 'ses-*', 'anat', '*_WMprob.nii')))
	    create_data_NIfTI_WMProb();
	end
	
	im_ba = ImporterBrainAtlasXLS( ...
	    'FILE', fullfile(example_atlas_dir, 'aal120_atlas.xlsx'), ...
	    'WAITBAR', false ...
	    );
	
	ba_aal120 = im_ba.get('BA');
	
	im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
	    'DIRECTORY', example_data_dir, ...
	    'MODALITY', 'pet', ...
	    'BA', ba_aal120, ...
	    'WAITBAR', false ...
	    );
	
	gr_pet = im_gr_pet.get('GR');
	
	im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
	    'DIRECTORY', example_data_dir, ...
	    'MODALITY', 'anat', ...
	    'TARGET', 'GMprob', ...
	    'BA', ba_aal120, ...
	    'WAITBAR', false ...
	    );
	
	gr_gmprob = im_gr_gm.get('GR');
	
	im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
	    'DIRECTORY', example_data_dir, ...
	    'MODALITY', 'anat', ...
	    'TARGET', 'WMprob', ...
	    'BA', ba_aal120, ...
	    'WAITBAR', false ...
	    );
	
	gr_wmprob = im_gr_wm.get('GR');
	
	brain_regions_to_convert = {};
	for i = 1:5
	    brain_regions_to_convert{end + 1} = ba_aal120.get('BR_DICT').get('IT', i).get('ID'); %#ok<AGROW>
	end
	
	bin_edges = linspace(0, 3, 101);
	
	cn = ConverterNeuroimaging2PDFs( ...
	    'BA_LIST', {ba_aal120}, ...
	    'BA_NIFTI_FILES', {fullfile(example_atlas_dir, 'aal120_atlas.nii')}, ...
	    'BA_MAPPING_FILES', {fullfile(example_atlas_dir, 'aal120_atlas_mapping.csv')}, ...
	    'CONVERT_BR', brain_regions_to_convert, ...
	    'GR_NEUROIMAGING', gr_pet, ...
	    'GR_LIST_ANAT_REF', {gr_gmprob, gr_wmprob}, ...
	    'THRESHOLD_ANAT_REF', 0.5, ...
	    'ANAT_REF_COMBINE_RULE', 'or', ...
	    'BIN_EDGES', bin_edges, ...
	    'WAITBAR', false ...
	    );
	
	gr_fun = cn.get('GR_FUN');
	
	assert(isequal(gr_fun.get('SUB_DICT').get('LENGTH'), 10), ...
	    'The converted PET group should contain 10 subjects.')
	
	sub_fun = gr_fun.get('SUB_DICT').get('IT', 1);
	fun = sub_fun.get('FUN');
	
	assert(isequal(size(fun), [100 5]), ...
	    'The converted PET subject should contain a 100-by-5 PDF matrix.')
	
	assert(all(~isnan(fun(:))), ...
	    'The converted PET regional PDFs should not contain NaN values.')
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ConverterNeuroimaging2PDFs:' BRAPH2.FAIL_TEST], ...
		[' When testing ConverterNeuroimaging2PDFs no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

