%EXAMPLE_NIFTI_2_ROI_STRUCTURAL
% Script example pipeline neuroimaing (T1w) conversion to region-of-interest structural
% data
clear variables %#ok<*NASGU>

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data ST XLS' filesep 'atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data ST XLS' filesep 'ST_Group_1.xlsx'], ...
    'MODALITY', 'pet', ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr_pet = im_gr.get('GR');

im_gr_ = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data ST XLS' filesep 'ST_Group_1.xlsx'], ...
    'MODALITY', 'anat', ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr_anat = im_gr.get('GR');
%% Convert neuroimaging data to region-of-interest structural data
gr_st = ConverterNeuroimaging2RegionalValues( ...
    'BA', ba, ...
    'SELECTED_BR', selected_br_dict', ...
    'GR_NEUROIMAGING', gr_pet, ...
    'GR_REFERENCE', gr_anat, ...
    'BA_NIfTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_REGION_LIST', ref_region_list).get('GR_ST')

%% Export to group of ST
file = [fileparts(which('SubjectNeuroimaging')) filesep 'trial_group_subjects_ST_to_be_erased.xlsx'];
ex = ExporterGroupSubjectST_XLS( ...
    'FILE', file, ...
    'GR', gr_st ...
    );
ex.get('SAVE');
