%EXAMPLE_PDFS_2_CON
% Script example pipeline PDFs conversion to connectivity data using
% correlation
clear variables %#ok<*NASGU>

%% Create dataset
atlas_path = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];

example_data_dir = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Converted data T1w'];
if ~isfolder(example_data_dir)
    example_NEUROIMAGING_2_PDFs_T1W
end    

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [example_data_dir filesep 'atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Groups of SubjectFUN
im_gr = ImporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', [example_data_dir filesep 'Group ID'], ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr = im_gr.get('GR');

%% Analysis FUN WU
a_WU = AnalyzeEnsemble_FUN_WU( ...
    'GR', gr ...
    );

g_dict = a_WU.get('G_DICT');

% Create output group.
gr_con = Group( ...
    'SUB_CLASS', 'SubjectCON', ...
    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectCON') ...
    );

sub_dict = gr_con.memorize('SUB_DICT');
sub_dict_neuroimaging = gr_con.get('SUB_DICT');
subject_number = gr_con.get('LENGTH');

sub_fun = SubjectFUN( ...
        'ID', subject_id, ...
        'LABEL', sub_neuroimaging.get('LABEL'), ...
        'NOTES', sub_neuroimaging.get('NOTES'), ...
        'BA', ba_fun, ...
        'FUN', pdf_matrix, ...
        'VOI_DICT', sub_neuroimaging.get('VOI_DICT') ...
        );

    sub_dict.get('ADD', sub_fun);

