%TEST_CONVERTERPDFS2CON

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	c = ConverterPDFs2CON();
	 
	% get('ELCLASS')
	if isa(ConverterPDFs2CON, 'ConcreteElement')
		assert(strcmp(ConverterPDFs2CON().get('ELCLASS'), 'ConverterPDFs2CON'), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON().get(''ELCLASS'') should return ''ConverterPDFs2CON''.')
	end
	 
	% getBuild()
	assert(ConverterPDFs2CON.getBuild() == 1 && ConverterPDFs2CON.getBuild() > 0, ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getBuild() should return the ConverterPDFs2CON build number.')
	assert(c.getBuild() == 1 && c.getBuild() > 0 , ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getBuild() should return the ConverterPDFs2CON build number.')
	assert(Element.getBuild(c) == 1 && Element.getBuild(c) > 0, ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(c) should return the ConverterPDFs2CON build number.')
	assert(Element.getBuild('ConverterPDFs2CON') == 1 && Element.getBuild('ConverterPDFs2CON') > 0, ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ConverterPDFs2CON'') should return the ConverterPDFs2CON build number.')
	 
	% getClass()
	assert(strcmp(ConverterPDFs2CON.getClass(), 'ConverterPDFs2CON'), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getClass() should return ''ConverterPDFs2CON''.')
	assert(strcmp(c.getClass(), 'ConverterPDFs2CON'), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getClass() should return ''ConverterPDFs2CON''.')
	assert(strcmp(Element.getClass(c), 'ConverterPDFs2CON'), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(c) should return ''ConverterPDFs2CON''.')
	assert(strcmp(Element.getClass('ConverterPDFs2CON'), 'ConverterPDFs2CON'), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ConverterPDFs2CON'') should return ''ConverterPDFs2CON''.')
	 
	% getSubclasses()
	assert(isequal(ConverterPDFs2CON.getSubclasses(), subclasses('ConverterPDFs2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getSubclasses() should return the same result as subclasses(''ConverterPDFs2CON'', [], [], true).')
	assert(isequal(c.getSubclasses(), subclasses('ConverterPDFs2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ConverterPDFs2CON'', [], [], true).')
	assert(isequal(Element.getSubclasses(c), subclasses('ConverterPDFs2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(c) should return the same result as subclasses(''ConverterPDFs2CON'', [], [], true).')
	assert(isequal(Element.getSubclasses('ConverterPDFs2CON'), subclasses('ConverterPDFs2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ConverterPDFs2CON'') should return the same result as subclasses(''ConverterPDFs2CON'', [], [], true).')
	 
	% getProps()
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(ConverterPDFs2CON.getProps(), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(c.getProps(), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(Element.getProps(c), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(c) should return a row vector [1:1:N].')
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(Element.getProps('ConverterPDFs2CON'), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterPDFs2CON'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ConverterPDFs2CON.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getProps(category) does not work.')
	tmp = cellfun(@(category) c.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(c, category), categories, 'UniformOutput', false);
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(c, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ConverterPDFs2CON', category), categories, 'UniformOutput', false);
	assert(isempty(ConverterPDFs2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterPDFs2CON.getProps())), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterPDFs2CON'', category) does not work.')
	 
	% getPropNumber()
	assert(ConverterPDFs2CON.getPropNumber() == length(ConverterPDFs2CON.getProps()), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getPropNumber() should return the number of properties.')
	assert(c.getPropNumber() == length(ConverterPDFs2CON.getProps()), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(c) == length(ConverterPDFs2CON.getProps()), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(c) should return the number of properties.')
	assert(Element.getPropNumber('ConverterPDFs2CON') == length(ConverterPDFs2CON.getProps()), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterPDFs2CON'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ConverterPDFs2CON.getPropNumber(category), categories)) == ConverterPDFs2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) c.getPropNumber(category), categories)) == ConverterPDFs2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(c, category), categories)) == ConverterPDFs2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(c, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ConverterPDFs2CON', category), categories)) == ConverterPDFs2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterPDFs2CON'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ConverterPDFs2CON.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.existsProp(prop) does not work.')
	assert(~c.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.existsProp(prop) does not work.')
	assert(~Element.existsProp(c, NaN), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(c, prop) does not work.')
	assert(~Element.existsProp('ConverterPDFs2CON', NaN), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ConverterPDFs2CON'', prop) does not work.')
	 
	assert_with_error('ConverterPDFs2CON.existsProp(NaN)', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], c)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], c)
	assert_with_error('Element.existsProp(''ConverterPDFs2CON'', NaN)', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		assert(ConverterPDFs2CON.existsProp(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.existsProp(prop) does not work.')
		assert(c.existsProp(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.existsProp(prop) does not work.')
		assert(Element.existsProp(c, prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(c, prop) does not work.')
		assert(Element.existsProp('ConverterPDFs2CON', prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ConverterPDFs2CON'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ConverterPDFs2CON.existsTag(''), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.existsTag(tag) does not work.')
	assert(~c.existsTag(''), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'c.existsTag(tag) does not work.')
	assert(~Element.existsTag(c, ''), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(c, tag) does not work.')
	assert(~Element.existsTag('ConverterPDFs2CON', ''), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ConverterPDFs2CON'', tag) does not work.')
	 
	assert_with_error('ConverterPDFs2CON.existsTag('''')', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], c)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], c)
	assert_with_error('Element.existsTag(''ConverterPDFs2CON'', '''')', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
		assert(ConverterPDFs2CON.existsTag(tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.existsTag(tag) does not work.')
		assert(c.existsTag(tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.existsTag(tag) does not work.')
		assert(Element.existsTag(c, tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(c, tga) does not work.')
		assert(Element.existsTag('ConverterPDFs2CON', tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		assert(ConverterPDFs2CON.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropProp(prop) does not work.')
		assert(c.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropProp(prop) does not work.')
		assert(Element.getPropProp(c, prop) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(c, prop) does not work.')
		assert(Element.getPropProp('ConverterPDFs2CON', prop) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterPDFs2CON'', prop) does not work.')
	 
		tag = c.getPropTag(prop);
		assert(ConverterPDFs2CON.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropProp(tag) does not work.')
		assert(c.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropProp(tag) does not work.')
		assert(Element.getPropProp(c, tag) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(c, tag) does not work.')
		assert(Element.getPropProp('ConverterPDFs2CON', prop) == prop, ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		assert(strcmp(ConverterPDFs2CON.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropTag(prop) does not work.')
		assert(strcmp(c.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(c, prop), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(c, prop) does not work.')
		assert(strcmp(Element.getPropTag('ConverterPDFs2CON', prop), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterPDFs2CON'', prop) does not work.')
	 
		assert(strcmp(ConverterPDFs2CON.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropTag(tag) does not work.')
		assert(strcmp(c.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(c, tag), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(c, tag) does not work.')
		assert(strcmp(Element.getPropTag('ConverterPDFs2CON', prop), tag), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		assert(Category.existsCategory(ConverterPDFs2CON.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(c.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(c, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterPDFs2CON'', prop) does not work.')
	 
		assert(Category.existsCategory(ConverterPDFs2CON.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(c.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(c, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		assert(Format.existsFormat(ConverterPDFs2CON.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(c.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(c, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterPDFs2CON'', prop) does not work.')
	 
		assert(Format.existsFormat(ConverterPDFs2CON.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(c.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(c, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		assert(ischar(ConverterPDFs2CON.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropDescription(prop) does not work.')
		assert(ischar(c.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(c, prop) does not work.')
		assert(ischar(Element.getPropDescription(c, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterPDFs2CON'', prop) does not work.')
	 
		assert(ischar(ConverterPDFs2CON.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.getPropDescription(tag) does not work.')
		assert(ischar(c.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(c, tag) does not work.')
		assert(ischar(Element.getPropDescription(c, tag)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterPDFs2CON'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		settings = ConverterPDFs2CON.getPropSettings(prop);
		settings = c.getPropSettings(prop);
		settings = Element.getPropSettings(c, prop);
		settings = Element.getPropSettings('ConverterPDFs2CON', prop);
	 
		settings = ConverterPDFs2CON.getPropSettings(tag);
		settings = c.getPropSettings(tag);
		settings = Element.getPropSettings(c, tag);
		settings = Element.getPropSettings('ConverterPDFs2CON', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		default = ConverterPDFs2CON.getPropDefault(prop);
		default = c.getPropDefault(prop);
		default = Element.getPropDefault(c, prop);
		default = Element.getPropDefault('ConverterPDFs2CON', prop);
	 
		default = ConverterPDFs2CON.getPropDefault(tag);
		default = c.getPropDefault(tag);
		default = Element.getPropDefault(c, tag);
		default = Element.getPropDefault('ConverterPDFs2CON', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		conditioned_default = ConverterPDFs2CON.getPropDefaultConditioned(prop);
		conditioned_default = c.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(c, prop);
		conditioned_default = Element.getPropDefaultConditioned('ConverterPDFs2CON', prop);
	 
		conditioned_default = ConverterPDFs2CON.getPropDefaultConditioned(tag);
		conditioned_default = c.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(c, tag);
		conditioned_default = Element.getPropDefaultConditioned('ConverterPDFs2CON', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		tag = c.getPropTag(prop);
	 
		assert(~ConverterPDFs2CON.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.checkProp(prop, value) does not work.')
		assert(~c.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(c, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(c, prop, value) does not work.')
		assert(~Element.checkProp('ConverterPDFs2CON', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterPDFs2CON'', prop, value) does not work.')
	 
		assert_with_error('ConverterPDFs2CON.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], prop, c)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], prop, c)
		assert_with_error('Element.checkProp(''ConverterPDFs2CON'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ConverterPDFs2CON.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.checkProp(tag, value) does not work.')
		assert(~c.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(c, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(c, tag, value) does not work.')
		assert(~Element.checkProp('ConverterPDFs2CON', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterPDFs2CON'', tag, value) does not work.')
	 
		assert_with_error('ConverterPDFs2CON.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], tag, c)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], tag, c)
		assert_with_error('Element.checkProp(''ConverterPDFs2CON'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ConverterPDFs2CON.checkProp(prop, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.checkProp(prop, <conditioned default value>) does not work.')
		assert(c.checkProp(prop, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(c, prop, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(c, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterPDFs2CON', prop, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterPDFs2CON'', prop, <conditioned default value>) does not work.')
	 
		assert(ConverterPDFs2CON.checkProp(tag, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.checkProp(tag, <conditioned default value>) does not work.')
		assert(c.checkProp(tag, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'c.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(c, tag, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(c, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterPDFs2CON', tag, Element.getPropDefaultConditioned(ConverterPDFs2CON, prop)), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterPDFs2CON'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterPDFs2CON.TEMPLATE ConverterPDFs2CON.GRAPH_TEMPLATE ConverterPDFs2CON.ANALYSIS ConverterPDFs2CON.G_DICT])
			continue
		end
	 
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					c.getr(prop) == ConverterPDFs2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterPDFs2CON.getCategoryName(ConverterPDFs2CON.getPropCategory(prop)) ', ConverterPDFs2CON.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					c.getr(TAG) == ConverterPDFs2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterPDFs2CON.getCategoryName(ConverterPDFs2CON.getPropCategory(prop)) ', ConverterPDFs2CON.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(c.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(c.getPropSettings(prop))
					assert( ...
						c.checkFormat(c.getPropFormat(prop), c.get(prop)), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						c.checkFormat(c.getPropFormat(prop), c.get(prop), c.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					c.getr(prop) == ConverterPDFs2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterPDFs2CON.getCategoryName(ConverterPDFs2CON.getPropCategory(prop)) ', ConverterPDFs2CON.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					c.getr(TAG) == ConverterPDFs2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterPDFs2CON.getCategoryName(ConverterPDFs2CON.getPropCategory(prop)) ', ConverterPDFs2CON.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ConverterPDFs2CON']);
				assert( ...
					~isa(c.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(c.getPropSettings(prop))
					assert( ...
						c.checkFormat(c.getPropFormat(prop), c.get(prop)), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						c.checkFormat(c.getPropFormat(prop), c.get(prop), c.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(c.getr(prop), ConverterPDFs2CON.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ConverterPDFs2CON.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(c.getr(TAG), ConverterPDFs2CON.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ConverterPDFs2CON.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterPDFs2CON.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterPDFs2CON.TEMPLATE ConverterPDFs2CON.GRAPH_TEMPLATE ConverterPDFs2CON.ANALYSIS ConverterPDFs2CON.G_DICT])
			continue
		end
	 
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(c.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(c.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					c.checkFormat(c.getPropFormat(prop), c.getr(prop),c.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterPDFs2CON']);
				assert( ...
					~isa(c.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterPDFs2CON']);
	% 			assert( ...
	% 				~isa(c.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterPDFs2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(c.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				c.checkFormat(c.getPropFormat(prop), c.getr(prop),c.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterPDFs2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ConverterPDFs2CON']);
				assert( ...
					~isa(c.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(c.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					c.checkFormat(c.getPropFormat(prop), c.getr(prop),c.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if c.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ConverterPDFs2CON');
					delete(ancestor(c.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ConverterPDFs2CON.getProps(Category.RESULT))
		for prop = 1:1:ConverterPDFs2CON.getPropNumber()
	 
			% excluded props
			if any(prop == [ConverterPDFs2CON.TEMPLATE ConverterPDFs2CON.GRAPH_TEMPLATE ConverterPDFs2CON.ANALYSIS ConverterPDFs2CON.G_DICT])
				continue
			end
	 
			switch ConverterPDFs2CON.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						c.isLocked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~c.isLocked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON();
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		assert( ...
			~c.isLocked(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~c.isLocked(TAG), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	c.lock()
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					c.isLocked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~c.isLocked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON();
	 
	warning_backup = warning('off', 'BRAPH2:ConverterPDFs2CON');
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		c.lock(prop)
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					c.isLocked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~c.isLocked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON();
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		assert( ...
			c.isChecked(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			c.isChecked(TAG), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	c.unchecked()
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		assert( ...
			~c.isChecked(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	c.checked()
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		assert( ...
			c.isChecked(prop), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterPDFs2CON.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ConverterPDFs2CON
	c_0 = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	% ConverterPDFs2CON with 1st callbacks
	c_1 = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, c_0.getCallback(4), ..., ...
		ConverterPDFs2CON.ID, c_0.getCallback(5), ..., ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, c_0.getCallback(9), ..., ...
		ConverterPDFs2CON.METHOD, c_0.getCallback(10), ..., ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, c_0.getCallback(11), ..., ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, c_0.getCallback(16) ... ...
		);
	 
	prop_number = ConverterPDFs2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(c_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(c_1.get(prop), c_0.get(prop)) && ~isa(c_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(c_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterPDFs2CON with 2nd callbacks
	c_2 = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, c_1.getCallback(4), ..., ...
		ConverterPDFs2CON.ID, c_1.getCallback(5), ..., ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, c_1.getCallback(9), ..., ...
		ConverterPDFs2CON.METHOD, c_1.getCallback(10), ..., ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, c_1.getCallback(11), ..., ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, c_1.getCallback(16) ... ...
		);
	 
	prop_number = ConverterPDFs2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(c_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(c_2.get(prop), c_0.get(prop)) && ~isa(c_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(c_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterPDFs2CON with 3rd callbacks
	c_3 = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, c_2.getCallback(4), ..., ...
		ConverterPDFs2CON.ID, c_2.getCallback(5), ..., ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, c_2.getCallback(9), ..., ...
		ConverterPDFs2CON.METHOD, c_2.getCallback(10), ..., ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, c_2.getCallback(11), ..., ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, c_2.getCallback(16) ... ...
		);
	 
	prop_number = ConverterPDFs2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(c_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(c_3.get(prop), c_0.get(prop)) && ~isa(c_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(c_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	c = ConverterPDFs2CON();
	 
	c_copy = c.copy();
	 
	assert(c_copy ~= c, ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(c_copy, c), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		value = c.getr(prop);
		value_copy = c_copy.getr(prop);
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					c_copy.isLocked(prop) == c.isLocked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					c_copy.isChecked(prop) == c.isChecked(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					c_copy.getPropSeed(prop) == c.getPropSeed(prop), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		if ConverterPDFs2CON.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ConverterPDFs2CON']);
			% c.memorize(prop);
			% warning(warning_backup)
		elseif ConverterPDFs2CON.getPropCategory(prop) == Category.EVANESCENT && c.getPropFormat(prop) == Format.HANDLE
			c.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ConverterPDFs2CON');
			delete(ancestor(c.get(prop), 'figure'))
			warning(warning_backup)
		else
			c.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	c_copy = c.copy();
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		value = c.getr(prop);
		value_copy = c_copy.getr(prop);
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						c_copy.isLocked(prop) == c.isLocked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						c_copy.isChecked(prop) == c.isChecked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						c_copy.getPropSeed(prop) == c.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	c_0 = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, c_0.getCallback(4), ..., ...
		ConverterPDFs2CON.ID, c_0.getCallback(5), ..., ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, c_0.getCallback(9), ..., ...
		ConverterPDFs2CON.METHOD, c_0.getCallback(10), ..., ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, c_0.getCallback(11), ..., ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, c_0.getCallback(16) ... ...
		);
	 
	c_copy = c.copy();
	c_0_copy = c_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
		value = c.getr(prop);
		value_copy = c_copy.getr(prop);
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterPDFs2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterPDFs2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == c_0.getCallback(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The callback should be obtained from ConverterPDFs2CON.getCallback().' ...
						)
					assert( ...
						value_copy == c_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The callback should be obtained from ConverterPDFs2CON.getCallback().' ...
						)
				end
	 
					assert( ...
						c_copy.isLocked(prop) == c.isLocked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						c_copy.isChecked(prop) == c.isChecked(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						c_copy.getPropSeed(prop) == c.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c_template = ConverterPDFs2CON();
	c = ConverterPDFs2CON('TEMPLATE', c_template);
	 
	for prop = 1:1:ConverterPDFs2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterPDFs2CON.TEMPLATE ConverterPDFs2CON.GRAPH_TEMPLATE ConverterPDFs2CON.ANALYSIS ConverterPDFs2CON.G_DICT])
			continue
		end
	 
		TAG = upper(ConverterPDFs2CON.getPropTag(prop));
		switch ConverterPDFs2CON.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ConverterPDFs2CON.TEMPLATE
					assert( ...
						isa(c.getr(prop), 'ConverterPDFs2CON'), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON.getr(''TEMPLATE'') should be a ConverterPDFs2CON element.' ...
						)
					assert( ...
						isa(c_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(c.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						c.getr(prop).get('EL') == c_template && c.getr(prop).get('PROP') == prop && strcmp(c.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON.getr(' TAG ') should be a Callback to c_template.' TAG '.'] ...
						)
					assert( ...
						isa(c_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(c.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(c_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterPDFs2CON TEMPLATE does not work. ConverterPDFs2CON_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'converterpdfs2con_to_be_erased.b2'];
	 
	Element.save(c, filename)
	 
	c_loaded = Element.load(filename);
	 
	assert( ...
		isequal(c.copy(), c_loaded), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.save(c) and/or ConverterPDFs2CON.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	c = ConverterPDFs2CON( ...
		ConverterPDFs2CON.ELCLASS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.NAME, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.DESCRIPTION, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.TEMPLATE), ...
		ConverterPDFs2CON.ID, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.ID), ...
		ConverterPDFs2CON.LABEL, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.LABEL), ...
		ConverterPDFs2CON.NOTES, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.NOTES), ...
		ConverterPDFs2CON.TOSTRING, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_PDFS, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GR_PDFS), ...
		ConverterPDFs2CON.METHOD, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.METHOD), ...
		ConverterPDFs2CON.GRAPH_TEMPLATE, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.GRAPH_TEMPLATE), ...
		ConverterPDFs2CON.ANALYSIS, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.G_DICT, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.GR_CON, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.BA, ConverterPDFs2CON.getNoValue(), ...
		ConverterPDFs2CON.WAITBAR, ConverterPDFs2CON.getPropDefault(ConverterPDFs2CON.WAITBAR) ...
		);
	 
	[json, struct, el_list] = encodeJSON(c);
	[c_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(c_dec ~= c, ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterPDFs2CON.encodeJSON() or ConverterPDFs2CON.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ConverterPDFs2CON.getPropFormat(prop), num2cell(ConverterPDFs2CON.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ConverterPDFs2CON.getPropFormat(prop), num2cell(ConverterPDFs2CON.getProps())) == Format.NET)
		assert(isequal(c_dec, c), ...
			[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterPDFs2CON.encodeJSON() or ConverterPDFs2CON.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Convert SubjectFUN PDFs to SubjectCON using correlation
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ba = BrainAtlas( ...
	    'BR_DICT', IndexedDictionary( ...
	        'IT_CLASS', 'BrainRegion', ...
	        'IT_LIST', { ...
	            BrainRegion('ID', 'BR1'), ...
	            BrainRegion('ID', 'BR2'), ...
	            BrainRegion('ID', 'BR3') ...
	            } ...
	        ) ...
	    );
	
	gr_pdfs = Group( ...
	    'SUB_CLASS', 'SubjectFUN', ...
	    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectFUN') ...
	    );
	
	for i = 1:3
	    sub = SubjectFUN( ...
	        'ID', ['sub-' int2str(i)], ...
	        'BA', ba, ...
	        'FUN', rand(100, 3) ...
	        );
	
	    gr_pdfs.get('SUB_DICT').get('ADD', sub)
	end
	
	c = ConverterPDFs2CON( ...
	    'GR_PDFS', gr_pdfs, ...
	    'METHOD', 'correlation', ...
	    'WAITBAR', false ...
	    );
	
	gr_con = c.get('GR_CON');
	
	assert(isequal(gr_con.get('SUB_DICT').get('LENGTH'), 3), ...
	    'The converted SubjectCON group should contain 3 subjects.')
	
	sub_con = gr_con.get('SUB_DICT').get('IT', 1);
	
	assert(isequal(size(sub_con.get('CON')), [3 3]), ...
	    'The converted connectivity matrix should be 3-by-3.')
end

%% Test 13: Convert SubjectFUN PDFs to SubjectCON using Jensen-Shannon similarity
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	ba = BrainAtlas( ...
	    'BR_DICT', IndexedDictionary( ...
	        'IT_CLASS', 'BrainRegion', ...
	        'IT_LIST', { ...
	            BrainRegion('ID', 'BR1'), ...
	            BrainRegion('ID', 'BR2'), ...
	            BrainRegion('ID', 'BR3') ...
	            } ...
	        ) ...
	    );
	
	gr_pdfs = Group( ...
	    'SUB_CLASS', 'SubjectFUN', ...
	    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectFUN') ...
	    );
	
	for i = 1:3
	    pdf_data = rand(100, 3);
	    pdf_data = pdf_data ./ sum(pdf_data, 1);
	
	    sub = SubjectFUN( ...
	        'ID', ['sub-' int2str(i)], ...
	        'BA', ba, ...
	        'FUN', pdf_data ...
	        );
	
	    gr_pdfs.get('SUB_DICT').get('ADD', sub)
	end
	
	c = ConverterPDFs2CON( ...
	    'GR_PDFS', gr_pdfs, ...
	    'METHOD', 'jensen-shannon', ...
	    'WAITBAR', false ...
	    );
	
	gr_con = c.get('GR_CON');
	
	assert(isequal(gr_con.get('SUB_DICT').get('LENGTH'), 3), ...
	    'The converted SubjectCON group should contain 3 subjects.')
	
	sub_con = gr_con.get('SUB_DICT').get('IT', 1);
	A = sub_con.get('CON');
	
	assert(isequal(size(A), [3 3]), ...
	    'The converted connectivity matrix should be 3-by-3.')
	
	assert(max(abs(A - A'), [], 'all') < 1e-12, ...
	    'The Jensen-Shannon connectivity matrix should be symmetric.')
	
	assert(all(A(:) >= 0) && all(A(:) <= 1), ...
	    'The Jensen-Shannon connectivity values should be in the range [0, 1].')
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ConverterPDFs2CON:' BRAPH2.FAIL_TEST], ...
		[' When testing ConverterPDFs2CON no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

