%EXAMPLE_CREATE_TWO_SIMULATED_GROUPS
% Script example pipeline creating two simulated T1w GM probability NIfTI
% groups and converting them to structural regional values.
clear variables %#ok<*NASGU>

%% Setup paths
base_dir = fileparts(which('example_mahalanobis_ST_2_CON'));

atlas_dir = [fileparts(which('ConverterNeuroimaging2RegionalValues')) ...
    filesep 'Example atlases NIfTI'];

atlas_path = [atlas_dir filesep 'aal120_atlas.nii'];
atlas_xlsx = [atlas_dir filesep 'aal120_atlas.xlsx'];
atlas_mapping_file = [atlas_dir filesep 'aal120_atlas_mapping.csv'];

reference_nifti_dir = [base_dir filesep 'Example data NIfTI reference group'];
target_nifti_dir = [base_dir filesep 'Example data NIfTI target group'];

reference_st_dir = [base_dir filesep 'Converted data structural T1w reference group'];
target_st_dir = [base_dir filesep 'Converted data structural T1w target group'];

%% Load BrainAtlas
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', atlas_xlsx, ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

%% Define converted brain regions
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in AAL120

for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID'); %#ok<SAGROW>
end

%% Create two simulated NIfTI groups
rng(42)

reference_covarying_roi_indices = sort(randperm(94, 20));
target_covarying_roi_indices = sort(reference_covarying_roi_indices(randperm(numel(reference_covarying_roi_indices), 5)));

if ~isfolder(reference_nifti_dir)
    create_data_NIfTI_GMProb( ...
        atlas_path, ...
        reference_nifti_dir, ...
        {'Reference'}, ...
        20, ...
        42, ...
        reference_covarying_roi_indices ...
        );
end

if ~isfolder(target_nifti_dir)
    create_data_NIfTI_GMProb( ...
        atlas_path, ...
        target_nifti_dir, ...
        {'Target'}, ...
        10, ...
        43, ...
        target_covarying_roi_indices ...
        );
end

%% Convert reference NIfTI group to structural regional values
im_gr_reference_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', reference_nifti_dir, ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

gr_reference_gmprob = im_gr_reference_gm.get('GR');

cn_reference = ConverterNeuroimaging2RegionalValues( ...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {atlas_path}, ...
    'BA_MAPPING_FILES', {atlas_mapping_file}, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_reference_gmprob, ...
    'WAITBAR', true ...
    );

gr_reference_st = cn_reference.get('GR_ST');
ba_st = cn_reference.get('BA');

if ~isfolder(reference_st_dir)
    mkdir(reference_st_dir);
end

file = [reference_st_dir filesep 'group_subjects_VOLUME.xlsx'];
ex = ExporterGroupSubjectST_XLS( ...
    'FILE', file, ...
    'GR', gr_reference_st ...
    );
ex.get('SAVE');

file_ba = [reference_st_dir filesep 'brain_atlas.xlsx'];
ex = ExporterBrainAtlasXLS( ...
    'FILE', file_ba, ...
    'BA', ba_st ...
    );
ex.get('SAVE');

%% Convert target NIfTI group to structural regional values
im_gr_target_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', target_nifti_dir, ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

gr_target_gmprob = im_gr_target_gm.get('GR');

cn_target = ConverterNeuroimaging2RegionalValues( ...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {atlas_path}, ...
    'BA_MAPPING_FILES', {atlas_mapping_file}, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_target_gmprob, ...
    'WAITBAR', true ...
    );

gr_target_st = cn_target.get('GR_ST');
ba_st = cn_target.get('BA');

if ~isfolder(target_st_dir)
    mkdir(target_st_dir);
end

file = [target_st_dir filesep 'group_subjects_VOLUME.xlsx'];
ex = ExporterGroupSubjectST_XLS( ...
    'FILE', file, ...
    'GR', gr_target_st ...
    );
ex.get('SAVE');

file_ba = [target_st_dir filesep 'brain_atlas.xlsx'];
ex = ExporterBrainAtlasXLS( ...
    'FILE', file_ba, ...
    'BA', ba_st ...
    );
ex.get('SAVE');

%% Verification
assert(isequal(gr_reference_st.get('SUB_DICT').get('LENGTH'), 20), ...
    'Verification failed: reference structural group should contain 20 subjects.')

assert(isequal(gr_target_st.get('SUB_DICT').get('LENGTH'), 10), ...
    'Verification failed: target structural group should contain 10 subjects.')

assert(isequal(ba_st.get('BR_DICT').get('LENGTH'), numel(brain_regions_to_convert)), ...
    'Verification failed: converted atlas does not match the number of selected brain regions.')

fprintf('Verification passed: two structural regional-value groups were created.\n');
fprintf('Reference group subjects: %d\n', gr_reference_st.get('SUB_DICT').get('LENGTH'));
fprintf('Target group subjects: %d\n', gr_target_st.get('SUB_DICT').get('LENGTH'));
fprintf('Reference covarying ROI indices: %s\n', mat2str(reference_covarying_roi_indices));
fprintf('Target covarying ROI indices: %s\n', mat2str(target_covarying_roi_indices));
