%EXAMPLE_MAHALANOBIS_ST_2_CON
% Script example pipeline structural regional values conversion to
% individual connectivity data using the Mahalanobis approach.
clear variables %#ok<*NASGU>

%% Create / load structural regional-value dataset
example_data_dir = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Converted data structural T1w'];

if ~isfolder(example_data_dir)
    example_NEUROIMAGING_2_RVs_T1W
    example_data_dir = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Converted data structural T1w'];
end

%% Load BrainAtlas
atlas_file = [example_data_dir filesep 'brain_atlas.xlsx'];

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', atlas_file, ...
    'WAITBAR', true ...
    );

ba = im_ba.get('BA');

%% Load Group of SubjectST with regional values
group_file = [example_data_dir filesep 'group_subjects_VOLUME.xlsx'];

im_gr = ImporterGroupSubjectST_XLS( ...
    'FILE', group_file, ...
    'BA', ba, ...
    'WAITBAR', true ...
    );

gr_st = im_gr.get('GR');

%% Split SubjectST group into reference and target groups
% For this example:
%   - first half  = reference group
%   - second half = target group to convert into individual connectomes
%
% In real use, the reference group should normally be the control group.

sub_dict_st = gr_st.get('SUB_DICT');
subject_number = sub_dict_st.get('LENGTH');

if subject_number < 4
    error('This example requires at least 4 subjects to split into reference and target groups.')
end

reference_idx = 1:floor(subject_number / 2);
target_idx = floor(subject_number / 2) + 1:subject_number;

gr_reference = Group( ...
    'ID', 'Reference group', ...
    'LABEL', 'Reference group', ...
    'NOTES', 'Reference subjects used to estimate the Mahalanobis population model.', ...
    'SUB_CLASS', 'SubjectST', ...
    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST') ...
    );

gr_target = Group( ...
    'ID', 'Target group', ...
    'LABEL', 'Target group', ...
    'NOTES', 'Target subjects converted into Mahalanobis individual connectomes.', ...
    'SUB_CLASS', 'SubjectST', ...
    'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST') ...
    );

sub_dict_reference = gr_reference.memorize('SUB_DICT');
sub_dict_target = gr_target.memorize('SUB_DICT');

for i = reference_idx
    sub_st = sub_dict_st.get('IT', i);

    sub_reference = SubjectST( ...
        'ID', sub_st.get('ID'), ...
        'LABEL', sub_st.get('LABEL'), ...
        'NOTES', sub_st.get('NOTES'), ...
        'BA', sub_st.get('BA'), ...
        'ST', sub_st.get('ST'), ...
        'VOI_DICT', sub_st.get('VOI_DICT') ...
        );

    sub_dict_reference.get('ADD', sub_reference);
end

for i = target_idx
    sub_st = sub_dict_st.get('IT', i);

    sub_target = SubjectST( ...
        'ID', sub_st.get('ID'), ...
        'LABEL', sub_st.get('LABEL'), ...
        'NOTES', sub_st.get('NOTES'), ...
        'BA', sub_st.get('BA'), ...
        'ST', sub_st.get('ST'), ...
        'VOI_DICT', sub_st.get('VOI_DICT') ...
        );

    sub_dict_target.get('ADD', sub_target);
end

%% Convert regional values to individual connectomes
cn = ConverterST2CON( ...
    'GR_ST', gr_target, ...
    'GR_REFERENCE', gr_reference, ...
    'METHOD', 'mahalanobis', ...
    'WAITBAR', true ...
    );

gr_con = cn.get('GR_CON');

%% Export data
directory_base = [fileparts(which('example_mahalanobis_ST_2_CON')) filesep 'Converted CON data Mahalanobis'];

if ~isfolder(directory_base)
    mkdir(directory_base);
end

ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', directory_base, ...
    'GR', gr_con ...
    );

ex.get('SAVE');

file = [directory_base filesep 'brain_atlas.xlsx'];

ex = ExporterBrainAtlasXLS( ...
    'FILE', file, ...
    'BA', ba ...
    );

ex.get('SAVE');

%% Verification
sub_dict_con = gr_con.get('SUB_DICT');
target_number = gr_target.get('SUB_DICT').get('LENGTH');

assert(isequal(sub_dict_con.get('LENGTH'), target_number), ...
    'Verification failed: converted CON group and target ST group have different numbers of subjects.')

sub_con = sub_dict_con.get('IT', 1);
con = sub_con.get('CON');

br_number = ba.get('BR_DICT').get('LENGTH');

assert(isequal(size(con), [br_number br_number]), ...
    'Verification failed: individual connectome size does not match the brain atlas size.')

assert(all(~isnan(con(:))), ...
    'Verification failed: Mahalanobis individual connectome contains NaN values.')

assert(isequal(con, con'), ...
    'Verification failed: Mahalanobis individual connectome is not symmetric.')

fprintf('Verification passed: Mahalanobis ST-to-CON conversion generated %d individual connectomes.\n', ...
    sub_dict_con.get('LENGTH'));
