%TEST_CONVERTERST2CON

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	cn = ConverterST2CON();
	 
	% get('ELCLASS')
	if isa(ConverterST2CON, 'ConcreteElement')
		assert(strcmp(ConverterST2CON().get('ELCLASS'), 'ConverterST2CON'), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON().get(''ELCLASS'') should return ''ConverterST2CON''.')
	end
	 
	% getBuild()
	assert(ConverterST2CON.getBuild() == 1 && ConverterST2CON.getBuild() > 0, ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getBuild() should return the ConverterST2CON build number.')
	assert(cn.getBuild() == 1 && cn.getBuild() > 0 , ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getBuild() should return the ConverterST2CON build number.')
	assert(Element.getBuild(cn) == 1 && Element.getBuild(cn) > 0, ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(cn) should return the ConverterST2CON build number.')
	assert(Element.getBuild('ConverterST2CON') == 1 && Element.getBuild('ConverterST2CON') > 0, ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ConverterST2CON'') should return the ConverterST2CON build number.')
	 
	% getClass()
	assert(strcmp(ConverterST2CON.getClass(), 'ConverterST2CON'), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getClass() should return ''ConverterST2CON''.')
	assert(strcmp(cn.getClass(), 'ConverterST2CON'), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getClass() should return ''ConverterST2CON''.')
	assert(strcmp(Element.getClass(cn), 'ConverterST2CON'), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(cn) should return ''ConverterST2CON''.')
	assert(strcmp(Element.getClass('ConverterST2CON'), 'ConverterST2CON'), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ConverterST2CON'') should return ''ConverterST2CON''.')
	 
	% getSubclasses()
	assert(isequal(ConverterST2CON.getSubclasses(), subclasses('ConverterST2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getSubclasses() should return the same result as subclasses(''ConverterST2CON'', [], [], true).')
	assert(isequal(cn.getSubclasses(), subclasses('ConverterST2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ConverterST2CON'', [], [], true).')
	assert(isequal(Element.getSubclasses(cn), subclasses('ConverterST2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(cn) should return the same result as subclasses(''ConverterST2CON'', [], [], true).')
	assert(isequal(Element.getSubclasses('ConverterST2CON'), subclasses('ConverterST2CON', [], [], true)), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ConverterST2CON'') should return the same result as subclasses(''ConverterST2CON'', [], [], true).')
	 
	% getProps()
	assert(isempty(ConverterST2CON.getProps()) || isequal(ConverterST2CON.getProps(), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterST2CON.getProps()) || isequal(cn.getProps(), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConverterST2CON.getProps()) || isequal(Element.getProps(cn), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(cn) should return a row vector [1:1:N].')
	assert(isempty(ConverterST2CON.getProps()) || isequal(Element.getProps('ConverterST2CON'), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterST2CON'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ConverterST2CON.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterST2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getProps(category) does not work.')
	tmp = cellfun(@(category) cn.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConverterST2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(cn, category), categories, 'UniformOutput', false);
	assert(isempty(ConverterST2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(cn, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ConverterST2CON', category), categories, 'UniformOutput', false);
	assert(isempty(ConverterST2CON.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConverterST2CON.getProps())), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConverterST2CON'', category) does not work.')
	 
	% getPropNumber()
	assert(ConverterST2CON.getPropNumber() == length(ConverterST2CON.getProps()), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getPropNumber() should return the number of properties.')
	assert(cn.getPropNumber() == length(ConverterST2CON.getProps()), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(cn) == length(ConverterST2CON.getProps()), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(cn) should return the number of properties.')
	assert(Element.getPropNumber('ConverterST2CON') == length(ConverterST2CON.getProps()), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterST2CON'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ConverterST2CON.getPropNumber(category), categories)) == ConverterST2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) cn.getPropNumber(category), categories)) == ConverterST2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(cn, category), categories)) == ConverterST2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(cn, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ConverterST2CON', category), categories)) == ConverterST2CON.getPropNumber(), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConverterST2CON'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ConverterST2CON.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.existsProp(prop) does not work.')
	assert(~cn.existsProp(NaN), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.existsProp(prop) does not work.')
	assert(~Element.existsProp(cn, NaN), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(cn, prop) does not work.')
	assert(~Element.existsProp('ConverterST2CON', NaN), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ConverterST2CON'', prop) does not work.')
	 
	assert_with_error('ConverterST2CON.existsProp(NaN)', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsProp(''ConverterST2CON'', NaN)', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		assert(ConverterST2CON.existsProp(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.existsProp(prop) does not work.')
		assert(cn.existsProp(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.existsProp(prop) does not work.')
		assert(Element.existsProp(cn, prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(cn, prop) does not work.')
		assert(Element.existsProp('ConverterST2CON', prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ConverterST2CON'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ConverterST2CON.existsTag(''), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.existsTag(tag) does not work.')
	assert(~cn.existsTag(''), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'cn.existsTag(tag) does not work.')
	assert(~Element.existsTag(cn, ''), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(cn, tag) does not work.')
	assert(~Element.existsTag('ConverterST2CON', ''), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ConverterST2CON'', tag) does not work.')
	 
	assert_with_error('ConverterST2CON.existsTag('''')', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], cn)
	assert_with_error('Element.existsTag(''ConverterST2CON'', '''')', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
		assert(ConverterST2CON.existsTag(tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.existsTag(tag) does not work.')
		assert(cn.existsTag(tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.existsTag(tag) does not work.')
		assert(Element.existsTag(cn, tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(cn, tga) does not work.')
		assert(Element.existsTag('ConverterST2CON', tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		assert(ConverterST2CON.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropProp(prop) does not work.')
		assert(cn.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropProp(prop) does not work.')
		assert(Element.getPropProp(cn, prop) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(cn, prop) does not work.')
		assert(Element.getPropProp('ConverterST2CON', prop) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterST2CON'', prop) does not work.')
	 
		tag = cn.getPropTag(prop);
		assert(ConverterST2CON.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropProp(tag) does not work.')
		assert(cn.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropProp(tag) does not work.')
		assert(Element.getPropProp(cn, tag) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(cn, tag) does not work.')
		assert(Element.getPropProp('ConverterST2CON', prop) == prop, ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(strcmp(ConverterST2CON.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropTag(prop) does not work.')
		assert(strcmp(cn.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(cn, prop), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(cn, prop) does not work.')
		assert(strcmp(Element.getPropTag('ConverterST2CON', prop), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterST2CON'', prop) does not work.')
	 
		assert(strcmp(ConverterST2CON.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropTag(tag) does not work.')
		assert(strcmp(cn.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(cn, tag), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(cn, tag) does not work.')
		assert(strcmp(Element.getPropTag('ConverterST2CON', prop), tag), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(Category.existsCategory(ConverterST2CON.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(cn.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(cn, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterST2CON'', prop) does not work.')
	 
		assert(Category.existsCategory(ConverterST2CON.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(cn.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(cn, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(Format.existsFormat(ConverterST2CON.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(cn.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(cn, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterST2CON'', prop) does not work.')
	 
		assert(Format.existsFormat(ConverterST2CON.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(cn.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(cn, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(ischar(ConverterST2CON.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropDescription(prop) does not work.')
		assert(ischar(cn.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(cn, prop) does not work.')
		assert(ischar(Element.getPropDescription(cn, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterST2CON'', prop) does not work.')
	 
		assert(ischar(ConverterST2CON.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.getPropDescription(tag) does not work.')
		assert(ischar(cn.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(cn, tag) does not work.')
		assert(ischar(Element.getPropDescription(cn, tag)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConverterST2CON'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		settings = ConverterST2CON.getPropSettings(prop);
		settings = cn.getPropSettings(prop);
		settings = Element.getPropSettings(cn, prop);
		settings = Element.getPropSettings('ConverterST2CON', prop);
	 
		settings = ConverterST2CON.getPropSettings(tag);
		settings = cn.getPropSettings(tag);
		settings = Element.getPropSettings(cn, tag);
		settings = Element.getPropSettings('ConverterST2CON', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		default = ConverterST2CON.getPropDefault(prop);
		default = cn.getPropDefault(prop);
		default = Element.getPropDefault(cn, prop);
		default = Element.getPropDefault('ConverterST2CON', prop);
	 
		default = ConverterST2CON.getPropDefault(tag);
		default = cn.getPropDefault(tag);
		default = Element.getPropDefault(cn, tag);
		default = Element.getPropDefault('ConverterST2CON', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		conditioned_default = ConverterST2CON.getPropDefaultConditioned(prop);
		conditioned_default = cn.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(cn, prop);
		conditioned_default = Element.getPropDefaultConditioned('ConverterST2CON', prop);
	 
		conditioned_default = ConverterST2CON.getPropDefaultConditioned(tag);
		conditioned_default = cn.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(cn, tag);
		conditioned_default = Element.getPropDefaultConditioned('ConverterST2CON', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ConverterST2CON.getPropNumber()
		tag = cn.getPropTag(prop);
	 
		assert(~ConverterST2CON.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.checkProp(prop, value) does not work.')
		assert(~cn.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(cn, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, prop, value) does not work.')
		assert(~Element.checkProp('ConverterST2CON', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterST2CON'', prop, value) does not work.')
	 
		assert_with_error('ConverterST2CON.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], prop, cn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], prop, cn)
		assert_with_error('Element.checkProp(''ConverterST2CON'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ConverterST2CON.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.checkProp(tag, value) does not work.')
		assert(~cn.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(cn, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, tag, value) does not work.')
		assert(~Element.checkProp('ConverterST2CON', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterST2CON'', tag, value) does not work.')
	 
		assert_with_error('ConverterST2CON.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], tag, cn)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], tag, cn)
		assert_with_error('Element.checkProp(''ConverterST2CON'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConverterST2CON:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ConverterST2CON.checkProp(prop, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.checkProp(prop, <conditioned default value>) does not work.')
		assert(cn.checkProp(prop, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(cn, prop, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterST2CON', prop, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterST2CON'', prop, <conditioned default value>) does not work.')
	 
		assert(ConverterST2CON.checkProp(tag, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.checkProp(tag, <conditioned default value>) does not work.')
		assert(cn.checkProp(tag, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'cn.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(cn, tag, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(cn, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConverterST2CON', tag, Element.getPropDefaultConditioned(ConverterST2CON, prop)), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConverterST2CON'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterST2CON.ST_MATRIX ConverterST2CON.ST_REF_MATRIX ConverterST2CON.VOI_MATRIX ConverterST2CON.VOI_REF_MATRIX ConverterST2CON.EXTRACT_VOI_MATRIX ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT ConverterST2CON.MAHALANOBIS_CONNECTOMES ConverterST2CON.PERTURBATION_CONNECTOMES ConverterST2CON.CONNECTOMES])
			continue
		end
	 
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					cn.getr(prop) == ConverterST2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterST2CON.getCategoryName(ConverterST2CON.getPropCategory(prop)) ', ConverterST2CON.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterST2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					cn.getr(TAG) == ConverterST2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterST2CON.getCategoryName(ConverterST2CON.getPropCategory(prop)) ', ConverterST2CON.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterST2CON.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(cn.getPropSettings(prop))
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop)), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop), cn.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					cn.getr(prop) == ConverterST2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterST2CON.getCategoryName(ConverterST2CON.getPropCategory(prop)) ', ConverterST2CON.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterST2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					cn.getr(TAG) == ConverterST2CON.getNoValue(), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConverterST2CON.getCategoryName(ConverterST2CON.getPropCategory(prop)) ', ConverterST2CON.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConverterST2CON.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ConverterST2CON']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(cn.getPropSettings(prop))
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop)), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						cn.checkFormat(cn.getPropFormat(prop), cn.get(prop), cn.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(cn.getr(prop), ConverterST2CON.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ConverterST2CON.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterST2CON.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(cn.getr(TAG), ConverterST2CON.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ConverterST2CON.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConverterST2CON.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterST2CON.ST_MATRIX ConverterST2CON.ST_REF_MATRIX ConverterST2CON.VOI_MATRIX ConverterST2CON.VOI_REF_MATRIX ConverterST2CON.EXTRACT_VOI_MATRIX ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT ConverterST2CON.MAHALANOBIS_CONNECTOMES ConverterST2CON.PERTURBATION_CONNECTOMES ConverterST2CON.CONNECTOMES])
			continue
		end
	 
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(cn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterST2CON']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConverterST2CON']);
	% 			assert( ...
	% 				~isa(cn.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterST2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(cn.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterST2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
	% 				['ConverterST2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ConverterST2CON']);
				assert( ...
					~isa(cn.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(cn.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					cn.checkFormat(cn.getPropFormat(prop), cn.getr(prop),cn.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if cn.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ConverterST2CON');
					delete(ancestor(cn.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ConverterST2CON.getProps(Category.RESULT))
		for prop = 1:1:ConverterST2CON.getPropNumber()
	 
			% excluded props
			if any(prop == [ConverterST2CON.ST_MATRIX ConverterST2CON.ST_REF_MATRIX ConverterST2CON.VOI_MATRIX ConverterST2CON.VOI_REF_MATRIX ConverterST2CON.EXTRACT_VOI_MATRIX ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT ConverterST2CON.MAHALANOBIS_CONNECTOMES ConverterST2CON.PERTURBATION_CONNECTOMES ConverterST2CON.CONNECTOMES])
				continue
			end
	 
			switch ConverterST2CON.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON();
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		TAG = upper(ConverterST2CON.getPropTag(prop));
		assert( ...
			~cn.isLocked(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~cn.isLocked(TAG), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	cn.lock()
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON();
	 
	warning_backup = warning('off', 'BRAPH2:ConverterST2CON');
	for prop = 1:1:ConverterST2CON.getPropNumber()
		cn.lock(prop)
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON();
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		TAG = upper(ConverterST2CON.getPropTag(prop));
		assert( ...
			cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			cn.isChecked(TAG), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	cn.unchecked()
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		assert( ...
			~cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	cn.checked()
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		assert( ...
			cn.isChecked(prop), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			['ConverterST2CON.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ConverterST2CON
	cn_0 = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	% ConverterST2CON with 1st callbacks
	cn_1 = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, cn_0.getCallback(4), ..., ...
		ConverterST2CON.ID, cn_0.getCallback(5), ..., ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, cn_0.getCallback(9), ..., ...
		ConverterST2CON.GR_REFERENCE, cn_0.getCallback(10), ..., ...
		ConverterST2CON.METHOD, cn_0.getCallback(11), ..., ...
		ConverterST2CON.REFERENCE_MODE, cn_0.getCallback(12), ..., ...
		ConverterST2CON.VOI_SELECTION, cn_0.getCallback(13), ..., ...
		ConverterST2CON.PERTURBATION_RULE, cn_0.getCallback(14), ..., ...
		ConverterST2CON.REGULARIZATION, cn_0.getCallback(15), ..., ...
		ConverterST2CON.OUTPUT_RULE, cn_0.getCallback(16), ..., ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, cn_0.getCallback(29) ... ...
		);
	 
	prop_number = ConverterST2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_1.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterST2CON with 2nd callbacks
	cn_2 = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, cn_1.getCallback(4), ..., ...
		ConverterST2CON.ID, cn_1.getCallback(5), ..., ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, cn_1.getCallback(9), ..., ...
		ConverterST2CON.GR_REFERENCE, cn_1.getCallback(10), ..., ...
		ConverterST2CON.METHOD, cn_1.getCallback(11), ..., ...
		ConverterST2CON.REFERENCE_MODE, cn_1.getCallback(12), ..., ...
		ConverterST2CON.VOI_SELECTION, cn_1.getCallback(13), ..., ...
		ConverterST2CON.PERTURBATION_RULE, cn_1.getCallback(14), ..., ...
		ConverterST2CON.REGULARIZATION, cn_1.getCallback(15), ..., ...
		ConverterST2CON.OUTPUT_RULE, cn_1.getCallback(16), ..., ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, cn_1.getCallback(29) ... ...
		);
	 
	prop_number = ConverterST2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_2.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConverterST2CON with 3rd callbacks
	cn_3 = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, cn_2.getCallback(4), ..., ...
		ConverterST2CON.ID, cn_2.getCallback(5), ..., ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, cn_2.getCallback(9), ..., ...
		ConverterST2CON.GR_REFERENCE, cn_2.getCallback(10), ..., ...
		ConverterST2CON.METHOD, cn_2.getCallback(11), ..., ...
		ConverterST2CON.REFERENCE_MODE, cn_2.getCallback(12), ..., ...
		ConverterST2CON.VOI_SELECTION, cn_2.getCallback(13), ..., ...
		ConverterST2CON.PERTURBATION_RULE, cn_2.getCallback(14), ..., ...
		ConverterST2CON.REGULARIZATION, cn_2.getCallback(15), ..., ...
		ConverterST2CON.OUTPUT_RULE, cn_2.getCallback(16), ..., ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, cn_2.getCallback(29) ... ...
		);
	 
	prop_number = ConverterST2CON.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(cn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(cn_3.get(prop), cn_0.get(prop)) && ~isa(cn_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(cn_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	cn = ConverterST2CON();
	 
	cn_copy = cn.copy();
	 
	assert(cn_copy ~= cn, ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(cn_copy, cn), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					cn_copy.isLocked(prop) == cn.isLocked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					cn_copy.isChecked(prop) == cn.isChecked(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		if ConverterST2CON.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ConverterST2CON']);
			% cn.memorize(prop);
			% warning(warning_backup)
		elseif ConverterST2CON.getPropCategory(prop) == Category.EVANESCENT && cn.getPropFormat(prop) == Format.HANDLE
			cn.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ConverterST2CON');
			delete(ancestor(cn.get(prop), 'figure'))
			warning(warning_backup)
		else
			cn.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	cn_copy = cn.copy();
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						cn_copy.isLocked(prop) == cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.isChecked(prop) == cn.isChecked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	cn_0 = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, cn_0.getCallback(4), ..., ...
		ConverterST2CON.ID, cn_0.getCallback(5), ..., ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, cn_0.getCallback(9), ..., ...
		ConverterST2CON.GR_REFERENCE, cn_0.getCallback(10), ..., ...
		ConverterST2CON.METHOD, cn_0.getCallback(11), ..., ...
		ConverterST2CON.REFERENCE_MODE, cn_0.getCallback(12), ..., ...
		ConverterST2CON.VOI_SELECTION, cn_0.getCallback(13), ..., ...
		ConverterST2CON.PERTURBATION_RULE, cn_0.getCallback(14), ..., ...
		ConverterST2CON.REGULARIZATION, cn_0.getCallback(15), ..., ...
		ConverterST2CON.OUTPUT_RULE, cn_0.getCallback(16), ..., ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, cn_0.getCallback(29) ... ...
		);
	 
	cn_copy = cn.copy();
	cn_0_copy = cn_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
		value = cn.getr(prop);
		value_copy = cn_copy.getr(prop);
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					'ConverterST2CON.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
							'ConverterST2CON.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == cn_0.getCallback(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The callback should be obtained from ConverterST2CON.getCallback().' ...
						)
					assert( ...
						value_copy == cn_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The callback should be obtained from ConverterST2CON.getCallback().' ...
						)
				end
	 
					assert( ...
						cn_copy.isLocked(prop) == cn.isLocked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.isChecked(prop) == cn.isChecked(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						cn_copy.getPropSeed(prop) == cn.getPropSeed(prop), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn_template = ConverterST2CON();
	cn = ConverterST2CON('TEMPLATE', cn_template);
	 
	for prop = 1:1:ConverterST2CON.getPropNumber()
	 
		% excluded props
		if any(prop == [ConverterST2CON.ST_MATRIX ConverterST2CON.ST_REF_MATRIX ConverterST2CON.VOI_MATRIX ConverterST2CON.VOI_REF_MATRIX ConverterST2CON.EXTRACT_VOI_MATRIX ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT ConverterST2CON.MAHALANOBIS_CONNECTOMES ConverterST2CON.PERTURBATION_CONNECTOMES ConverterST2CON.CONNECTOMES])
			continue
		end
	 
		TAG = upper(ConverterST2CON.getPropTag(prop));
		switch ConverterST2CON.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ConverterST2CON.TEMPLATE
					assert( ...
						isa(cn.getr(prop), 'ConverterST2CON'), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON TEMPLATE does not work. ConverterST2CON.getr(''TEMPLATE'') should be a ConverterST2CON element.' ...
						)
					assert( ...
						isa(cn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						'ConverterST2CON TEMPLATE does not work. ConverterST2CON_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(cn.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON TEMPLATE does not work. ConverterST2CON.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						cn.getr(prop).get('EL') == cn_template && cn.getr(prop).get('PROP') == prop && strcmp(cn.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON TEMPLATE does not work. ConverterST2CON.getr(' TAG ') should be a Callback to cn_template.' TAG '.'] ...
						)
					assert( ...
						isa(cn_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
						['ConverterST2CON TEMPLATE does not work. ConverterST2CON_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(cn.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON TEMPLATE does not work. ConverterST2CON.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(cn_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
					['ConverterST2CON TEMPLATE does not work. ConverterST2CON_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'converterst2con_to_be_erased.b2'];
	 
	Element.save(cn, filename)
	 
	cn_loaded = Element.load(filename);
	 
	assert( ...
		isequal(cn.copy(), cn_loaded), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.save(cn) and/or ConverterST2CON.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	cn = ConverterST2CON( ...
		ConverterST2CON.ELCLASS, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.NAME, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.DESCRIPTION, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.TEMPLATE, ConverterST2CON.getPropDefault(ConverterST2CON.TEMPLATE), ...
		ConverterST2CON.ID, ConverterST2CON.getPropDefault(ConverterST2CON.ID), ...
		ConverterST2CON.LABEL, ConverterST2CON.getPropDefault(ConverterST2CON.LABEL), ...
		ConverterST2CON.NOTES, ConverterST2CON.getPropDefault(ConverterST2CON.NOTES), ...
		ConverterST2CON.TOSTRING, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_ST, ConverterST2CON.getPropDefault(ConverterST2CON.GR_ST), ...
		ConverterST2CON.GR_REFERENCE, ConverterST2CON.getPropDefault(ConverterST2CON.GR_REFERENCE), ...
		ConverterST2CON.METHOD, ConverterST2CON.getPropDefault(ConverterST2CON.METHOD), ...
		ConverterST2CON.REFERENCE_MODE, ConverterST2CON.getPropDefault(ConverterST2CON.REFERENCE_MODE), ...
		ConverterST2CON.VOI_SELECTION, ConverterST2CON.getPropDefault(ConverterST2CON.VOI_SELECTION), ...
		ConverterST2CON.PERTURBATION_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.PERTURBATION_RULE), ...
		ConverterST2CON.REGULARIZATION, ConverterST2CON.getPropDefault(ConverterST2CON.REGULARIZATION), ...
		ConverterST2CON.OUTPUT_RULE, ConverterST2CON.getPropDefault(ConverterST2CON.OUTPUT_RULE), ...
		ConverterST2CON.BA, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.ST_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.VOI_REF_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.EXTRACT_VOI_MATRIX, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.REFERENCE_VOI_MATRIX_FOR_SUBJECT, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.MAHALANOBIS_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.PERTURBATION_CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.CONNECTOMES, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.GR_CON, ConverterST2CON.getNoValue(), ...
		ConverterST2CON.WAITBAR, ConverterST2CON.getPropDefault(ConverterST2CON.WAITBAR) ...
		);
	 
	[json, struct, el_list] = encodeJSON(cn);
	[cn_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(cn_dec ~= cn, ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		'ConverterST2CON.encodeJSON() or ConverterST2CON.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ConverterST2CON.getPropFormat(prop), num2cell(ConverterST2CON.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ConverterST2CON.getPropFormat(prop), num2cell(ConverterST2CON.getProps())) == Format.NET)
		assert(isequal(cn_dec, cn), ...
			[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
			'ConverterST2CON.encodeJSON() or ConverterST2CON.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Sanity check - Mahalanobis external reference
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', 'aal90_atlas.xlsx', 'WAITBAR', false);
	ba = im_ba.get('BA');
	
	region_number = 10;
	subject_number = 8;
	reference_number = 20;
	
	br_list = {};
	for i = 1:region_number
	    br_list{end + 1} = ba.get('BR_DICT').get('IT', i); %#ok<AGROW>
	end
	
	ba_test = BrainAtlas( ...
	    'ID', 'TestAtlas', ...
	    'BR_DICT', IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST', br_list) ...
	    );
	
	gr_st = Group('SUB_CLASS', 'SubjectST', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST'));
	
	for i = 1:subject_number
	    sub = SubjectST( ...
	        'ID', ['sub-' int2str(i)], ...
	        'BA', ba_test, ...
	        'ST', rand(region_number, 1) ...
	        );
	
	    gr_st.get('SUB_DICT').get('ADD', sub)
	end
	
	gr_reference = Group('SUB_CLASS', 'SubjectST', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST'));
	
	for i = 1:reference_number
	    sub = SubjectST( ...
	        'ID', ['ref-' int2str(i)], ...
	        'BA', ba_test, ...
	        'ST', rand(region_number, 1) ...
	        );
	
	    gr_reference.get('SUB_DICT').get('ADD', sub)
	end
	
	cn = ConverterST2CON( ...
	    'GR_ST', gr_st, ...
	    'GR_REFERENCE', gr_reference, ...
	    'METHOD', 'mahalanobis', ...
	    'REFERENCE_MODE', 'external', ...
	    'WAITBAR', false ...
	    );
	
	gr_con = cn.get('GR_CON');
	
	assert(isequal(gr_con.get('SUB_DICT').get('LENGTH'), subject_number), ...
	    'The converted group should contain the same number of subjects as GR_ST.')
	
	sub_con = gr_con.get('SUB_DICT').get('IT', 1);
	con = sub_con.get('CON');
	
	assert(isequal(size(con), [region_number region_number]), ...
	    'The converted connectivity matrix should have region_number-by-region_number size.')
	
	assert(isequal(con, con'), ...
	    'The Mahalanobis connectivity matrix should be symmetric.')
	
	assert(all(diag(con) == 0), ...
	    'The Mahalanobis connectivity matrix should have zero diagonal.')
end

%% Test 13: Sanity check - Paper-style perturbation external reference
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', 'aal90_atlas.xlsx', 'WAITBAR', false);
	ba = im_ba.get('BA');
	
	region_number = 10;
	subject_number = 8;
	reference_number = 20;
	
	br_list = {};
	for i = 1:region_number
	    br_list{end + 1} = ba.get('BR_DICT').get('IT', i); %#ok<AGROW>
	end
	
	ba_test = BrainAtlas( ...
	    'ID', 'TestAtlas', ...
	    'BR_DICT', IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST', br_list) ...
	    );
	
	gr_st = Group('SUB_CLASS', 'SubjectST', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST'));
	
	for i = 1:subject_number
	    sub = SubjectST( ...
	        'ID', ['sub-' int2str(i)], ...
	        'BA', ba_test, ...
	        'ST', rand(region_number, 1) ...
	        );
	
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 60 + i))
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', 1 + mod(i, 2)))
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Education', 'V', 12 + mod(i, 8)))
	
	    gr_st.get('SUB_DICT').get('ADD', sub)
	end
	
	gr_reference = Group('SUB_CLASS', 'SubjectST', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST'));
	
	for i = 1:reference_number
	    sub = SubjectST( ...
	        'ID', ['ref-' int2str(i)], ...
	        'BA', ba_test, ...
	        'ST', rand(region_number, 1) ...
	        );
	
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 60 + i))
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', 1 + mod(i, 2)))
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Education', 'V', 12 + mod(i, 8)))
	
	    gr_reference.get('SUB_DICT').get('ADD', sub)
	end
	
	cn = ConverterST2CON( ...
	    'GR_ST', gr_st, ...
	    'GR_REFERENCE', gr_reference, ...
	    'WAITBAR', false ...
	    );
	
	gr_con = cn.get('GR_CON');
	
	assert(isequal(gr_con.get('SUB_DICT').get('LENGTH'), subject_number), ...
	    'The converted group should contain the same number of subjects as GR_ST.')
	
	sub_con = gr_con.get('SUB_DICT').get('IT', 1);
	con = sub_con.get('CON');
	
	assert(isequal(size(con), [region_number region_number]), ...
	    'The converted connectivity matrix should have region_number-by-region_number size.')
	
	assert(isequal(con, con'), ...
	    'The perturbation connectivity matrix should be symmetric.')
	
	assert(all(diag(con) == 0), ...
	    'The perturbation connectivity matrix should have zero diagonal.')
end

%% Test 14: Sanity check - Perturbation leave-one-out
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', 'aal90_atlas.xlsx', 'WAITBAR', false);
	ba = im_ba.get('BA');
	
	region_number = 10;
	subject_number = 20;
	
	br_list = {};
	for i = 1:region_number
	    br_list{end + 1} = ba.get('BR_DICT').get('IT', i); %#ok<AGROW>
	end
	
	ba_test = BrainAtlas( ...
	    'ID', 'TestAtlas', ...
	    'BR_DICT', IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST', br_list) ...
	    );
	
	gr_st = Group('SUB_CLASS', 'SubjectST', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectST'));
	
	for i = 1:subject_number
	    sub = SubjectST( ...
	        'ID', ['sub-' int2str(i)], ...
	        'BA', ba_test, ...
	        'ST', rand(region_number, 1) ...
	        );
	
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 20 + i))
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', 1 + mod(i, 2)))
	
	    gr_st.get('SUB_DICT').get('ADD', sub)
	end
	
	cn = ConverterST2CON( ...
	    'GR_ST', gr_st, ...
	    'METHOD', 'perturbation', ...
	    'REFERENCE_MODE', 'leave-one-out', ...
	    'VOI_SELECTION', {'Age', 'Sex'}, ...
	    'PERTURBATION_RULE', 'absolute_difference', ...
	    'WAITBAR', false ...
	    );
	
	gr_con = cn.get('GR_CON');
	
	assert(isequal(gr_con.get('SUB_DICT').get('LENGTH'), subject_number), ...
	    'The converted group should contain the same number of subjects as GR_ST.')
	
	sub_con = gr_con.get('SUB_DICT').get('IT', 1);
	con = sub_con.get('CON');
	
	assert(isequal(size(con), [region_number region_number]), ...
	    'The converted connectivity matrix should have region_number-by-region_number size.')
	
	assert(isequal(con, con'), ...
	    'The perturbation connectivity matrix should be symmetric.')
	
	assert(all(diag(con) == 0), ...
	    'The perturbation connectivity matrix should have zero diagonal.')
end

%% Test 15: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ConverterST2CON:' BRAPH2.FAIL_TEST], ...
		[' When testing ConverterST2CON no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 16: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

