%TEST_CONSTRUCTORINDIVIDUALCONBASE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	base = ConstructorIndividualConBase();
	 
	% get('ELCLASS')
	if isa(ConstructorIndividualConBase, 'ConcreteElement')
		assert(strcmp(ConstructorIndividualConBase().get('ELCLASS'), 'ConstructorIndividualConBase'), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase().get(''ELCLASS'') should return ''ConstructorIndividualConBase''.')
	end
	 
	% getBuild()
	assert(ConstructorIndividualConBase.getBuild() == 1 && ConstructorIndividualConBase.getBuild() > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getBuild() should return the ConstructorIndividualConBase build number.')
	assert(base.getBuild() == 1 && base.getBuild() > 0 , ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getBuild() should return the ConstructorIndividualConBase build number.')
	assert(Element.getBuild(base) == 1 && Element.getBuild(base) > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(base) should return the ConstructorIndividualConBase build number.')
	assert(Element.getBuild('ConstructorIndividualConBase') == 1 && Element.getBuild('ConstructorIndividualConBase') > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ConstructorIndividualConBase'') should return the ConstructorIndividualConBase build number.')
	 
	% getClass()
	assert(strcmp(ConstructorIndividualConBase.getClass(), 'ConstructorIndividualConBase'), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getClass() should return ''ConstructorIndividualConBase''.')
	assert(strcmp(base.getClass(), 'ConstructorIndividualConBase'), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getClass() should return ''ConstructorIndividualConBase''.')
	assert(strcmp(Element.getClass(base), 'ConstructorIndividualConBase'), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(base) should return ''ConstructorIndividualConBase''.')
	assert(strcmp(Element.getClass('ConstructorIndividualConBase'), 'ConstructorIndividualConBase'), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ConstructorIndividualConBase'') should return ''ConstructorIndividualConBase''.')
	 
	% getSubclasses()
	assert(isequal(ConstructorIndividualConBase.getSubclasses(), subclasses('ConstructorIndividualConBase', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getSubclasses() should return the same result as subclasses(''ConstructorIndividualConBase'', [], [], true).')
	assert(isequal(base.getSubclasses(), subclasses('ConstructorIndividualConBase', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ConstructorIndividualConBase'', [], [], true).')
	assert(isequal(Element.getSubclasses(base), subclasses('ConstructorIndividualConBase', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(base) should return the same result as subclasses(''ConstructorIndividualConBase'', [], [], true).')
	assert(isequal(Element.getSubclasses('ConstructorIndividualConBase'), subclasses('ConstructorIndividualConBase', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ConstructorIndividualConBase'') should return the same result as subclasses(''ConstructorIndividualConBase'', [], [], true).')
	 
	% getProps()
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(ConstructorIndividualConBase.getProps(), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(base.getProps(), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(Element.getProps(base), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(base) should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(Element.getProps('ConstructorIndividualConBase'), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConstructorIndividualConBase'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ConstructorIndividualConBase.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getProps(category) does not work.')
	tmp = cellfun(@(category) base.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(base, category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(base, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ConstructorIndividualConBase', category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConBase.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConBase.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConstructorIndividualConBase'', category) does not work.')
	 
	% getPropNumber()
	assert(ConstructorIndividualConBase.getPropNumber() == length(ConstructorIndividualConBase.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getPropNumber() should return the number of properties.')
	assert(base.getPropNumber() == length(ConstructorIndividualConBase.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(base) == length(ConstructorIndividualConBase.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(base) should return the number of properties.')
	assert(Element.getPropNumber('ConstructorIndividualConBase') == length(ConstructorIndividualConBase.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConstructorIndividualConBase'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ConstructorIndividualConBase.getPropNumber(category), categories)) == ConstructorIndividualConBase.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) base.getPropNumber(category), categories)) == ConstructorIndividualConBase.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(base, category), categories)) == ConstructorIndividualConBase.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(base, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ConstructorIndividualConBase', category), categories)) == ConstructorIndividualConBase.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConstructorIndividualConBase'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ConstructorIndividualConBase.existsProp(NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.existsProp(prop) does not work.')
	assert(~base.existsProp(NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.existsProp(prop) does not work.')
	assert(~Element.existsProp(base, NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(base, prop) does not work.')
	assert(~Element.existsProp('ConstructorIndividualConBase', NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ConstructorIndividualConBase'', prop) does not work.')
	 
	assert_with_error('ConstructorIndividualConBase.existsProp(NaN)', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], base)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], base)
	assert_with_error('Element.existsProp(''ConstructorIndividualConBase'', NaN)', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		assert(ConstructorIndividualConBase.existsProp(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.existsProp(prop) does not work.')
		assert(base.existsProp(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.existsProp(prop) does not work.')
		assert(Element.existsProp(base, prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(base, prop) does not work.')
		assert(Element.existsProp('ConstructorIndividualConBase', prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ConstructorIndividualConBase'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ConstructorIndividualConBase.existsTag(''), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.existsTag(tag) does not work.')
	assert(~base.existsTag(''), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'base.existsTag(tag) does not work.')
	assert(~Element.existsTag(base, ''), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(base, tag) does not work.')
	assert(~Element.existsTag('ConstructorIndividualConBase', ''), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ConstructorIndividualConBase'', tag) does not work.')
	 
	assert_with_error('ConstructorIndividualConBase.existsTag('''')', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], base)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], base)
	assert_with_error('Element.existsTag(''ConstructorIndividualConBase'', '''')', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
		assert(ConstructorIndividualConBase.existsTag(tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.existsTag(tag) does not work.')
		assert(base.existsTag(tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.existsTag(tag) does not work.')
		assert(Element.existsTag(base, tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(base, tga) does not work.')
		assert(Element.existsTag('ConstructorIndividualConBase', tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		assert(ConstructorIndividualConBase.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropProp(prop) does not work.')
		assert(base.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropProp(prop) does not work.')
		assert(Element.getPropProp(base, prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(base, prop) does not work.')
		assert(Element.getPropProp('ConstructorIndividualConBase', prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConstructorIndividualConBase'', prop) does not work.')
	 
		tag = base.getPropTag(prop);
		assert(ConstructorIndividualConBase.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropProp(tag) does not work.')
		assert(base.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropProp(tag) does not work.')
		assert(Element.getPropProp(base, tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(base, tag) does not work.')
		assert(Element.getPropProp('ConstructorIndividualConBase', prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		assert(strcmp(ConstructorIndividualConBase.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropTag(prop) does not work.')
		assert(strcmp(base.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(base, prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(base, prop) does not work.')
		assert(strcmp(Element.getPropTag('ConstructorIndividualConBase', prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConstructorIndividualConBase'', prop) does not work.')
	 
		assert(strcmp(ConstructorIndividualConBase.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropTag(tag) does not work.')
		assert(strcmp(base.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(base, tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(base, tag) does not work.')
		assert(strcmp(Element.getPropTag('ConstructorIndividualConBase', prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		assert(Category.existsCategory(ConstructorIndividualConBase.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(base.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(base, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConstructorIndividualConBase'', prop) does not work.')
	 
		assert(Category.existsCategory(ConstructorIndividualConBase.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(base.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(base, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		assert(Format.existsFormat(ConstructorIndividualConBase.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(base.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(base, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConstructorIndividualConBase'', prop) does not work.')
	 
		assert(Format.existsFormat(ConstructorIndividualConBase.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(base.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(base, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		assert(ischar(ConstructorIndividualConBase.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropDescription(prop) does not work.')
		assert(ischar(base.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(base, prop) does not work.')
		assert(ischar(Element.getPropDescription(base, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConstructorIndividualConBase'', prop) does not work.')
	 
		assert(ischar(ConstructorIndividualConBase.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.getPropDescription(tag) does not work.')
		assert(ischar(base.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(base, tag) does not work.')
		assert(ischar(Element.getPropDescription(base, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConstructorIndividualConBase'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		settings = ConstructorIndividualConBase.getPropSettings(prop);
		settings = base.getPropSettings(prop);
		settings = Element.getPropSettings(base, prop);
		settings = Element.getPropSettings('ConstructorIndividualConBase', prop);
	 
		settings = ConstructorIndividualConBase.getPropSettings(tag);
		settings = base.getPropSettings(tag);
		settings = Element.getPropSettings(base, tag);
		settings = Element.getPropSettings('ConstructorIndividualConBase', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		default = ConstructorIndividualConBase.getPropDefault(prop);
		default = base.getPropDefault(prop);
		default = Element.getPropDefault(base, prop);
		default = Element.getPropDefault('ConstructorIndividualConBase', prop);
	 
		default = ConstructorIndividualConBase.getPropDefault(tag);
		default = base.getPropDefault(tag);
		default = Element.getPropDefault(base, tag);
		default = Element.getPropDefault('ConstructorIndividualConBase', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		conditioned_default = ConstructorIndividualConBase.getPropDefaultConditioned(prop);
		conditioned_default = base.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(base, prop);
		conditioned_default = Element.getPropDefaultConditioned('ConstructorIndividualConBase', prop);
	 
		conditioned_default = ConstructorIndividualConBase.getPropDefaultConditioned(tag);
		conditioned_default = base.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(base, tag);
		conditioned_default = Element.getPropDefaultConditioned('ConstructorIndividualConBase', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		tag = base.getPropTag(prop);
	 
		assert(~ConstructorIndividualConBase.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.checkProp(prop, value) does not work.')
		assert(~base.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(base, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(base, prop, value) does not work.')
		assert(~Element.checkProp('ConstructorIndividualConBase', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConBase'', prop, value) does not work.')
	 
		assert_with_error('ConstructorIndividualConBase.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], prop, base)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], prop, base)
		assert_with_error('Element.checkProp(''ConstructorIndividualConBase'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ConstructorIndividualConBase.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.checkProp(tag, value) does not work.')
		assert(~base.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(base, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(base, tag, value) does not work.')
		assert(~Element.checkProp('ConstructorIndividualConBase', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConBase'', tag, value) does not work.')
	 
		assert_with_error('ConstructorIndividualConBase.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], tag, base)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], tag, base)
		assert_with_error('Element.checkProp(''ConstructorIndividualConBase'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ConstructorIndividualConBase.checkProp(prop, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.checkProp(prop, <conditioned default value>) does not work.')
		assert(base.checkProp(prop, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(base, prop, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(base, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConstructorIndividualConBase', prop, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConBase'', prop, <conditioned default value>) does not work.')
	 
		assert(ConstructorIndividualConBase.checkProp(tag, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.checkProp(tag, <conditioned default value>) does not work.')
		assert(base.checkProp(tag, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'base.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(base, tag, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(base, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConstructorIndividualConBase', tag, Element.getPropDefaultConditioned(ConstructorIndividualConBase, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConBase'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					base.getr(prop) == ConstructorIndividualConBase.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConBase.getCategoryName(ConstructorIndividualConBase.getPropCategory(prop)) ', ConstructorIndividualConBase.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					base.getr(TAG) == ConstructorIndividualConBase.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConBase.getCategoryName(ConstructorIndividualConBase.getPropCategory(prop)) ', ConstructorIndividualConBase.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(base.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(base.getPropSettings(prop))
					assert( ...
						base.checkFormat(base.getPropFormat(prop), base.get(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						base.checkFormat(base.getPropFormat(prop), base.get(prop), base.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					base.getr(prop) == ConstructorIndividualConBase.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConBase.getCategoryName(ConstructorIndividualConBase.getPropCategory(prop)) ', ConstructorIndividualConBase.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					base.getr(TAG) == ConstructorIndividualConBase.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConBase.getCategoryName(ConstructorIndividualConBase.getPropCategory(prop)) ', ConstructorIndividualConBase.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConBase']);
				assert( ...
					~isa(base.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(base.getPropSettings(prop))
					assert( ...
						base.checkFormat(base.getPropFormat(prop), base.get(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						base.checkFormat(base.getPropFormat(prop), base.get(prop), base.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(base.getr(prop), ConstructorIndividualConBase.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ConstructorIndividualConBase.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(base.getr(TAG), ConstructorIndividualConBase.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ConstructorIndividualConBase.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConstructorIndividualConBase.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(base.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(base.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					base.checkFormat(base.getPropFormat(prop), base.getr(prop),base.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConBase']);
				assert( ...
					~isa(base.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConBase']);
	% 			assert( ...
	% 				~isa(base.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConBase.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(base.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				base.checkFormat(base.getPropFormat(prop), base.getr(prop),base.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConBase.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConBase']);
				assert( ...
					~isa(base.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(base.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					base.checkFormat(base.getPropFormat(prop), base.getr(prop),base.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if base.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConBase');
					delete(ancestor(base.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ConstructorIndividualConBase.getProps(Category.RESULT))
		for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch ConstructorIndividualConBase.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						base.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~base.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase();
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		assert( ...
			~base.isLocked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~base.isLocked(TAG), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	base.lock()
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					base.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~base.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase();
	 
	warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConBase');
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		base.lock(prop)
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					base.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~base.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase();
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		assert( ...
			base.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			base.isChecked(TAG), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	base.unchecked()
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		assert( ...
			~base.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	base.checked()
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		assert( ...
			base.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConBase.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ConstructorIndividualConBase
	base_0 = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	% ConstructorIndividualConBase with 1st callbacks
	base_1 = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, base_0.getCallback(4), ..., ...
		ConstructorIndividualConBase.ID, base_0.getCallback(5), ..., ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, base_0.getCallback(9), ..., ...
		ConstructorIndividualConBase.GR_SUVR, base_0.getCallback(10), ..., ...
		ConstructorIndividualConBase.GR_SUVR_REF, base_0.getCallback(11), ..., ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConBase.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(base_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(base_1.get(prop), base_0.get(prop)) && ~isa(base_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(base_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConstructorIndividualConBase with 2nd callbacks
	base_2 = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, base_1.getCallback(4), ..., ...
		ConstructorIndividualConBase.ID, base_1.getCallback(5), ..., ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, base_1.getCallback(9), ..., ...
		ConstructorIndividualConBase.GR_SUVR, base_1.getCallback(10), ..., ...
		ConstructorIndividualConBase.GR_SUVR_REF, base_1.getCallback(11), ..., ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConBase.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(base_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(base_2.get(prop), base_0.get(prop)) && ~isa(base_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(base_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConstructorIndividualConBase with 3rd callbacks
	base_3 = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, base_2.getCallback(4), ..., ...
		ConstructorIndividualConBase.ID, base_2.getCallback(5), ..., ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, base_2.getCallback(9), ..., ...
		ConstructorIndividualConBase.GR_SUVR, base_2.getCallback(10), ..., ...
		ConstructorIndividualConBase.GR_SUVR_REF, base_2.getCallback(11), ..., ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConBase.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(base_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(base_3.get(prop), base_0.get(prop)) && ~isa(base_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(base_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	base = ConstructorIndividualConBase();
	 
	base_copy = base.copy();
	 
	assert(base_copy ~= base, ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(base_copy, base), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		value = base.getr(prop);
		value_copy = base_copy.getr(prop);
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					base_copy.isLocked(prop) == base.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					base_copy.isChecked(prop) == base.isChecked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					base_copy.getPropSeed(prop) == base.getPropSeed(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		if ConstructorIndividualConBase.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConBase']);
			% base.memorize(prop);
			% warning(warning_backup)
		elseif ConstructorIndividualConBase.getPropCategory(prop) == Category.EVANESCENT && base.getPropFormat(prop) == Format.HANDLE
			base.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConBase');
			delete(ancestor(base.get(prop), 'figure'))
			warning(warning_backup)
		else
			base.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	base_copy = base.copy();
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		value = base.getr(prop);
		value_copy = base_copy.getr(prop);
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						base_copy.isLocked(prop) == base.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						base_copy.isChecked(prop) == base.isChecked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						base_copy.getPropSeed(prop) == base.getPropSeed(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	base_0 = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, base_0.getCallback(4), ..., ...
		ConstructorIndividualConBase.ID, base_0.getCallback(5), ..., ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, base_0.getCallback(9), ..., ...
		ConstructorIndividualConBase.GR_SUVR, base_0.getCallback(10), ..., ...
		ConstructorIndividualConBase.GR_SUVR_REF, base_0.getCallback(11), ..., ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	base_copy = base.copy();
	base_0_copy = base_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
		value = base.getr(prop);
		value_copy = base_copy.getr(prop);
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConBase.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConBase.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == base_0.getCallback(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The callback should be obtained from ConstructorIndividualConBase.getCallback().' ...
						)
					assert( ...
						value_copy == base_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The callback should be obtained from ConstructorIndividualConBase.getCallback().' ...
						)
				end
	 
					assert( ...
						base_copy.isLocked(prop) == base.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						base_copy.isChecked(prop) == base.isChecked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						base_copy.getPropSeed(prop) == base.getPropSeed(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base_template = ConstructorIndividualConBase();
	base = ConstructorIndividualConBase('TEMPLATE', base_template);
	 
	for prop = 1:1:ConstructorIndividualConBase.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConBase.getPropTag(prop));
		switch ConstructorIndividualConBase.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ConstructorIndividualConBase.TEMPLATE
					assert( ...
						isa(base.getr(prop), 'ConstructorIndividualConBase'), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase.getr(''TEMPLATE'') should be a ConstructorIndividualConBase element.' ...
						)
					assert( ...
						isa(base_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(base.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						base.getr(prop).get('EL') == base_template && base.getr(prop).get('PROP') == prop && strcmp(base.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase.getr(' TAG ') should be a Callback to base_template.' TAG '.'] ...
						)
					assert( ...
						isa(base_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(base.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(base_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConBase TEMPLATE does not work. ConstructorIndividualConBase_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'constructorindividualconbase_to_be_erased.b2'];
	 
	Element.save(base, filename)
	 
	base_loaded = Element.load(filename);
	 
	assert( ...
		isequal(base.copy(), base_loaded), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.save(base) and/or ConstructorIndividualConBase.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	base = ConstructorIndividualConBase( ...
		ConstructorIndividualConBase.ELCLASS, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.NAME, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.DESCRIPTION, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.TEMPLATE, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.TEMPLATE), ...
		ConstructorIndividualConBase.ID, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.ID), ...
		ConstructorIndividualConBase.LABEL, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.LABEL), ...
		ConstructorIndividualConBase.NOTES, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.NOTES), ...
		ConstructorIndividualConBase.TOSTRING, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.WAITBAR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.WAITBAR), ...
		ConstructorIndividualConBase.GR_SUVR, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR), ...
		ConstructorIndividualConBase.GR_SUVR_REF, ConstructorIndividualConBase.getPropDefault(ConstructorIndividualConBase.GR_SUVR_REF), ...
		ConstructorIndividualConBase.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConBase.getNoValue(), ...
		ConstructorIndividualConBase.GR, ConstructorIndividualConBase.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(base);
	[base_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(base_dec ~= base, ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConBase.encodeJSON() or ConstructorIndividualConBase.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ConstructorIndividualConBase.getPropFormat(prop), num2cell(ConstructorIndividualConBase.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ConstructorIndividualConBase.getPropFormat(prop), num2cell(ConstructorIndividualConBase.getProps())) == Format.NET)
		assert(isequal(base_dec, base), ...
			[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConBase.encodeJSON() or ConstructorIndividualConBase.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ConstructorIndividualConBase:' BRAPH2.FAIL_TEST], ...
		[' When testing ConstructorIndividualConBase no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

