%TEST_CONSTRUCTORINDIVIDUALCONMAHALANOBIS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	icd = ConstructorIndividualConMahalanobis();
	 
	% get('ELCLASS')
	if isa(ConstructorIndividualConMahalanobis, 'ConcreteElement')
		assert(strcmp(ConstructorIndividualConMahalanobis().get('ELCLASS'), 'ConstructorIndividualConMahalanobis'), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis().get(''ELCLASS'') should return ''ConstructorIndividualConMahalanobis''.')
	end
	 
	% getBuild()
	assert(ConstructorIndividualConMahalanobis.getBuild() == 1 && ConstructorIndividualConMahalanobis.getBuild() > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getBuild() should return the ConstructorIndividualConMahalanobis build number.')
	assert(icd.getBuild() == 1 && icd.getBuild() > 0 , ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getBuild() should return the ConstructorIndividualConMahalanobis build number.')
	assert(Element.getBuild(icd) == 1 && Element.getBuild(icd) > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(icd) should return the ConstructorIndividualConMahalanobis build number.')
	assert(Element.getBuild('ConstructorIndividualConMahalanobis') == 1 && Element.getBuild('ConstructorIndividualConMahalanobis') > 0, ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ConstructorIndividualConMahalanobis'') should return the ConstructorIndividualConMahalanobis build number.')
	 
	% getClass()
	assert(strcmp(ConstructorIndividualConMahalanobis.getClass(), 'ConstructorIndividualConMahalanobis'), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getClass() should return ''ConstructorIndividualConMahalanobis''.')
	assert(strcmp(icd.getClass(), 'ConstructorIndividualConMahalanobis'), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getClass() should return ''ConstructorIndividualConMahalanobis''.')
	assert(strcmp(Element.getClass(icd), 'ConstructorIndividualConMahalanobis'), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(icd) should return ''ConstructorIndividualConMahalanobis''.')
	assert(strcmp(Element.getClass('ConstructorIndividualConMahalanobis'), 'ConstructorIndividualConMahalanobis'), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ConstructorIndividualConMahalanobis'') should return ''ConstructorIndividualConMahalanobis''.')
	 
	% getSubclasses()
	assert(isequal(ConstructorIndividualConMahalanobis.getSubclasses(), subclasses('ConstructorIndividualConMahalanobis', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getSubclasses() should return the same result as subclasses(''ConstructorIndividualConMahalanobis'', [], [], true).')
	assert(isequal(icd.getSubclasses(), subclasses('ConstructorIndividualConMahalanobis', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ConstructorIndividualConMahalanobis'', [], [], true).')
	assert(isequal(Element.getSubclasses(icd), subclasses('ConstructorIndividualConMahalanobis', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(icd) should return the same result as subclasses(''ConstructorIndividualConMahalanobis'', [], [], true).')
	assert(isequal(Element.getSubclasses('ConstructorIndividualConMahalanobis'), subclasses('ConstructorIndividualConMahalanobis', [], [], true)), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ConstructorIndividualConMahalanobis'') should return the same result as subclasses(''ConstructorIndividualConMahalanobis'', [], [], true).')
	 
	% getProps()
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(ConstructorIndividualConMahalanobis.getProps(), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(icd.getProps(), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getProps() should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(Element.getProps(icd), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(icd) should return a row vector [1:1:N].')
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(Element.getProps('ConstructorIndividualConMahalanobis'), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConstructorIndividualConMahalanobis'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ConstructorIndividualConMahalanobis.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getProps(category) does not work.')
	tmp = cellfun(@(category) icd.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(icd, category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(icd, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ConstructorIndividualConMahalanobis', category), categories, 'UniformOutput', false);
	assert(isempty(ConstructorIndividualConMahalanobis.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ConstructorIndividualConMahalanobis.getProps())), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ConstructorIndividualConMahalanobis'', category) does not work.')
	 
	% getPropNumber()
	assert(ConstructorIndividualConMahalanobis.getPropNumber() == length(ConstructorIndividualConMahalanobis.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getPropNumber() should return the number of properties.')
	assert(icd.getPropNumber() == length(ConstructorIndividualConMahalanobis.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(icd) == length(ConstructorIndividualConMahalanobis.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(icd) should return the number of properties.')
	assert(Element.getPropNumber('ConstructorIndividualConMahalanobis') == length(ConstructorIndividualConMahalanobis.getProps()), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConstructorIndividualConMahalanobis'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ConstructorIndividualConMahalanobis.getPropNumber(category), categories)) == ConstructorIndividualConMahalanobis.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) icd.getPropNumber(category), categories)) == ConstructorIndividualConMahalanobis.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(icd, category), categories)) == ConstructorIndividualConMahalanobis.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(icd, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ConstructorIndividualConMahalanobis', category), categories)) == ConstructorIndividualConMahalanobis.getPropNumber(), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ConstructorIndividualConMahalanobis'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ConstructorIndividualConMahalanobis.existsProp(NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.existsProp(prop) does not work.')
	assert(~icd.existsProp(NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.existsProp(prop) does not work.')
	assert(~Element.existsProp(icd, NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(icd, prop) does not work.')
	assert(~Element.existsProp('ConstructorIndividualConMahalanobis', NaN), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
	assert_with_error('ConstructorIndividualConMahalanobis.existsProp(NaN)', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsProp(''ConstructorIndividualConMahalanobis'', NaN)', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		assert(ConstructorIndividualConMahalanobis.existsProp(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.existsProp(prop) does not work.')
		assert(icd.existsProp(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.existsProp(prop) does not work.')
		assert(Element.existsProp(icd, prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(icd, prop) does not work.')
		assert(Element.existsProp('ConstructorIndividualConMahalanobis', prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ConstructorIndividualConMahalanobis.existsTag(''), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.existsTag(tag) does not work.')
	assert(~icd.existsTag(''), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'icd.existsTag(tag) does not work.')
	assert(~Element.existsTag(icd, ''), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(icd, tag) does not work.')
	assert(~Element.existsTag('ConstructorIndividualConMahalanobis', ''), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	 
	assert_with_error('ConstructorIndividualConMahalanobis.existsTag('''')', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], icd)
	assert_with_error('Element.existsTag(''ConstructorIndividualConMahalanobis'', '''')', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
		assert(ConstructorIndividualConMahalanobis.existsTag(tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.existsTag(tag) does not work.')
		assert(icd.existsTag(tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.existsTag(tag) does not work.')
		assert(Element.existsTag(icd, tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(icd, tga) does not work.')
		assert(Element.existsTag('ConstructorIndividualConMahalanobis', tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		assert(ConstructorIndividualConMahalanobis.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropProp(prop) does not work.')
		assert(icd.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropProp(prop) does not work.')
		assert(Element.getPropProp(icd, prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(icd, prop) does not work.')
		assert(Element.getPropProp('ConstructorIndividualConMahalanobis', prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
		tag = icd.getPropTag(prop);
		assert(ConstructorIndividualConMahalanobis.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropProp(tag) does not work.')
		assert(icd.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropProp(tag) does not work.')
		assert(Element.getPropProp(icd, tag) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(icd, tag) does not work.')
		assert(Element.getPropProp('ConstructorIndividualConMahalanobis', prop) == prop, ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(strcmp(ConstructorIndividualConMahalanobis.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropTag(prop) does not work.')
		assert(strcmp(icd.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(icd, prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(icd, prop) does not work.')
		assert(strcmp(Element.getPropTag('ConstructorIndividualConMahalanobis', prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
		assert(strcmp(ConstructorIndividualConMahalanobis.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropTag(tag) does not work.')
		assert(strcmp(icd.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(icd, tag), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(icd, tag) does not work.')
		assert(strcmp(Element.getPropTag('ConstructorIndividualConMahalanobis', prop), tag), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(Category.existsCategory(ConstructorIndividualConMahalanobis.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(icd.getPropCategory(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(icd, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
		assert(Category.existsCategory(ConstructorIndividualConMahalanobis.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(icd.getPropCategory(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(icd, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(Format.existsFormat(ConstructorIndividualConMahalanobis.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(icd.getPropFormat(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(icd, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
		assert(Format.existsFormat(ConstructorIndividualConMahalanobis.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(icd.getPropFormat(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(icd, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(ischar(ConstructorIndividualConMahalanobis.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropDescription(prop) does not work.')
		assert(ischar(icd.getPropDescription(prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(icd, prop) does not work.')
		assert(ischar(Element.getPropDescription(icd, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConstructorIndividualConMahalanobis'', prop) does not work.')
	 
		assert(ischar(ConstructorIndividualConMahalanobis.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.getPropDescription(tag) does not work.')
		assert(ischar(icd.getPropDescription(tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(icd, tag) does not work.')
		assert(ischar(Element.getPropDescription(icd, tag)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ConstructorIndividualConMahalanobis'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		settings = ConstructorIndividualConMahalanobis.getPropSettings(prop);
		settings = icd.getPropSettings(prop);
		settings = Element.getPropSettings(icd, prop);
		settings = Element.getPropSettings('ConstructorIndividualConMahalanobis', prop);
	 
		settings = ConstructorIndividualConMahalanobis.getPropSettings(tag);
		settings = icd.getPropSettings(tag);
		settings = Element.getPropSettings(icd, tag);
		settings = Element.getPropSettings('ConstructorIndividualConMahalanobis', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		default = ConstructorIndividualConMahalanobis.getPropDefault(prop);
		default = icd.getPropDefault(prop);
		default = Element.getPropDefault(icd, prop);
		default = Element.getPropDefault('ConstructorIndividualConMahalanobis', prop);
	 
		default = ConstructorIndividualConMahalanobis.getPropDefault(tag);
		default = icd.getPropDefault(tag);
		default = Element.getPropDefault(icd, tag);
		default = Element.getPropDefault('ConstructorIndividualConMahalanobis', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		conditioned_default = ConstructorIndividualConMahalanobis.getPropDefaultConditioned(prop);
		conditioned_default = icd.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(icd, prop);
		conditioned_default = Element.getPropDefaultConditioned('ConstructorIndividualConMahalanobis', prop);
	 
		conditioned_default = ConstructorIndividualConMahalanobis.getPropDefaultConditioned(tag);
		conditioned_default = icd.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(icd, tag);
		conditioned_default = Element.getPropDefaultConditioned('ConstructorIndividualConMahalanobis', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		tag = icd.getPropTag(prop);
	 
		assert(~ConstructorIndividualConMahalanobis.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.checkProp(prop, value) does not work.')
		assert(~icd.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(icd, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, prop, value) does not work.')
		assert(~Element.checkProp('ConstructorIndividualConMahalanobis', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConMahalanobis'', prop, value) does not work.')
	 
		assert_with_error('ConstructorIndividualConMahalanobis.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], prop, icd)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], prop, icd)
		assert_with_error('Element.checkProp(''ConstructorIndividualConMahalanobis'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ConstructorIndividualConMahalanobis.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.checkProp(tag, value) does not work.')
		assert(~icd.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(icd, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, tag, value) does not work.')
		assert(~Element.checkProp('ConstructorIndividualConMahalanobis', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConMahalanobis'', tag, value) does not work.')
	 
		assert_with_error('ConstructorIndividualConMahalanobis.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], tag, icd)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], tag, icd)
		assert_with_error('Element.checkProp(''ConstructorIndividualConMahalanobis'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ConstructorIndividualConMahalanobis.checkProp(prop, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.checkProp(prop, <conditioned default value>) does not work.')
		assert(icd.checkProp(prop, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(icd, prop, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConstructorIndividualConMahalanobis', prop, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConMahalanobis'', prop, <conditioned default value>) does not work.')
	 
		assert(ConstructorIndividualConMahalanobis.checkProp(tag, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.checkProp(tag, <conditioned default value>) does not work.')
		assert(icd.checkProp(tag, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'icd.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(icd, tag, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(icd, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ConstructorIndividualConMahalanobis', tag, Element.getPropDefaultConditioned(ConstructorIndividualConMahalanobis, prop)), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ConstructorIndividualConMahalanobis'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					icd.getr(prop) == ConstructorIndividualConMahalanobis.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConMahalanobis.getCategoryName(ConstructorIndividualConMahalanobis.getPropCategory(prop)) ', ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					icd.getr(TAG) == ConstructorIndividualConMahalanobis.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConMahalanobis.getCategoryName(ConstructorIndividualConMahalanobis.getPropCategory(prop)) ', ConstructorIndividualConMahalanobis.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(icd.getPropSettings(prop))
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop), icd.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					icd.getr(prop) == ConstructorIndividualConMahalanobis.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConMahalanobis.getCategoryName(ConstructorIndividualConMahalanobis.getPropCategory(prop)) ', ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					icd.getr(TAG) == ConstructorIndividualConMahalanobis.getNoValue(), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['Being a ' ConstructorIndividualConMahalanobis.getCategoryName(ConstructorIndividualConMahalanobis.getPropCategory(prop)) ', ConstructorIndividualConMahalanobis.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConMahalanobis']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(icd.getPropSettings(prop))
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						icd.checkFormat(icd.getPropFormat(prop), icd.get(prop), icd.getPropSettings(prop)), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(icd.getr(prop), ConstructorIndividualConMahalanobis.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ConstructorIndividualConMahalanobis.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(icd.getr(TAG), ConstructorIndividualConMahalanobis.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ConstructorIndividualConMahalanobis.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ConstructorIndividualConMahalanobis.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(icd.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConMahalanobis']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConMahalanobis']);
	% 			assert( ...
	% 				~isa(icd.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConMahalanobis.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(icd.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
	% 				['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConMahalanobis']);
				assert( ...
					~isa(icd.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(icd.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					icd.checkFormat(icd.getPropFormat(prop), icd.getr(prop),icd.getPropSettings(prop)), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if icd.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConMahalanobis');
					delete(ancestor(icd.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ConstructorIndividualConMahalanobis.getProps(Category.RESULT))
		for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						icd.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~icd.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis();
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		assert( ...
			~icd.isLocked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~icd.isLocked(TAG), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	icd.lock()
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					icd.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~icd.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis();
	 
	warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConMahalanobis');
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		icd.lock(prop)
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					icd.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~icd.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis();
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		assert( ...
			icd.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			icd.isChecked(TAG), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	icd.unchecked()
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		assert( ...
			~icd.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	icd.checked()
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		assert( ...
			icd.isChecked(prop), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			['ConstructorIndividualConMahalanobis.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ConstructorIndividualConMahalanobis
	icd_0 = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	% ConstructorIndividualConMahalanobis with 1st callbacks
	icd_1 = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, icd_0.getCallback(4), ..., ...
		ConstructorIndividualConMahalanobis.ID, icd_0.getCallback(5), ..., ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, icd_0.getCallback(9), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR, icd_0.getCallback(10), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, icd_0.getCallback(11), ..., ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConMahalanobis.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_1.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConstructorIndividualConMahalanobis with 2nd callbacks
	icd_2 = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, icd_1.getCallback(4), ..., ...
		ConstructorIndividualConMahalanobis.ID, icd_1.getCallback(5), ..., ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, icd_1.getCallback(9), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR, icd_1.getCallback(10), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, icd_1.getCallback(11), ..., ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConMahalanobis.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_2.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ConstructorIndividualConMahalanobis with 3rd callbacks
	icd_3 = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, icd_2.getCallback(4), ..., ...
		ConstructorIndividualConMahalanobis.ID, icd_2.getCallback(5), ..., ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, icd_2.getCallback(9), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR, icd_2.getCallback(10), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, icd_2.getCallback(11), ..., ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	prop_number = ConstructorIndividualConMahalanobis.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(icd_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(icd_3.get(prop), icd_0.get(prop)) && ~isa(icd_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(icd_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	icd = ConstructorIndividualConMahalanobis();
	 
	icd_copy = icd.copy();
	 
	assert(icd_copy ~= icd, ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(icd_copy, icd), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					icd_copy.isLocked(prop) == icd.isLocked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					icd_copy.isChecked(prop) == icd.isChecked(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		if ConstructorIndividualConMahalanobis.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ConstructorIndividualConMahalanobis']);
			% icd.memorize(prop);
			% warning(warning_backup)
		elseif ConstructorIndividualConMahalanobis.getPropCategory(prop) == Category.EVANESCENT && icd.getPropFormat(prop) == Format.HANDLE
			icd.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ConstructorIndividualConMahalanobis');
			delete(ancestor(icd.get(prop), 'figure'))
			warning(warning_backup)
		else
			icd.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	icd_copy = icd.copy();
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						icd_copy.isLocked(prop) == icd.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.isChecked(prop) == icd.isChecked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	icd_0 = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, icd_0.getCallback(4), ..., ...
		ConstructorIndividualConMahalanobis.ID, icd_0.getCallback(5), ..., ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, icd_0.getCallback(9), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR, icd_0.getCallback(10), ..., ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, icd_0.getCallback(11), ..., ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	icd_copy = icd.copy();
	icd_0_copy = icd_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
		value = icd.getr(prop);
		value_copy = icd_copy.getr(prop);
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					'ConstructorIndividualConMahalanobis.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
							'ConstructorIndividualConMahalanobis.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == icd_0.getCallback(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The callback should be obtained from ConstructorIndividualConMahalanobis.getCallback().' ...
						)
					assert( ...
						value_copy == icd_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The callback should be obtained from ConstructorIndividualConMahalanobis.getCallback().' ...
						)
				end
	 
					assert( ...
						icd_copy.isLocked(prop) == icd.isLocked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.isChecked(prop) == icd.isChecked(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						icd_copy.getPropSeed(prop) == icd.getPropSeed(prop), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd_template = ConstructorIndividualConMahalanobis();
	icd = ConstructorIndividualConMahalanobis('TEMPLATE', icd_template);
	 
	for prop = 1:1:ConstructorIndividualConMahalanobis.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(ConstructorIndividualConMahalanobis.getPropTag(prop));
		switch ConstructorIndividualConMahalanobis.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ConstructorIndividualConMahalanobis.TEMPLATE
					assert( ...
						isa(icd.getr(prop), 'ConstructorIndividualConMahalanobis'), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis.getr(''TEMPLATE'') should be a ConstructorIndividualConMahalanobis element.' ...
						)
					assert( ...
						isa(icd_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						'ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(icd.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						icd.getr(prop).get('EL') == icd_template && icd.getr(prop).get('PROP') == prop && strcmp(icd.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis.getr(' TAG ') should be a Callback to icd_template.' TAG '.'] ...
						)
					assert( ...
						isa(icd_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
						['ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(icd.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(icd_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
					['ConstructorIndividualConMahalanobis TEMPLATE does not work. ConstructorIndividualConMahalanobis_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'constructorindividualconmahalanobis_to_be_erased.b2'];
	 
	Element.save(icd, filename)
	 
	icd_loaded = Element.load(filename);
	 
	assert( ...
		isequal(icd.copy(), icd_loaded), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.save(icd) and/or ConstructorIndividualConMahalanobis.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	icd = ConstructorIndividualConMahalanobis( ...
		ConstructorIndividualConMahalanobis.ELCLASS, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.NAME, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.DESCRIPTION, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.TEMPLATE, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.TEMPLATE), ...
		ConstructorIndividualConMahalanobis.ID, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.ID), ...
		ConstructorIndividualConMahalanobis.LABEL, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.LABEL), ...
		ConstructorIndividualConMahalanobis.NOTES, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.NOTES), ...
		ConstructorIndividualConMahalanobis.TOSTRING, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.WAITBAR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.WAITBAR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR), ...
		ConstructorIndividualConMahalanobis.GR_SUVR_REF, ConstructorIndividualConMahalanobis.getPropDefault(ConstructorIndividualConMahalanobis.GR_SUVR_REF), ...
		ConstructorIndividualConMahalanobis.CONNECTOME_CONSTRUCT_METHOD, ConstructorIndividualConMahalanobis.getNoValue(), ...
		ConstructorIndividualConMahalanobis.GR, ConstructorIndividualConMahalanobis.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(icd);
	[icd_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(icd_dec ~= icd, ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		'ConstructorIndividualConMahalanobis.encodeJSON() or ConstructorIndividualConMahalanobis.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ConstructorIndividualConMahalanobis.getPropFormat(prop), num2cell(ConstructorIndividualConMahalanobis.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ConstructorIndividualConMahalanobis.getPropFormat(prop), num2cell(ConstructorIndividualConMahalanobis.getProps())) == Format.NET)
		assert(isequal(icd_dec, icd), ...
			[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
			'ConstructorIndividualConMahalanobis.encodeJSON() or ConstructorIndividualConMahalanobis.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Example data
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	group_dir = fullfile(fileparts(which('IndividualDistanceConConstructor')),'Example data Nifti');
	if ~exist(group_dir)
	    create_example_NIfTI([],group_dir)
	end
end

%% Test 13: Verify the Distance-based individual connectome pipeline
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	im_ba = ImporterBrainAtlasXLS('FILE', which('aal94_atlas.xlsx'));
	ba = im_ba.get('BA');
	atlas = ba;
	br_dict = atlas.get('BR_DICT');
	selected_ids = num2cell(1:94);
	selected_br = cellfun(@(id) br_dict.get('IT', id), selected_ids, 'UniformOutput', false);
	selected_br_dict = IndexedDictionary('IT_CLASS', 'BrainRegion', 'IT_LIST',  selected_br);
	
	im_ba = ImporterBrainAtlasXLS('FILE', which('aal94_atlas.xlsx'));
	ba = im_ba.get('BA');
	
	group_dir1 = fullfile(fileparts(which('IndividualDistanceConConstructor')),'Example data Nifti', 'Group1');
	im_gr1_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir1, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr1_WM_GM = im_gr1_WM_GM.get('GR');
	
	im_gr1_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir1, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr1_PET = im_gr1_PET.get('GR');
	
	group_dir2 = fullfile(fileparts(which('IndividualDistanceConConstructor')),'Example data Nifti', 'Group2');
	im_gr2_WM_GM = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir2, ...
	    'NIFTI_TYPE', {'T1'}, ...
	    'WAITBAR', true ...
	    );
	gr2_WM_GM = im_gr2_WM_GM.get('GR');
	
	im_gr2_PET = ImporterGroupSubjNIfTI( ...
	    'DIRECTORY', group_dir2, ...
	    'NIFTI_TYPE', {'PET'}, ...
	    'WAITBAR', true ...
	    );
	gr2_PET = im_gr2_PET.get('GR');
	
	path_dict = IndexedDictionary(...
	    'IT_CLASS', 'FILE_PATH', ...
	    'IT_LIST', {FILE_PATH('PATH', which('upsampled_AAL2.nii'))} ...
	    );
	
	ref_region_list = [2001];% reference region label
	
	gr1 = SUVRConstructor('GR_PET',gr1_PET, ...
	    'GR_T1',gr1_WM_GM, ...
	    'BA', {ba},...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'SUVR_REGION_SELECTION', selected_br_dict);
	
	SUVR_gr1 = gr1.get('GR');
	
	gr2 = SUVRConstructor('GR_PET',gr2_PET, ...
	    'GR_T1',gr2_WM_GM, ...
	    'BA', {ba},...
	    'ATLAS_PATH_DICT' ,path_dict, ...
	    'REF_REGION_LIST',{ref_region_list}, ...
	    'SUVR_REGION_SELECTION', selected_br_dict);
	
	SUVR_gr2 = gr2.get('GR');
	
	constructor1 = IndividualDistanceConConstructor( ...
	    'GR_SUVR', SUVR_gr1,'GR_SUVR_REF', SUVR_gr2);
	
	distance_connectomes_gr1 = constructor1.get('GR');
	
	
	g_temp  = GraphWU('STANDARDIZE_RULE', 'range');
	a_WU1 = AnalyzeEnsemble_CON_WU('GR', distance_connectomes_gr1,'GRAPH_TEMPLATE', g_temp);
	num_subjects = a_WU1.get('G_DICT').get('LENGTH');
	
	% Initialize arrays for strength measures
	strength_first20_1 = zeros(num_subjects, 20);
	strength_others_1 = zeros(num_subjects,size(distance_connectomes_gr1.get('SUB_DICT').get('IT', 1).get('CON'),1)- 20);
	
	for i = 1:num_subjects
	    g = a_WU1.get('G_DICT').get('IT', i);
	    strength = g.get('MEASURE', 'Strength').get('M'); % Strength for all regions
	    strength20_regions = strength{1}(1:20,:);
	    strengthother_regions = strength{1}(21:end,:);
	    mean_20 = mean(strength20_regions(:));
	    mean_others = mean(strengthother_regions(:));
	    % Assert for each subject
	    assert(mean_20 < mean_others, ...
	        sprintf('Test failed for subject %d: The first 20 regions do not have higher distance than the other regions.', i));
	end
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ConstructorIndividualConMahalanobis:' BRAPH2.FAIL_TEST], ...
		[' When testing ConstructorIndividualConMahalanobis no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

