%EXAMPLE_NEUROIMGING_2_PDFS_PET
% Script example pipeline neuroimaing (PET) conversion to
% probability density functions (PDFs)
clear variables %#ok<*NASGU>

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data NIfTI'], ...
    'MODALITY', 'pet', ...
    'BA', ba_aal120, ...
    'WAITBAR', true ...
    );

gr_pet = im_gr.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data NIfTI'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob'
    'BA', ba_aal120, ...
    'WAITBAR', true ...
    );

gr_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('SubjectNeuroimaging')) filesep 'Example data NIfTI'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob'
    'BA', ba_aal120, ...
    'WAITBAR', true ...
    );

gr_anat_wmprob = im_gr_wm.get('GR');

%% Convert neuroimaging data to probability density functions
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases neuroimaging NIfTI' filesep 'td_atlas_mapping.csv']
    };

ref_brain_regions = {};
ref_brain_regions_idx = 95:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end

brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

cn = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIfTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_pet, ...
    'GR_LIST_ANAT_REF', {gr_anat_gmprob, gr_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr_pdfs = cn.get('GR_PDFS')
ba_pdfs = cn.get('BA')

%% Export data
directory_base = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Converted data PET'];
mkdir(directory);
directory_group = [directory_base filesep 'group']
ex = ExporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', directory_group, ...
    'GR', gr_pdfs ...
    );
ex.get('SAVE');

file = [directory_base filesep 'brain_atlas.xlsx'];
ex = ExporterBrainAtlasXLS( ...
    'FILE', file, ...
    'BA', ba_pdfs ...
    );
ex.get('SAVE');
