%TEST_NNCLASSIFIERMLP_EVALUATOR_VOIS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nne = NNClassifierMLP_Evaluator_VOIs();
	 
	% get('ELCLASS')
	if isa(NNClassifierMLP_Evaluator_VOIs, 'ConcreteElement')
		assert(strcmp(NNClassifierMLP_Evaluator_VOIs().get('ELCLASS'), 'NNClassifierMLP_Evaluator_VOIs'), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs().get(''ELCLASS'') should return ''NNClassifierMLP_Evaluator_VOIs''.')
	end
	 
	% getBuild()
	assert(NNClassifierMLP_Evaluator_VOIs.getBuild() == 1 && NNClassifierMLP_Evaluator_VOIs.getBuild() > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getBuild() should return the NNClassifierMLP_Evaluator_VOIs build number.')
	assert(nne.getBuild() == 1 && nne.getBuild() > 0 , ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getBuild() should return the NNClassifierMLP_Evaluator_VOIs build number.')
	assert(Element.getBuild(nne) == 1 && Element.getBuild(nne) > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nne) should return the NNClassifierMLP_Evaluator_VOIs build number.')
	assert(Element.getBuild('NNClassifierMLP_Evaluator_VOIs') == 1 && Element.getBuild('NNClassifierMLP_Evaluator_VOIs') > 0, ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNClassifierMLP_Evaluator_VOIs'') should return the NNClassifierMLP_Evaluator_VOIs build number.')
	 
	% getClass()
	assert(strcmp(NNClassifierMLP_Evaluator_VOIs.getClass(), 'NNClassifierMLP_Evaluator_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getClass() should return ''NNClassifierMLP_Evaluator_VOIs''.')
	assert(strcmp(nne.getClass(), 'NNClassifierMLP_Evaluator_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getClass() should return ''NNClassifierMLP_Evaluator_VOIs''.')
	assert(strcmp(Element.getClass(nne), 'NNClassifierMLP_Evaluator_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nne) should return ''NNClassifierMLP_Evaluator_VOIs''.')
	assert(strcmp(Element.getClass('NNClassifierMLP_Evaluator_VOIs'), 'NNClassifierMLP_Evaluator_VOIs'), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNClassifierMLP_Evaluator_VOIs'') should return ''NNClassifierMLP_Evaluator_VOIs''.')
	 
	% getSubclasses()
	assert(isequal(NNClassifierMLP_Evaluator_VOIs.getSubclasses(), subclasses('NNClassifierMLP_Evaluator_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getSubclasses() should return the same result as subclasses(''NNClassifierMLP_Evaluator_VOIs'', [], [], true).')
	assert(isequal(nne.getSubclasses(), subclasses('NNClassifierMLP_Evaluator_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNClassifierMLP_Evaluator_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses(nne), subclasses('NNClassifierMLP_Evaluator_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nne) should return the same result as subclasses(''NNClassifierMLP_Evaluator_VOIs'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNClassifierMLP_Evaluator_VOIs'), subclasses('NNClassifierMLP_Evaluator_VOIs', [], [], true)), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNClassifierMLP_Evaluator_VOIs'') should return the same result as subclasses(''NNClassifierMLP_Evaluator_VOIs'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(NNClassifierMLP_Evaluator_VOIs.getProps(), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(nne.getProps(), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(Element.getProps(nne), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nne) should return a row vector [1:1:N].')
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(Element.getProps('NNClassifierMLP_Evaluator_VOIs'), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNClassifierMLP_Evaluator_VOIs'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNClassifierMLP_Evaluator_VOIs.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getProps(category) does not work.')
	tmp = cellfun(@(category) nne.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nne, category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nne, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNClassifierMLP_Evaluator_VOIs', category), categories, 'UniformOutput', false);
	assert(isempty(NNClassifierMLP_Evaluator_VOIs.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNClassifierMLP_Evaluator_VOIs.getProps())), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNClassifierMLP_Evaluator_VOIs'', category) does not work.')
	 
	% getPropNumber()
	assert(NNClassifierMLP_Evaluator_VOIs.getPropNumber() == length(NNClassifierMLP_Evaluator_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getPropNumber() should return the number of properties.')
	assert(nne.getPropNumber() == length(NNClassifierMLP_Evaluator_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nne) == length(NNClassifierMLP_Evaluator_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nne) should return the number of properties.')
	assert(Element.getPropNumber('NNClassifierMLP_Evaluator_VOIs') == length(NNClassifierMLP_Evaluator_VOIs.getProps()), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNClassifierMLP_Evaluator_VOIs'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNClassifierMLP_Evaluator_VOIs.getPropNumber(category), categories)) == NNClassifierMLP_Evaluator_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nne.getPropNumber(category), categories)) == NNClassifierMLP_Evaluator_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nne, category), categories)) == NNClassifierMLP_Evaluator_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nne, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNClassifierMLP_Evaluator_VOIs', category), categories)) == NNClassifierMLP_Evaluator_VOIs.getPropNumber(), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNClassifierMLP_Evaluator_VOIs'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNClassifierMLP_Evaluator_VOIs.existsProp(NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.existsProp(prop) does not work.')
	assert(~nne.existsProp(NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.existsProp(prop) does not work.')
	assert(~Element.existsProp(nne, NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nne, prop) does not work.')
	assert(~Element.existsProp('NNClassifierMLP_Evaluator_VOIs', NaN), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
	assert_with_error('NNClassifierMLP_Evaluator_VOIs.existsProp(NaN)', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsProp(''NNClassifierMLP_Evaluator_VOIs'', NaN)', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		assert(NNClassifierMLP_Evaluator_VOIs.existsProp(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.existsProp(prop) does not work.')
		assert(nne.existsProp(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.existsProp(prop) does not work.')
		assert(Element.existsProp(nne, prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nne, prop) does not work.')
		assert(Element.existsProp('NNClassifierMLP_Evaluator_VOIs', prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNClassifierMLP_Evaluator_VOIs.existsTag(''), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.existsTag(tag) does not work.')
	assert(~nne.existsTag(''), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'nne.existsTag(tag) does not work.')
	assert(~Element.existsTag(nne, ''), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nne, tag) does not work.')
	assert(~Element.existsTag('NNClassifierMLP_Evaluator_VOIs', ''), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	 
	assert_with_error('NNClassifierMLP_Evaluator_VOIs.existsTag('''')', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsTag(''NNClassifierMLP_Evaluator_VOIs'', '''')', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
		assert(NNClassifierMLP_Evaluator_VOIs.existsTag(tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.existsTag(tag) does not work.')
		assert(nne.existsTag(tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.existsTag(tag) does not work.')
		assert(Element.existsTag(nne, tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nne, tga) does not work.')
		assert(Element.existsTag('NNClassifierMLP_Evaluator_VOIs', tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		assert(NNClassifierMLP_Evaluator_VOIs.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropProp(prop) does not work.')
		assert(nne.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nne, prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nne, prop) does not work.')
		assert(Element.getPropProp('NNClassifierMLP_Evaluator_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
		tag = nne.getPropTag(prop);
		assert(NNClassifierMLP_Evaluator_VOIs.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropProp(tag) does not work.')
		assert(nne.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nne, tag) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nne, tag) does not work.')
		assert(Element.getPropProp('NNClassifierMLP_Evaluator_VOIs', prop) == prop, ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(strcmp(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropTag(prop) does not work.')
		assert(strcmp(nne.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nne, prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nne, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNClassifierMLP_Evaluator_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
		assert(strcmp(NNClassifierMLP_Evaluator_VOIs.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropTag(tag) does not work.')
		assert(strcmp(nne.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nne, tag), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nne, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNClassifierMLP_Evaluator_VOIs', prop), tag), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(Category.existsCategory(NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nne.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nne, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
		assert(Category.existsCategory(NNClassifierMLP_Evaluator_VOIs.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nne.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nne, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(Format.existsFormat(NNClassifierMLP_Evaluator_VOIs.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nne.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nne, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
		assert(Format.existsFormat(NNClassifierMLP_Evaluator_VOIs.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nne.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nne, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(ischar(NNClassifierMLP_Evaluator_VOIs.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropDescription(prop) does not work.')
		assert(ischar(nne.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nne, prop) does not work.')
		assert(ischar(Element.getPropDescription(nne, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNClassifierMLP_Evaluator_VOIs'', prop) does not work.')
	 
		assert(ischar(NNClassifierMLP_Evaluator_VOIs.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.getPropDescription(tag) does not work.')
		assert(ischar(nne.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nne, tag) does not work.')
		assert(ischar(Element.getPropDescription(nne, tag)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNClassifierMLP_Evaluator_VOIs'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		settings = NNClassifierMLP_Evaluator_VOIs.getPropSettings(prop);
		settings = nne.getPropSettings(prop);
		settings = Element.getPropSettings(nne, prop);
		settings = Element.getPropSettings('NNClassifierMLP_Evaluator_VOIs', prop);
	 
		settings = NNClassifierMLP_Evaluator_VOIs.getPropSettings(tag);
		settings = nne.getPropSettings(tag);
		settings = Element.getPropSettings(nne, tag);
		settings = Element.getPropSettings('NNClassifierMLP_Evaluator_VOIs', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		default = NNClassifierMLP_Evaluator_VOIs.getPropDefault(prop);
		default = nne.getPropDefault(prop);
		default = Element.getPropDefault(nne, prop);
		default = Element.getPropDefault('NNClassifierMLP_Evaluator_VOIs', prop);
	 
		default = NNClassifierMLP_Evaluator_VOIs.getPropDefault(tag);
		default = nne.getPropDefault(tag);
		default = Element.getPropDefault(nne, tag);
		default = Element.getPropDefault('NNClassifierMLP_Evaluator_VOIs', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		conditioned_default = NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(prop);
		conditioned_default = nne.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nne, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNClassifierMLP_Evaluator_VOIs', prop);
	 
		conditioned_default = NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(tag);
		conditioned_default = nne.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nne, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNClassifierMLP_Evaluator_VOIs', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(~NNClassifierMLP_Evaluator_VOIs.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.checkProp(prop, value) does not work.')
		assert(~nne.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nne, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, prop, value) does not work.')
		assert(~Element.checkProp('NNClassifierMLP_Evaluator_VOIs', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', prop, value) does not work.')
	 
		assert_with_error('NNClassifierMLP_Evaluator_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], prop, nne)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], prop, nne)
		assert_with_error('Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNClassifierMLP_Evaluator_VOIs.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.checkProp(tag, value) does not work.')
		assert(~nne.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nne, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, tag, value) does not work.')
		assert(~Element.checkProp('NNClassifierMLP_Evaluator_VOIs', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', tag, value) does not work.')
	 
		assert_with_error('NNClassifierMLP_Evaluator_VOIs.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], tag, nne)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], tag, nne)
		assert_with_error('Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNClassifierMLP_Evaluator_VOIs.checkProp(prop, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.checkProp(prop, <conditioned default value>) does not work.')
		assert(nne.checkProp(prop, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nne, prop, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNClassifierMLP_Evaluator_VOIs', prop, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', prop, <conditioned default value>) does not work.')
	 
		assert(NNClassifierMLP_Evaluator_VOIs.checkProp(tag, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.checkProp(tag, <conditioned default value>) does not work.')
		assert(nne.checkProp(tag, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nne, tag, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNClassifierMLP_Evaluator_VOIs', tag, Element.getPropDefaultConditioned(NNClassifierMLP_Evaluator_VOIs, prop)), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNClassifierMLP_Evaluator_VOIs'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_Evaluator_VOIs.PFROC])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nne.getr(prop) == NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_Evaluator_VOIs.getCategoryName(NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)) ', NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nne.getr(TAG) == NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_Evaluator_VOIs.getCategoryName(NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)) ', NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nne.getPropSettings(prop))
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop), nne.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nne.getr(prop) == NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_Evaluator_VOIs.getCategoryName(NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)) ', NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nne.getr(TAG) == NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNClassifierMLP_Evaluator_VOIs.getCategoryName(NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)) ', NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nne.getPropSettings(prop))
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop), nne.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nne.getr(prop), NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nne.getr(TAG), NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNClassifierMLP_Evaluator_VOIs.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNClassifierMLP_Evaluator_VOIs.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_Evaluator_VOIs.PFROC])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nne.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs']);
	% 			assert( ...
	% 				~isa(nne.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_Evaluator_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nne.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
	% 				['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nne.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nne.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_Evaluator_VOIs');
					delete(ancestor(nne.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNClassifierMLP_Evaluator_VOIs.getProps(Category.RESULT))
		for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
	 
			% excluded props
			if any(prop == [NNClassifierMLP_Evaluator_VOIs.PFROC])
				continue
			end
	 
			switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nne.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nne.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs();
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		assert( ...
			~nne.isLocked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nne.isLocked(TAG), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nne.lock()
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nne.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nne.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs();
	 
	warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_Evaluator_VOIs');
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		nne.lock(prop)
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nne.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nne.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs();
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		assert( ...
			nne.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nne.isChecked(TAG), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nne.unchecked()
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		assert( ...
			~nne.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nne.checked()
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		assert( ...
			nne.isChecked(prop), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			['NNClassifierMLP_Evaluator_VOIs.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNClassifierMLP_Evaluator_VOIs
	nne_0 = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	% NNClassifierMLP_Evaluator_VOIs with 1st callbacks
	nne_1 = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, nne_0.getCallback(4), ..., ...
		NNClassifierMLP_Evaluator_VOIs.ID, nne_0.getCallback(5), ..., ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, nne_0.getCallback(9), ..., ...
		NNClassifierMLP_Evaluator_VOIs.D, nne_0.getCallback(10), ..., ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, nne_0.getCallback(13), ..., ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, nne_0.getCallback(16) ... ...
		);
	 
	prop_number = NNClassifierMLP_Evaluator_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_1.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNClassifierMLP_Evaluator_VOIs with 2nd callbacks
	nne_2 = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, nne_1.getCallback(4), ..., ...
		NNClassifierMLP_Evaluator_VOIs.ID, nne_1.getCallback(5), ..., ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, nne_1.getCallback(9), ..., ...
		NNClassifierMLP_Evaluator_VOIs.D, nne_1.getCallback(10), ..., ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, nne_1.getCallback(13), ..., ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, nne_1.getCallback(16) ... ...
		);
	 
	prop_number = NNClassifierMLP_Evaluator_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_2.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNClassifierMLP_Evaluator_VOIs with 3rd callbacks
	nne_3 = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, nne_2.getCallback(4), ..., ...
		NNClassifierMLP_Evaluator_VOIs.ID, nne_2.getCallback(5), ..., ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, nne_2.getCallback(9), ..., ...
		NNClassifierMLP_Evaluator_VOIs.D, nne_2.getCallback(10), ..., ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, nne_2.getCallback(13), ..., ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, nne_2.getCallback(16) ... ...
		);
	 
	prop_number = NNClassifierMLP_Evaluator_VOIs.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_3.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nne = NNClassifierMLP_Evaluator_VOIs();
	 
	nne_copy = nne.copy();
	 
	assert(nne_copy ~= nne, ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nne_copy, nne), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nne_copy.isLocked(prop) == nne.isLocked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nne_copy.isChecked(prop) == nne.isChecked(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		if NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs']);
			% nne.memorize(prop);
			% warning(warning_backup)
		elseif NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop) == Category.EVANESCENT && nne.getPropFormat(prop) == Format.HANDLE
			nne.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNClassifierMLP_Evaluator_VOIs');
			delete(ancestor(nne.get(prop), 'figure'))
			warning(warning_backup)
		else
			nne.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nne_copy = nne.copy();
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nne_copy.isLocked(prop) == nne.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.isChecked(prop) == nne.isChecked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nne_0 = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, nne_0.getCallback(4), ..., ...
		NNClassifierMLP_Evaluator_VOIs.ID, nne_0.getCallback(5), ..., ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, nne_0.getCallback(9), ..., ...
		NNClassifierMLP_Evaluator_VOIs.D, nne_0.getCallback(10), ..., ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, nne_0.getCallback(13), ..., ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, nne_0.getCallback(16) ... ...
		);
	 
	nne_copy = nne.copy();
	nne_0_copy = nne_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
							'NNClassifierMLP_Evaluator_VOIs.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nne_0.getCallback(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The callback should be obtained from NNClassifierMLP_Evaluator_VOIs.getCallback().' ...
						)
					assert( ...
						value_copy == nne_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The callback should be obtained from NNClassifierMLP_Evaluator_VOIs.getCallback().' ...
						)
				end
	 
					assert( ...
						nne_copy.isLocked(prop) == nne.isLocked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.isChecked(prop) == nne.isChecked(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne_template = NNClassifierMLP_Evaluator_VOIs();
	nne = NNClassifierMLP_Evaluator_VOIs('TEMPLATE', nne_template);
	 
	for prop = 1:1:NNClassifierMLP_Evaluator_VOIs.getPropNumber()
	 
		% excluded props
		if any(prop == [NNClassifierMLP_Evaluator_VOIs.PFROC])
			continue
		end
	 
		TAG = upper(NNClassifierMLP_Evaluator_VOIs.getPropTag(prop));
		switch NNClassifierMLP_Evaluator_VOIs.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNClassifierMLP_Evaluator_VOIs.TEMPLATE
					assert( ...
						isa(nne.getr(prop), 'NNClassifierMLP_Evaluator_VOIs'), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs.getr(''TEMPLATE'') should be a NNClassifierMLP_Evaluator_VOIs element.' ...
						)
					assert( ...
						isa(nne_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						'NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nne.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nne.getr(prop).get('EL') == nne_template && nne.getr(prop).get('PROP') == prop && strcmp(nne.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') should be a Callback to nne_template.' TAG '.'] ...
						)
					assert( ...
						isa(nne_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
						['NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nne_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
					['NNClassifierMLP_Evaluator_VOIs TEMPLATE does not work. NNClassifierMLP_Evaluator_VOIs_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnclassifiermlp_evaluator_vois_to_be_erased.b2'];
	 
	Element.save(nne, filename)
	 
	nne_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nne.copy(), nne_loaded), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.save(nne) and/or NNClassifierMLP_Evaluator_VOIs.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNClassifierMLP_Evaluator_VOIs( ...
		NNClassifierMLP_Evaluator_VOIs.ELCLASS, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NAME, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.DESCRIPTION, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.TEMPLATE, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.TEMPLATE), ...
		NNClassifierMLP_Evaluator_VOIs.ID, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.ID), ...
		NNClassifierMLP_Evaluator_VOIs.LABEL, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.LABEL), ...
		NNClassifierMLP_Evaluator_VOIs.NOTES, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NOTES), ...
		NNClassifierMLP_Evaluator_VOIs.TOSTRING, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.NN, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.NN), ...
		NNClassifierMLP_Evaluator_VOIs.D, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D), ...
		NNClassifierMLP_Evaluator_VOIs.GROUND_TRUTH, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.PFROC, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.PFROC), ...
		NNClassifierMLP_Evaluator_VOIs.MACRO_AUC, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.C_MATRIX, NNClassifierMLP_Evaluator_VOIs.getNoValue(), ...
		NNClassifierMLP_Evaluator_VOIs.D_VOIS, NNClassifierMLP_Evaluator_VOIs.getPropDefault(NNClassifierMLP_Evaluator_VOIs.D_VOIS) ...
		);
	 
	[json, struct, el_list] = encodeJSON(nne);
	[nne_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nne_dec ~= nne, ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		'NNClassifierMLP_Evaluator_VOIs.encodeJSON() or NNClassifierMLP_Evaluator_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNClassifierMLP_Evaluator_VOIs.getPropFormat(prop), num2cell(NNClassifierMLP_Evaluator_VOIs.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNClassifierMLP_Evaluator_VOIs.getPropFormat(prop), num2cell(NNClassifierMLP_Evaluator_VOIs.getProps())) == Format.NET)
		assert(isequal(nne_dec, nne), ...
			[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
			'NNClassifierMLP_Evaluator_VOIs.encodeJSON() or NNClassifierMLP_Evaluator_VOIs.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Evaluate a classifier with the example data and variable of interest
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	% Step 1: Ensure example data exists
	data_dir = [fileparts(which('NNDataPoint_VOIs')) filesep 'Example data NN CLA CON XLS VOIs'];
	if ~isfile([data_dir filesep 'atlas.xlsx'])
	    create_data_NN_CLA_CON_XLS(data_dir); % Generate example files with VOIs
	end
	
	% Step 2: Load Brain Atlas
	im_ba = ImporterBrainAtlasXLS('FILE', [data_dir filesep 'atlas.xlsx'], 'WAITBAR', true);
	ba = im_ba.get('BA');
	
	% Step 3: Load Groups of SubjectCON (primary connectivity data)
	im_gr1 = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [data_dir filesep 'CON_Group_1_XLS'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	);
	gr1 = im_gr1.get('GR');
	
	im_gr2 = ImporterGroupSubjectCON_XLS( ...
	    'DIRECTORY', [data_dir filesep 'CON_Group_2_XLS'], ...
	    'BA', ba, ...
	    'WAITBAR', true ...
	);
	gr2 = im_gr2.get('GR');
	
	% Step 4: Create NNDataPoint_CON_CLA for primary connectivity data
	% Group 1
	sub_dict1 = gr1.get('SUB_DICT');
	sub_list1 = sub_dict1.get('IT_LIST');
	[~, group_folder_name1] = fileparts(im_gr1.get('DIRECTORY'));
	it_list1 = cellfun(@(x) NNDataPoint_CON_CLA( ...
	    'ID', x.get('ID'), ...
	    'SUB', x, ...
	    'TARGET_CLASS', {group_folder_name1}), ...
	    sub_list1, 'UniformOutput', false);
	
	% Group 2
	sub_dict2 = gr2.get('SUB_DICT');
	sub_list2 = sub_dict2.get('IT_LIST');
	[~, group_folder_name2] = fileparts(im_gr2.get('DIRECTORY'));
	it_list2 = cellfun(@(x) NNDataPoint_CON_CLA( ...
	    'ID', x.get('ID'), ...
	    'SUB', x, ...
	    'TARGET_CLASS', {group_folder_name2}), ...
	    sub_list2, 'UniformOutput', false);
	
	% Create IndexedDictionary for primary data
	dp_list1 = IndexedDictionary('IT_CLASS', 'NNDataPoint_CON_CLA', 'IT_LIST', it_list1);
	dp_list2 = IndexedDictionary('IT_CLASS', 'NNDataPoint_CON_CLA', 'IT_LIST', it_list2);
	
	% Create NNDataset for primary data
	d1 = NNDataset('DP_CLASS', 'NNDataPoint_CON_CLA', 'DP_DICT', dp_list1);
	d2 = NNDataset('DP_CLASS', 'NNDataPoint_CON_CLA', 'DP_DICT', dp_list2);
	
	% Split primary datasets into training and test sets (70% training, 30% test)
	d_split1 = NNDatasetSplit('D', d1, 'SPLIT', {0.7, 0.3});
	d_split2 = NNDatasetSplit('D', d2, 'SPLIT', {0.7, 0.3});
	
	% Combine training and test sets for primary data
	d_training = NNDatasetCombine('D_LIST', {d_split1.get('D_LIST_IT', 1), d_split2.get('D_LIST_IT', 1)}).get('D');
	d_test = NNDatasetCombine('D_LIST', {d_split1.get('D_LIST_IT', 2), d_split2.get('D_LIST_IT', 2)}).get('D');
	
	% Step 5: Create NNDataPoint_VOIs for VOI data  data using gr.get('VOIS')
	% Group 1
	it_list_voi1 = cellfun(@(sub) NNDataPoint_VOIs( ...
	    'ID', sub.get('ID'), ...
	    'VOI_DICT', IndexedDictionary( ...
	        'ID', 'subject_idict', ...
	        'IT_CLASS', 'SubjectCON', ... % Adjusted to match SubjectCON
	        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
	        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
	    ), ...
	    'TARGET_CLASS', {group_folder_name1} ...
	), sub_list1, 'UniformOutput', false);
	
	% Group 2
	it_list_voi2 = cellfun(@(sub) NNDataPoint_VOIs( ...
	    'ID', sub.get('ID'), ...
	    'VOI_DICT', IndexedDictionary( ...
	        'ID', 'subject_idict', ...
	        'IT_CLASS', 'SubjectCON', ...
	        'IT_KEY', IndexedDictionary.getPropDefault(IndexedDictionary.IT_KEY), ...
	        'IT_LIST', sub.get('VOI_DICT').get('IT_LIST') ...
	    ), ...
	    'TARGET_CLASS', {group_folder_name2} ...
	), sub_list2, 'UniformOutput', false);
	
	% Create IndexedDictionary for VOI data
	voi_dp_list1 = IndexedDictionary('IT_CLASS', 'NNDataPoint_VOIs', 'IT_LIST', it_list_voi1);
	voi_dp_list2 = IndexedDictionary('IT_CLASS', 'NNDataPoint_VOIs', 'IT_LIST', it_list_voi2);
	
	% Create NNDataset for VOI data
	d_vois1 = NNDataset('DP_CLASS', 'NNDataPoint_VOIs', 'DP_DICT', voi_dp_list1);
	d_vois2 = NNDataset('DP_CLASS', 'NNDataPoint_VOIs', 'DP_DICT', voi_dp_list2);
	
	% Split VOI datasets into training and test sets (same split as primary data)
	d_vois_split1 = NNDatasetSplit('D', d_vois1, 'SPLIT', {0.7, 0.3});
	d_vois_split2 = NNDatasetSplit('D', d_vois2, 'SPLIT', {0.7, 0.3});
	
	% Combine training and test sets for VOI data
	d_vois_training = NNDatasetCombine('D_LIST', {d_vois_split1.get('D_LIST_IT', 1), d_vois_split2.get('D_LIST_IT', 1)}).get('D');
	d_vois_test = NNDatasetCombine('D_LIST', {d_vois_split1.get('D_LIST_IT', 2), d_vois_split2.get('D_LIST_IT', 2)}).get('D');
	
	% Step 6: Define and train the neural network with VOIs
	nn = NNClassifierMLP_VOIs( ...
	    'D', d_training, ...
	    'D_VOIS', d_vois_training, ...
	    'LAYERS', [128 128], ...
	    'VOI_SELECTION', {'Age', 'Sex'} ...
	);
	nn.get('TRAIN');
	
	% Step 7: Evaluate the classifier with the test set
	nne_test = NNClassifierMLP_Evaluator_VOIs('D', d_test, 'D_VOIS', d_vois_test, 'NN', nn);
	confusion_matrix = nne_test.get('C_MATRIX');
	auc = nne_test.get('AUC');
	av_auc = nne_test.get('MACRO_AUC');
	
	% Step 8: Assertions
	% Assert that accuracy is high (e.g., >= 0.9)
	assert(av_auc >= 0.9, ...
	    [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	    'NNClassifierMLP_VOIs failed to achieve sufficient accuracy with VOI-only differences. Expected >= 90%, got %.2f%%.', av_auc * 100 ...
	);
	
	% Check if the number of fully connected layers matches the specified LAYERS property
	trained_model = nn.get('MODEL');
	assert(length(nn.get('LAYERS')) == sum(contains({trained_model.Layers.Name}, 'Dense')) - 1, ...
	    [BRAPH2.STR ':NNClassifierMLP_VOIs:' BRAPH2.FAIL_TEST], ...
	    'NNClassifierMLP_VOIs does not construct the layers correctly. The number of hidden layers should match the specified LAYERS property.' ...
	);
	
	
	% Check whether the ground truth are derived as expected
	ground_truth = nne_test.get('GROUND_TRUTH');
	targets = nne_test.get('NN').get('TARGET_CLASSES', d_test);
	
	for i = 1:size(ground_truth, 1)
	    check(i) = isequal(targets{i}, ground_truth{i});
	end
	assert(all(check), ...
	    [BRAPH2.STR ':NNEvaluator_CLA:' BRAPH2.FAIL_TEST], ...
	    'NNEvaluator_CLA does not calculate the ground truth correctly.' ...
	    )
	
	% Check whether the number of predictions are the same as the input datapoints
	predictions = cell2mat(nne_test.get('NN').get('PREDICT', nne_test.get('D'),nne_test.get('D_VOIS')));
	num_predictions = length(predictions);
	num_datapoints = nne_test.get('D').get('DP_DICT').get('LENGTH');
	assert(isequal(num_predictions, num_datapoints), ...
	    [BRAPH2.STR ':NNEvaluator_CLA:' BRAPH2.FAIL_TEST], ...
	    'NNEvaluator_CLA does not calculate the predictions correctly.' ...
	    )
	
	% Check whether the dimension of the confusion matrix matches with the number of classes
	c_matrix = nne_test.get('C_MATRIX');
	dim_c = size(c_matrix, 1);
	num_classes = numel(nne_test.get('NN').get('MODEL').Layers(end).Classes);
	assert(isequal(dim_c, num_classes), ...
	    [BRAPH2.STR ':NNEvaluator_CLA:' BRAPH2.FAIL_TEST], ...
	    'NNEvaluator_CLA does not calculate the confusion matrix correctly.' ...
	    )
	
	% Check whether the dimension of the AUC matches with the number of classes
	auc = nne_test.get('AUC');
	dim_auc = length(auc);
	num_classes = numel(nne_test.get('NN').get('MODEL').Layers(end).Classes);
	assert(isequal(dim_auc, num_classes), ...
	    [BRAPH2.STR ':NNEvaluator_CLA:' BRAPH2.FAIL_TEST], ...
	    'NNEvaluator_CLA does not calculate the confusion matrix correctly.' ...
	    )
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNClassifierMLP_Evaluator_VOIs:' BRAPH2.FAIL_TEST], ...
		[' When testing NNClassifierMLP_Evaluator_VOIs no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

