%TEST_SUBJECTNIFTI

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	sub = SubjectNIfTI();
	 
	% get('ELCLASS')
	if isa(SubjectNIfTI, 'ConcreteElement')
		assert(strcmp(SubjectNIfTI().get('ELCLASS'), 'SubjectNIfTI'), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI().get(''ELCLASS'') should return ''SubjectNIfTI''.')
	end
	 
	% getBuild()
	assert(SubjectNIfTI.getBuild() == 1 && SubjectNIfTI.getBuild() > 0, ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getBuild() should return the SubjectNIfTI build number.')
	assert(sub.getBuild() == 1 && sub.getBuild() > 0 , ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getBuild() should return the SubjectNIfTI build number.')
	assert(Element.getBuild(sub) == 1 && Element.getBuild(sub) > 0, ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(sub) should return the SubjectNIfTI build number.')
	assert(Element.getBuild('SubjectNIfTI') == 1 && Element.getBuild('SubjectNIfTI') > 0, ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SubjectNIfTI'') should return the SubjectNIfTI build number.')
	 
	% getClass()
	assert(strcmp(SubjectNIfTI.getClass(), 'SubjectNIfTI'), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getClass() should return ''SubjectNIfTI''.')
	assert(strcmp(sub.getClass(), 'SubjectNIfTI'), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getClass() should return ''SubjectNIfTI''.')
	assert(strcmp(Element.getClass(sub), 'SubjectNIfTI'), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(sub) should return ''SubjectNIfTI''.')
	assert(strcmp(Element.getClass('SubjectNIfTI'), 'SubjectNIfTI'), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SubjectNIfTI'') should return ''SubjectNIfTI''.')
	 
	% getSubclasses()
	assert(isequal(SubjectNIfTI.getSubclasses(), subclasses('SubjectNIfTI', [], [], true)), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getSubclasses() should return the same result as subclasses(''SubjectNIfTI'', [], [], true).')
	assert(isequal(sub.getSubclasses(), subclasses('SubjectNIfTI', [], [], true)), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SubjectNIfTI'', [], [], true).')
	assert(isequal(Element.getSubclasses(sub), subclasses('SubjectNIfTI', [], [], true)), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(sub) should return the same result as subclasses(''SubjectNIfTI'', [], [], true).')
	assert(isequal(Element.getSubclasses('SubjectNIfTI'), subclasses('SubjectNIfTI', [], [], true)), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SubjectNIfTI'') should return the same result as subclasses(''SubjectNIfTI'', [], [], true).')
	 
	% getProps()
	assert(isempty(SubjectNIfTI.getProps()) || isequal(SubjectNIfTI.getProps(), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectNIfTI.getProps()) || isequal(sub.getProps(), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getProps() should return a row vector [1:1:N].')
	assert(isempty(SubjectNIfTI.getProps()) || isequal(Element.getProps(sub), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub) should return a row vector [1:1:N].')
	assert(isempty(SubjectNIfTI.getProps()) || isequal(Element.getProps('SubjectNIfTI'), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectNIfTI'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SubjectNIfTI.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getProps(category) does not work.')
	tmp = cellfun(@(category) sub.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(sub, category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(sub, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SubjectNIfTI', category), categories, 'UniformOutput', false);
	assert(isempty(SubjectNIfTI.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SubjectNIfTI.getProps())), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SubjectNIfTI'', category) does not work.')
	 
	% getPropNumber()
	assert(SubjectNIfTI.getPropNumber() == length(SubjectNIfTI.getProps()), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getPropNumber() should return the number of properties.')
	assert(sub.getPropNumber() == length(SubjectNIfTI.getProps()), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(sub) == length(SubjectNIfTI.getProps()), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub) should return the number of properties.')
	assert(Element.getPropNumber('SubjectNIfTI') == length(SubjectNIfTI.getProps()), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectNIfTI'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SubjectNIfTI.getPropNumber(category), categories)) == SubjectNIfTI.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) sub.getPropNumber(category), categories)) == SubjectNIfTI.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(sub, category), categories)) == SubjectNIfTI.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(sub, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SubjectNIfTI', category), categories)) == SubjectNIfTI.getPropNumber(), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SubjectNIfTI'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SubjectNIfTI.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.existsProp(prop) does not work.')
	assert(~sub.existsProp(NaN), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.existsProp(prop) does not work.')
	assert(~Element.existsProp(sub, NaN), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(sub, prop) does not work.')
	assert(~Element.existsProp('SubjectNIfTI', NaN), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SubjectNIfTI'', prop) does not work.')
	 
	assert_with_error('SubjectNIfTI.existsProp(NaN)', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsProp(''SubjectNIfTI'', NaN)', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		assert(SubjectNIfTI.existsProp(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.existsProp(prop) does not work.')
		assert(sub.existsProp(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.existsProp(prop) does not work.')
		assert(Element.existsProp(sub, prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(sub, prop) does not work.')
		assert(Element.existsProp('SubjectNIfTI', prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SubjectNIfTI'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SubjectNIfTI.existsTag(''), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.existsTag(tag) does not work.')
	assert(~sub.existsTag(''), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'sub.existsTag(tag) does not work.')
	assert(~Element.existsTag(sub, ''), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(sub, tag) does not work.')
	assert(~Element.existsTag('SubjectNIfTI', ''), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SubjectNIfTI'', tag) does not work.')
	 
	assert_with_error('SubjectNIfTI.existsTag('''')', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], sub)
	assert_with_error('Element.existsTag(''SubjectNIfTI'', '''')', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
		assert(SubjectNIfTI.existsTag(tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.existsTag(tag) does not work.')
		assert(sub.existsTag(tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.existsTag(tag) does not work.')
		assert(Element.existsTag(sub, tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(sub, tga) does not work.')
		assert(Element.existsTag('SubjectNIfTI', tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		assert(SubjectNIfTI.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropProp(prop) does not work.')
		assert(sub.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(prop) does not work.')
		assert(Element.getPropProp(sub, prop) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, prop) does not work.')
		assert(Element.getPropProp('SubjectNIfTI', prop) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectNIfTI'', prop) does not work.')
	 
		tag = sub.getPropTag(prop);
		assert(SubjectNIfTI.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropProp(tag) does not work.')
		assert(sub.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropProp(tag) does not work.')
		assert(Element.getPropProp(sub, tag) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(sub, tag) does not work.')
		assert(Element.getPropProp('SubjectNIfTI', prop) == prop, ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(strcmp(SubjectNIfTI.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropTag(prop) does not work.')
		assert(strcmp(sub.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(sub, prop), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, prop) does not work.')
		assert(strcmp(Element.getPropTag('SubjectNIfTI', prop), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectNIfTI'', prop) does not work.')
	 
		assert(strcmp(SubjectNIfTI.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropTag(tag) does not work.')
		assert(strcmp(sub.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(sub, tag), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(sub, tag) does not work.')
		assert(strcmp(Element.getPropTag('SubjectNIfTI', prop), tag), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Category.existsCategory(SubjectNIfTI.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectNIfTI'', prop) does not work.')
	 
		assert(Category.existsCategory(SubjectNIfTI.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(sub.getPropCategory(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(sub, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(Format.existsFormat(SubjectNIfTI.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectNIfTI'', prop) does not work.')
	 
		assert(Format.existsFormat(SubjectNIfTI.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(sub.getPropFormat(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(sub, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(ischar(SubjectNIfTI.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropDescription(prop) does not work.')
		assert(ischar(sub.getPropDescription(prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, prop) does not work.')
		assert(ischar(Element.getPropDescription(sub, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectNIfTI'', prop) does not work.')
	 
		assert(ischar(SubjectNIfTI.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.getPropDescription(tag) does not work.')
		assert(ischar(sub.getPropDescription(tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(sub, tag) does not work.')
		assert(ischar(Element.getPropDescription(sub, tag)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SubjectNIfTI'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		settings = SubjectNIfTI.getPropSettings(prop);
		settings = sub.getPropSettings(prop);
		settings = Element.getPropSettings(sub, prop);
		settings = Element.getPropSettings('SubjectNIfTI', prop);
	 
		settings = SubjectNIfTI.getPropSettings(tag);
		settings = sub.getPropSettings(tag);
		settings = Element.getPropSettings(sub, tag);
		settings = Element.getPropSettings('SubjectNIfTI', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		default = SubjectNIfTI.getPropDefault(prop);
		default = sub.getPropDefault(prop);
		default = Element.getPropDefault(sub, prop);
		default = Element.getPropDefault('SubjectNIfTI', prop);
	 
		default = SubjectNIfTI.getPropDefault(tag);
		default = sub.getPropDefault(tag);
		default = Element.getPropDefault(sub, tag);
		default = Element.getPropDefault('SubjectNIfTI', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		conditioned_default = SubjectNIfTI.getPropDefaultConditioned(prop);
		conditioned_default = sub.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(sub, prop);
		conditioned_default = Element.getPropDefaultConditioned('SubjectNIfTI', prop);
	 
		conditioned_default = SubjectNIfTI.getPropDefaultConditioned(tag);
		conditioned_default = sub.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(sub, tag);
		conditioned_default = Element.getPropDefaultConditioned('SubjectNIfTI', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		tag = sub.getPropTag(prop);
	 
		assert(~SubjectNIfTI.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.checkProp(prop, value) does not work.')
		assert(~sub.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(sub, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, value) does not work.')
		assert(~Element.checkProp('SubjectNIfTI', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNIfTI'', prop, value) does not work.')
	 
		assert_with_error('SubjectNIfTI.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], prop, sub)
		assert_with_error('Element.checkProp(''SubjectNIfTI'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SubjectNIfTI.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.checkProp(tag, value) does not work.')
		assert(~sub.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(sub, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, value) does not work.')
		assert(~Element.checkProp('SubjectNIfTI', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNIfTI'', tag, value) does not work.')
	 
		assert_with_error('SubjectNIfTI.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], tag, sub)
		assert_with_error('Element.checkProp(''SubjectNIfTI'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SubjectNIfTI:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SubjectNIfTI.checkProp(prop, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.checkProp(prop, <conditioned default value>) does not work.')
		assert(sub.checkProp(prop, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, prop, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectNIfTI', prop, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNIfTI'', prop, <conditioned default value>) does not work.')
	 
		assert(SubjectNIfTI.checkProp(tag, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.checkProp(tag, <conditioned default value>) does not work.')
		assert(sub.checkProp(tag, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'sub.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(sub, tag, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(sub, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SubjectNIfTI', tag, Element.getPropDefaultConditioned(SubjectNIfTI, prop)), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SubjectNIfTI'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					sub.getr(prop) == SubjectNIfTI.getNoValue(), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNIfTI.getCategoryName(SubjectNIfTI.getPropCategory(prop)) ', SubjectNIfTI.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectNIfTI.getNoValue(), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNIfTI.getCategoryName(SubjectNIfTI.getPropCategory(prop)) ', SubjectNIfTI.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					sub.getr(prop) == SubjectNIfTI.getNoValue(), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNIfTI.getCategoryName(SubjectNIfTI.getPropCategory(prop)) ', SubjectNIfTI.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					sub.getr(TAG) == SubjectNIfTI.getNoValue(), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['Being a ' SubjectNIfTI.getCategoryName(SubjectNIfTI.getPropCategory(prop)) ', SubjectNIfTI.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SubjectNIfTI']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(sub.getPropSettings(prop))
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop)), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						sub.checkFormat(sub.getPropFormat(prop), sub.get(prop), sub.getPropSettings(prop)), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(sub.getr(prop), SubjectNIfTI.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SubjectNIfTI.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(sub.getr(TAG), SubjectNIfTI.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SubjectNIfTI.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SubjectNIfTI.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectNIfTI']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SubjectNIfTI']);
	% 			assert( ...
	% 				~isa(sub.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(sub.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
	% 				['SubjectNIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SubjectNIfTI']);
				assert( ...
					~isa(sub.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(sub.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					sub.checkFormat(sub.getPropFormat(prop), sub.getr(prop),sub.getPropSettings(prop)), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if sub.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SubjectNIfTI');
					delete(ancestor(sub.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SubjectNIfTI.getProps(Category.RESULT))
		for prop = 1:1:SubjectNIfTI.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch SubjectNIfTI.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI();
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		assert( ...
			~sub.isLocked(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~sub.isLocked(TAG), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	sub.lock()
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI();
	 
	warning_backup = warning('off', 'BRAPH2:SubjectNIfTI');
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		sub.lock(prop)
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI();
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			sub.isChecked(TAG), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	sub.unchecked()
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		assert( ...
			~sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	sub.checked()
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		assert( ...
			sub.isChecked(prop), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			['SubjectNIfTI.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SubjectNIfTI
	sub_0 = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	% SubjectNIfTI with 1st callbacks
	sub_1 = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectNIfTI.ID, sub_0.getCallback(5), ..., ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectNIfTI.NIFTI_PATH_DICT, sub_0.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_1.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectNIfTI with 2nd callbacks
	sub_2 = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, sub_1.getCallback(4), ..., ...
		SubjectNIfTI.ID, sub_1.getCallback(5), ..., ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, sub_1.getCallback(9), ..., ...
		SubjectNIfTI.NIFTI_PATH_DICT, sub_1.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_2.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SubjectNIfTI with 3rd callbacks
	sub_3 = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, sub_2.getCallback(4), ..., ...
		SubjectNIfTI.ID, sub_2.getCallback(5), ..., ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, sub_2.getCallback(9), ..., ...
		SubjectNIfTI.NIFTI_PATH_DICT, sub_2.getCallback(10) ... ...
		);
	 
	prop_number = SubjectNIfTI.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(sub_3.get(prop), sub_0.get(prop)) && ~isa(sub_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(sub_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	sub = SubjectNIfTI();
	 
	sub_copy = sub.copy();
	 
	assert(sub_copy ~= sub, ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(sub_copy, sub), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					sub_copy.isLocked(prop) == sub.isLocked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.isChecked(prop) == sub.isChecked(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		if SubjectNIfTI.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SubjectNIfTI']);
			% sub.memorize(prop);
			% warning(warning_backup)
		elseif SubjectNIfTI.getPropCategory(prop) == Category.EVANESCENT && sub.getPropFormat(prop) == Format.HANDLE
			sub.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SubjectNIfTI');
			delete(ancestor(sub.get(prop), 'figure'))
			warning(warning_backup)
		else
			sub.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	sub_copy = sub.copy();
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	sub_0 = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, sub_0.getCallback(4), ..., ...
		SubjectNIfTI.ID, sub_0.getCallback(5), ..., ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, sub_0.getCallback(9), ..., ...
		SubjectNIfTI.NIFTI_PATH_DICT, sub_0.getCallback(10) ... ...
		);
	 
	sub_copy = sub.copy();
	sub_0_copy = sub_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
		value = sub.getr(prop);
		value_copy = sub_copy.getr(prop);
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					'SubjectNIfTI.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
							'SubjectNIfTI.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == sub_0.getCallback(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The callback should be obtained from SubjectNIfTI.getCallback().' ...
						)
					assert( ...
						value_copy == sub_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The callback should be obtained from SubjectNIfTI.getCallback().' ...
						)
				end
	 
					assert( ...
						sub_copy.isLocked(prop) == sub.isLocked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.isChecked(prop) == sub.isChecked(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						sub_copy.getPropSeed(prop) == sub.getPropSeed(prop), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub_template = SubjectNIfTI();
	sub = SubjectNIfTI('TEMPLATE', sub_template);
	 
	for prop = 1:1:SubjectNIfTI.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(SubjectNIfTI.getPropTag(prop));
		switch SubjectNIfTI.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SubjectNIfTI.TEMPLATE
					assert( ...
						isa(sub.getr(prop), 'SubjectNIfTI'), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI TEMPLATE does not work. SubjectNIfTI.getr(''TEMPLATE'') should be a SubjectNIfTI element.' ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						'SubjectNIfTI TEMPLATE does not work. SubjectNIfTI_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(sub.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI TEMPLATE does not work. SubjectNIfTI.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						sub.getr(prop).get('EL') == sub_template && sub.getr(prop).get('PROP') == prop && strcmp(sub.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI TEMPLATE does not work. SubjectNIfTI.getr(' TAG ') should be a Callback to sub_template.' TAG '.'] ...
						)
					assert( ...
						isa(sub_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
						['SubjectNIfTI TEMPLATE does not work. SubjectNIfTI_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(sub.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI TEMPLATE does not work. SubjectNIfTI.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(sub_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
					['SubjectNIfTI TEMPLATE does not work. SubjectNIfTI_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'subjectnifti_to_be_erased.b2'];
	 
	Element.save(sub, filename)
	 
	sub_loaded = Element.load(filename);
	 
	assert( ...
		isequal(sub.copy(), sub_loaded), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.save(sub) and/or SubjectNIfTI.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	sub = SubjectNIfTI( ...
		SubjectNIfTI.ELCLASS, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.NAME, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.DESCRIPTION, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.TEMPLATE, SubjectNIfTI.getPropDefault(SubjectNIfTI.TEMPLATE), ...
		SubjectNIfTI.ID, SubjectNIfTI.getPropDefault(SubjectNIfTI.ID), ...
		SubjectNIfTI.LABEL, SubjectNIfTI.getPropDefault(SubjectNIfTI.LABEL), ...
		SubjectNIfTI.NOTES, SubjectNIfTI.getPropDefault(SubjectNIfTI.NOTES), ...
		SubjectNIfTI.TOSTRING, SubjectNIfTI.getNoValue(), ...
		SubjectNIfTI.VOI_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.VOI_DICT), ...
		SubjectNIfTI.NIFTI_PATH_DICT, SubjectNIfTI.getPropDefault(SubjectNIfTI.NIFTI_PATH_DICT) ...
		);
	 
	[json, struct, el_list] = encodeJSON(sub);
	[sub_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(sub_dec ~= sub, ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		'SubjectNIfTI.encodeJSON() or SubjectNIfTI.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SubjectNIfTI.getPropFormat(prop), num2cell(SubjectNIfTI.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SubjectNIfTI.getPropFormat(prop), num2cell(SubjectNIfTI.getProps())) == Format.NET)
		assert(isequal(sub_dec, sub), ...
			[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
			'SubjectNIfTI.encodeJSON() or SubjectNIfTI.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GUI
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% Step 1: Load Brain Atlas
	im_ba = ImporterBrainAtlasXLS('FILE', 'desikan_atlas.xlsx');
	ba = im_ba.get('BA');
	
	% Step 2: Create Group with SubjectNIfTI instances
	gr = Group('SUB_CLASS', 'SubjectNIfTI', 'SUB_DICT', IndexedDictionary('IT_CLASS', 'SubjectNIfTI'));
	for i = 1:1:50
	    sub = SubjectNIfTI( ...
	        'ID', ['SUB Nifti ' int2str(i)]);
	    % Add the file path to the subject's nifty dictionary
	    sub.memorize('NIFTI_PATH_DICT').get('ADD', FILE_PATH('ID', convertStringsToChars(string(i)), 'PATH', convertStringsToChars('*/*')));
	    sub.memorize('VOI_DICT').get('ADD', VOINumeric('ID', 'Age', 'V', 100 * rand()));
	    sub.memorize('VOI_DICT').get('ADD', VOICategoric('ID', 'Sex', 'CATEGORIES', {'Female', 'Male'}, 'V', randi(2, 1)));
	    gr.get('SUB_DICT').get('ADD', sub);
	end
	
	% Step 3: Test GUI
	gui = GUIElement('PE', gr, 'CLOSEREQ', false);
	gui.get('DRAW');
	gui.get('SHOW');
	
	% Pause for visual confirmation
	disp('GUI is open. Closing in 3 seconds...');
	pause(3);
	
	gui.get('CLOSE');
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SubjectNIfTI:' BRAPH2.FAIL_TEST], ...
		[' When testing SubjectNIfTI no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

