%EXAMPLE_NEUROIMGING_2_RVS_PET
% Script example pipeline neuroimaing (PET) conversion to
% regional values (SUVR)
clear variables %#ok<*NASGU>

%% Create dataset
example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI1'];

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
create_data_NIfTI_GMProb(atlas_path, example_data_dir)

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
create_data_NIfTI_WMProb(atlas_path, example_data_dir)

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
create_data_NIfTI_PET(atlas_path, example_data_dir)

example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI2'];

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
create_data_NIfTI_GMProb(atlas_path, example_data_dir)

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
create_data_NIfTI_WMProb(atlas_path, example_data_dir)

atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
covarying_roi_indices = [21:40];
create_data_NIfTI_PET(atlas_path, example_data_dir,[],[],[],covarying_roi_indices)
%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI1'], ...
    'MODALITY', 'pet', ...
    'TARGET', '', ...
    'WAITBAR', true ...
    );

gr_pet1 = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI1'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

gr_anat_gmprob1 = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI1'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

gr_anat_wmprob1 = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI2'], ...
    'MODALITY', 'pet', ...
    'TARGET', '', ...
    'WAITBAR', true ...
    );

gr_pet2 = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI2'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

gr_anat_gmprob2 = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI2'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

gr_anat_wmprob2 = im_gr_wm.get('GR');

%% Convert neuroimaging data to region-of-interest data
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas_mapping.csv']
    };

% set the reference brain regions for PET normalization
ref_brain_regions = {};
ref_brain_regions_idx = 95:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

% for i = 1:ba_td.get('BR_DICT').get('LENGTH') % all regions in TD
%     brain_regions_to_convert{end + 1} = ba_td.get('BR_DICT').get('IT', i).get('ID');
% end

gr1 = ConverterNeuroimaging2RegionalValues( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_pet1, ...
    'GR_LIST_ANAT_REF', {gr_anat_gmprob1, gr_anat_wmprob1}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 1.0);

gr_st1 = gr1.get('GR_ST');
ba_st = gr1.get('BA');

gr2 = ConverterNeuroimaging2RegionalValues( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', gr_pet2, ...
    'GR_LIST_ANAT_REF', {gr_anat_gmprob2, gr_anat_wmprob2}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 1.0);

gr_st2 = gr2.get('GR_ST');
%%
a_WU1 = AnalyzeGroup_ST_WU( ...
    'GR', gr_st1, ...
    'CORRELATION_RULE', Correlation.PEARSON ...
    );

a_WU2 = AnalyzeGroup_ST_WU( ...
    'TEMPLATE', a_WU1, ...
    'GR', gr_st2 ...
    );



% comparison
c_WU = CompareGroup( ...
    'P', 100, ...
    'A1', a_WU1, ...
    'A2', a_WU2, ...
    'WAITBAR', true, ...
    'VERBOSE', false, ...
    'MEMORIZE', true ...
    );

Clustering_WU_diff = c_WU.get('COMPARISON', 'Clustering').get('DIFF');
Clustering_WU_p1 = c_WU.get('COMPARISON', 'Clustering').get('P1');
Clustering_WU_p2 = c_WU.get('COMPARISON', 'Clustering').get('P2');
Clustering_WU_cil = c_WU.get('COMPARISON', 'Clustering').get('CIL');
Clustering_WU_ciu = c_WU.get('COMPARISON', 'Clustering').get('CIU');

GlobalEfficiency_av_WU_diff = c_WU.get('COMPARISON', 'GlobalEfficiency').get('DIFF');
GlobalEfficiency_av_WU_p1 = c_WU.get('COMPARISON', 'GlobalEfficiency').get('P1');
GlobalEfficiency_av_WU_p2 = c_WU.get('COMPARISON', 'GlobalEfficiency').get('P2');
GlobalEfficiency_av_WU_cil = c_WU.get('COMPARISON', 'GlobalEfficiency').get('CIL');
GlobalEfficiency_av_WU_ciu = c_WU.get('COMPARISON', 'GlobalEfficiency').get('CIU');

distance_WU_diff = c_WU.get('COMPARISON', 'Distance').get('DIFF');
distance_WU_p1 = c_WU.get('COMPARISON', 'Distance').get('P1');
distance_WU_p2 = c_WU.get('COMPARISON', 'Distance').get('P2');
distance_WU_cil = c_WU.get('COMPARISON', 'Distance').get('CIL');
distance_WU_ciu = c_WU.get('COMPARISON', 'Distance').get('CIU');

%% VISUALIZATION
c_WU.get('COMPARISON', 'Clustering').get('PFBG').set('VIEW',[0 90])
c_WU.get('COMPARISON', 'Clustering').get('PFBG').get('DRAWN')
c_WU.get('COMPARISON', 'Clustering').get('PFBG').get('DRAW')
c_WU.get('COMPARISON', 'Clustering').get('PFBG').get('SHOW')
% 
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFBG').set('VIEW',[0 90])
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFBG').get('DRAWN')
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFBG').get('DRAW')
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFBG').get('SHOW')

c_WU.get('COMPARISON', 'Strength').get('PFBG').get('DRAWN')
c_WU.get('COMPARISON', 'Strength').get('PFBG').get('DRAW')
c_WU.get('COMPARISON', 'Strength').get('PFBG').get('SHOW')