% EXAMPLE_NEUROIMGING_2_RVS_PET
% Script example pipeline neuroimaing (PET) conversion to
% regional values (SUVR)
clear variables %#ok<*NASGU>

%% Create dataset
% example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];

% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
% create_data_NIfTI_WMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_PET(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
base_Dir = '/home/hang/GitHub/IndividualConnectome-YuweiHangRefator/group_data/HangFDG_dataBIDS';
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grad_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grad_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grad_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grmci_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grcn_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_wmprob = im_gr_wm.get('GR');
%% Convert neuroimaging data to region-of-interest data
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas_mapping.csv']
    };

% set the reference brain regions for PET normalization
ref_brain_regions = {};
ref_brain_regions_idx = 120-7:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end
ref_brain_regions_idx_tds = 7;
for i = 1:length(ref_brain_regions_idx_tds)
    ref_brain_regions{end + 1} = ba_td.get('BR_DICT').get('IT', ref_brain_regions_idx_tds).get('ID');
end

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

% for i = 1:ba_td.get('BR_DICT').get('LENGTH') % all regions in TD
%     brain_regions_to_convert{end + 1} = ba_td.get('BR_DICT').get('IT', i).get('ID');
% end

ad_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','AD',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_pet, ...
    'GR_LIST_ANAT_REF', {grad_anat_gmprob, grad_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr1_pet = ad_pet.get('GR_ST');

mci_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','MCI',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_pet, ...
    'GR_LIST_ANAT_REF', {grmci_anat_gmprob, grmci_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr2_pet = mci_pet.get('GR_ST');

cn_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','CN',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_pet, ...
    'GR_LIST_ANAT_REF', {grcn_anat_gmprob, grcn_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr3_pet = cn_pet.get('GR_ST');
ba_st = cn_pet.get('BA');

ad_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','AD',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_anat_gmprob);

gr1_t1w = ad_t1w.get('GR_ST');

mci_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','MCI',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_anat_gmprob);

gr2_t1w = mci_t1w.get('GR_ST');

cn_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','CN',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_anat_gmprob);

gr3_t1w = cn_t1w.get('GR_ST');

%% Multiplex / multimodal binary classification: T1w + PET

% Use the same converted brain atlas for all regional vectors.
% It should have the same number/order of regions as both gr*_t1w and gr*_pet.
ba_st = cn_pet.get('BA');  % or cn_t1w.get('BA'), if identical

layer_labels = {'T1w_GMprob', 'PET_SUVR'};

% Build SubjectST_MP groups:
% layer 1 = T1w regional GM probability
% layer 2 = PET SUVR regional values
gr1_t1w_pet = make_ST_MP_from_ST_groups( ...
    'AD', ba_st, gr1_t1w, gr1_pet, layer_labels);

gr2_t1w_pet = make_ST_MP_from_ST_groups( ...
    'MCI', ba_st, gr2_t1w, gr2_pet, layer_labels);

gr3_t1w_pet = make_ST_MP_from_ST_groups( ...
    'CN', ba_st, gr3_t1w, gr3_pet, layer_labels);

% Convert groups to NN datasets.
% NNDataPoint_ST_MM_CLA expects SubjectST_MP input; its INPUT is the
% subject ST_MP cell array. 
AD_mp = AnalyzeGroup_ST_MP_WU('GR', gr1_t1w_pet,'CORRELATION_RULE', Correlation.PEARSON); % Analyze ensemble for CN_pos group
MCI_mp = AnalyzeGroup_ST_MP_WU('GR', gr2_t1w_pet,'CORRELATION_RULE', Correlation.PEARSON); % Analyze ensemble for CN_pos group
CN_mp = AnalyzeGroup_ST_MP_WU('GR', gr3_t1w_pet,'CORRELATION_RULE', Correlation.PEARSON); % Analyze ensemble for CN_pos group

dp_list1 = cellfun(@(sub) NNDataPoint_ST_CLA('ID', sub.get('ID'), ...
    'SUB', sub, 'TARGET_CLASS', {'negative'}), ...
    gr1_t1w_pet.get('SUB_DICT').get('IT_LIST'), 'UniformOutput', false);
dp_list2 = cellfun(@(sub) NNDataPoint_ST_CLA('ID', sub.get('ID'), ...
    'SUB', sub, 'TARGET_CLASS', {'positive'}), ...
    {AD_mp.get('GR').get('SUB_DICT').get('IT_LIST')}, 'UniformOutput', false);
% 
% d1 = make_dataset_ST_MM_CLA(gr1_t1w_pet);
% d2 = make_dataset_ST_MM_CLA(gr2_t1w_pet);
% d3 = make_dataset_ST_MM_CLA(gr3_t1w_pet);

%% Binary classifications

% AD vs CN
nncv_ad_cn = NNClassifierMLP_CrossValidation( ...
    'D', {d1, d3}, ...
    'KFOLDS', 5 ...
    );
nncv_ad_cn.get('TRAIN');

% AD vs MCI
nncv_ad_mci = NNClassifierMLP_CrossValidation( ...
    'D', {d1, d2}, ...
    'KFOLDS', 5 ...
    );
nncv_ad_mci.get('TRAIN');

% MCI vs CN
nncv_mci_cn = NNClassifierMLP_CrossValidation( ...
    'D', {d2, d3}, ...
    'KFOLDS', 5 ...
    );
nncv_mci_cn.get('TRAIN');

%% Display results

print_nncv_results(nncv_ad_cn,  'AD vs CN');
print_nncv_results(nncv_ad_mci, 'AD vs MCI');
print_nncv_results(nncv_mci_cn, 'MCI vs CN');
function gr_mp = make_ST_MP_from_ST_groups(gr_id, ba, gr_t1w, gr_pet, layer_labels)

    sub_list_t1w = gr_t1w.get('SUB_DICT').get('IT_LIST');
    sub_list_pet = gr_pet.get('SUB_DICT').get('IT_LIST');

    pet_ids = cellfun(@(s) s.get('ID'), sub_list_pet, 'UniformOutput', false);

    n_sub = length(sub_list_t1w);
    it_list = cell(1, n_sub);

    br_number = ba.get('BR_DICT').get('LENGTH');

    fprintf('Building SubjectST_MP group %s: %d subjects\n', gr_id, n_sub)

    for i = 1:n_sub
        sub_t1w = sub_list_t1w{i};
        sid = sub_t1w.get('ID');

        match_idx = find(strcmp(pet_ids, sid), 1);

        if isempty(match_idx)
            error('Missing PET subject with ID "%s" in group "%s".', sid, gr_id);
        end

        sub_pet = sub_list_pet{match_idx};

        t1w_vec = sub_t1w.get('ST');
        pet_vec = sub_pet.get('ST');

        % Important for SubjectST_MP: each layer should be one regional column vector.
        t1w_vec = t1w_vec(:);
        pet_vec = pet_vec(:);

        if length(t1w_vec) ~= length(pet_vec)
            error( ...
                'ROI mismatch for subject "%s" in group "%s": T1w has %d regions, PET has %d regions.', ...
                sid, gr_id, length(t1w_vec), length(pet_vec) ...
                );
        end

        if length(t1w_vec) ~= br_number
            error( ...
                'Atlas mismatch for subject "%s" in group "%s": data has %d regions, atlas has %d regions.', ...
                sid, gr_id, length(t1w_vec), br_number ...
                );
        end

        it_list{i} = SubjectST_MP( ...
            'ID', sid, ...
            'BA', ba, ...
            'L', 2, ...
            'LAYERLABELS', layer_labels(:), ...
            'ST_MP', {t1w_vec, pet_vec} ...
            );
    end

    % Important:
    % Use IT_CLASS = 'Subject', not 'SubjectST_MP'.
    % The actual stored objects are still SubjectST_MP.
    sub_dict = IndexedDictionary( ...
        'IT_CLASS', 'Subject', ...
        'IT_LIST', it_list ...
        );

    gr_mp = Group( ...
        'ID', gr_id, ...
        'SUB_CLASS', 'SubjectST_MP', ...
        'SUB_DICT', sub_dict ...
        );

    % Do not do this here:
    % gr_mp = AnalyzeEnsemble_CON_MP_WU('GR', gr_mp);
    %
    % For NN classification, gr_mp must remain a Group containing SubjectST_MP.
end
function d = make_dataset_ST_MM_CLA(gr_mp)

    sub_list = gr_mp.get('SUB_DICT').get('IT_LIST');

    it_list = cellfun(@(x) NNDataPoint_ST( ...
        'ID', x.get('ID'), ...
        'SUB', x, ...
        'TARGET_CLASS', {gr_mp.get('ID')} ...
        ), ...
        sub_list, ...
        'UniformOutput', false);

    dp_dict = IndexedDictionary( ...
        'IT_CLASS', 'NNDataPoint_ST', ...
        'IT_LIST', it_list ...
        );

    d = NNDataset( ...
        'DP_CLASS', 'NNDataPoint_ST', ...
        'DP_DICT', dp_dict ...
        );
end
function print_nncv_results(nncv, title_str)

    fprintf('\n==============================\n')
    fprintf('%s\n', title_str)
    fprintf('==============================\n')

    confusion_matrix = nncv.get('C_MATRIX');
    av_auc = nncv.get('AV_AUC');
    av_macro_auc = nncv.get('AV_MACRO_AUC');

    fprintf('Confusion matrix:\n')
    disp(confusion_matrix)

    fprintf('Average AUC:\n')
    disp(av_auc)

    fprintf('Average macro AUC:\n')
    disp(av_macro_auc)
end