%EXAMPLE_NEUROIMGING_2_RVS_PET
% Script example pipeline neuroimaing (PET) conversion to
% regional values (SUVR)
clear variables %#ok<*NASGU>

%% Create dataset
% example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];

% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
% create_data_NIfTI_WMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_PET(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
base_Dir = '/home/hang/GitHub/IndividualConnectome-YuweiHangRefator/group_data/HangFDG_dataBIDS';
im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grad_anat_gmprob = im_gr_gm.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_gmprob = im_gr_gm.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_gmprob = im_gr_gm.get('GR');

%% Convert neuroimaging data to region-of-interest data
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']};
ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']};

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

ad = ConverterNeuroimaging2RegionalValues( ...
    'ID','AD',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr1 = ad.get('GR_ST');

mci = ConverterNeuroimaging2RegionalValues( ...
    'ID','MCI',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr2 = mci.get('GR_ST');

cn = ConverterNeuroimaging2RegionalValues( ...
    'ID','CN',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr3 = cn.get('GR_ST');
ba_st = cn.get('BA');
%% Training-test split
% create item lists of NNDataPoint_ST_CLA
it_list1 = cellfun(@(x) NNDataPoint_ST_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {ad.get('ID')}), ...
    gr1.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

it_list2 = cellfun(@(x) NNDataPoint_ST_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {mci.get('ID')}), ...
    gr2.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

it_list3 = cellfun(@(x) NNDataPoint_ST_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {cn.get('ID')}), ...
    gr3.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% create NNDataPoint_ST_CLA DICT items
dp_list1 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_CLA', ...
        'IT_LIST', it_list1 ...
        );

dp_list2 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_CLA', ...
        'IT_LIST', it_list2 ...
        );

dp_list3 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_CLA', ...
        'IT_LIST', it_list3 ...
        );

% create a NNDataset containing the NNDataPoint_ST_CLA DICT
d1 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_CLA', ...
    'DP_DICT', dp_list1 ...
    );

d2 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_CLA', ...
    'DP_DICT', dp_list2 ...
    );

d3 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_CLA', ...
    'DP_DICT', dp_list3 ...
    );

%% Create classifier cross-validation

n_repeats = 10;
kfolds = 4;

confusion_matrix_cnmci = cell(1, n_repeats);
confusion_matrix_cnad  = cell(1, n_repeats);

av_macro_auc_cnmci = cell(1, n_repeats);
av_macro_auc_cnad  = cell(1, n_repeats);

split_index_cnmci_all = cell(1, n_repeats);
split_index_cnad_all  = cell(1, n_repeats);

nn_template_local = NNClassifierMLP( ...
    'EPOCHS', 75, ...
    'LAYERS', [128 128] ...
    );

parfor h = 1:n_repeats

    seed_split = h;

    % Optional but useful for reproducibility of NN initialization
    rng(seed_split)

    %% CN vs MCI
    % Dataset order:
    %   d3 = CN
    %   d2 = MCI
    split_index_cnmci = make_kfold_split_index({d3, d2}, kfolds, seed_split);

    nncvcn_mci = NNClassifierMLP_CrossValidation( ...
        'D', {d3, d2}, ...
        'KFOLDS', kfolds, ...
        'SPLIT', split_index_cnmci, ...
        'NN_TEMPLATE', nn_template_local ...
        );

    nncvcn_mci.get('TRAIN');

    confusion_matrix_cnmci{h} = nncvcn_mci.get('C_MATRIX');
    av_macro_auc_cnmci{h} = nncvcn_mci.get('AV_MACRO_AUC');
    split_index_cnmci_all{h} = split_index_cnmci;


    %% CN vs AD
    % Dataset order:
    %   d3 = CN
    %   d1 = AD
    split_index_cnad = make_kfold_split_index({d3, d1}, kfolds, seed_split);

    nncvcn_ad = NNClassifierMLP_CrossValidation( ...
        'D', {d3, d1}, ...
        'KFOLDS', kfolds, ...
        'SPLIT', split_index_cnad, ...
        'NN_TEMPLATE', nn_template_local ...
        );

    nncvcn_ad.get('TRAIN');

    confusion_matrix_cnad{h} = nncvcn_ad.get('C_MATRIX');
    av_macro_auc_cnad{h} = nncvcn_ad.get('AV_MACRO_AUC');
    split_index_cnad_all{h} = split_index_cnad;

end

%% Save results and split indices
save('T1wHang_CV_results.mat', ...
    'confusion_matrix_cnmci', ...
    'confusion_matrix_cnad', ...
    'av_macro_auc_cnmci', ...
    'av_macro_auc_cnad', ...
    'split_index_cnmci_all', ...
    'split_index_cnad_all' ...
    );

function split_index = make_kfold_split_index(d_list, kfolds, seed)
%MAKE_KFOLD_SPLIT_INDEX Creates BRAPH2-compatible split indices.
%
% Output:
%   split_index is n_groups x kfolds cell.
%   split_index{g, k} contains datapoint indices for group g, fold k.
%
% Important:
%   Indices are local to each dataset, not global across both groups.

    rng(seed)

    n_groups = numel(d_list);
    split_index = cell(n_groups, kfolds);

    for g = 1:n_groups
        n = d_list{g}.get('DP_DICT').get('LENGTH');

        idx = randperm(n);

        for k = 1:kfolds
            split_index{g, k} = sort(idx(k:kfolds:end));
        end
    end
end