%EXAMPLE_NEUROIMGING_2_PDFS_PET
% Script example pipeline neuroimaing (PET) conversion to
% probability density functions (PDFs)
clear variables %#ok<*NASGU>

%% Create dataset
example_data_dir =  [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example data NIfTI PDF shape covariation'];

% atlas_path = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_GMProb_PDFShape(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
% create_data_NIfTI_WMProb_PDFShape(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_PET_PDFShape(atlas_path, example_data_dir)
% 

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('ConverterNeuroimaging2PDFs')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
base_Dir = '/home/hang/GitHub/IndividualConnectome-YuweiHangRefator/group_data/HangFDG_dataBIDS';
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grad_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grad_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grad_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grmci_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grcn_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_wmprob = im_gr_wm.get('GR');
%% Convert neuroimaging data to region-of-interest data
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas_mapping.csv']
    };

% set the reference brain regions for PET normalization
ref_brain_regions = {};
ref_brain_regions_idx = 120-7:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end
ref_brain_regions_idx_tds = 7;
for i = 1:length(ref_brain_regions_idx_tds)
    ref_brain_regions{end + 1} = ba_td.get('BR_DICT').get('IT', ref_brain_regions_idx_tds).get('ID');
end

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

for i = 1:ba_td.get('BR_DICT').get('LENGTH') % all regions in TD
    brain_regions_to_convert{end + 1} = ba_td.get('BR_DICT').get('IT', i).get('ID');
end

cn = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_pet, ...
    'GR_LIST_ANAT_REF', {grcn_anat_gmprob, grcn_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'REF_TOP_PERCENTAGE', 0.5);

CN_pdfs = cn.get('GR_FUN');
ba_pdfs = cn.get('BA');


mci = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_pet, ...
    'GR_LIST_ANAT_REF', {grmci_anat_gmprob, grmci_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'REF_TOP_PERCENTAGE', 0.5);

mci_pdfs = mci.get('GR_FUN');
ba_pdfs = mci.get('BA');


ad = ConverterNeuroimaging2PDFs( ...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_pet, ...
    'GR_LIST_ANAT_REF', {grad_anat_gmprob, grad_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'PDF_METHOD', 'kde', ...
    'KDE_NUM_POINTS', 500, ...
    'REF_TOP_PERCENTAGE', 0.5);

ad_pdfs = ad.get('GR_FUN');
ba_pdfs = ad.get('BA');
%% export pdf

directory_base = [fileparts(which('hang_NNCV_PET_ST_CLA.m')) filesep 'Converted data PET PDF'];
mkdir(directory_base);
mkdir([directory_base filesep 'CN']);
ex = ExporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', [directory_base filesep 'CN'], ...
    'GR', CN_pdfs ...
    );
ex.get('SAVE');
mkdir([directory_base filesep 'AD']);
ex = ExporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', [directory_base filesep 'AD'], ...
    'GR', ad_pdfs ...
    );
ex.get('SAVE');
mkdir([directory_base filesep 'MCI']);
ex = ExporterGroupSubjectFUN_XLS( ...
    'DIRECTORY', [directory_base filesep 'MCI'], ...
    'GR', mci_pdfs ...
    );
ex.get('SAVE');
%% convert correlation conn.
cad = ConverterPDFs2CON( ...
    'GR_PDFS', ad_pdfs, ...
    'METHOD', 'correlation' ...
    );

gr_conad = cad.get('GR_CON');


cmci = ConverterPDFs2CON( ...
    'GR_PDFS', mci_pdfs, ...
    'METHOD', 'correlation' ...
    );

gr_conmci = cmci.get('GR_CON');

ccn = ConverterPDFs2CON( ...
    'GR_PDFS', CN_pdfs, ...
    'METHOD', 'correlation' ...
    );

gr_concn = ccn.get('GR_CON');

%% Export CON data
directory_base = [fileparts(which('hang_NNCV_PET_ST_CLA.m')) filesep 'Converted Correlation CON data'];

if ~isfolder(directory_base)
    mkdir(directory_base);
end
mkdir([directory_base filesep 'CN']);
mkdir([directory_base filesep 'MCI']);
mkdir([directory_base filesep 'AD']);
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [directory_base filesep 'CN'], ...
    'GR', gr_concn ...
    );

ex.get('SAVE');
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [directory_base filesep 'MCI'], ...
    'GR', gr_concn ...
    );

ex.get('SAVE');
ex = ExporterGroupSubjectCON_XLS( ...
    'DIRECTORY', [directory_base filesep 'AD'], ...
    'GR', gr_concn ...
    );

ex.get('SAVE');

file = [directory_base filesep 'brain_atlas.xlsx'];

ex = ExporterBrainAtlasXLS( ...
    'FILE', file, ...
    'BA', ba_aal120 ...
    );

ex.get('SAVE');

%% COMPARISON

a_WU1 = AnalyzeEnsemble_CON_WU( ...
    'GR', gr_conmci);

a_WU2 = AnalyzeEnsemble_CON_WU( ...
    'TEMPLATE', a_WU1, ...
    'GR', gr_concn ...
    );


% comparison
c_WU = CompareEnsemble( ...
    'P', 500, ...
    'A1', a_WU1, ...
    'A2', a_WU2, ...
    'WAITBAR', true, ...
    'VERBOSE', false, ...
    'MEMORIZE', true ...
    );

Clustering_WU_diff = c_WU.get('COMPARISON', 'Clustering').get('DIFF');
Clustering_WU_p1 = c_WU.get('COMPARISON', 'Clustering').get('P1');
Clustering_WU_p2 = c_WU.get('COMPARISON', 'Clustering').get('P2');
Clustering_WU_cil = c_WU.get('COMPARISON', 'Clustering').get('CIL');
Clustering_WU_ciu = c_WU.get('COMPARISON', 'Clustering').get('CIU');

GlobalEfficiency_av_WU_diff = c_WU.get('COMPARISON', 'GlobalEfficiency').get('DIFF');
GlobalEfficiency_av_WU_p1 = c_WU.get('COMPARISON', 'GlobalEfficiency').get('P1');
GlobalEfficiency_av_WU_p2 = c_WU.get('COMPARISON', 'GlobalEfficiency').get('P2');
GlobalEfficiency_av_WU_cil = c_WU.get('COMPARISON', 'GlobalEfficiency').get('CIL');
GlobalEfficiency_av_WU_ciu = c_WU.get('COMPARISON', 'GlobalEfficiency').get('CIU');

distance_WU_diff = c_WU.get('COMPARISON', 'Distance').get('DIFF');
distance_WU_p1 = c_WU.get('COMPARISON', 'Distance').get('P1');
distance_WU_p2 = c_WU.get('COMPARISON', 'Distance').get('P2');
distance_WU_cil = c_WU.get('COMPARISON', 'Distance').get('CIL');
distance_WU_ciu = c_WU.get('COMPARISON', 'Distance').get('CIU');
%% VISUALIZATION
c_WU.get('COMPARISON', 'Clustering').get('PFB').set('VIEW',[0 90])
c_WU.get('COMPARISON', 'Clustering').get('PFB').get('DRAWN')
c_WU.get('COMPARISON', 'Clustering').get('PFB').get('DRAW')
c_WU.get('COMPARISON', 'Clustering').get('PFB').get('SHOW')
% 
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFB').set('VIEW',[0 90])
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFB').get('DRAWN')
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFB').get('DRAW')
c_WU.get('COMPARISON', 'GlobalEfficiency').get('PFB').get('SHOW')

c_WU.get('COMPARISON', 'Strength').get('PFBG').get('DRAWN')
c_WU.get('COMPARISON', 'Strength').get('PFBG').get('DRAW')
c_WU.get('COMPARISON', 'Strength').get('PFBG').get('SHOW')