% EXAMPLE_NEUROIMGING_2_RVS_PET
% Script example pipeline neuroimaing (PET) conversion to
% regional values (SUVR)
clear variables %#ok<*NASGU>

%% Create dataset
% example_data_dir =  [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example data NIfTI'];

% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_GMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii'];
% create_data_NIfTI_WMProb(atlas_path, example_data_dir)
% 
% atlas_path = [fileparts(which('ConverterNeuroimaging2RegionalValues')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii'];
% create_data_NIfTI_PET(atlas_path, example_data_dir)

%% Load BrainAtlases
im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_aal120 = im_ba.get('BA');

im_ba = ImporterBrainAtlasXLS( ...
    'FILE', [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.xlsx'], ...
    'WAITBAR', true ...
    );

ba_td = im_ba.get('BA');

%% Load Groups of SubjectNeuroimaging
base_Dir = '/home/hang/GitHub/IndividualConnectome-YuweiHangRefator/group_data/HangFDG_dataBIDS';
im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grad_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grad_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/AD_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grad_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grmci_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/MCI_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grmci_anat_wmprob = im_gr_wm.get('GR');

im_gr_pet = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'pet', ...
     'TARGET', 'pet', ...
    'WAITBAR', true ...
    );

grcn_pet = im_gr_pet.get('GR');

im_gr_gm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY', [base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'gmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_gmprob = im_gr_gm.get('GR');

im_gr_wm = ImporterGroupSubjectNeuroimaging_NIfTI( ...
    'DIRECTORY',[base_Dir, '/Healthy_PositiveAmyloid'], ...
    'MODALITY', 'anat', ...
    'TARGET', 'wmprob', ...
    'WAITBAR', true ...
    );

grcn_anat_wmprob = im_gr_wm.get('GR');
%% Convert neuroimaging data to region-of-interest data
ba_nifti_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas.nii']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas.nii']
    };

ba_mapping_files = {
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'aal120_atlas_mapping.csv']
    [fileparts(which('SubjectNeuroimaging')) filesep 'Example atlases NIfTI' filesep 'td_atlas_mapping.csv']
    };

% set the reference brain regions for PET normalization
ref_brain_regions = {};
ref_brain_regions_idx = 120-7:120; % cerebellum all regions in aal120
for i = 1:length(ref_brain_regions_idx)
    ref_brain_regions{i} = ba_aal120.get('BR_DICT').get('IT', ref_brain_regions_idx(i)).get('ID');
end
ref_brain_regions_idx_tds = 7;
for i = 1:length(ref_brain_regions_idx_tds)
    ref_brain_regions{end + 1} = ba_td.get('BR_DICT').get('IT', ref_brain_regions_idx_tds).get('ID');
end

% set the brain regions to convert the regional values (aal120 + TD)
brain_regions_to_convert = {};
convert_brain_regions_idx = 1:94; % cerebral all regions in aal120
for i = 1:length(convert_brain_regions_idx)
    brain_regions_to_convert{i} = ba_aal120.get('BR_DICT').get('IT', convert_brain_regions_idx(i)).get('ID');
end 

% for i = 1:ba_td.get('BR_DICT').get('LENGTH') % all regions in TD
%     brain_regions_to_convert{end + 1} = ba_td.get('BR_DICT').get('IT', i).get('ID');
% end

ad_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','AD',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_pet, ...
    'GR_LIST_ANAT_REF', {grad_anat_gmprob, grad_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 0.5);

gr1_pet = ad_pet.get('GR_ST');

mci_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','MCI',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_pet, ...
    'GR_LIST_ANAT_REF', {grmci_anat_gmprob, grmci_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 0.5);

gr2_pet = mci_pet.get('GR_ST');

cn_pet = ConverterNeuroimaging2RegionalValues( ...
    'ID','CN',...
    'BA_LIST', {ba_aal120, ba_td}, ...
    'BA_NIFTI_FILES', ba_nifti_files, ...
    'BA_MAPPING_FILES', ba_mapping_files, ...
    'REF_BR', ref_brain_regions, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_pet, ...
    'GR_LIST_ANAT_REF', {grcn_anat_gmprob, grcn_anat_wmprob}, ...
    'THRESHOLD_ANAT_REF', 0.5, ...
    'REF_TOP_PERCENTAGE', 0.5);

gr3_pet = cn_pet.get('GR_ST');
ba_st = cn_pet.get('BA');

ad_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','AD',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grad_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr1_t1w = ad_t1w.get('GR_ST');

mci_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','MCI',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'REF_BR', {}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grmci_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr2_t1w = mci_t1w.get('GR_ST');

cn_t1w = ConverterNeuroimaging2RegionalValues( ...
    'ID','CN',...
    'BA_LIST', {ba_aal120}, ...
    'BA_NIFTI_FILES', {ba_nifti_files{1}}, ...
    'BA_MAPPING_FILES', {ba_mapping_files{1}}, ...
    'REF_BR', {}, ...
    'CONVERT_BR', brain_regions_to_convert, ...
    'GR_NEUROIMAGING', grcn_anat_gmprob, ...
    'THRESHOLD_ANAT_REF', 0.5);

gr3_t1w = cn_t1w.get('GR_ST');

%% T1w + PET structural multiplex classification

ba_st = cn_pet.get('BA');  % same region order for T1w and PET
layer_labels = {'T1w_GMprob', 'PET_SUVR'};

gr1_t1w_pet = make_ST_MP_from_ST_groups( ...
    'AD', ba_st, gr1_t1w, gr1_pet, layer_labels);

gr2_t1w_pet = make_ST_MP_from_ST_groups( ...
    'MCI', ba_st, gr2_t1w, gr2_pet, layer_labels);

gr3_t1w_pet = make_ST_MP_from_ST_groups( ...
    'CN', ba_st, gr3_t1w, gr3_pet, layer_labels);
%%
it_list1 = cellfun(@(x) NNDataPoint_ST_MM_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {gr1_t1w_pet.get('ID')}), ...
    gr1_t1w_pet.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);
it_list2 = cellfun(@(x) NNDataPoint_ST_MM_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {gr2_t1w_pet.get('ID')}), ...
    gr2_t1w_pet.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);
it_list3 = cellfun(@(x) NNDataPoint_ST_MM_CLA( ...
    'ID', x.get('ID'), ...
    'SUB', x, ...
    'TARGET_CLASS', {gr3_t1w_pet.get('ID')}), ...
    gr3_t1w_pet.get('SUB_DICT').get('IT_LIST'), ...
    'UniformOutput', false);

% create NNDataPoint_ST_MM_CLA DICT items
dp_list1 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_MM_CLA', ...
        'IT_LIST', it_list1 ...
        );

dp_list2 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_MM_CLA', ...
        'IT_LIST', it_list2 ...
        );

dp_list3 = IndexedDictionary(...
        'IT_CLASS', 'NNDataPoint_ST_MM_CLA', ...
        'IT_LIST', it_list3 ...
        );

% create a NNDataset containing the NNDataPoint_ST_MM_CLA DICT
d1 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_MM_CLA', ...
    'DP_DICT', dp_list1 ...
    );

d2 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_MM_CLA', ...
    'DP_DICT', dp_list2 ...
    );

d3 = NNDataset( ...
    'DP_CLASS', 'NNDataPoint_ST_MM_CLA', ...
    'DP_DICT', dp_list3 ...
    );

%% Binary classifications with repeated CV and saved results

number_runs = 10;
kfolds = 2;

ad_cn_auc  = zeros(number_runs, 1);
ad_mci_auc = zeros(number_runs, 1);
mci_cn_auc = zeros(number_runs, 1);

ad_cn_confusion  = cell(number_runs, 1);
ad_mci_confusion = cell(number_runs, 1);
mci_cn_confusion = cell(number_runs, 1);

ad_cn_split  = cell(number_runs, 1);
ad_mci_split = cell(number_runs, 1);
mci_cn_split = cell(number_runs, 1);

parfor h = 1:number_runs

    rng(h)

    %% AD vs CN
    split_ad_cn = make_kfold_split_index({d1, d3}, kfolds, h);

    nncv_ad_cn = NNClassifierMLP_CrossValidation( ...
        'D', {d1, d3}, ...
        'KFOLDS', kfolds, ...
        'SPLIT', split_ad_cn ...
        );

    nncv_ad_cn.get('TRAIN');

    ad_cn_auc(h) = nncv_ad_cn.get('AV_MACRO_AUC');
    ad_cn_confusion{h} = nncv_ad_cn.get('C_MATRIX');
    ad_cn_split{h} = split_ad_cn;


    %% AD vs MCI
    split_ad_mci = make_kfold_split_index({d1, d2}, kfolds, h);

    nncv_ad_mci = NNClassifierMLP_CrossValidation( ...
        'D', {d1, d2}, ...
        'KFOLDS', kfolds, ...
        'SPLIT', split_ad_mci ...
        );

    nncv_ad_mci.get('TRAIN');

    ad_mci_auc(h) = nncv_ad_mci.get('AV_MACRO_AUC');
    ad_mci_confusion{h} = nncv_ad_mci.get('C_MATRIX');
    ad_mci_split{h} = split_ad_mci;


    %% MCI vs CN
    split_mci_cn = make_kfold_split_index({d2, d3}, kfolds, h);

    nncv_mci_cn = NNClassifierMLP_CrossValidation( ...
        'D', {d2, d3}, ...
        'KFOLDS', kfolds, ...
        'SPLIT', split_mci_cn ...
        );

    nncv_mci_cn.get('TRAIN');

    mci_cn_auc(h) = nncv_mci_cn.get('AV_MACRO_AUC');
    mci_cn_confusion{h} = nncv_mci_cn.get('C_MATRIX');
    mci_cn_split{h} = split_mci_cn;

end


%% Save results

result_table = table( ...
    {'AD vs CN'; 'AD vs MCI'; 'MCI vs CN'}, ...
    [mean(ad_cn_auc); mean(ad_mci_auc); mean(mci_cn_auc)], ...
    [std(ad_cn_auc); std(ad_mci_auc); std(mci_cn_auc)], ...
    [std(ad_cn_auc) / sqrt(number_runs); ...
     std(ad_mci_auc) / sqrt(number_runs); ...
     std(mci_cn_auc) / sqrt(number_runs)], ...
    [1.96 * std(ad_cn_auc) / sqrt(number_runs); ...
     1.96 * std(ad_mci_auc) / sqrt(number_runs); ...
     1.96 * std(mci_cn_auc) / sqrt(number_runs)], ...
    'VariableNames', {'Comparison', 'Mean_AUC', 'STD_AUC', 'SEM_AUC', 'CI95_AUC'} ...
    );

disp(result_table)
save('T1wPET_binary_classification_results.mat', ...
    'number_runs', ...
    'kfolds', ...
    'ad_cn_auc', ...
    'ad_mci_auc', ...
    'mci_cn_auc', ...
    'ad_cn_confusion', ...
    'ad_mci_confusion', ...
    'mci_cn_confusion', ...
    'ad_cn_split', ...
    'ad_mci_split', ...
    'mci_cn_split', ...
    'result_table' ...
    );


fprintf('\nSaved:\n')
fprintf('T1wPET_binary_classification_results.mat\n')
fprintf('T1wPET_binary_classification_summary.csv\n')
function gr_mp = make_ST_MP_from_ST_groups(gr_id, ba, gr_t1w, gr_pet, layer_labels)

    sub_list_t1w = gr_t1w.get('SUB_DICT').get('IT_LIST');
    sub_list_pet = gr_pet.get('SUB_DICT').get('IT_LIST');

    pet_ids = cellfun(@(s) s.get('ID'), sub_list_pet, 'UniformOutput', false);

    n_sub = length(sub_list_t1w);
    it_list = cell(1, n_sub);

    br_number = ba.get('BR_DICT').get('LENGTH');

    fprintf('Building SubjectST_MP group %s: %d subjects\n', gr_id, n_sub)

    for i = 1:n_sub
        sub_t1w = sub_list_t1w{i};
        sid = sub_t1w.get('ID');

        match_idx = find(strcmp(pet_ids, sid), 1);

        if isempty(match_idx)
            error('Missing PET subject with ID "%s" in group "%s".', sid, gr_id);
        end

        sub_pet = sub_list_pet{match_idx};

        t1w_vec = sub_t1w.get('ST');
        pet_vec = sub_pet.get('ST');

        % Required by SubjectST_MP: each layer is number_of_regions x 1
        t1w_vec = t1w_vec(:);
        pet_vec = pet_vec(:);
        it_list{i} = SubjectST_MP( ...
            'ID', sid, ...
            'BA', ba, ...
            'L', 2, ...
            'LAYERLABELS', layer_labels, ...
            'ST_MP', {t1w_vec, pet_vec} ...
            );
    end

    % BRAPH2 tutorial pattern for SubjectST_MP groups
    gr_mp = Group( ...
        'ID', gr_id, ...
        'SUB_CLASS', 'SubjectST_MP', ...
        'SUB_DICT', IndexedDictionary( ...
            'IT_CLASS', 'SubjectST_MP', ...
            'IT_LIST', it_list ...
            ) ...
        );
end

function d = make_dataset_ST_MM_CLA(gr_mp)

    if isempty(which('NNDataPoint_ST_MM_CLA'))
        error([ ...
            'NNDataPoint_ST_MM_CLA is not on the MATLAB path. ', ...
            'The official BRAPH2 develop branch has it under ', ...
            'braph2/pipelines/structural multi_modality NN/. ', ...
            'Add that pipeline to the path or use the SubjectST concatenation fallback.' ...
            ]);
    end

    sub_list = gr_mp.get('SUB_DICT').get('IT_LIST');

    it_list = cellfun(@(x) NNDataPoint_ST_MM_CLA( ...
        'ID', x.get('ID'), ...
        'SUB', x, ...
        'TARGET_CLASS', {gr_mp.get('ID')} ...
        ), ...
        sub_list, ...
        'UniformOutput', false);

    dp_list = IndexedDictionary( ...
        'IT_CLASS', 'NNDataPoint_ST_MM_CLA', ...
        'IT_LIST', it_list ...
        );

    d = NNDataset( ...
        'DP_CLASS', 'NNDataPoint_ST_MM_CLA', ...
        'DP_DICT', dp_list ...
        );
end

function split_index = make_kfold_split_index(d_list, kfolds, seed)

    rng(seed)

    n_groups = numel(d_list);
    split_index = cell(n_groups, kfolds);

    for g = 1:n_groups
        n = d_list{g}.get('DP_DICT').get('LENGTH');

        idx = randperm(n);

        for k = 1:kfolds
            split_index{g, k} = sort(idx(k:kfolds:end));
        end
    end
end